OSC/ondemand

nginx_stage/lib/nginx_stage/configuration.rb, nginx_stage/share/nginx_stage_example.yml
Now the default path for dev apps is similar to usr apps - it is the local disk
of the webnode, and requires a symlink "gateway" to be created pointing to the users
"sandbox" dev directory in their home directory
=> Change default path for dev apps: require opt in

nginx_stage/lib/nginx_stage.rb, nginx_stage/lib/nginx_stage/configuration.rb, nginx_stage/lib/nginx_stage/generator.rb, nginx_stage/lib/nginx_stage/generators/pun_config_generator.rb, nginx_stage/lib/nginx_stage/secret_base_key_file.rb, nginx_stage/lib/nginx_stage/secret_key_base_file.rb
Generate a unique secrete key for each user and set it to SECRET_KEY_BASE env var.
TODO: Fix this so that:
1. Add object `SecretBaseKeyFile. new(path)` that implements `SecretBaseKeyFile#generate` and `SecretBaseKeyFile#exist?` and `SecretBaseKeyFile#secret` and maybe ``SecretBaseKeyFile#build(user:)`. `SecretBaseKeyFile#secret` would output a warning or raise exception if secret is nil (?) - could just output a warning for now...
2. Add to `pun_config_generator` a block like:
```ruby
add_hook :create_secret_key_base do
secret = SecretKeyBaseFile.build(user: user)
secret.generate unless secret.exist?
end
```
3. Update `NginxStage.nginx_env` to use `'SECRET_KEY_BASE' => SecretKeyBaseFile.build(user: user).secret`
This ensures the secret is only generated during the launching of a PUN (and …
=> nginx_stage: generate secret key and set to env

nginx_stage/html/missing_home_directory.html, nginx_stage/html/missing_home_directory.html.example.pam_mkhomedir, nginx_stage/lib/nginx_stage/configuration.rb, nginx_stage/lib/nginx_stage/generator_helpers.rb, nginx_stage/lib/nginx_stage/views/pun_config_view.rb, nginx_stage/templates/pun.conf.erb
serve error file missing_home_directory.html if user's home directory
is missing, by default from
/opt/ood/nginx_stage/html/missing_home_directory.html
optionally load custom error file at
/etc/ood/config/pun/html/missing_home_directory.html if it exists
in both cases, set Cache-Control header to no-store so user can restart
webserver easily by clicking a button, and not view the cached file
instead
=> Serve error file missing_home_directory.html

nginx_stage/etc/profile, nginx_stage/lib/nginx_stage.rb, nginx_stage/lib/nginx_stage/configuration.rb, nginx_stage/sbin/nginx_stage, nginx_stage/share/nginx_stage_example.yml, ood-portal-generator/bin/generate, ood-portal-generator/lib/ood_portal_generator/view.rb, ood-portal-generator/share/ood_portal_example.yml, tests.sh
Support ondemand SCL
* Replace /var/lib/nginx with /var/lib/ondemand-nginx
* Replace /var/run/nginx with /var/run/ondemand-nginx
* Replace /var/log/nginx with /var/log/ondemand-nginx
* Load ondemand SCL only
Migrations of /var/lib and /var/log locations will be handled by ondemand RPM.
=> Support ondemand SCL

ood-portal-generator/sbin/update_ood_portal
This is needed to make output more friendly for RPMs using new flag but keep old behavior if run without new flag.
Copied into vagrant:
```
[root@ood ~]# /opt/ood/ood-portal-generator/sbin/update_ood_portal 
Generating Apache config using YAML config: '/etc/ood/config/ood_portal.yml'
No change in Apache config.
Completed successfully!
Restart the httpd24-httpd service now.
Suggested command:
sudo systemctl try-restart httpd24-httpd.service httpd24-htcacheclean.service
[root@ood ~]# /opt/ood/ood-portal-generator/sbin/update_ood_portal -h
Usage: update_ood_portal [-r|--rpm]
-r|--rpm      Execution performed during RPM install
[root@ood ~]# /opt/ood/ood-portal-generator/sbin/update_ood_portal -r
Generating Apache config using YAML config: '/etc/ood/config/ood_portal.yml'
No change in Apache …
```
=> Add -r|--rpm flags to update_ood_portal

nginx_stage/sbin/nginx_stage
Now that we ship a ondemand SCL it should be loaded always and before anything in /etc/ood/profile could possibly prevent it from loading.  A site-specific /etc/ood/profile can still make changes after ondemand SCL is loaded.
I added a commit to docs https://github.com/OSC/ood-documentation/pull/142 that could be reverted or re-worded if this merged for 1.5.
=> Always load ondemand SCL environment for nginx_stage

CHANGELOG.md, nginx_stage/lib/nginx_stage/configuration.rb
Fixes error where integer values for pun_custom_env would cause TypeErrors: "no implicit conversion of Integer into String".
Fixes #26.
=> Explicitly stringify the values for pun_custom_env

nginx_stage/lib/nginx_stage/generators/nginx_clean_generator.rb, nginx_stage/lib/nginx_stage/pid_file.rb, nginx_stage/lib/nginx_stage/socket_file.rb
=> Remove stale pid and socket files

ood-portal-generator/lib/ood_portal_generator/version.rb, ood-portal-generator/lib/ood_portal_generator/view.rb, ood-portal-generator/share/ood_portal_example.yml, ood-portal-generator/templates/ood-portal.conf.erb
https://discourse.osc.edu/t/implications-of-disabling-the-portal-rewriteengine/378
=> Support disabling RewriteEngine

nginx_stage/bin/node, nginx_stage/bin/python, nginx_stage/bin/ruby, ood_auth_map/bin/ood_auth_map.mapfile, ood_auth_map/bin/ood_auth_map.regex
Ubuntu doesn't provide this symlink.
```
$ docker run --rm centos:7 ls /bin/env /usr/bin/env
/bin/env
/usr/bin/env
$ docker run --rm ubuntu:18.04 ls /bin/env /usr/bin/env
ls: cannot access '/bin/env': No such file or directory
/usr/bin/env
```
=> Change /bin/env to /usr/bin/env in all shebangs

packaging/ondemand-selinux-systemd.te, packaging/ondemand-selinux.fc, packaging/ondemand-selinux.te, packaging/ondemand.spec
Piecing together the method from Fedora guidelines and Foreman:
https://fedoraproject.org/wiki/PackagingDrafts/SELinux
https://github.com/theforeman/foreman-packaging/blob/rpm/1.23/packages/foreman/foreman-selinux/foreman-selinux.spec
https://github.com/theforeman/foreman-selinux
Foreman used entire repo just for SELinux but I'm hoping we can do everything in just single policy file and some logic in spec file.
So far policy changes are based on using Vagrant w/ SLURM and enabling SELinux in Permissive mode. I am setting up a system at OSC that uses a more production-like environment with SELinux to get a better sense of what else would be required.
=> Supporting SELinux with OnDemand

config.json
Updates all the base apps for Debian pathes.
See the description given in the [files app PR](https://github.com/OSC/ood-fileeditor/pull/89) for the more details on that issue.
=> bump base ruby apps to next version

ood-portal-generator/sbin/update_ood_portal, packaging/ondemand.spec
This isn't fool proof. The first time this code gets run a replace will occur. If someone changes the `ood-portal.con` after this change is run then future executions won't modify anything.
=> Do not replace ood-portal.conf if the checksum does not match previous execution of ood-portal-generator

ood-portal-generator/sbin/update_ood_portal, packaging/ondemand.spec
Fixes #69
@ericfranz @MorganRodgers @johrstrom This is a must before we announce latest 1.6 to public to avoid restarting Apache for no changes.
This can be released as 1.6.17-2
=> Only restart Apache if changes take place

ood-portal-generator/sbin/update_ood_portal
The redirection to /dev/null was eating a `[: too many arguments` error which wasn't letting people update during an upgrade process.
See [this discourse topic](https://discourse.osc.edu/t/update-ood-portal-in-ondemand-1-6-19-1-el7-x86-64-refuses-to-make-new-configuration/546).
=> sha256sum shouldn't be in brackets.

.travis.yml, nginx_stage/sbin/nginx_stage, ood-portal-generator/sbin/update_ood_portal
Adds shellcheck items to travis CI and also fixes all the issues with our shells that would have caused tests to fail.
=> Add shell check

apps/activejobs/app/views/layouts/application.html.erb, apps/dashboard/app/assets/javascripts/products.coffee, apps/dashboard/app/controllers/products_controller.rb, apps/dashboard/app/views/layouts/application.html.erb, apps/dashboard/app/views/layouts/nav/_all_apps.html.erb, apps/dashboard/app/views/layouts/nav/_develop_dropdown.html.erb, apps/dashboard/app/views/layouts/nav/_help_dropdown.html.erb, apps/dashboard/app/views/layouts/nav/_link.html.erb, apps/dashboard/app/views/layouts/nav/_sessions.html.erb, apps/dashboard/app/views/products/_form_git.html.erb, apps/file-editor/app/views/layouts/application.html.erb, apps/myjobs/app/views/layouts/application.html.erb
Some minor accessibility fixes and fixing a couple broken HTML elements. Accessibility changes are largely, but not limited to, results from Deque's aXe utility (https://www.deque.com/axe/).
=> Accessibility fixes

apps/dashboard/bin/setup
This fixes a change introduced in #93.
Error I was getting:
```
Traceback (most recent call last):
3: from ./bin/setup:36:in `<main>'
2: from /opt/rh/rh-ruby25/root/usr/share/ruby/fileutils.rb:122:in `cd'
1: from /opt/rh/rh-ruby25/root/usr/share/ruby/fileutils.rb:122:in `chdir'
./bin/setup:45:in `block in <main>': undefined method `sh' for main:Object (NoMethodError)
```
=> Fix bin/setup for dashboard

Rakefile, apps/activejobs/bin/setup, apps/dashboard/bin/setup, apps/file-editor/bin/setup, apps/myjobs/bin/setup
Shaved 30s to 1 minute off RPM builds of OnDemand. These are flags commonly used by CI/CD tools like Travis and Appveyor. I think the retry one is especially useful to avoid build failures from intermittent issues with rubygems.org.
=> Add flags to bundle install to improve gem install speed

packaging/ondemand.spec
This is what the requires look like using `rpm -qp --requires` on built RPM
```
ondemand-apache >= 1.7-5
ondemand-apache < 2.0
ondemand-apache < 1.8
ondemand-nginx = 1.17.3
ondemand-passenger = 6.0.4
ondemand-ruby >= 1.7-5
ondemand-ruby < 2.0
ondemand-ruby < 1.8
ondemand-python >= 1.7-5
ondemand-python < 2.0
ondemand-python < 1.8
ondemand-nodejs >= 1.7-5
ondemand-nodejs < 2.0
ondemand-nodejs < 1.8
ondemand-runtime >= 1.7-5
ondemand-runtime < 2.0
ondemand-runtime < 1.8
ondemand-gems-1.7.1
```
This ensures that we don't have to rebuild ondemand RPM if we release ondemand-runtime 1.7-6 that maybe not 100% needed. If it is needed by OnDemand then we rebuild RPM with `runtime_version` release incremented.
=> Require very specific versions of ondemand-runtime

nginx_stage/share/nginx_stage_example.yml
While syncing up Puppet's template with comments from this repo's example I noticed `ondemand_title` was not documented. I still see it referenced in code.
=> Document ondemand_title for nginx_stage.yml

packaging/ondemand.spec
This ensures the various GEM_PATH locations exist so we don't end up trying to iterate over non-existant directories.
=> Use latest runtime

apps/dashboard/app/helpers/batch_connect/session_contexts_helper.rb
Supports specifying widget type "radio" or "radio_button", works
similar to select field:
version:
widget: radio
label: "MATLAB version"
help: "This defines the version of MATLAB you want to load."
options:
- [ "R2018b", "matlab/r2018b" ]
- [ "R2018a", "matlab/r2018a" ]
- [ "R2017a", "matlab/r2017a" ]
- [ "R2016b", "matlab/r2016b" ]
- [ "R2015b", "matlab/r2015b" ]
checked: "matlab/r2018a"
doesn't support arbitrary option data attributes like in select fields
=> radio button groups in batch connect apps

apps/shell/app.js
Currently, the LANG env var defaults to LANG=C, which actually was also an issue resolved back in 2016 for https://github.com/OSC/ood-shell/issues/3 when wetty was still in use.
The fix provided in this commit (https://github.com/OSC/ood-shell/commit/b996d368a503a2df5259d9053059feeeb0d1b2aa) was removed when moving away from wetty in this commit (https://github.com/OSC/ood-shell/commit/2c8a02283e3a7549747c244e73e6e5c231232ae5).
=> add en_US.UTF-8 as LANG (for new terminal backend)

nginx_stage/lib/nginx_stage/configuration.rb, nginx_stage/lib/nginx_stage/views/pun_config_view.rb, nginx_stage/share/nginx_stage_example.yml, nginx_stage/templates/pun.conf.erb, packaging/ondemand.spec
Fixes #302
The bump for ondemand-runtime will pull in build from https://github.com/OSC/ondemand-packaging/pull/83 that has `ondemand-ruby` now depending on `ondemand-rubygem-bundler` which uses bundler 1.17.3.
=> Set BUNDLE_USER_CONFIG to /dev/null in PUN environment

apps/activejobs/app/views/jobs/_extended_panel.html.erb
Fixes #323
OnDemand production:
Vagrant with this fix:
=> Fix font awesome icon usage for activejobs

apps/dashboard/app/apps/ood_app.rb, apps/dashboard/app/controllers/products_controller.rb, apps/dashboard/app/models/product.rb
Maybe fix for #316 
FWIW I made this change on webdev02 and it solved the problem of launching My Jobs with a `~/.bundle/config` present.
=> Fix bundler execution

packaging/ondemand.spec
@ericfranz This is needed to fix 1.7.3 builds. If you don't want to do `git tag -f` to force new 1.7.3 tag then this can be 1.7.3-2
=> Fix packaging of SELinux

.gitlab-ci.yml
* Always deploy packages to the ci repos
* Only deploy non-CI releases to latest repo
This avoids dev nodes getting many versions behind.
=> Better gitlab-ci deployment workflow

apps/dashboard/public/noVNC-1.0.0/app.v1.js
Fixes https://github.com/OSC/ondemand/issues/198 for Chrome. See issue for summary of solution.
Note: after this is approved, we will need to use our poor-man's cache bust of `noVNC-1.0.0/app.v1.js` by renaming it `noVNC-1.0.0/app.v2.js`.
=> Copy paste NoVNC chrome

apps/myjobs/app/models/workflow.rb, apps/myjobs/app/models/workflow_file.rb, apps/myjobs/test/models/workflow_file_test.rb
- Changes `WorkflowFile#{path,staged_dir}` to be methods to maintain backward compatibility, while using Pathnames internally
- Removed unnecessary assignment in `WorkflowFile#grouped_script_options`
- Add a test for WorkflowFile
Note that this change also hides dot files and descendants from the Job Details panel in the workflow list view, which may or may not be desirable.
Fixes #346.
=> Reject hidden files from the script suggestion list

apps/activejobs/app/views/layouts/application.html.erb, apps/dashboard/app/views/layouts/application.html.erb, apps/file-editor/app/views/layouts/application.html.erb, apps/myjobs/app/views/layouts/application.html.erb
fixes #322
Can't set to `nil` like other apps because that throws errors. Seems setting favicon normally to `/public/favicon.ico` doesn't work unless you do so in `href` I think because PUN URL gets prefixed even if begins with "/".
=> Fix favicon on dashboard,

apps/dashboard/lib/tasks/test.rake
parameterize.underscore the name of the job script in order to avoid
illegal characters like colon, which cause problems with some schedulers (pbspro?)
fixes issue raised in https://github.com/OSC/ondemand/issues/341
=> dashboard: avoid colon in rake task's job script name

apps/myjobs/app/views/workflows/_edit_form.html.erb
Fixes #389 
Unlike other form helpers that auto-set the value, this does not occur in the case of select
when you are using a helper method like options_for_select or grouped_options_for_select
(or at least this is the case for bootstrap_form helper when using grouped_options_for_select)
Those methods produce the string of option tags, so you need to provide the current selection value
as an argument to those methods
See https://api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-grouped_options_for_select
=> Fix preserving selection in myjobs job options

ood-portal-generator/lib/ood_portal_generator/view.rb, ood-portal-generator/share/maintenance.html, ood-portal-generator/share/ood_portal_example.yml, ood-portal-generator/spec/application_spec.rb, ood-portal-generator/spec/fixtures/ood-portal.conf.maint_with_ips, ood-portal-generator/spec/fixtures/ood-portal.conf.nomaint, ood-portal-generator/spec/fixtures/sum.default, ood-portal-generator/templates/ood-portal.conf.erb, packaging/ondemand.spec
A few items that may need to still be addressed:
* Adding default image to serve. I put RewriteCond assuming there is one
* Possibly add helper script or nginx_stage subcommand to touch the file and execute `nginx_stage nginx_clean -f`.
This mimics XDMOD maintenance mode used at OSC
=> Support putting OnDemand into maintenance mode

apps/activejobs/app/helpers/jobs_helper.rb, apps/activejobs/app/views/jobs/_job_details_node_view.html.erb, apps/activejobs/spec/helpers/jobs_helper_spec.rb
There are some HTML elements that get added if neither grafana or ganglia are present in cluster config. This is slight regression due to #400 
Notice the two dashes.  This change brings back past behavior where essentially the entire partial is ignored if a site doesn't configure ganglia or grafana.
=> Fix activejobs when ganglia or grafana is not present

packaging/ondemand.spec
This requires some extra testing. Failures from update_ood_portal will not break Apache because the command is prefixed with a hyphen.
=> Regenerate ood-portal.conf when Apache starts or is reloaded

nginx_stage/nginx_stage.gemspec, ood_auth_map/ood_auth_map.gemspec
Simple rake updates for nginx_stage and ood_auth_map to get rid of security alerts and be in line with all our other apps.
=> update rake for nginx_stage and ood_auth_map

apps/shell/app.js
Our situation:
We use the same login nodes for all clusters. When using the shell app we wanted a shell directly to the right cluster and needed to pass some ssh arguments.
We had the information in the url but no clean way to pass to the ssh command.
Rather than hacink the shell app.js wit our custom code it would be nice to just set the ssh wrapper to use by the shell app in the settings.env
For all users:
- This allows for a per cluster different set environment through the gui.
- Different clients if needed
- a lot more possibility to tailor the command as needed
or just do nothing and the basic system ssh keeps in effect
=> allowe the ssh command to be replaced by a wrapper in ood/apps/sys/dashboard/.env.production

apps/dashboard/Gemfile, apps/dashboard/Gemfile.lock, apps/dashboard/app/helpers/batch_connect/sessions_helper.rb, apps/dashboard/app/models/batch_connect/session.rb, apps/dashboard/app/views/batch_connect/session_contexts/new.html.erb, apps/dashboard/config/locales/en.yml, apps/dashboard/test/models/batch_connect/session_test.rb, apps/dashboard/test/test_helper.rb
TODO: 
> When attempting to submit this job OnDemand set the job name to "ondemand/...". If any of these characters are not allowed, please ask your administrator to configure OnDemand to set the environment variable OOD_JOB_NAME_ILLEGAL_CHARS. For example OOD_JOB_NAME_ILLEGAL_CHARS="/" will ensure that / is replaced with -
=> Sanitize batch connect job name with new ood_core sanitize_job_name method

apps/activejobs/app/assets/javascripts/application.js.erb, apps/activejobs/app/assets/stylesheets/jobs.scss, apps/activejobs/app/models/jobs_json_request_handler.rb, apps/activejobs/app/views/jobs/index.html.erb, apps/activejobs/app/views/layouts/application.html.erb
Adds a delete column to active jobs to enable #416.  Looks like the image below.
I called it 'actions' column and left a small button to leave room for #138. 
There is a confirmation button, but maybe it should say the job name instead of the jobid? It may be easier to recognize that way.
=> Add delete column

apps/shell/app.js
This adds a second test for origin, along with the csrf token, which can be disabled by setting the env var OOD_SHELL_ORIGIN_CHECK to any string not starting with `http`.
This by default uses X-Forwarded-Proto and X-Forwarded-Host which Apache mod_proxy should be setting.
It doesn't handle the case where X-Forwarded-Host contains multiple values or it is needed to have multiple valid values to check against - which is why the ability to disable it is present.
=> Verify origin when upgrading websocket

apps/dashboard/config/examples/osc/initializers/ood.rb
The example for adding titles to favourite paths currently breaks with this error. 
```text
App 71969 output: Error: The application encountered the following error: wrong number of arguments (given 2, expected 1) (ArgumentError)
App 71969 output:     /users/PZS0714/johrstrom/ondemand/misc/ondemand/apps/dashboard/app/apps/favorite_path.rb:2:in `initialize'
App 71969 output:     /users/PZS0714/johrstrom/ondemand/misc/ondemand/apps/dashboard/config/initializers/paths.rb:7:in `new'
App 71969 output:     /users/PZS0714/johrstrom/ondemand/misc/ondemand/apps/dashboard/config/initializers/paths.rb:7:in `block in <top (required)>'
App 71969 output:     /users/PZS0714/johrstrom/ondemand/misc/ondemand/apps/dashboard/config/initializers/paths.rb:1:in `tap'
App 71969 output: …
```
=> fix favorite path example

nginx_stage/lib/nginx_stage/generators/nginx_clean_generator.rb
Fixes #485
Verified in Docker:
```
[root@a00186abb497 /]# /ondemand/nginx_stage/sbin/nginx_stage nginx_clean --user ood --force
ood
```
The issue was the comparison `user != u` was comparing a string against `NginxStage::User`, so doing `to_s` fixes the mixed class comparison.
=> Fix nginx_clean --user flag

apps/bc_desktop/template/desktops/kde.sh
With the realizations in #388 I was able to get a KDE desktop to run at OSC in a container, even though we don't support kde or have the libraries on the host.
With this PR users could choose KDE given their setup is correct or they have a container to do so. If you want to test this, you can use my image at `/users/PZS0714/johrstrom/Public/images/sing/kde.sif` 
with this `submit.yml.erb` 
```ruby
<%
image="/users/PZS0714/johrstrom/Public/images/sing/" + desktop + ".sif"
%>
---
script:
native:
resources:
nodes: "<%= bc_num_slots %><%= node_type %>"
template: "vnc"
batch_connect:
websockify_cmd: '/usr/bin/websockify'
script_wrapper: |
cat << "CTRSCRIPT" > container.sh
export PATH="$PATH:/opt/TurboVNC/bin"
echo "path is $PATH"
%s  
CTRSCRIPT
export …
```
=> add support for KDE bc desktop

apps/dashboard/public/noVNC-1.1.0/vnc.html
This PR fixes https://discourse.osc.edu/t/bc-desktop-stopped-working-in-macos-safari-possibly-across-ood-1-7-upgrade/904
Safari 13.1.1 was failing to load app/ui.js because noVNC was attempting to load the ui module without credentials.
=> Fix Safari CORS bug in noVNC

apps/shell/app.js
Uses chaining instead of destructuring to make code more readable
=> Refactor sshhost whitelist

apps/dashboard/app/controllers/batch_connect/session_contexts_controller.rb, apps/dashboard/app/models/batch_connect/app.rb, apps/dashboard/app/models/batch_connect/session.rb, apps/dashboard/test/models/batch_connect/app_test.rb
A possible fix to #227.  
Users only need to add items to the `cluster` attribute like below to enable a dropdown. If only 1 cluster is given, a hidden element in the form is generated that has the value of the cluster so it has backward compatibility. 
```yaml
cluster:
- owens
- pitzer
```
A possible enhancement may be to allow users to redo the cluster attribute as so say turn `owens` into `Owens` for example.  This is also rather simplistic so check or enforce that all the clusters be of the same scheduler type.
=> allow batch_connect apps to use multiple clusters

apps/dashboard/app/models/batch_connect/app.rb, apps/dashboard/test/models/batch_connect/app_test.rb
Solution for #531.  The only oddity I found is that `*` needs to be quoted where something like `.*` doesn't. YAML for whatever reason doesn't parse it correctly so we'll have to be sure to highlight that folks need to use `cluster: '*'` if they want to use that alias.
=> allow batch_connect apps to accept regular expressions as their

packaging/ondemand.spec
The actual packages that this change references are built but moved out of latest repo until we are ready to begin building 1.8.  I can move them back before a tag.
=> Minor change to support ondemand-1.8 builds

.github/workflows/document-merge.yml
We have so many things in flight and being pulled in. I thought it may be nice to have some automation to create documentation tickets whenever we pull in something so things so we at least have the reminder in the form of issues on the documentation repo.
=> add a gh action for creating documentation issues on PRs

apps/dashboard/app/helpers/dashboard_helper.rb, apps/dashboard/app/views/shared/_welcome.html.erb, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/config/examples/osc/env
We wanted to use an SVG version of our at OSC. SVGs scale infinitely, I needed to set the height on the image. I made use of Bootstrap 3's grid system to do this responsively.
**Net Improvements:**
* Fixes Dashboard logo appearing to be cut off on mobile devices
**Old version:**
**New version:**
=> Make Dashboard logo responsive

apps/activejobs/config/locales/zh-CN.yml, apps/dashboard/config/locales/zh-CN.yml, apps/file-editor/config/locales/zh-CN.yml, apps/myjobs/config/locales/zh-CN.yml
Hello，l have translated part of the OOD UI into Chinese.
This is the progress of my work.
=> [WIP]Chinese

apps/dashboard/app/models/batch_connect/app.rb, apps/dashboard/test/models/batch_connect/app_test.rb
Fixes #532 
* users can change the order (the cluster is usually first) by
specifying cluster in the form
* if attributes are specified the bc app now respects that config
but does not do any validation
=> allow users to change cluster dropdown in the form yml

.github/workflows/document-merge.yml
OK third time's the charm. I created a new token for the oscwiag user, applied it to this repo and so the tickets will be created by @oscwiag.
=> use oscwiag token instead of gh action token

apps/dashboard/app/models/batch_connect/session.rb, apps/dashboard/config/locales/en.yml, apps/dashboard/test/models/batch_connect/session_test.rb
Fix for #529 
Users can now specify the cluster in the form.yml.erb or the submit.yml.erb files.  If not defined in either, the dashboard now throws a translatable error message. 
cluster is expected to be a string on the top level yaml of the submit.yml file.  Something like this:
```erb
<%-
cluster = 'owens'
-%>
---
cluster: "<%= cluster %>"
batch_connect:
template: "basic"
```
=> Allow users to specify cluster in the submit.yml.erb

apps/dashboard/app/helpers/batch_connect/sessions_helper.rb, apps/dashboard/app/models/batch_connect/app.rb, apps/dashboard/app/models/batch_connect/session.rb, apps/dashboard/app/views/batch_connect/sessions/connections/_info.html.erb
Adds functionality to allow any batch connect application include `info.html.erb` in its root directory and that info will be rendered in the session panel view. Closes #488.
`info.html.erb` in this example:
```html
Custom info.html.erb on Code Server app
<h1>HTML works here</h1>
Customize your batch connect apps with custom info.html.erb
```
=> Add support for custom info in batch connect apps

apps/dashboard/Gemfile, apps/dashboard/app/helpers/batch_connect/sessions_helper.rb
Moves rendering `<hr>` tag from `custom_info_view()` into `session_view()`
The `info` partial shouldn't be aware of where its rendered, this PR fixes that
=> Update rendering logic in session panel helper

apps/files/app.js, nginx_stage/lib/nginx_stage.rb, nginx_stage/lib/nginx_stage/configuration.rb, nginx_stage/lib/nginx_stage/views/pun_config_view.rb, nginx_stage/share/nginx_stage_example.yml, nginx_stage/templates/pun.conf.erb
Allow configuration of maximum file upload size in nginx. Closes #424 and Closes #503 
Sets the default `client_max_body_size` to `10G` and allows overriding this value in `nginx_stage.yml` like so:
`nginx_file_upload_max: 50G`
=> Add support for setting client_max_body_size

apps/files/bin/setup, apps/shell/bin/setup
Node apps use their own cache directory  to avoid collisions when building becuase they are colliding.
=> node apps use their own cache directory

apps/shell/app.js
(in case envvar DEFAULT_SSHHOST is not in cluster configs)
=> Add default_sshhost to set

apps/shell/package.json, apps/shell/test/testing.test.js, apps/shell/yarn.lock
Add `jest` for testing. An example test is included in `/test/testing.test.js`:
```js
function distance(x1, y1, x2, y2) {
return Math.sqrt(Math.pow(x2 - x1, 2) + Math.pow(y2 - y1, 2))
}
```
Run the test suite with command `yarn test`
=> Add Jest for tests with example test suite for Shell app

apps/dashboard/Gemfile, apps/dashboard/Gemfile.lock
gems in the dashboard (and other core app) gemfiles get
added to the ondemand-gems rpm which gets installed system wide
and made available when doing module load ondemand
so with these three gems we can make status apps like the system status
app or the example passenger app, without requiring a Gemfile or
installing gems to the app directory
=> include gems for status apps

apps/dashboard/app/views/dashboard/_xdmod_widget_job_efficiency.html.erb
the job efficiency report request wasn't specifying all the statistics required
which caused the report to return a subset of the required data in XDMoD 9
=> add missing stats to XDMoD report request

apps/dashboard/app/models/batch_connect/app.rb, apps/dashboard/test/models/batch_connect/app_test.rb
Fix a bug where empty cluster configs like "" and "  " where valid. Now this just eats them and users will be presented with the 'you never defined a cluster' error when they submit.
=> Empty cluster bug

apps/dashboard/app/assets/javascripts/application.js
Working with @ericfranz found that FireFox was not doing the login properly.
The issue being that an iframe with display:none wont allow the javascript inside of it to click a form element.
Also left -10000 is not valid it needs to be in px
=> Fix for Firefox not submitting

apps/shell/app.js
All environment variables in the Shell app are prepended with `OOD`. This PR adds adds backwards compatibility for `DEFAULT_SSHHOST` so its accepted, though `OOD_DEFAULT_SSHHOST` is preferred. Closes #602
=> Add backwards compatibility in Shell app for default SSH host

apps/dashboard/app/assets/javascripts/application.js, apps/dashboard/app/views/dashboard/_xdmod_widget_job_efficiency.html.erb, apps/dashboard/app/views/dashboard/_xdmod_widget_jobs.html.erb, apps/dashboard/config/configuration_singleton.rb
This reverts commit d945c604fd9a36aa292730aa48b9bff44c38ef26.
It introduced a bug - probably due to `this` changing in the promise callback.
=> Revert "make xdmod auto-login timeout configurable"

apps/dashboard/app/models/batch_connect/app.rb, apps/dashboard/test/models/batch_connect/app_test.rb
=> Bc regex bug

apps/shell/app.js
during a manual merge conflict resolution, the name of a variable accidentally got renamed
=> fix accidental rename of variable

apps/dashboard/app/views/dashboard/_xdmod_widget_jobs.html.erb
the report limits display of first 10 pages
if the total count is fewer than 10 jobs (such as 7) the text read
"Showing first 10 of 7 jobs..."
Now it says
"Showing first 7 of 7 jobs..."
=> fix xdmod job report page limit number

apps/dashboard/app/views/batch_connect/sessions/connections/_native_vnc.html.erb, apps/dashboard/app/views/batch_connect/sessions/connections/_native_vnc_linux.html.erb, apps/dashboard/app/views/batch_connect/sessions/connections/_native_vnc_mac.html.erb, apps/dashboard/app/views/batch_connect/sessions/connections/_native_vnc_windows.html.erb, apps/dashboard/config/configuration_singleton.rb
This PR makes the `Native Instructions` tab for VNC interactive sessions available. Closes #618
* Allow OOD_NATIVE_VNC_LOGIN_HOST to be set (purely for visual improvements)
* Fix Linux connection instructions
If you set `OOD_NATIVE_VNC_LOGIN_HOST` then the command will be auto populated with that host. This is purely for visual improvement and has no impact on the VNC connection at all.
To enable the Native Instructions tab, `ENABLE_NATIVE_VNC` must be set to a truthy value such as `1` or `true`
To override the template for different platforms (Windows, MacOS, Linux):
`views/batch_connect/sessions/connections/_native_vnc_{windows,mac,linux}.html.erb`
Screenshots (on Windows):
and without `OOD_NATIVE_VNC_LOGIN_HOST` set
=> Make Native Instructions tab for VNC sessions available for other OOD sites

apps/dashboard/app/views/layouts/_browser_warning.html.erb
* Dex is now the default recommendation for auth instead of Basic Auth. Closes #608 
We will document this in https://github.com/OSC/ood-documentation/issues/333
=> Remove Safari compatibility alert (#608)

apps/dashboard/Gemfile.lock
Need to update again because we ran into [this issue in dotiw](https://github.com/radar/distance_of_time_in_words/issues/110).
=> update to pick up dotiw 5.1.0

apps/dashboard/app/views/batch_connect/sessions/connections/_native_vnc_windows.html.erb, apps/dashboard/test/models/batch_connect/vnc_view_test.rb, apps/dashboard/test/system/configuration_singleton_test.rb
Update native instructions for Windows noVNC sessions, they make more sense now
Add test to check existence of partial `app/views/batch_connect/sessions/connections/_native_vnc_windows.html.erb`:
=> Update native instructions for Windows noVNC sessions

ood-portal-generator/lib/ood_portal_generator/dex.rb
This means a user can do this and not have to worry about also setting `frontend`:
```yaml
dex:
frontend:
extra:
...
```
Without this change to define extra settings and use our theme they would have to do this:
```yaml
dex:
frontend:
theme: ondemand
extra:
...
```
=> Better default for dex frontend configuration

apps/activejobs/app/helpers/jobs_helper.rb
This is especially useful on Pitzer Expansion where the cluster config name in OOD is `pitzer-exp` but the cluster is still called `pitzer` for Prometheus/Grafana.
=> Allow grafana config to override cluster name

apps/myjobs/app/models/workflow.rb, apps/myjobs/app/views/workflows/show.json.jbuilder
Add guard clauses for when staged_dir and script_path are nil in a workflow which can happen in a rare cases that have yet to be determined (something obviously went wrong  in the staging process).
=> job composer guard clauses for nil staged_dir/script_path

ood-portal-generator/lib/ood_portal_generator/view.rb, ood-portal-generator/share/ood_portal_example.yml, ood-portal-generator/spec/fixtures/ood-portal.conf.dex, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-full, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-ldap, ood-portal-generator/spec/fixtures/ood-portal.conf.oidc, ood-portal-generator/spec/fixtures/ood-portal.conf.oidc-ssl, ood-portal-generator/templates/ood-portal.conf.erb
This sets OIDCCookieSameSite to On by default without SSL, and Off (default) with SSL
This is mostly to work around restrictions in Chrome when dealing with non-SSL sites
=> Add ood_cookie_same_site to OIDC configs.

apps/dashboard/app/models/batch_connect/session_context.rb, apps/dashboard/test/models/batch_connect/session_context_test.rb
To reproduce - take a context.json that stores the cache values of any batch connect app, and modify it to include key value pairs where the key is not an attribute defined in the app.
=> dashboard: ignore cache keys that do not exist

apps/files/lib/cloudcmd/lib/client/dom.js, apps/files/lib/cloudcmd/lib/cloudfunc.js
- `templateLink({` is already a handlebars template so it will escape all the values by default, so we don’t need to escape again
- The Go To dialog - we insert the value we get from the URL on the page - which is provided by the user - and in this case may contain bad characters
- since its the only dialog that takes the current browser URL and displays the value, this is the only one we escape
=> More files app escaping

apps/files/package.json, apps/files/yarn.lock
Use resolutions for minimist, node-uuid, and tar-stream to enforce later versions than older ones that are dependended on by cloud commander dependencies.
This is pulling back into production changes we made to 1.6 and 1.7 to address some dependencies with security issues.
=> Files: update dependencies using resolutions

apps/dashboard/app/helpers/application_helper.rb, apps/dashboard/app/views/apps/_app_list_item.html.erb
This hidses FA icons from screen readers and sets the icons to use a real `title` instead of `data-title`. This means screen readers don't read the icons and they just read the text.
Fixes #663
=> make icons aria-hidden and use title in links instead of data-ttitle

apps/dashboard/app/helpers/batch_connect/sessions_helper.rb, apps/dashboard/app/models/batch_connect/app.rb, apps/dashboard/app/models/batch_connect/session.rb, apps/dashboard/app/views/batch_connect/sessions/connections/_info.html.erb
If an interactive session has an `info.{md,html}.erb` file that cannot render properly, this PR fixes the entire page breaking and isolates the error to only break within the session panel itself.
Closes #654
**Merge message:**
* `info.{md,html}.erb` isn't cached anymore, now it is pulled directly from the app directory.
* If a batch connect session has a custom info view and the view has an error while being parsed, `session.render_info_view_error_message` is set.
* Developing a custom info view is a pleasant experience now, you don't have to launch a new session to test your view changes anymore.
**Screenshot:**
=> Show error message if info partial fails to render

apps/dashboard/app/views/dashboard/_xdmod_widget_job_efficiency.html.erb, apps/dashboard/app/views/dashboard/_xdmod_widget_jobs.html.erb, apps/dashboard/app/views/dashboard/index.html.erb, apps/myjobs/Gemfile, apps/myjobs/Gemfile.lock, apps/myjobs/app/assets/javascripts/workflows.js.coffee, apps/myjobs/app/assets/stylesheets/application.css.scss, apps/myjobs/app/helpers/workflows_helper.rb, apps/myjobs/app/models/workflow.rb, apps/myjobs/app/views/workflows/index.html.erb, apps/myjobs/app/views/workflows/show.json.jbuilder, apps/myjobs/config/locales/en.yml, apps/myjobs/test/helpers/workflow_helper_test.rb, apps/myjobs/test/test_helper.rb
Fix xdmod widget layout when no motd:
TODO:
XDMoD links in Job Composer may be broken for 24 hours:
1. i18n key for the xdmod job link warning message 
2. i18n key for the xdmod job link warning timespan (number of seconds after job completes to warn user) - we will display this message after job composer recognizes that the job completed (which is not necessarily the same time/date as the job completing)
3. use modified date of completed job (hack) or add completed date to job when switching from running to completed
4. update view to use i18n keys (bg-warning on paragraph underneath link):
- ![screen 2020-09-19 at 2 13 56 PM](https://user-images.githubusercontent.com/512333/93686174-8149a080-fa82-11ea-97ce-809f04d5219a.png)
- ![screen 2020-09-19 at 2 14 03 …
=> XDMoD integration minor fixes

apps/myjobs/app/assets/javascripts/workflows.js.coffee, apps/myjobs/app/views/workflows/index.html.erb
To match the dashboard widgets, where we change "XDMoD" to "Open XDMoD"
=> Prepend XDMoD with word 'Open'

apps/dashboard/app/apps/ood_app.rb, apps/dashboard/app/models/product.rb, apps/dashboard/app/views/products/_product.html.erb, apps/dashboard/app/views/products/show.html.erb, apps/myjobs/app/controllers/templates_controller.rb, apps/myjobs/app/models/filesystem.rb, apps/myjobs/app/views/templates/_form.html.erb, apps/myjobs/test/models/configuration_singleton_test.rb, apps/myjobs/test/models/filesystem_test.rb
Also remove 'active_users' from developer interface which was broken as of Passenger 6 (and not really used anyways).
=> Properly escape user input by using Open3 capture methods

nginx_stage/nginx_stage.gemspec
Remove these files because installing this will put a 'ruby' file in your PATH which will create a recursive call back to that file.
Then anything trying to build or run ruby will inevitably have many many calls to this file resulting in "/usr/bin/env: 'ruby': Argument list too long" errors.
I came across this this week while refreshing my system to use `rvm` which puts the `GEM_HOME/bin` in the PATH, something I didn't have previously.
Now our builds https://travis-ci.org/github/OSC/ondemand/jobs/739295820#L308 are starting to fail, so it's come to a head.
The `ruby` file in this `bin` directory causes issues when it's dropped into `$GEM_HOME/bin`.  It's not clear why it was initially added, maybe to help development with different versions of ruby? In any case, it's now problematic even …
=> rm spec.executables from nginx_stage

apps/activejobs/app/assets/javascripts/application.js, apps/activejobs/app/assets/stylesheets/jobs.scss
use actual button for job details show/hide, so that it is controllable
using a keyboard
add aria attribute expanded expected by disclosure control
add aria label for button
This results in a slight change in look and feel:
But now since we use a button, you can activate using Enter or Space as expected by https://www.w3.org/TR/wai-aria-practices-1.1/#disclosure and focus on the button:
=> activejobs: use button for details disclosure

.gitlab-ci.yml
This is to be able to build 1.8 RPMs using automated build tools while still building 2.0 on master branch.
The corresponding packaging changes: https://github.com/OSC/ondemand-packaging/pull/93
I will do similar changes to this repo and ondemand-packaging for 1.7.
=> Use OnDemand version specific build repo

.github/labeler.yml
A simple change to add `area/build` labels to PRs based on `lib/tasks` files changed.
=> add area/build labels to PRs

.github/labeler.yml
`component/dashboard` label was being incorrectly applied to `activejobs`
=> Fix component/dashboard labeler action

apps/dashboard/app/controllers/batch_connect/session_contexts_controller.rb, apps/dashboard/test/controllers/batch_connect/session_contexts_controller_test.rb
don't use cached clusters when the cached cluster value conflicts with the current form
As the comment in delete_cached_cluster? says, it's possible to (a) have a cached
cluster value that no longer exists OR the app has simply reconfigured a different
cluster to use.
This is problematic for apps with only 1 cluster because the form presented to the
user does not give an option to change the value. So if you've cached a bad value,
they're stuck with it.
The tests will show the erroneous behavior by checking out app/ to the previous commit.
=> don't always use cached clusters 

.gitlab-ci.yml
gitlab ci use bash variable expansion instead of grep to remove v
=> gitlab ci use bash variable expansion instead of grep to remove v

apps/activejobs/app/assets/javascripts/application.js
This PR updates the `aria-label` for toggle job details and delete job buttons in Active Jobs. I tested this with NVDA Screen Reader and it works as expected. All data is escaped properly.
**Show details** `aria-label`:
```
Toggle visibility of job details for job ondemand/sys/dashboard/sys/bc_osc_rstudio_server on Pitzer
```
**Delete button** `aria-label`:
```
Delete job ondemand/sys/dashboard/sys/bc_osc_rstudio_server with ID 2141764
```
=> Update aria-labels for job details and delete button

mod_ood_proxy/lib/ood/user_map.lua
There's a simple mistake in mod_ood_proxy that's failing e2e tests.
=> removing trailing . from mod_ood_proxy

apps/dashboard/app/controllers/batch_connect/session_contexts_controller.rb, apps/dashboard/test/controllers/batch_connect/session_contexts_controller_test.rb
The original logic in was right because it accounts for clusters defined in the form/attributes. 
https://github.com/OSC/ondemand/pull/748/commits
=> (mainline) deleting clusters needs to account for form defined clusters too

apps/dashboard/app/controllers/batch_connect/session_contexts_controller.rb, apps/dashboard/test/controllers/batch_connect/session_contexts_controller_test.rb
Same as https://github.com/OSC/ondemand/pull/761 but for the 1.8 release branch. 
The original logic in was right because it accounts for clusters defined in the form/attributes.
https://github.com/OSC/ondemand/pull/748/commits
=> deleting clusters needs to account for form defined clusters too

Dockerfile
The move to using `lib` for tasks needs to be copied into container for docker development builds.
=> Fix docker dev builds

ood-portal-generator/share/ood_portal_example.yml
Fixes #775 
Unsure how exactly to test all options exist in the example YAML.  The only thing I could think is dump all instance variables from `OodPortalGenerator::View` and make sure those variable names are listed inside the commented out file.  Does that sound like a viable option?
=> Add user_map_match to example ood_portal.yml

.github/workflows/tests.yml, Dockerfile.dev, docker/dev-entrypoint.sh, lib/tasks/build_utils.rb, lib/tasks/docker.rb, lib/tasks/packaging.rb
This is the development container that I use, so here's a rake task and some files to build it.
It really centers around the fact that I use podman and I can launch this container rootlessly me, so I can also then mount `$HOME/ondemand/dev:$HOME/ondemand/dev` directly into the container and edit the files as me on both sides and I don't have to worry about privilege escalation.
I get this nice ps tree where "root" (UID 100000) starts everything up, but I'm still me.
```text
4 S jeff      608338  607955  0  80   0 - 87066 -      15:30 ?        00:00:00 Passenger watchdog
0 S jeff      608341  608338  0  80   0 - 378633 -     15:30 ?        00:00:00 Passenger core
5 S 100000    608353  607955  0  80   0 - 23078 -      15:30 ?        00:00:00 nginx: master process (jeff) -c …
```
=> add development container and refactor lib/tasks/packaging slightly.

packaging/ondemand-selinux.te
https://discourse.osc.edu/t/selinux-blocks-ondemand-from-talking-to-remote-slurm-server/1275/5
=> Fixes for SELinux policies

.github/workflows/update.yml
As you can see in #848 the commits aren't quite right and aren't tied to the oscwiag user.
=> wrong email address in oscwiag's update task

packaging/ondemand.spec
Do not depend directly on policycoreutils-python since all we need is semanage and that is already a dependency
=> (release 1.8) Fix SELinux package dependencies

packaging/ondemand.spec
Do not depend directly on policycoreutils-python since all we need is semanage and that is already a dependency
=> Fix SELinux package dependencies

docker/dev-entrypoint.sh
I updated to podman 2.2.1 and kernel `5.10.8-100.fc32.x86_64` yesterday and this started to fail for me today.  Apparently mount points with `--userns=keep-id` are much more strict so I can't these files and init the contianers correctly as my regular user.
=> dev container setup in sudo context

apps/dashboard/app/models/batch_connect/session.rb, apps/dashboard/test/models/batch_connect/session_test.rb
Host and password information are held in `script.native` attributes in kubernetes at the moment so this change is needed for the dashboard to recognize it's state and extract the information.
=> K8s dashboard

apps/dashboard/app/apps/featured_app.rb, apps/dashboard/app/apps/nav_config.rb, apps/dashboard/app/apps/ood_app.rb, apps/dashboard/app/apps/router.rb, apps/dashboard/app/controllers/application_controller.rb, apps/dashboard/app/helpers/dashboard_helper.rb, apps/dashboard/app/views/dashboard/_pinned_apps.html.erb, apps/dashboard/app/views/dashboard/index.html.erb, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/config/configuration_singleton_test.rb, apps/dashboard/test/controllers/dashboard_controller_test.rb, apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_desktop/local/owens.yml, apps/dashboard/test/test_helper.rb
Fix for #714.  Currently in draft as it needs test for sure.
If you like the general structure, I'll move forward on tests.
Given a config file like
```yaml
pinned_apps:
- 'sys/bc_osc_codeserver'
```
We'll generate pinned apps icons and navbar entry like so:
=> system pinned apps

nginx_stage/templates/pun.conf.erb
Before this change on OSC deployed OnDemand:
```
Server: nginx/1.18.0 + Phusion Passenger 6.0.7
X-Powered-By: Phusion Passenger 6.0.7
```
After this change logging into Docker based OnDemand:
```
Server: nginx + Phusion Passenger
X-Powered-By: Phusion Passenger
```
=> Hide NGINX and Passenger version information

nginx_stage/templates/pun.conf.erb
=> (Release 1.8) Hide NGINX and Passenger version information

apps/dashboard/app/assets/stylesheets/apps.scss, apps/dashboard/app/views/apps/_app_group_rows.html.erb, apps/dashboard/app/views/apps/_link.html.erb
app links are simplified which fixes the UI issues with the Files dropdown
and underline issues with the other app links
but omits the popovers which are probably misplaced on a table like this
(and not accessible anyways)
The files button is also a two-teir button now where the first link opens the
Files app to the first "favorite" found
The menu is still problematic because it doesn't scroll easily so this optional button
will avoid having to open the menu to just go to your home directory
=> simplify all apps page links

apps/activejobs/config/initializers/session_store.rb, apps/dashboard/config/initializers/session_store.rb, apps/file-editor/config/initializers/session_store.rb, apps/files/lib/cloudcmd/lib/client/ood.js, apps/myjobs/config/initializers/session_store.rb
This adds the secure flag to session cookies:
- _dashboard_session (dashboard)
- _job_constructor_session (job composer)
- _job_status_session (activejobs)
- _ood_app_session (file-editor)
- ownermode (files app)
For all apps except files app:
The secure cookie was set in `config/initializers/session_store.rb`
For files app:
The secure cookie was set in `lib/cloudcmd/lib/client/ood.js` in the `setCookie()` function
=> Changed cookies to be secure in production

apps/dashboard/app/views/layouts/_footer.html.erb
This PR fixes the broken link in the footer of the Dashboard app. The OnDemand logo was linking to the old Open OnDemand repo.
*Old link*
https://osc.github.io/Open-OnDemand/
*New link*
https://openondemand.org
=> Fix OnDemand logo broken link in Dashboard footer

apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/config/configuration_singleton_test.rb, apps/dashboard/test/fixtures/config/ondemand.d/bad_erb.yml.erb, apps/dashboard/test/fixtures/config/ondemand.d/good_erb.yml.erb, apps/dashboard/test/fixtures/config/ondemand.d/not_good_yml.yml, apps/dashboard/test/fixtures/config/ondemand.d/pinned_apps.yml, apps/dashboard/test/fixtures/config/ondemand.d/should_not_read.yml.bak, apps/dashboard/test/fixtures/config/ondemand.d/test_keys.yml, apps/dashboard/test/fixtures/config/ondemand.d/yml_with_a.yaml
add the ability to configure through ondemand.d/y*ml files. Still, only `pinned_apps` is exposed through the Configuration APIs, but arbitrary configurations are still read.
=> add the ability to configure through ondemand.d/y*ml files

apps/dashboard/app/apps/featured_app.rb, apps/dashboard/app/apps/ood_app.rb, apps/dashboard/app/apps/router.rb, apps/dashboard/app/controllers/application_controller.rb, apps/dashboard/app/helpers/dashboard_helper.rb, apps/dashboard/app/views/dashboard/_pinned_apps.html.erb, apps/dashboard/app/views/dashboard/index.html.erb, apps/dashboard/app/views/layouts/application.html.erb, apps/dashboard/test/fixtures/usr/cant_see/app_one/manifest.yml, apps/dashboard/test/fixtures/usr/cant_see/app_two/manifest.yml, apps/dashboard/test/fixtures/usr/me/my_shared_app/manifest.yml, apps/dashboard/test/fixtures/usr/shared/bc_app/form.yml, apps/dashboard/test/fixtures/usr/shared/bc_app/manifest.yml, apps/dashboard/test/fixtures/usr/shared/bc_with_subapps/form.yml, apps/dashboard/test/fixtures/usr/shared/bc_with_subapps/local/oakley.yml, apps/dashboard/test/fixtures/usr/shared/bc_with_subapps/local/owens.yml, apps/dashboard/test/fixtures/usr/shared/bc_with_subapps/manifest.yml, apps/dashboard/test/models/router_test.rb
Router#pinned_apps now supports glob style wildcards like sys/* and
sys/bc_desktop/* (usr/ and dev/ included). This also adds public Router#apps
methods to be possibly useful in the future.
This also adds a OodApp#has_sub_apps? api to determine if an app
in fact has valid sub apps for showing the subapp in the pinned
apps menus.
I can comment in the tickets where behaviour is defined more specifically, but basically here are a few common use cases for this:
```yaml
pinned_apps
- "sys/*"
- "usr/*"
- "sys/bc_desktop/*"
- "usr/some_user/*"
```
=> pinned apps to support wildcard globs

apps/dashboard/test/models/router_test.rb
Fix #908. I tracked that issue down to apps being returned in `@pinned_apps` that should not have been there.  They'd been cached during these test cases, but subsequently during the integration test did not meet `should_appear_in_nav?` requirements and should not have shown up at all.
=> invalidate cached @pinned_apps from Router in tests

apps/dashboard/app/apps/router.rb, apps/dashboard/app/apps/token_matcher.rb, apps/dashboard/app/models/batch_connect/app.rb, apps/dashboard/test/config/configuration_singleton_test.rb, apps/dashboard/test/fixtures/config/ondemand.d/pinned_apps.yml, apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/manifest.yml, apps/dashboard/test/fixtures/sys_with_gateway_apps/pseudofun/manifest.yml, apps/dashboard/test/models/router_test.rb
The final checkbox to fix #714, pinning apps by category, subcategory, type and/or metadata.
=> Pin apps by metadata

apps/dashboard/app/controllers/apps_controller.rb, apps/dashboard/app/views/apps/_app_group_rows.html.erb, apps/dashboard/app/views/apps/index.html.erb, apps/dashboard/test/integration/apps_test.rb
Last thing to fix #715. This adds extra columns to 
There's currently no limitation on how many columns we'd add, so I'm not sure if want to make that configurable or if at all.
Here's what 2 additional columns would look like
=> show metadata columns in the all apps table

apps/dashboard/app/views/apps/_app.html.erb
Looks like I accidentally removed this partial in #884 thinking it was a part of the apps table, but it is in fact a part of the main landing page when usr apps are enabled. So shared apps are broken.  I checked this file out from 01ef72e020f808768607b6bbaa85c4346d6f1ad3, our 2.0.0 tag.
=> add _app partial back for shared apps

apps/bc_desktop/template/desktops/xfce.sh
fixes #700 to eval dbus-launch in xfce so that it can start cleanly with or without a conda environment.
=> eval dbus-launch 

apps/dashboard/app/assets/stylesheets/_breadcrumb.scss, apps/dashboard/app/assets/stylesheets/_variables.scss.erb, apps/dashboard/app/assets/stylesheets/application.scss
Carried over from this conversation https://github.com/OSC/ondemand/pull/927#discussion_r590646363
This makes breadcrumb dividers purely visual for accessibility.  I'm happy to tweak the scss as they look slightly different.
Before:
After (initial):
After (using `0.8em` instead of %)
=> make breadcrumb dividers purely visual for accessability

apps/dashboard/app/views/layouts/nav/_featured_apps.html.erb, apps/dashboard/app/views/layouts/nav/_group.html.erb
This brings the branch up to parity in terms of navbar navigation. The `"role=menu"` seem to make things worse. But in looking at this, I do believe we need to create a follow up ticket for navbar accessability as we use no roles.  So I think clearly there's a need to add roles, it's just not clear where and I don't think the bootstrap upgrade is the place for it anyhow. So this just brings the bootstrap PR to parity with what we currently have. No better, but no worse.
Also the `_featured_apps` partial was just an .erb extension and not an `.html.erb`. I guess it didn't seem to matter to rails, but even so, we should be consistent.
=> parity for the accessability of the current master branch

apps/dashboard/bin/setup
the choice to do bin/yarn without the --production flag should be up to developer but by default we should not exclude the --production flag
=> rm duplicate yarn call in bin/setup

apps/dashboard/app/assets/stylesheets/_custom.scss.erb, apps/dashboard/app/views/dashboard/_xdmod_widget_job_efficiency.html.erb, apps/dashboard/app/views/dashboard/_xdmod_widget_jobs.html.erb
- xdmod header should be h3 not h6 for accessibility
- fixed h3 sizing to be similar to the original bootstrap 3 widgets
- removed header and collocate date with title as in original widgets
NOTE: The efficency report title and the XDMoD links are very close together. This is due to the font size increase in bootstrap 4. Not sure what to do with that yet...
original bootstrap 3 widgets:
after these changes, bootstrap 4:
=> fix xdmod bootstrap4 widget style/header

apps/dashboard/app/views/shared/_insufficient_quota_resource.html.erb
Removed testing text and fixed floating top right help text.
=> Fix insufficient quota banner

apps/dashboard/app/assets/stylesheets/_custom.scss.erb, apps/dashboard/app/assets/stylesheets/_variables.scss.erb, apps/dashboard/app/views/layouts/nav/_styles.html.erb
This PR includes a better default for the font size. https://github.com/OSC/ondemand/blob/de6439b24ffac7ea52ae98b87c3500f1cb3bb448/apps/dashboard/app/assets/stylesheets/_variables.scss.erb#L7
`$primary` color comes from the [Bootstrap 3 SASS variables](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss#L18)
=> Adjust Dashboard branding colors #967

apps/dashboard/app/assets/stylesheets/apps.scss, apps/dashboard/app/views/apps/_app.html.erb, apps/dashboard/app/views/dashboard/_pinned_apps.html.erb, apps/dashboard/test/integration/pinned_apps_test.rb
Was the quickest solution but not sure about extending some of the helper classes (it spaces based on `$spacer`).
```
.app-card {
@extend .card;
@extend .rounded;
@extend .p-2;
@extend .mb-3;
```
=> fix app card styles for bootstrap 4

apps/dashboard/app/helpers/batch_connect/sessions_helper.rb
fix #977
Note that the element containing the button is already in a `float-right`, so it may not be needed. 
https://github.com/OSC/ondemand/blob/0d898a0937119d6f8ae082755ab2a661da4eea1f/apps/dashboard/app/helpers/batch_connect/sessions_helper.rb#L39
=> inner delete button to also use float-right

apps/dashboard/app/assets/stylesheets/application.scss, apps/dashboard/app/views/layouts/application.html.erb
Could fix #962
Setting the navbar's height seems to be problematic. 962 says ".navbar-brand needs a height fixed to the desired height of the navbar".  
The height of the navbar is dynamic.  This PR has this look & feel, but these show the navbar height can't really be reliably known before everything is set in it.
Or maybe `2em` _is_ the desired height of the navar.
40px on my desktop
40px on mobile with awesim's PNG
80px on mobile the OOD svg that's wider than awesim's PNG.  **maybe we need to control the width too?**
When the dropdown is open it's 520!
=> contain the navbar's logo height

apps/dashboard/app/views/shared/_insufficient_balance_resource.html.erb
Fixes #970. 
There is more that we could do in this PR, but I'd like to create a follow up ticket to fix the accessibility with using `h4`s into perhaps using lists instead.  We could also then tweak the font sizes as you can see they went up a little.
mainline:
this PR:
=> upgrade balance warnings to bootstrap 4

apps/dashboard/app/views/files/index.html.erb
Convert file mode (chmod permissions) into a human readable string in the client side of Files App.
=> Add client side file mode conversion in Files App

apps/dashboard/app/views/layouts/application.html.erb
This fixes #951 by only showing the 'Apps' navbar menu item when @featured_group is present because @featured_group is a part of the NavConfig.categories when @pinned_apps isn't.
So `@featured_group` - what's passed into the partial - is nil because it was filtered when `@pinned_apps` is still valid and will be shown on the landing page.
I'd say we put this on hold until we get bootstrap sorted because it may have a conflict after that.
=> Fix #951 (Pinned apps crash)

ood-portal-generator/templates/ood-portal.conf.erb
The link in this template is broken and results in a 404 error. The link I updated it to is the closest page I could find to the original
=> Update link to ood-portal-generator configuration documentation page

apps/dashboard/app/assets/javascripts/application.js, apps/dashboard/app/assets/stylesheets/application.scss, apps/dashboard/app/views/layouts/application.html.erb, apps/dashboard/package.json, apps/dashboard/yarn.lock
Short term solution. Would be preferable to have this in webpack so we don't include the kitchen sink (500k lib though gzipped is still small), but that presents a number of complications. A partial implementation of that is https://github.com/OSC/ondemand/pull/1019.
=> Uppy Simple

apps/dashboard/app/apps/featured_app.rb, apps/dashboard/app/apps/ood_app_group.rb, apps/dashboard/app/assets/stylesheets/apps.scss, apps/dashboard/app/views/dashboard/_pinned_apps.html.erb, apps/dashboard/app/views/dashboard/pinned_apps/_app.html.erb, apps/dashboard/app/views/dashboard/pinned_apps/_group.html.erb, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/config/locales/en.yml, apps/dashboard/test/config/configuration_singleton_test.rb, apps/dashboard/test/integration/pinned_apps_test.rb, apps/dashboard/test/models/ood_app_group_test.rb
Fixes #920
group pinned apps  by their original category and add a heading for each section.  This is essentially making the `dashboard#index` with pinned apps the same as `apps#featured` (i.e., shared apps). 
It is slightly different in the way the widgets are arranged (how they interact with the MOTD and the XDMOD panels) but the partials to generate the rows in `app/views/dashboard/pinned_apps` are basically carbon copies of similar partials in `app/views/apps/`. (only these headings are `h4` instead of `h2`)
`apps#featured`
`dashboard#index`
=> group pinned apps 

CHANGELOG.md
add 1.8.20 to the changelog. Note that this is sorted by version not date, so it's below 2.0.0. Not sure what we want to standardize on as this is the first time it's come up.
=> add 1.8.20 to the changelog

apps/dashboard/app/views/files/index.html.erb
The iframe was using `hidden` instead of `d-none` (Bootstrap visibility control) on the iframe when you're downloading a file.
This PR prevents the iframe container from being shown:
=> Files App – Fix iframe visibility

ood-portal-generator/lib/ood_portal_generator.rb
In response to https://discourse.osc.edu/t/ood-portal-generator-support-oracle-linux-8/1427
=> Fix ood-portal-generator to work with Oracle Linux

ood-portal-generator/lib/ood_portal_generator.rb
In response to https://discourse.osc.edu/t/ood-portal-generator-support-oracle-linux-8/1427
=> (release 1.8) Fix ood-portal-generator to work with Oracle Linux

nginx_stage/templates/pun.conf.erb, spec/e2e/browser_spec.rb, spec/e2e/e2e_helper.rb
redirect old activejobs url to new dashboard activejobs url in the pun config instead of the apache config.
Note this also adds end to end tests for the same and slightly refactors the e2e tests to allow for multiple page hits without logging in every time.
=> redirect old activejobs url to new dashboard 

apps/dashboard/app/apps/ood_app_group.rb, apps/dashboard/test/integration/pinned_apps_test.rb, apps/dashboard/test/models/ood_app_group_test.rb
This allows for pinned_apps to be grouped by metadata fields. To accommodate that a few things had to change. First is that OodAppGroup#groups_for should guarantee that the group with a nil title is always last. This also adds metadata keys as attr_accessor methods to the OodApp, expanding it's interface based off of configuration. Manfiest#metadata keys are now sanitized for a bit of safety for this.
=> configure pinned_apps through metadata fields

apps/dashboard/app/assets/javascripts/active_jobs.js, apps/dashboard/app/helpers/active_jobs_helper.rb, apps/dashboard/app/views/active_jobs/_extended_panel.html.erb, apps/dashboard/app/views/active_jobs/_job_details_node_view.html.erb, apps/dashboard/app/views/active_jobs/index.html.erb, apps/dashboard/app/views/layouts/active_jobs.html.erb
- avoid using small text on headers and body
- use fluid layout to expand entire space
- use Bootstrap 4 cards instead of Bootstrap 3 panels for the details view
- indent the details view cards
- remove bordered and striped table classes to be closer to previous styles (the new ones
made it more difficult to view, especially with the striped view when expanding certain rows)
note:
- doesn't use <ul><li> which may be more semantically desirable
- doesn't fix ganglia table view partial
=> fix activejobs styles for Bootstrap 4

apps/myjobs/app/controllers/workflows_controller.rb
Fixes #692 
ActiveRecord#preload uses a 'where in ...' clause and sqlite3 has limitations of 1000 variables in that 'in' portion. So just get all
workflows.
=> fix #692 by using #all instead of #preload

apps/dashboard/app/views/files/index.html.erb
in files interface, name column has links that trigger download - now they trigger view file
and in the future will trigger file details view
add missing href attrs to row action dropdown, and use the href to determine
the url to open the view window to, rather than using the datatables API
=> change main file link to view instead of download

CHANGELOG.md
Here's a start on the changelog updates.  It's still in unreleased, because at the time of writing it is.
=> update changelog for everything after 2.0.0

CHANGELOG.md
just a quick fix to the changelog to add today as the release date along with a link.
=> add release date to 2.0.1 changelog

nginx_stage/templates/pun.conf.erb
Limit app instances to 1 so apps can safely utilize in memory session data which could actually break functionality with the dashboard app (the node.js apps don't expand to multiple instances by default which is why we didn't have this problem till now).
=> Address some obvious performance issues

packaging/ondemand.spec
On update, replace `HTTPD24_HTTPD_SCLS_ENABLED` with default value, on fresh install make no changes to SCLs loaded by Apache.
=> No longer add rh-ruby SCL to httpd24 enabled SCLs

apps/dashboard/app/views/files/edit.html.erb
by rendering the file editor url and path in html data attributes
and then pulling those using JS we avoid issues with encoding of
characters like & resulting in a malformed url when it is used by JS
=> fix file editor opening files w ampersand in name

apps/dashboard/app/helpers/batch_connect/sessions_helper.rb, apps/dashboard/app/views/batch_connect/sessions/index.js.erb
CSS can only work with HTML id's that follow HTML4 rules, so the id must be prefixed by a letter
UUIDs may be prefixed with a number, and this causes problems when using UUID as an HTML id
in particular, the bootstrap 4 tab control doesn't work if the id's start with a number
The solution:
1. prefix session card id with "id_"
2. prefix connection tab ids with "c_"
3. remove unused ids that were also duplicates of card from tag content wrapper div and nav tabs ul
4. add data-id attribute to session card for convenience use by JS wanting quick access to session id
=> don't use UUID as HTML id  in session card

apps/shell/views/index.hbs
In reference to this discussion on Discourse: https://discourse.osc.edu/t/shell-app-configuration-disable-bell/1455/1
=> Removed Audible Bell by Default in Shell

apps/dashboard/app/helpers/dashboard_helper.rb, apps/dashboard/app/views/dashboard/index.html.erb, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/integration/dashboard_layout_test.rb
Fix #1092
Renames are in external configurations as well as internal usage for consistency.
=> rename landing_page_layout to dashboard_layout

apps/activejobs/manifest.yml, apps/dashboard/app/apps/manifest.rb, apps/dashboard/app/apps/ood_app.rb, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/integration/nav_test.rb, apps/file-editor/manifest.yml, apps/files/manifest.yml, apps/shell/manifest.yml
when default is to open in new window,
any OodApp will open in a new window unless the
manifest of that app specifies otherwise
using new_window: true or new_window: false
set activejobs and files to always open in same window using manifest
set file-editor and shell to always open in new window using manifest
specified default via Configuration.open_apps_in_new_window?
default is true (unless default is changed using OOD_OPEN_APPS_IN_NEW_WINDOW)
=> Control open_apps_in_new_window? using manifest

apps/dashboard/app/views/layouts/nav/_featured_apps.html.erb
Fix #953 by only showing 1 link/app. Meaning the files app only shows the home directory and not all of the favorite paths.
=> only show app.links.first in the feature apps menu 

apps/dashboard/Gemfile, apps/dashboard/Gemfile.lock
Fixes #1079
dalli gem for using memcached is provided as an optional gem to status apps or ihpc apps
=> add optional dalli gem for ihpc apps to use

apps/dashboard/app/assets/javascripts/files.js, apps/dashboard/app/views/files/_shell_dropdown.html.erb, apps/dashboard/app/views/files/index.html.erb, apps/dashboard/app/views/files/index.json.jbuilder, apps/dashboard/config/configuration_singleton.rb
If there are no valid clusters, the default Shell URL is provided by `OodAppkit::ShellUrl`
If there are valid clusters, then the dropdown turns into this:
=> Files App - Open in Terminal Dropdown

spec/e2e/e2e_helper.rb
e2e tests are still flaky so this stabalizes them by checking for connectivity and the text field.  I tested this a bunch in a loop and never got failures, so it should alleviate us for a bit.
=> stabalize e2e tests by checking for connectivity and the text field

Dockerfile.dev, Dockerfile.test, mod_ood_proxy/lib/node_proxy.lua, spec/e2e/e2e_helper.rb, spec/e2e/proxy_spec.rb, spec/fixtures/config/ood_portal/portal_with_proxies.yml, spec/fixtures/extras/simple_origin_server.py
Fixes #1103 and adds a bunch of test cases for testing proxies.
=> Ensure urls in proxies

apps/dashboard/Gemfile, apps/dashboard/Gemfile.lock, apps/dashboard/app/controllers/transfers_controller.rb, apps/dashboard/app/models/transfer.rb, apps/myjobs/Gemfile, apps/myjobs/Gemfile.lock, nginx_stage/lib/nginx_stage.rb
the 12factor gem pulled in two gem dependencies that changed two
configuration values:
1. rails_serve_static_assets set serve static assets to true
2. rails_stdout_logging created a default logger that connected to
STDOUT
in Rails 5, these can be controlled using env vars, so we set
RAILS_LOG_TO_STDOUT in NGINX stage
furthermore, we don't want to enable "serve static assets" from Rails,
since NGINX already serves static assets
when enabled, Rails tries to serve a missing static asset for 404 request,
which includes executing Webpacker::Compiler#compile though that just
pollutes the log file with lines like "[Webpacker] Everything's
up-to-date. Nothing to do"
(https://github.com/rails/webpacker/issues/2392).
So ensuring we disable "serve static assets" from Rails solves this
problem as …
=> remove rails_12factor gem

apps/dashboard/package.json, apps/dashboard/yarn.lock
use yarn resolutions to force postcss and xmlhttprequest-ssl to be later versions
than required by uppy and @rails/webpacker
=> force update postcss & xmlhttprequest-ssl

apps/dashboard/app/apps/router.rb, apps/dashboard/test/fixtures/sys_with_interactive_apps/bc_desktop/local/bad_sub_app.yml.erb
This fixes a bug found by UCCBR where the `submit.yml.erb`'s were being counted as a subapp and causing errors because it was an invalid sub app and had no links.
=> reject invalid subapps in pinned_apps

hooks/k8s-bootstrap/k8s-bootstrap-ondemand.sh
Without this, removing `USE_POD_SECURITY_POLICY` from hook.env would cause the logic that controls to get applied anyways.  This ensure only `USE_POD_SECURITY_POLICY=true` being present will apply that logic.
=> Fix for K8 bootstrap hooks

apps/dashboard/app/views/layouts/_browser_warning.html.erb
Removes the browser warning banner:
=> Remove mobile browser warning banner in Dashboard

apps/dashboard/app/controllers/files_controller.rb
fix #1164 by creating parent directory, not path. I tested this for subdirectories too.
=> fix #1164 by creating parent directory, not path

hooks/k8s-bootstrap/k8s-bootstrap-ondemand.sh, hooks/k8s-bootstrap/yaml/namespace.yaml
Right now I have https://github.com/OSC/k8-namespace-reaper that will reap unused K8 namespaces because at some point we will have the K8 hook run for all OnDemand users at OSC and I don't want an ever growing list of namespaces, most of which won't be used. The reaping happens on an interval but to avoid reaping a namespace of someone who is logged in I need some way to know the last time the K8 hook was executed so that the k8-namespace-reaper code can look at that timestamp and still only reap namespaces that are truly idle and unused.
=> Add annotation to K8 namespace of when hook was last used

nginx_stage/lib/nginx_stage/configuration.rb, nginx_stage/lib/nginx_stage/views/pun_config_view.rb, nginx_stage/share/nginx_stage_example.yml, nginx_stage/templates/pun.conf.erb
=> Support setting passenger_pool_idle_time

nginx_stage/lib/nginx_stage/configuration.rb, nginx_stage/lib/nginx_stage/views/pun_config_view.rb, nginx_stage/share/nginx_stage_example.yml, nginx_stage/templates/pun.conf.erb
Fixes #1210
If we don't auto set the `passenger_` prefix then we are essentially allowing any NGINX options, which might be better to change config option name.
=> Support custom passenger options for NGINX PUN

.github/workflows/pr-labeler.yml
use `pull_request_target` so PRs from forks can securely apply labels on the PRs they create.
=> use pull_request_target so PRs from forks can create labels

apps/dashboard/test/integration/apps_test.rb, apps/dashboard/test/models/router_test.rb, apps/dashboard/test/test_helper.rb
refactor some usr stubbing helpers because I'm working on #1243 and all usr routing tests seem to follow the same setup & teardown patterns.  I thought it'd be better to refactor in a separate PR to reduce complexity of any one given PR.
=> refactor some usr stubbing helpers

ood-portal-generator/lib/ood_portal_generator/view.rb, ood-portal-generator/spec/fixtures/ood-portal.conf.all, ood-portal-generator/spec/fixtures/ood_portal.yaml.all, ood-portal-generator/templates/ood-portal.conf.erb
These changes are to add CORS support to the Apache server.
CORS is needed to access the dashboard API from a front end application in a different domain.
This is a proposal that have worked for us while doing the API prototyping.
=> Added support for CORS to the Apache configuration

ood-portal-generator/lib/ood_portal_generator/view.rb, ood-portal-generator/spec/fixtures/ood-portal.conf.all, ood-portal-generator/spec/fixtures/ood_portal.yaml.all, ood-portal-generator/templates/ood-portal.conf.erb
This is a proposal to add API client authorization using an API key and secret. This is on top of the existing end user authentication. For API requests, both will be needed.
This model is compatible and with OOD current user authentication and Apache configuration.
It used mod_rewrite to check the HTTP headers: `X-OOD-API-ID` and `X-OOD-API-CLIENT-SECRET`.
The combination of the two header values form a filename that if created in the configured directory, access is granted.
These files will be managed by system administrators.
It is a simple implementation, easy to understand and has the following benefits:
- All clients will have to register to obtain credentials.
- Client credentials can be revoked by sys admins at any time.
- Client secrets can be rotated periodically to improve …
=> Added support for API key and secret to Apache for API clients

apps/dashboard/app/models/batch_connect/session.rb, apps/dashboard/test/models/batch_connect/session_test.rb
=> Fix ssh_to_compute_node? to not error on non-existant cluster

.rubocop.yml
Here's an initial rubocop file taken from just what I've found is the style of the project so far.
I don't think we should symlink it around given how we move the subdirectories when we install, it'll just create a bunch of broken links. So, our vscode or similar settings should just look for this file wherever it is.
=> add a rubocop

apps/dashboard/app/models/batch_connect/app.rb, apps/dashboard/test/models/batch_connect/app_test.rb, apps/dashboard/test/models/batch_connect/session_test.rb
[Trey asked this question](https://github.com/OSC/bc_osc_jupyter/pull/61#discussion_r656458291) which reminded me of this bug I found while working on #1159.
They are unrelated but I ran into this stack trace during that PR while writing tests. This PR removes those stubs they're now no longer necessary, but the stack illustrates the point - you're referencing `clusters` in the logic of the method, but we have short circuit based on `configured_clusters`.
```text
Error:
BatchConnect::SessionTest#test_session_is_running?_when_info.running_and_connection.yml_exists:
NoMethodError: undefined method `id' for nil:NilClass
app/models/batch_connect/app.rb:373:in `add_cluster_widget'
app/models/batch_connect/app.rb:197:in `build_session_context'
test/models/batch_connect/session_test.rb:361:in …
```
=> short circuit based on clusters not configured_clusters.

apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/config/configuration_singleton_test.rb
Fixed a small bug that caused setting environmental variable OOD_NAVBAR_TYPE to light to not work as expected.
=> Fix OOD_NAVBAR_TYPE=light not working

apps/dashboard/Rakefile
=> Setting RAILS_ENV to ignore .env.local type files for testing.

Rakefile
Fix #856 to add 'yarn upgrade' to the update rake task. Replaces #905.
=> add 'yarn upgrade' to the update rake task

apps/dashboard/app/views/files/_shell_dropdown.html.erb
Fixes #1315.
fix shell dropdown menu to correctly redirect to the shell app. This also slightly cleans that ERB becuase the `<% } %>` threw me off.
=> fix shell dropdown menu to correctly redirect to the shell app

apps/dashboard/app/controllers/application_controller.rb, apps/dashboard/config/application.rb, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/config/environments/production.rb, apps/dashboard/config/initializers/locales.rb
Fixes #1252. 
I can really only test this manually - but here's the test where Cluster dropdown _could_ be in `zh-CN`, but there's no translation for them so they're in english. I.e., the fallback to english worked.
There's not clean way to test in system or integration tests because the system boots up and sets defaults (english) that, even if you override in a test case, everything's already setup, you can't reset it. So looks like we'll have to add some end-to-end coverage for locales.
=> fix locale fallbacks so they actually fallback

apps/dashboard/app/apps/manifest.rb
Fixes #238  we seem to use safe load every where else. I tried to come up with a test case - but couldn't manage to actually get ruby code to execute.
=> safely read yaml

.github/workflows/tests.yml, .gitignore, lib/tasks/packaging.rb
Example execution:
```
rake package:rpm[el7] VERSION=2.0.15
```
The Github action just takes latest tag in git repo and uses that since the package isn't getting used, just need some version to use for building tar and passing to build script to match tar file.
Fixes #1265
=> Add RPM packaging tests and RPM packaging rake task

.github/workflows/update.yml
fix the update workflow to use bundle exec because we've been changing that top Rakefile a bit.
=> fix the update workflow to use bundle exec

apps/dashboard/app/javascript/packs/fa/faIconInfo.js, apps/dashboard/app/javascript/packs/fa/faIconPicker.js, apps/dashboard/app/views/products/_form_icon.html.erb, apps/dashboard/config/webpack/environment.js
refactor fa icon info into a webpack.
The `_form_icon.html.erb` in this change was dos encoded and I switched it to unix so that's why it looks as if it's changed more than it has. What has _really_ changed in it is only removing the `script` element to a pack and adding the pack_tag.
=> refactor fa icon info into a webpack

.github/workflows/tests.yml
There was a failure in #1335 and was impossible to know what broke without adding `-v` flag to print mock RPM build output.
=> Make RPM package tests verbose for easier debugging

.gitlab-ci.yml, lib/tasks/lint.rb, lib/tasks/packaging.rb
Fixes #1366 
The version of nightly RPM where latest OnDemand tag is `v2.0.15` would be `v2.0.15-99.20210825.nightly`.  So each days build will be seen as an upgrade by YUM/DNF.  
I think one way to test this is not merge, but leave in this branch and setup gitlab CI pipeline schedule to build off this branch to test with.
I already bootstrapped the nightly repos using ondemand-packaging scripts.
=> Support nightly RPM builds

Dockerfile, Gemfile, Gemfile.lock, docker/dev-entrypoint.sh, docker/launch-ood, lib/tasks/development.rb, lib/tasks/lint.rb, ood-portal-generator/Gemfile, ood-portal-generator/Gemfile.lock, ood-portal-generator/lib/ood_portal_generator/application.rb, ood-portal-generator/lib/ood_portal_generator/dex.rb, ood-portal-generator/spec/application_spec.rb, ood-portal-generator/spec/fixtures/dex.yaml.default, ood-portal-generator/spec/fixtures/dex.yaml.static_passwords, packaging/ondemand.spec, spec/e2e/e2e_helper.rb
Fixes #1318 
Also mount ondemand repo local path to container at `/ondemand` so don't have to rebuild entire container over and over to test small changes, can mount code and reinstall code into running container without full rebuild.  This is what `docker` namespace tasks do which I figured the `dev` namespace would replace.
=> Support Dex local users

nginx_stage/lib/nginx_stage/configuration.rb, ood-portal-generator/lib/ood_portal_generator/view.rb, ood-portal-generator/share/ood_portal_example.yml, ood-portal-generator/spec/application_spec.rb, ood-portal-generator/spec/fixtures/input/allowlist.yml, ood-portal-generator/spec/fixtures/input/both_lists.yml, ood-portal-generator/spec/fixtures/input/whitelist.yml, ood-portal-generator/spec/fixtures/output/allowlist.conf, ood-portal-generator/spec/spec_helper.rb, ood-portal-generator/templates/ood-portal.conf.erb
Deals with ips and ood_portal_generator
=> IPS & ood-portal-generator: Change whitelist to allowlist

.rubocop.yml
This is a quick fix to the rubocop for `Layout/HashAlignment`. I can't replicate this output we see in our CI, so I'm not really sure what's going on (CI has a different version of rubocop?)
```text
Run bundle exec rake lint || true
bundle exec rake lint || true
shell: /usr/bin/bash -e {0}
Warning: Layout/HashAlignment does not support EnforcedStyle parameter.
Supported parameters are:
- Enabled
- AllowMultipleStyles
- EnforcedHashRocketStyle
- SupportedHashRocketStyles
- EnforcedColonStyle
- SupportedColonStyles
- EnforcedLastArgumentHashStyle
- SupportedLastArgumentHashStyles
apps/dashboard/config/initializers/browser.rb: Metrics/LineLength has the wrong namespace - should be Layout
apps/dashboard/config/initializers/browser.rb: Metrics/LineLength has the wrong namespace - should be …
```
=> fix HashAlignment rubocop

.github/workflows/changelog.yml
fixes #1388 by add workflow regularly update changelog.
Now the output doesn't look super pretty, but most entries will be removed anyhow. The expectation is that this workflow will open a new pull request that we can then manually fix up.
=> add workflow regularly update changelog

.github/workflows/changelog.yml
fix update changelog workflow. Sets the right PR title and commit user. Also grabs more commits so it can search through the history.
=> fix update changelog workflow

.github/workflows/changelog.yml
OK - I looked this up in PAM now instead of just relying on my memory of the email address for the osc-bot user.
=> changelog workflow use right email

apps/dashboard/config/initializers/session_store.rb, apps/myjobs/config/initializers/session_store.rb
use strict same site cookies because there's no real advantage to lax. I mean the session store cookies serve no purpose on another site.
Also just to get rid of these warnings:
=> use strict same site cookies

apps/dashboard/app/models/batch_connect/session.rb, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/models/batch_connect/session_test.rb
Fixes #1328
Batch connect apps to use a per cluster dataroot to support sites that have seperate file systems for each cluster.
Surprisingly, all the tests still pass. Mostly because we have stubs for `dataroot` in all the tests.
This feature should have:
=> batch connect apps to use a per cluster dataroot

.rubocop.yml, lib/tasks/test.rb
Fixes #1423 although it doesn't cache node_modules. That's sort of a bigger change with the way `bin/setup` works.
The additional rubocop entry is just something I found we needed when I updated this file.
=> add shell app to unit tests

lib/tasks/development.rb
Working over the weekend I found that I needed to set term widths when I exec into a container.
=> set term widths for rake dev:exec

ood-portal-generator/checksum.rb, ood-portal-generator/spec/fixtures/ood-portal.conf.all, ood-portal-generator/spec/fixtures/ood-portal.conf.default, ood-portal-generator/spec/fixtures/ood-portal.conf.dex, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-full, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-ldap, ood-portal-generator/spec/fixtures/ood-portal.conf.maint_with_ips, ood-portal-generator/spec/fixtures/ood-portal.conf.oidc, ood-portal-generator/spec/fixtures/ood-portal.conf.oidc-ssl, ood-portal-generator/spec/fixtures/ood-portal.dex-full.proxy.conf, ood-portal-generator/spec/fixtures/sum.default, ood-portal-generator/templates/ood-portal.conf.erb
Fixes #1271 so we can start to cache images (again? seems we missed it when the change was made).
I tracked the change down to #370. @treydock do you recall off hand why we needed a Cache-Control header for maintenance mode?
https://github.com/OSC/ondemand/blob/7222ff58cc4edea65e6e3b3abc38ca8dd2047e8d/ood-portal-generator/templates/ood-portal.conf.erb#L95
This PR also adds a `checksum.rb` as a helper when we need to update these templates and need a new checksum to test against. Also, you'll note that I only changed 1 of the sum file fixtures. `sum.dex` and `sum.not-default` are being loaded in tests, though I'm not quite sure why they're not being evaluated or respected.
=> rm Cache-Control header so we can cache images

apps/dashboard/app/controllers/transfers_controller.rb, apps/dashboard/app/views/files/index.html.erb
To fix the 404 loop, stop transfer polling after 3 attempts to delete the file / directory and display an error message to user.
Error message: "Operation may not have happened. Failed to retrieve file operation status."
=> Add retry attempt counter to 404 loop to fix client side loop

apps/shell/test/helpers.test.js, apps/shell/test/no.defaults.clusters.d/pitzer.yml, apps/shell/test/no.defaults.clusters.d/ruby.yml, apps/shell/utils/helpers.js
#1427 missed this one feature where if there's no default ssh host defined, we just use the first one available. This fixes that bug.
=> bugfix to define the default ssh host if it is not specified

CHANGELOG.md, apps/dashboard/app/controllers/files_controller.rb
Same as #1435 but for the 2.0 release branch. Force SVGs to be downloaded (2.0 backport).
=> Force SVGs to be downloaded (2.0 backport)

.github/workflows/tests.yml, packaging/deb/control, packaging/rpm/ondemand.spec, spec/e2e/e2e_helper.rb
The runtime updates to nodejs 14, fixes #1382
Require NGINX 1.20.1, fixes #1440
Remove dependency on ondemand-python
Bump E2E test version
@johrstrom I am hoping this will resolve issues you saw in #1548
=> Prepare for 2.1

.github/workflows/release.yml, lib/tasks/packaging.rb, packaging/rpm/ondemand.spec
Fixes #1546
@johrstrom Because the release action needs the release URL, the release page is also generated using actions.  I think that means that to do a new tag, you use git to generate tag, push that tag and then a new release page is created as draft and you can go in and make edits to that draft release.
=> Push ondemand tar.gz to release page on tags

apps/dashboard/app/helpers/application_helper.rb, apps/dashboard/app/helpers/batch_connect/sessions_helper.rb
Fixes #1565.
`icon` provided by font-awesome-sass isn't available anymore. Luckily we already have `fa_icon` api. All I had to do was fix it up so that `app-icon` as a class can be overridden.
=> icon provided by font-awesome-sass no longer provided

apps/dashboard/Gemfile, apps/dashboard/Gemfile.lock
cant get rid of sass-rails just yet. This should fix the update CI and other build errors we're seeing.
=> cant get rid of sass-rails just yet

ood-portal-generator/lib/ood_portal_generator/application.rb, ood-portal-generator/spec/application_spec.rb, packaging/deb/postinst, packaging/deb/postrm, packaging/deb/rules
Use absolute paths for Apache symlinks, works with Puppet
Ensure that both ood-portal.conf and checksum exist inside package to do what RPM does to make things behave the same with automation
Also use the sites-available which is where vhost configs go.
=> Numerous fixes for deb package

.github/workflows/tests.yml, apps/dashboard/app/models/batch_connect/app.rb, apps/dashboard/test/fixtures/config/clusters.d/ruby.yml, apps/dashboard/test/integration/apps_test.rb, apps/dashboard/test/models/batch_connect/app_test.rb, apps/dashboard/test/models/batch_connect/session_test.rb, apps/dashboard/test/system/batch_connect_test.rb, apps/dashboard/test/test_helper.rb
I believe this is ready now. I believe `OodCore::Clusters`'s order is determined by the order the files are read which may be platform dependent.  This is currently breaking tests because our CI seems to be different than our laptops.
The main fix here is for `BatchConnect::App#cluster` to try to preserve the order of how things are defined in the `form.*` file, not the order they were read off disk which is how `OodCore::Clusters`' (and subsequently ood appkit) seem to behave.
Globs configurations like `o*` or just `*` for all clusters do not guarantee any order.
Test files have been updated because they had stubs at the wrong layer. Tests now read fixture files directly instead of stubbing at some other layer.
=> ensure bc clusters preserve the order

apps/dashboard/app/views/files/index.html.erb
Relates to #1378.  (I don't want to automatically close this yet).
I can't quite get 1378 to trigger, but I believe this resolves it. A google search and a spot check show that Linux default TCP TTL is 64 and Windows is 128. So, I set this to the larger, even if we don't support Windows - though I can reset to 64 if we think that better.
=> extend the timeout for uppy uploads

.github/workflows/tests.yml, spec/e2e/e2e_helper.rb
Release 2.0 for #1556
Needed so any pull requests targeting 2.0 will have E2E tests work.
=> Use versioned build repo for E2E tests (Release 2.0)

ood-portal-generator/checksum.rb, ood-portal-generator/spec/fixtures/ood-portal.conf.all, ood-portal-generator/spec/fixtures/ood-portal.conf.default, ood-portal-generator/spec/fixtures/ood-portal.conf.dex, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-full, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-ldap, ood-portal-generator/spec/fixtures/ood-portal.conf.maint_with_ips, ood-portal-generator/spec/fixtures/ood-portal.conf.nomaint, ood-portal-generator/spec/fixtures/ood-portal.conf.oidc, ood-portal-generator/spec/fixtures/ood-portal.conf.oidc-ssl, ood-portal-generator/spec/fixtures/ood-portal.dex-full.proxy.conf, ood-portal-generator/spec/fixtures/sum.default, ood-portal-generator/templates/ood-portal.conf.erb
A release 2.0 of #1618
* Removed Index from Public RootOptions as to not allow Directory Indexing - Issues #1617
* Cleaned up ood-portal.conf.erb and updated fixtures to not contain Indexes
* Updated CheckSum for ood-portal.conf.default
=> Removed Index from Public RootOptions as to not allow Directory Index

apps/dashboard/app/javascript/packs/batchConnect.js, apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml, apps/dashboard/test/system/batch_connect_test.rb
Fixes #1607.
Here the `Table` class is going to normalize keys internally as a pose to the upper layers having to keep track of things.
This means `any-40core` turns into `any_40core` internally.
This also fixes bugs with snake casing words with hyphens in them.
=> normalize keys in table to account for options with hyphens

apps/dashboard/app/javascript/packs/batchConnect.js, apps/dashboard/app/views/batch_connect/session_contexts/_form.html.erb, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/application_system_test_case.rb, apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml, apps/dashboard/test/system/batch_connect_test.rb, apps/dashboard/test/test_helper.rb
This backports dynamic batch connect javascript to 2.0. I didn't want to do this initially, but we at OSC need this for classrooms next semester.
=> backport dynamic javascript to 2.0

apps/dashboard/app/apps/featured_app.rb, apps/dashboard/config/locales/en.yml, apps/dashboard/test/integration/pinned_apps_test.rb
Alternative solution to #1664.
Internationalizes the title for the featured apps in the navbar.
=> Internationalize Apps menu title

apps/dashboard/app/javascript/packs/batchConnect.js, apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml, apps/dashboard/test/system/batch_connect_test.rb
account for options with numbers after hyphens & underscores.
Options like this do not work. The key we're looking for is `Physics-1234` which preserves the hyphen. 
```yaml
data-option-for-classroom-physics-1234: false
```
You can see with a configuration like that above is translated to this in HTML:
But in jQuery you can see the that the hyphen is preserved.
=> account for options with numbers after hyphens & underscores

apps/dashboard/app/views/products/new_from_git_remote.html.erb
To test, do the following:
DEV URL: https://ondemand-dev.osc.edu/pun/dev/dashboard/admin/usr/products/new_from_git_remote
Navigate to ondemand-dev
Click "Develop" and then "My Shared Apps (Production)"
On next page, click "New App" button
On "New App" Page, click the "Back" Button.
It will take you to the Products Index page
=> Fix backbutton issue on new app page

CHANGELOG.md, apps/dashboard/app/javascript/packs/batchConnect.js, apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml, apps/dashboard/test/system/batch_connect_test.rb
Backport these 3 dynamic javascript bugfixes to 2.0.
- Dynamic javascript now correctly clamps values correcting [1649](https://github.com/OSC/ondemand/issues/1649).
- Dynamic javascript can hide multiple elements correcting [1666](https://github.com/OSC/ondemand/issues/1666).
- Dynamic javascript now correctly handles options with numbers, hyphens and underscores
back-porting [1656](https://github.com/OSC/ondemand/pull/1656).
=> Backport js fixes

apps/dashboard/app/javascript/packs/batchConnect.js, apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml, apps/dashboard/test/system/batch_connect_test.rb
While #1656 may have fixed options with numbers, it broke options with hyhens (like clusters that are named `kubernetes-test`). It seems to be a very simple mistake with an extra `[` in the regex and sadly, there was no test case for the same.
=> options with hyphens still dont work right

.gitlab-ci.yml
Still need to clone non-gem to push packages to repos as those are still Python scripts.  The actual packaging is gem, the push to repo server is not yet.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201546099455280/1201613089927415) by [Unito](https://www.unito.io)
=> Fix nightlies

DEVELOPMENT.md, lib/tasks/development.rb
allow for additonal capabilites in the dev container with some documentation.
I'm having to add `net_admin` and `net_raw` so I can play with iptables in the container.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201546099455280/1201573096078266) by [Unito](https://www.unito.io)
=> allow for additonal capabilites in the dev container

apps/dashboard/app/views/active_jobs/_job_details_node_view.html.erb
The "Detail Metrics" link to Grafana was broken for us as it was missing the jobid. Not sure if this was intentionally left out but this patch works well for us and pains the link correctly.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201625178070145/1201662052788860) by [Unito](https://www.unito.io)
=> Add jobid to Detail Metrics link

apps/dashboard/app/models/jobs/project.rb, apps/dashboard/test/integration/jobs_controller_test.rb
In looking this feature branch over to pull into the mainline - I made these small additions. Primarily - to use `OodAppKit.dataroot` like other apps and to ensure it's safe to do that.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201625178070145/1201675722026924) by [Unito](https://www.unito.io)
=> use dataroot and ensure its safe to use & traverse

mod_ood_proxy/lib/nginx.lua
This should limit the redirects as needed for Issue #1663
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201625178070145/1201695829260909) by [Unito](https://www.unito.io)
=> validate the redir on stop requests

apps/dashboard/test/config/configuration_singleton_test.rb
#1765 showed that this test case relies on the fixture file. Let's change the test case to remove the reliance of the file and instead write out a temp file to test against.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201625178070145/1201682645298791) by [Unito](https://www.unito.io)
=> Fix boolean test

nginx_stage/lib/nginx_stage/configuration.rb
This PR fixes a bug we found while trying to enable `passenger_options` in `nginx_stage.yml`.
Error -- undefined method `starts_with?' for "passenger_friendly_error_pages":String
Did you mean?  start_with?
Run 'nginx_stage --help' to see a full list of available command line options.
`starts_with?` is available in Rails only, and is deprecated anyway from what I understand.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201625178070145/1201727777708717) by [Unito](https://www.unito.io)
=> Fix passenger_options using wrong method

apps/dashboard/app/javascript/packs/products_show.js, apps/dashboard/test/fixtures/sys_with_gateway_apps/dashboard/.bundle/config, apps/dashboard/test/fixtures/sys_with_gateway_apps/dashboard/Gemfile.lock, apps/dashboard/test/system/products_dev_test.rb
#1782 changed how modals are imported and broke this feature, so this is to add test cases for pressing buttons in products show.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737259084270) by [Unito](https://www.unito.io)
=> add test cases for pressing buttons in products show

packaging/ondemand.spec, spec/e2e/nodesets/el8.yml
Pulls in https://github.com/OSC/ondemand-packaging/pull/187 so that when someone does `yum update ondemand` or fresh install, the dependency is fixed. This mostly affects fresh installs.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201754840610064) by [Unito](https://www.unito.io)
=> Bump ondemand-runtime dependency

apps/dashboard/Gemfile, apps/dashboard/Gemfile.lock, apps/dashboard/app/views/layouts/application.html.erb, apps/dashboard/config/configuration_singleton.rb
Fixes #1809 by removing turoblinks.
I don't know how many sites enabled turoblinks, but I don't know how much I like relying on a package that's been archived anyhow.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201767819725804) by [Unito](https://www.unito.io)
=> remove turobolinks

apps/dashboard/app/apps/ood_app_link.rb, apps/dashboard/app/controllers/batch_connect/session_contexts_controller.rb, apps/dashboard/app/models/batch_connect/app.rb, apps/dashboard/app/views/batch_connect/shared/_app_list_item.html.erb, apps/dashboard/app/views/layouts/nav/_featured_apps.html.erb, apps/dashboard/app/views/layouts/nav/_group.html.erb, apps/dashboard/app/views/widgets/pinned_apps/_app.html.erb, apps/dashboard/test/application_system_test_case.rb, apps/dashboard/test/fixtures/apps/preset_app/form.yml, apps/dashboard/test/fixtures/apps/preset_app/local/preset.yml, apps/dashboard/test/fixtures/apps/preset_app/manifest.yml, apps/dashboard/test/system/preset_apps_navbar_test.rb, apps/dashboard/test/system/preset_apps_pinned_test.rb
Starts work on #1175.
The premise of this functionality is hard coding all the values in a sub app.
Let's took at this example app that has 3 fields.
```yaml
cluster: 'owens'
form:
- account
- node_type
- version
```
And the sub-app  that's hard coded all the attributes.
```yaml
attributes:
account: 'abc123'
node_type: 'any'
version: 7
```
Now all the links are will be empty POST requests to create the sessions instead of a GET request to the form.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201772179663434) by [Unito](https://www.unito.io)
=> preset apps can just launch

mod_ood_proxy/lib/nginx.lua, spec/e2e/proxy_spec.rb
Fixes #1800 to correctly redirect from `/nginx/stop`.
How to test - 
* get a container
* mount this addition into the container by setting `OOD_MNT_PROXY`
* login
* restart the PUN and you should be correctly redirected to `/pun/sys/dashboard`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201847407045909) by [Unito](https://www.unito.io)
=> fix /nginx/stop redirections

apps/dashboard/app/controllers/files_controller.rb
This PR fixes a bug we found where uploaded files had incorrect permissions when the umask was 0007.
umask 0007 gave the permissions:
`----rw-r-x. 1 robinkar robinkar 0 Feb 21 16:31 test.txt`
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201860781440061) by [Unito](https://www.unito.io)
=> Fix incorrect permissions on uploaded file

apps/myjobs/app/models/resource_mgr_adapter.rb, apps/myjobs/app/models/workflow.rb, apps/myjobs/app/views/workflows/_edit_form_job_attrs.html.erb, apps/myjobs/config/locales/en.yml
allow for job composer to copy environment so things like `srun` in Slurm work of out the box.
To test, I just copied the default job and began to edit it
* allocate more cores through `#SBATCH --ntasks=5` comment
* add a `srun hostname` to the file so it uses srun
* run with copy environment checked (this will work)
* run without copy environment checked (this will complain about srun)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201863073369921) by [Unito](https://www.unito.io)
=> allow for job composer to copy environment

apps/dashboard/app/controllers/files_controller.rb
This PR fixed a bug we also found yesterday.
Uploading files always uses the default group owner and does not respect the setgid bit for the directory. This is important for us as our project directories use the setgid bit.
e.g.
```
mkdir test
chgrp some_group test
chmod g+s test
touch test/file.txt
```
Uploading a file via OOD to the `test` directory would have the wrong group while the correct group would be the one that `file.txt` has.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201872852242021) by [Unito](https://www.unito.io)
=> Fix uploaded file group owner

nginx_stage/lib/nginx_stage/user.rb, nginx_stage/spec/user_spec.rb
This backports #1816 to 2.0.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201875003888865) by [Unito](https://www.unito.io)
=> backport #1816

apps/dashboard/app/controllers/files_controller.rb
This backports a couple of file uploading bug fixes. One with umask (#1845) and another for setgid bits (#1851).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201874954338113) by [Unito](https://www.unito.io)
=> Backport file updates to 2.0

nginx_stage/templates/app.conf.erb, nginx_stage/templates/pun.conf.erb
This allows users to re-initialize dev apps when the app.conf is broken (e.g. due to app_root path change).
If Open OnDemand is configured to "[Make everyone a developer by default](https://osc.github.io/ood-documentation/latest/app-development/enabling-development-mode.html#make-everyone-a-developer-by-default-optional)," then the app initialization process (`nginx_stage app`) will write the user's home directory path to the app config file (`/var/lib/ondemand-nginx/config/apps/dev/%{owner}/%{name}.conf`). If the path to the user's home directory then later changes, the app will not load, and visiting the app URL will result in a bare nginx 404 page:
At this point, the user could restore the app functionality by re-initializing the app, but there is no link for this in the UI. The link …
=> Use the same 404 error message in app.conf.erb as in pun.conf.erb

apps/dashboard/app/javascript/packs/config.js
correctly append css rules to the end of the list. `styles.lenth` is not only a mistype that evaluates to `undefined` and puts the rules at the top of the list - it should be `styles.rules.length` to append the rules to the bottom.
=> correctly append css rules to the end of the list

.github/workflows/release.yml, .zenodo.json
A replacement for #1885 to use a GH action instead of our own rake task.
This is our zenodo artifact https://zenodo.org/record/6325946#.Yid-QerMJPY with doi for all versions being https://doi.org/10.5281/zenodo.6323791
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201922183782012) by [Unito](https://www.unito.io)
=> add an action to release archives to zenodo

apps/dashboard/Gemfile, apps/dashboard/Gemfile.lock, apps/dashboard/app/apps/manifest.rb
Fixes #1868 by moving resetting the sprockets dependency (the other Manifest).  We really don't need sprockets anymore, but rails requires _a_ version of it, so may as well be the latest in 3.7.
=> fix Manifest superclass issue

apps/dashboard/app/views/layouts/application.html.erb, apps/dashboard/app/views/layouts/editor.html.erb, apps/dashboard/config/initializers/content_security_policy.rb
This enable nonces on js and css assets.
You'll start to see a header a lot like this
```
[Content-Security-Policy: default-src 'self' https:; font-src 'self' https: data:; img-src 'self' https: data:; object-src 'none'; script-src 'self' https: 'nonce-um92Kvq+YpwJX9z74sfSMA=='; style-src 'self' https: 'nonce-um92Kvq+YpwJX9z74sfSMA=='; connect-src 'self' https: localhost:3035 ws://localhost:3035
```
See the docs for content security policy and specifically the part about nonces.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
=> enable nonces on js and css assets

apps/dashboard/app/helpers/dashboard_helper.rb
Stop inlining style and instead use a bootstrap class for the logo image.
=> stop inlining style and instead use a bootstrap class

apps/dashboard/Gemfile, apps/dashboard/Gemfile.lock
Reverts OSC/ondemand#1914
That PR did not actually do anything WRT #1868, so this is to revert it.
=> Revert "fix Manifest superclass issue"

apps/dashboard/app/views/layouts/application.html.erb, apps/dashboard/app/views/widgets/_xdmod_widget_job_efficiency.html.erb, apps/dashboard/app/views/widgets/_xdmod_widget_jobs.html.erb
add nonces to inline js and change the element tag of this `script` because it's not really a script.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202015403377175) by [Unito](https://www.unito.io)
=> add nonces to inline js and change this elements tag

apps/dashboard/app/apps/manifest.rb, apps/dashboard/test/models/manifest_test.rb
Fix #1868  by having subclass manifests within the class to avoid superclass mismatches.
I think we're OK given nothing else references the subclasses.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202015484285621) by [Unito](https://www.unito.io)
=> subclass manifests within the class to avoid superclass mismatches

apps/dashboard/app/models/hpc_module.rb, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/config/configuration_singleton_test.rb, apps/dashboard/test/fixtures/config/ondemand.d/string.yml, apps/dashboard/test/fixtures/modules/simple.json, apps/dashboard/test/models/hpc_module_test.rb
Fixes #1922
It also add `string_configs` to the configuration singleton. I didn't _need_ to add the string configs, but I did want to make it easier to add string configurations like we already have. This way, with this addition we cna start to backport some of our existing string (and boolean for that matter) configurations to this new scheme.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202022568160314) by [Unito](https://www.unito.io)
=> add support for reading modules and dynamic string configs

apps/dashboard/app/views/batch_connect/session_contexts/new.html.erb, apps/dashboard/test/application_system_test_case.rb, apps/dashboard/test/system/batch_connect_test.rb, apps/dashboard/test/system/preset_apps_navbar_test.rb, apps/dashboard/test/system/preset_apps_pinned_test.rb, apps/dashboard/test/test_helper.rb
Fixes #1869 - to enumerate over activemodel#errors as an array, not hash.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202038629870848) by [Unito](https://www.unito.io)
=> enumerate over activemodel#errors as an array, not hash

apps/dashboard/app/views/files/index.json.jbuilder
Using . in partial file names here is deprecated. Instead specify the formats.
This fixes this warning:
```
DEPRECATION WARNING: Rendering actions with '.' in the name is deprecated: files/_breadcrumb.html.erb (called from _app_views_files_index_json_jbuilder___283522221466645663_19980 at /home/jeff/ondemand/src/apps/dashboard/app/views/files/index.json.jbuilder:23)
DEPRECATION WARNING: Rendering actions with '.' in the name is deprecated: files/_shell_dropdown.html.erb (called from _app_views_files_index_json_jbuilder___283522221466645663_19980 at /home/jeff/ondemand/src/apps/dashboard/app/views/files/index.json.jbuilder:24)
```
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202111656403898) by [Unito](https://www.unito.io)
=> using . in the file names here is deprecated.

apps/dashboard/app/models/local_transfer.rb, apps/dashboard/app/models/transfer.rb, apps/dashboard/test/jobs/transfer_local_job_test.rb, apps/dashboard/test/models/transfer_test.rb
This is a small PR I've been thinking about submitting for a while now, it should be useful for any approach we use for the cloud storage (Active Storage, Rclone, other?) as the way these classes are set up seems to handle tracking transfer progress quite well.
This adds a `LocalTransfer` class that handles the transfers(move, copy, delete) on the local filesystem.
The idea is that `Transfer.build` creates an instance of a suitable subclass depending what kind of transfer it is, e.g. `RemoteTransfer` or `S3Transfer` could be future classes.
Would this be better as `PosixTransfer` to match `PosixFile`?
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202100406538885) by [Unito](https://www.unito.io)
=> Refactor Transfer class to separate handling of different transfers

apps/dashboard/app/javascript/packs/batch_connect.js, apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml, apps/dashboard/test/system/batch_connect_test.rb
Fixes #1650
This initializes the min and max correctly if they're given.  I committed it like this to see the tests fail.  You see the defaults (the initial state) change, which is actually the behavior we're looking for.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202127307671326) by [Unito](https://www.unito.io)
=> init min & maxes to the right values

apps/dashboard/app/models/batch_connect/app.rb, apps/dashboard/test/fixtures/usr/shared/bc_with_subapps/local/owens.yml, apps/dashboard/test/models/batch_connect/app_test.rb
Fixes #1899 
The result is something like this
* Rstudio Server: Choice --- default
* Rstudio Server: Preset --- uses this feature
* Jupyter (no subapp) - uses caption from the app's manifest.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202158895428972) by [Unito](https://www.unito.io)
=> add the ability for sub apps to have their own caption

.github/workflows/tests.yml
This uploads images when system tests do fail so that we can at least see what's going on in the CI.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202194149595595) by [Unito](https://www.unito.io)
=> upload system test failures in CI

apps/shell/test/helpers.test.js
As requested in #1967. Add test case to ensure functionality if a yml does not have read permissions.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202234867920347) by [Unito](https://www.unito.io)
=> Shell: Create test for unreadable yml file

packaging/deb/control, packaging/rpm/ondemand.spec
Ubuntu 22.04 has no `python` package so rather than try some clever logic to make dependencies vary based on OS being built (which is actually quite complicated) , just have everything for deb packages depend on Python 3 which exists in both Ubuntu 20.04 and 22.04.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202262663427249) by [Unito](https://www.unito.io)
=> Use python3 for Ubuntu/Debian packages

apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml
As seen in #1988 - `release_2.0` tests are failing for some reason. Specifying the cluster order in the test fixes the issues because the tests all expect `owens` to be the first, default, choice in the cluster dropdown. But it is currently _not_ sorted, it is showing `oakley` and so all the tests fail because they have this assumption built in.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202249800590014) by [Unito](https://www.unito.io)
=> specify cluster in the form so it's got the right order

apps/dashboard/Gemfile.lock, apps/dashboard/yarn.lock, apps/myjobs/Gemfile.lock, apps/shell/package.json, apps/shell/yarn.lock
The workflow to update the apps is currently broken because the shell app prompts users.  Not really quite sure what's up with the shell app's yarn lock, but I suspect it's been broken for some it because jest, which we've had for some time, is not part of the lock file?!
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202250538892659) by [Unito](https://www.unito.io)
=> update apps and fix shell apps yarn lock

packaging/deb/source/format
I could not figure out how to make the necessary tar.gz files during build to have versions work.  Seems using `3.0 (native)` makes our version scheme work with Ubuntu 22.04 builds.  I already had to make this change to other deb builds like Passenger to get them to build with Ubuntu 22.04.
=> Switch format for deb packaging to make Ubuntu 22.04 builds work

apps/dashboard/app/javascript/packs/batchConnect.js, apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml, apps/dashboard/test/system/batch_connect_test.rb
=> backport #1955 to 2.0

apps/dashboard/app/models/active_jobs/jobstatusdata.rb
This PR adds some information about [GRES](https://slurm.schedmd.com/gres.html), start times and end times of Slurm jobs to the Active Jobs app. The fields are hidden if they are not defined (N/A).
Example output:
=> More Slurm job info in ActiveJobs

apps/dashboard/app/javascript/packs/pinned_apps.js, apps/dashboard/app/javascript/stylesheets/_variables.scss, apps/dashboard/app/javascript/stylesheets/application.scss, apps/dashboard/app/javascript/stylesheets/pinned_apps.scss, apps/dashboard/app/views/widgets/_pinned_apps.html.erb, apps/dashboard/app/views/widgets/pinned_apps/_app.html.erb, apps/dashboard/test/html_helper.rb, apps/dashboard/test/integration/dashboard_layout_test.rb, apps/dashboard/test/integration/pinned_apps_test.rb
Updates to the pinned_apps widget look and feel based on the IQSS work for quick launchers.
This PR implement changes for https://github.com/OSC/ondemand/issues/1836
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202292092727337) by [Unito](https://www.unito.io)
=> Updated pinned_apps widget look and feel (#1836)

packaging/ondemand.spec
johrstrom I believe it's still the case you could do a tag like v2.0.24-2 to keep 2.0.24 tag but bump package release since this is packaging change.  Or can just bump to v2.0.25 if that's easier.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202314069129887) by [Unito](https://www.unito.io)
=> [release_2.0] More specific ondemand-passenger dependency

Dockerfile, Dockerfile.dev, Gemfile, Gemfile.lock, ood-portal-generator/lib/ood_portal_generator.rb, packaging/rpm/ondemand.spec, spec/e2e/e2e_helper.rb
Simplify the dependencies of ondemand RPM
Also address one Ruby 3.0 deprecation warning
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202344085269182) by [Unito](https://www.unito.io)
=> Upgrade EL builds to use Ruby 3.0

packaging/rpm/ondemand.spec
Ran into what is likely a rare situation where nightly builds twice in one day did not result in ondemand-selinux update when ondemand was updated due to lacking dependency version that does not include release version.
=> Ensure ondemand-selinux gets updated if only ondemand release bumped

apps/shell/app.js
#1950 persists in the shell app even after #1988. We missed this one check that was in mainline. 
I tested this by sharing the shell app with my test user and overriding `OOD_CLUSTERS` with some unreadable files.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202348513637156) by [Unito](https://www.unito.io)
=> check config before accessing it

apps/dashboard/app/helpers/batch_connect/sessions_helper.rb
Fixes error caused by batch_connect session status group floating below the containing box of the header
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202429992257460) by [Unito](https://www.unito.io)
=> Add overflow-auto to batch_connect/sessions card-header

ood-portal-generator/lib/ood_portal_generator.rb, ood-portal-generator/spec/ood_portal_generator_spec.rb
Ran into this issue when testing EL9 builds in ondemand-packaging repo.  The EL9 builds were thinking they used Apache from SCL.  Reworked logic a bit since only one supported OS uses SCL, there are now more not using than using it.
=> Ensure ood-portal-generator doesn't treat EL9 as SCL

ood-portal-generator/spec/fixtures/ood-portal.conf.all, ood-portal-generator/spec/fixtures/ood-portal.conf.dex, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-full, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-ldap, ood-portal-generator/spec/fixtures/ood-portal.conf.maint_with_ips, ood-portal-generator/spec/fixtures/ood-portal.conf.nomaint, ood-portal-generator/spec/fixtures/ood-portal.conf.oidc, ood-portal-generator/spec/fixtures/ood-portal.conf.oidc-ssl, ood-portal-generator/spec/fixtures/ood-portal.dex-full.proxy.conf, ood-portal-generator/spec/fixtures/output/auth.conf, ood-portal-generator/spec/fixtures/output/auth_deb.conf, ood-portal-generator/templates/ood-portal.conf.erb
This disables apache's TRACE functionality which we don't need and could possibly be used in XSS attacks.  It's not optional as, again, it's a security whole and we do not respond to TRACE.
https://owasp.org/www-community/attacks/xss/
Apps in the wild may, so someone may ask us to remove it, but I feel like folks' shouldn't use TRACE either way.
=> disable apache's insecure trace

apps/dashboard/app/views/widgets/_xdmod_widget_job_efficiency.html.erb
add an aria-label for these progress bars so they read '% efficient' then give a number (give some context to the progress bars).
This also fixes the misspelling of inefficient.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202402701047226) by [Unito](https://www.unito.io)
=> add an aria-label for these progress bars

apps/dashboard/app/controllers/files_controller.rb, apps/dashboard/app/models/posix_file.rb
This PR moves parts of the update and upload route code to PosixFile.
Implementing upload and update for remote files using Rclone is quite easy after these changes.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202556882410121) by [Unito](https://www.unito.io)
=> Move FilesController posix file methods out from update and upload routes

Dockerfile.dev, lib/tasks/development.rb
Fix permissions on mounted folders for podman.  Right now, the `ondemand` folder is mounted as `root:root` in podman, but if we fix the UID maps and make the directory in the container (with the right permissions) podman will respect the permissions of the underlay (the fold in the image).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202343392178847) by [Unito](https://www.unito.io)
=> fix permissions on mounted folders for podman

.github/workflows/tests.yml, Dockerfile.dev, apps/dashboard/app/controllers/files_controller.rb, apps/dashboard/app/helpers/files_helper.rb, apps/dashboard/app/javascript/packs/files/data_table.js, apps/dashboard/app/javascript/packs/files/file_ops.js, apps/dashboard/app/javascript/packs/files/uppy_ops.js, apps/dashboard/app/models/remote_file.rb, apps/dashboard/app/views/files/_breadcrumb.html.erb, apps/dashboard/app/views/files/_inline_js.html.erb, apps/dashboard/app/views/files/edit.html.erb, apps/dashboard/app/views/files/index.json.jbuilder, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/config/routes.rb, apps/dashboard/lib/rclone_util.rb, apps/dashboard/test/controllers/files_controller_test.rb, apps/dashboard/test/fixtures/config/ondemand.d/booleans.yml, apps/dashboard/test/integration/remote_files_test.rb, apps/dashboard/test/models/remote_file_test.rb, apps/dashboard/test/rclone_helper.rb, apps/dashboard/test/system/remote_files_test.rb, nginx_stage/templates/pun.conf.erb, spec/e2e/browser_spec.rb
This PR adds support for listing, viewing, downloading, uploading, creating and editing remote files (part of #1789).
The env var `OOD_FILES_APP_REMOTE_FILES` can be set to true to enable support for remote files.
I have saved file transfers for a future PR, so those are currently not supported.
The features supported are currently implemented by using different [rclone](https://rclone.org/) commands (`lsf`, `lsjson`, `cat`, `rcat`, `touch`, `mkdir`, `moveto` and `listremotes`), using the rclone remotes configured in the default `rclone.conf` (see discussion below about that).
This PR modifies only the backend, no frontend changes have been done so far.
There are some frontend changes that would need to be done (mostly regarding paths), but some things need to be decided first.
There are …
=> Add initial support for remote files in files app

apps/dashboard/app/apps/router.rb, apps/dashboard/app/apps/user_configuration.rb, apps/dashboard/app/controllers/application_controller.rb, apps/dashboard/app/controllers/settings_controller.rb, apps/dashboard/app/helpers/application_helper.rb, apps/dashboard/app/helpers/dashboard_helper.rb, apps/dashboard/app/models/current_user.rb, apps/dashboard/app/views/layouts/nav/_help_dropdown.html.erb, apps/dashboard/app/views/layouts/nav/_link.html.erb, apps/dashboard/app/views/widgets/_pinned_apps.html.erb, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/config/locales/en.yml, apps/dashboard/config/routes.rb, apps/dashboard/test/config/configuration_singleton_test.rb, apps/dashboard/test/fixtures/config/ondemand.d/profile.yml, apps/dashboard/test/fixtures/config/ondemand.d/string.yml, apps/dashboard/test/fixtures/config/user_settings/.invalid, apps/dashboard/test/fixtures/config/user_settings/.valid, apps/dashboard/test/helpers/application_helper_test.rb, apps/dashboard/test/integration/dashboard_layout_test.rb, apps/dashboard/test/integration/pinned_apps_test.rb, apps/dashboard/test/integration/settings_controller_test.rb, apps/dashboard/test/models/current_user_test.rb, apps/dashboard/test/models/user_configuration_test.rb, apps/dashboard/test/system/preset_apps_pinned_test.rb
Enhance the current configuration object to support profiles. These new profiles will work as overrides to the default root configuration. For every configuration item, first, there will be a lookup into the current profile configuration, then into the root configuration.
Implementation for issue #2117
**Sample Configuration for testing**
Adding a new homepage layout for a `test` profile:
Add the following configuration to an existing or to a new configuration file under the `Configuration.config_directory`.
This is usually: `/etc/ood/config/ondemand.d`
```
pinned_apps:
- type: sys
profile_links:
- id: default
name: "default"
icon: "cog"
- id: test
name: "Test"
icon: "user"
dashboard_layout:
rows:
- columns:
- width: 12
widgets:
- "pinned_apps"
profiles:
test:
dashboard_layout:
rows:
- …
```
=> Add support for multiple Homepage layouts and widgets configurations (#2117)

.github/workflows/document-merge.yml
The goal (also will be in release_2.0 PR) is to open doc issues and automation when merging into release branches.
=> Also handle doc labels for release branches

spec/e2e/e2e_helper.rb
Avoids issue where previous sed would result in `/build/build/2.0`.  This allows the sed to be re-run during local tests.
=> Fix e2e repo logic to avoid issues when tests are re-run

apps/dashboard/lib/tasks/test.rake
fix #2133 so that test:jobs does not invoke asset building
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202671565324007) by [Unito](https://www.unito.io)
=> fix #2133 so that test:jobs does not invoke asset building

apps/dashboard/app/models/batch_connect/session.rb, apps/dashboard/test/models/batch_connect/session_test.rb
Stop serializing the connection view, and instead read it from the
app directly. This also forces the db files to be 600 for increased
security against umasks.
Lastly, it adds a test to boot.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202538066959106) by [Unito](https://www.unito.io)
=> Write bc session script db files with 600 permission and add 'writes db file correctly' test

apps/dashboard/app/javascript/packs/batch_connect.js
Fixes #1658
Examples:
"OSC_JUPYTER" -> "osc_jupyter"
"PascalOsc" -> "pascal_osc"
"camelOsc" -> "camel_osc"
"camel_Snake" -> "camel_snake"
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202699188025194) by [Unito](https://www.unito.io)
=> Fix snakeCaseWords not working as expected

apps/dashboard/app/javascript/packs/files/data_table.js
Closes #290 
Adds event listeners for show owner mode and show dotfiles checkboxes and each data table row checkbox.
It seems that this should be backported to 2.0 as well.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202699239333338) by [Unito](https://www.unito.io)
=> Enable using enter key for checkboxes in file explorer

CHANGELOG.md, apps/dashboard/Gemfile.lock, apps/myjobs/Gemfile.lock
prep 2.0.28 release. Updates `ood_core` to pick up the Fujitsu adapter and update the changelog. This will be the last change for `2.0.28`.
=> prep 2.0.28 release

apps/dashboard/app/views/dashboard/_motd_markdown.html.erb, apps/dashboard/app/views/dashboard/_motd_rss.html.erb, apps/dashboard/app/views/products/_form_git.html.erb, apps/dashboard/app/views/products/_form_reset_git.html.erb, apps/dashboard/app/views/products/_product.html.erb, apps/dashboard/app/views/products/show.html.erb
remove `html_safe` where necessary. `html_safe` actually renders html safely. Sometimes this is what we actually want, however in these cases identified we actually want to encode these characters.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202699184424295) by [Unito](https://www.unito.io)
=> remove html_safe where necessary 

nginx_stage/templates/pun.conf.erb
Fixes #2167
Can be disabled with 
```yaml
disable_bundle_user_config: false
```
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202699283182846) by [Unito](https://www.unito.io)
=> Enable passenger_preload_bundler for PUN

apps/dashboard/app/models/active_jobs/jobstatusdata.rb, apps/dashboard/lib/smart_attributes/attributes/bc_num_slots.rb
Fujitsu TCS resource manager as a new adapter has been added (https://github.com/OSC/ood_core/pull/766).
Along with that, I would like to display the details of the job information in Active Jobs.
I would also like to support a Fujitsu TCS for bc_num_slots.
Thanks,
=> Fix for Fujitsu TCS resource manager

ood-portal-generator/spec/fixtures/ood-portal.conf.all, ood-portal-generator/spec/fixtures/ood-portal.conf.default, ood-portal-generator/spec/fixtures/ood-portal.conf.dex, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-full, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-ldap, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-proxy, ood-portal-generator/spec/fixtures/ood-portal.conf.maint_with_ips, ood-portal-generator/spec/fixtures/ood-portal.conf.nomaint, ood-portal-generator/spec/fixtures/ood-portal.conf.oidc, ood-portal-generator/spec/fixtures/ood-portal.conf.oidc-ssl, ood-portal-generator/spec/fixtures/ood-portal.dex-full.proxy.conf, ood-portal-generator/spec/fixtures/sum.default, ood-portal-generator/templates/ood-portal.conf.erb
=> Improved maintenance page handling of 503 errors [release_2.0]

apps/dashboard/app/controllers/application_controller.rb, apps/dashboard/app/models/user_configuration.rb, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/fixtures/config/ondemand.d/booleans.yml, apps/dashboard/test/models/user_configuration_test.rb
Added a ProfileProvider to allow for different ways of selecting the current profile.
Added 2 profile providers: User Settings and Domain
Implements: #2127
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202699184946276) by [Unito](https://www.unito.io)
=> Added support automatic hostname based profiles

apps/dashboard/app/apps/favorite_path.rb, apps/dashboard/app/apps/ood_files_app.rb, apps/dashboard/app/views/files/_favorites.html.erb
This PR makes it possible to create favorite paths for remote filesystems (#1789). It defaults to `fs`, so it is fully backwards compatible.
Currently there is no validation that the remotes exists and their paths are valid, so that needs to be done in the `ood.rb` initializer if wanted.
Example `ood.rb` that adds all remotes from rclone
```
require "ood_files_app"
require "open3"
def remotes
o, e, s = Open3.capture3("rclone", "listremotes")
if s.success?
o.lines.map { |l| l.gsub(/:$/, "").strip }
else
raise "Error listing remotes: #{e}"
end
end
OodFilesApp.candidate_favorite_paths.tap do |paths|
paths.concat remotes.map { |r| FavoritePath.new("/", title: r, filesystem: r) }
end
```
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202699190561199) by …
=> Make favorite paths support remote filesystems

ood-portal-generator/lib/ood_portal_generator/view.rb, ood-portal-generator/share/ood_portal_example.yml, ood-portal-generator/spec/fixtures/ood-portal.conf.all, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-full, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-ldap, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-no-proxy, ood-portal-generator/spec/fixtures/ood-portal.conf.oidc-ssl, ood-portal-generator/spec/fixtures/ood-portal.dex-full.proxy.conf, ood-portal-generator/spec/fixtures/ood_portal.yaml.all, ood-portal-generator/templates/ood-portal.conf.erb
Fixes #1568
For HTTP to HTTPS only use `%{HTTP_HOST}` to ensure that any aliases are kept during redirect.
Also ensure port 80 virtual host is using ServerName to avoid possibly overriding other port 80 configs.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202725200138505) by [Unito](https://www.unito.io)
=> Support defining serveralias in Apache virtual host

apps/dashboard/app/javascript/packs/files/data_table.js, apps/dashboard/test/system/files_test.rb, apps/dashboard/test/system/remote_files_test.rb
#2094 seems to have a removed two lines of code, causing file uploads and changing directory to only work after a fresh page load, not after navigating into a different directory. This PR fixes that bug and also adds system tests for this for both local filesystem and cloud storage.
To reproduce:
* Open file browser
* Click on a directory
* Upload file as usual
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202710899810484) by [Unito](https://www.unito.io)
=> Fix file uploads and directory changes

apps/dashboard/test/system/files_test.rb
This PR fixes the systems tests for file uploading added in #2195 failing sometimes due to the test checking too quickly if the file exists.
This waits until the file is visible in the file browser before checking if it exists.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202734899114873) by [Unito](https://www.unito.io)
=> Fix files upload system tests randomly failing

apps/dashboard/app/controllers/files_controller.rb
fixes #2121 and solves INC0365594
When downloading a directory previously, the resulting zip would not include sub-directories without files in them. Now, those empty sub-directories are included in the zip download.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202710870115158) by [Unito](https://www.unito.io)
=> Enable downloading empty sub-directories with zip

apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/config/configuration_singleton_test.rb, apps/dashboard/test/fixtures/config/anchors_aliases/config.yml
Updated how YAML config files are loaded to support YAML anchors and aliases
Fixes #2214
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202780995115556) by [Unito](https://www.unito.io)
=> Added support for YAML anchors and aliases when reading configuration

apps/dashboard/config/routes.rb
Fixes #2239 by adding `api/v1` to the constraints of `fs`, so that `files/api/v1/...` URL is handled in the correct place.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202807937528109) by [Unito](https://www.unito.io)
=> Fix files/api/v1 route not working

apps/dashboard/app/controllers/transfers_controller.rb, apps/dashboard/app/javascript/packs/files/clip_board.js, apps/dashboard/app/javascript/packs/files/data_table.js, apps/dashboard/app/javascript/packs/files/file_ops.js, apps/dashboard/app/models/posix_transfer.rb, apps/dashboard/app/models/remote_transfer.rb, apps/dashboard/app/models/transfer.rb, apps/dashboard/app/views/files/_inline_js.html.erb, apps/dashboard/app/views/files/index.json.jbuilder, apps/dashboard/lib/rclone_util.rb, apps/dashboard/test/jobs/transfer_local_job_test.rb, apps/dashboard/test/models/transfer_test.rb, apps/dashboard/test/system/remote_files_test.rb
This PR adds support for moving, copying, deleting and renaming files and directories on cloud storages using Rclone, fixes #2129.
This adds `from_fs` and `to_fs` optional parameters to the transfers API, which are used to define from and to which Rclone remote files are transferred. The default is `fs`, which is treated as the local (posix) filesystem so that it is fully backwards compatible. The feature is enabled by setting `OOD_FILES_APP_REMOTE_FILES` to true.
Overwriting files is avoided so that it behaves in the same way as normal transfers on the local filesystem. That also simplifies the Rclone commands that are needed significantly. Allowlist paths are also checked for the local filesystem, and remotes of type local and alias are disabled when the allowlist is enabled (same …
=> Support cloud storage file transfers

apps/dashboard/app/apps/nav_config.rb, apps/dashboard/app/controllers/application_controller.rb, apps/dashboard/app/models/user_configuration.rb, apps/dashboard/app/views/layouts/application.html.erb, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/config/configuration_singleton_test.rb, apps/dashboard/test/integration/dashboard_controller_test.rb, apps/dashboard/test/models/user_configuration_test.rb, apps/dashboard/test/test_helper.rb
PR to move the navigation settings to the new profile based configuration (UserConfiguration)
The navigation settings this PR are:
* `NavConfig.categories`
* `NavConfig.categories_whitelist`
* `Configuration.show_all_apps_link?`
Fixes #2251
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202822721888116) by [Unito](https://www.unito.io)
=> Moved navigation settings to profile based configuration (#2251)

apps/dashboard/app/controllers/application_controller.rb, apps/dashboard/app/models/user_configuration.rb, apps/dashboard/test/integration/dashboard_controller_test.rb, apps/dashboard/test/models/user_configuration_test.rb
Fixes the outstanding issues for PR: https://github.com/OSC/ondemand/pull/2221
This completes issue: https://github.com/OSC/ondemand/issues/2215
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202839409341736) by [Unito](https://www.unito.io)
=> Renamed UserConfiguration.categories to nav_categories

apps/dashboard/app/apps/ood_app.rb, apps/dashboard/app/helpers/files_helper.rb, apps/dashboard/app/views/files/edit.html.erb, apps/dashboard/app/views/files/index.json.jbuilder, apps/dashboard/test/integration/dashboard_controller_test.rb, apps/dashboard/test/system/files_test.rb, apps/dashboard/test/system/remote_files_test.rb
This PR makes OOD use the `fs` parameter in ood_appkit URLs (introduced in #2201) instead of using workarounds (that are now broken after #2201). This PR fixes favorite path navbar links not working and changes the files browser and editor to use ood_appkit directly instead of using a workaround.
The PR also adds tests cases for remote favorite path navbar links and system tests for editing files.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202822812253549) by [Unito](https://www.unito.io)
=> Use new ood_appkit files and editor URLs

apps/dashboard/test/application_system_test_case.rb, apps/dashboard/test/system/files_test.rb, apps/dashboard/test/system/remote_files_test.rb
This fixes the selenium tests that look through a browsers logs.  Fixing this deprecation warning:
```
2022-08-18 16:48:08 WARN Selenium [DEPRECATION] Manager#logs is deprecated. Use Chrome::Driver#logs instead.
```
means we'll be able to upgrade these dependencies.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202828107774629) by [Unito](https://www.unito.io)
=> init and access browser logs differently for selenium 4.0+

apps/dashboard/config/locales/en.yml, apps/dashboard/lib/rclone_util.rb
Fixes #2247. This PR makes it possible to create directories on remotes that don't support empty directories. This is achieved by using `rclone touch` to touch a file in that directory.
Adding tests for this is a bit problematic as we can't easily set up a remote that doesn't have support for empty directories.
I attempted stubbing `RcloneUtil.rclone` to return the Rclone warning to trigger the workaround also for the local remotes used in the tests, but didn't seem like stubbing like that is possible without ugly workarounds.
I.e. I would like to do something like this:
```
RcloneUtil.stubs(:rclone).with('mkdir', 'alias_remote:/dir').returns('', "Warning: running mkdir on a remote which can't have empty directories does nothing", nil)
RcloneUtil.stubs(:rclone).with(any_parameters) # this …
```
=> Support creating directories on all remote filesystems

apps/dashboard/app/controllers/files_controller.rb, apps/dashboard/config/locales/en.yml, apps/dashboard/test/integration/files_app_test.rb
Fixes #2231.
This PR makes the FilesController show errors properly when trying to access a remote file system when the remote file system support is disabled.
`before_action` caused exceptions to not be handled by the routes, so the standard Rails error page was shown. Using `before_action` with `rescue_from` to handle the exceptions would probably have been possible but seemed overly complicated as we have so different behaviour (HTML, JSON, redirects) in the different routes.
This sets the `@path` to be a PosixFile, but `@filesystem` to be the requested filesystem in the case where remote file systems are disabled and the user tries to access it. This is done to be able to show the files browser index page with the error message while still avoiding accidentally accessing the remote …
=> Fix remote FS edge cases

apps/dashboard/app/apps/app_recategorizer.rb, apps/dashboard/app/apps/nav_bar.rb, apps/dashboard/app/apps/ood_app_group.rb, apps/dashboard/app/apps/ood_app_link.rb, apps/dashboard/app/controllers/application_controller.rb, apps/dashboard/app/helpers/application_helper.rb, apps/dashboard/app/models/user_configuration.rb, apps/dashboard/app/views/layouts/application.html.erb, apps/dashboard/app/views/layouts/nav/_develop_dropdown.html.erb, apps/dashboard/app/views/layouts/nav/_featured_apps.html.erb, apps/dashboard/app/views/layouts/nav/_group.html.erb, apps/dashboard/app/views/layouts/nav/_help_dropdown.html.erb, apps/dashboard/app/views/layouts/nav/_link.html.erb, apps/dashboard/test/apps/app_recategorizer_test.rb, apps/dashboard/test/apps/featured_app_test.rb, apps/dashboard/test/apps/nav_bar_test.rb, apps/dashboard/test/apps/ood_app_link_test.rb, apps/dashboard/test/integration/custom_navigation_test.rb, apps/dashboard/test/models/user_configuration_test.rb
Full navigation implementation based on Groups and Links.
Sample configuration and result:
```yaml
nav_bar:
- title: "Help"
links:
- group: "Doc Links"
- apps: "sys/sas"
- group: "Other Links"
- apps: "sys/sas"
- title: "how to docs"
icon_uri: fa://desktop
url: "/docs"
new_tab: false
- title: "Submit a help ticket"
icon_uri: fa://question-circle
url: "/tickets"
new_tab: false
- apps: "sys/sas"
- title: "Documentation"
url: "/sid2"
new_tab: true
- title: "Apps Menu"
links:
- "sys/Rstudio/*"
- apps: [ "sys/sas" ]
- group: "SubApp"
apps: [ "sys/bc_desktop" ]
- group: "Core Apps"
- apps: [ "sys/bc_desktop" ]
- title: "RStudio"
- apps: [ "sys/Rstudio/*" ]
- group: "Profiles"
- title: "Team 1"
profile: "team1"
- title: "Team 2"
profile: "team2"
- apps: "sys/sas"
- title: "Wiki"
icon_uri: …
```
=> Added full navigation definition in UserConfiguration (Group/Link)

apps/dashboard/config/locales/en.yml, apps/dashboard/lib/rclone_util.rb, apps/dashboard/test/fixtures/config/rclone/rclone.conf, apps/dashboard/test/rclone_helper.rb, apps/dashboard/test/unit/rclone_util_test.rb
Fixes #2232. This adds a `list_remotes` method that can be used for listing Rclone remotes available.
Example `ood.rb` initializer:
```
require "rclone_util"
Rails.application.config.after_initialize do |_|
remotes = RcloneUtil.list_remotes.map { |r| FavoritePath.new("", title: r, filesystem: r) }
OodFilesApp.candidate_favorite_paths.tap do |paths|
paths.concat(remotes)
end
rescue => e
Rails.logger.error(e.message)
end
```
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202917863766653) by [Unito](https://www.unito.io)
=> Add method for listing Rclone remotes to RcloneUtil

apps/dashboard/esbuild.config.js
Remove js source maps (because we don't use them) and minify for production javascript builds.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202989852390153) by [Unito](https://www.unito.io)
=> rm js source maps and minify for production builds

apps/dashboard/app/apps/nav_bar.rb, apps/dashboard/app/controllers/application_controller.rb, apps/dashboard/app/models/user_configuration.rb, apps/dashboard/app/views/layouts/application.html.erb, apps/dashboard/app/views/layouts/nav/_custom_navigation.html.erb, apps/dashboard/app/views/layouts/nav/_log_out.html.erb, apps/dashboard/app/views/layouts/nav/_user.html.erb, apps/dashboard/test/apps/nav_bar_test.rb, apps/dashboard/test/models/user_configuration_test.rb
Fixes #2276
Help navigation definition in UserConfiguration.
This is to customize the right hand side navigation in the same way as it is now possible to do for the main navigation
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202956058977851) by [Unito](https://www.unito.io)
=> Added help navigation definition in UserConfiguration

lib/tasks/build.rb, ood_auth_map/ood_auth_map.gemspec
This removes the bundler version dependency in ood_auth_map (because of bundler security updates).  It also fixes the now deprecated `--without` flag in installing gems just because I happen to see it's still there while I was investigating what bundler versions are available.
Lastly some changes are just linting fixes.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203009101239487) by [Unito](https://www.unito.io)
=> some bundler fixups

apps/dashboard/app/models/batch_connect/app.rb, apps/dashboard/app/models/batch_connect/session_context.rb, apps/dashboard/test/fixtures/sys_with_interactive_apps/bc_jupyter/form.yml, apps/dashboard/test/fixtures/sys_with_interactive_apps/bc_jupyter/submit.yml.erb, apps/dashboard/test/models/batch_connect/app_test.rb, apps/dashboard/test/models/batch_connect/session_context_test.rb
Fixes #605 by passing rendering off to an open struct instead of an object that is enumerable (i.e., SmartAttributes).  As a additional safety step - it checks for form items that _it_ has methods on (like `table`) and throws an error if one is trying to use one of these APIs/form fields.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203093865670232) by [Unito](https://www.unito.io)
=> Safer form rendering

apps/dashboard/app/models/batch_connect/session.rb, apps/dashboard/app/views/batch_connect/sessions/connections/_native_vnc.html.erb
Fixes #2237 by using SHA1 instead of MD5 for systems with FIPS 140-2 on and MD5 digests don't work.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203145353445079) by [Unito](https://www.unito.io)
=> use SHA1 instead of MD5 for FIPs systems

apps/dashboard/app/models/batch_connect/session.rb, apps/dashboard/app/views/batch_connect/sessions/connections/_native_vnc.html.erb
Backport #2325 so folks don't have to patch their systems every time they update.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203152209687182) by [Unito](https://www.unito.io)
=> use SHA1 instead of MD5 for FIPs systems (#2325)

apps/dashboard/app/javascript/packs/batch_connect.js, apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml, apps/dashboard/test/system/batch_connect_test.rb
Fixes a bug from discourse https://discourse.openondemand.org/t/implementing-a-case-statement-in-form-yml-erb/2306  where `data-for-option` directives cannot handle options with a forward slash (`/`).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203168202959244) by [Unito](https://www.unito.io)
=> Dynanic batch connect with slashes bugfix

apps/myjobs/app/models/resource_mgr_adapter.rb
For whatever reason, this works but still - we should have the space.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203230813906240) by [Unito](https://www.unito.io)
=> ternary should have a space here

apps/myjobs/app/models/resource_mgr_adapter.rb
For whatever reason, this works but still - we should have the space.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203230869270226) by [Unito](https://www.unito.io)
=> newline on ternay operator

apps/dashboard/app/javascript/packs/batchConnect.js, apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml, apps/dashboard/test/system/batch_connect_test.rb
backport #2319 to release 2.0.
change min/max cache key to allow for that choice to modify more than one other elements.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203230813474492) by [Unito](https://www.unito.io)
=> backport #2319 - allow for multiple min & max settings

apps/myjobs/app/models/workflow.rb, apps/myjobs/config/configuration_singleton.rb
Hi, 
We are exploring ondemand at Kuleuven and we would like to not show the job array in the myjobs app due to a competing implementation.
This pr would add an environment variable acting as an override for showing the job array. 
Is this the best way to go about it?
Thank you in advance.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203150488889195) by [Unito](https://www.unito.io)
=> Myjobs: Add ENV override for showing job array

mod_ood_proxy/lib/nginx.lua, mod_ood_proxy/lib/pun_proxy.lua, spec/e2e/proxy_spec.rb
remove /nginx/noop because it serves no real purpose.
I tracked it down to this commit (which is not noop, it tries to boot the pun). 
https://github.com/OSC/mod_ood_proxy/commit/120a2acbddda49c048639f69755fc4c61e816b90
Where I believe this is also left over from something erroneous. The commit message reads `do ... if 502` implying they thought this `r:custom_response` set the custom response _if_ the response was already 502?
```
-- handle if backend server isn't completely started yet
r:custom_response(502, nginx_uri .. "/noop?redir=" .. r:escape(r.unparsed_uri))
```
I'm not sure, in any case, I believe the `noop` functionality is completely useless. Just send the 302 directly instead of through this api.
┆Issue is synchronized with this [Asana …
=> remove /nginx/noop

packaging/deb/rules, packaging/rpm/ondemand.spec
Fixes #1544 by using the environment variables instead of --without CLI flag.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203429454484873) by [Unito](https://www.unito.io)
=> use bundler environment vars instead of deprecated --without flag

apps/dashboard/app/helpers/batch_connect/sessions_helper.rb, apps/dashboard/app/models/batch_connect/session.rb, apps/dashboard/app/views/support_ticket/email/default.text.erb, apps/dashboard/app/views/support_ticket/rt/rt_ticket_content.text.erb, apps/dashboard/test/models/batch_connect/session_test.rb
After looking more in detail at the BatchConnect::Session object, I think this is a better implementation to displaying the form parameters in the session card.
It does not require a new field, instead relies on the existing `user_defined_context` file that is already saved by the session.
As well, it adds the `user_defined_context` to the support ticket as this information will be useful fir debugging.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203432325440412) by [Unito](https://www.unito.io)
=> Improvements to logic for displaying form parameters in session cards

.github/workflows/lint.yml, lib/tasks/lint.rb
Add workflow and rake task to randomly lint a file so that over time our files will not have so many linting errors. Current schedule is every 3 days.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203428702523468) by [Unito](https://www.unito.io)
=> add workflow and rake task to randomly lint a file

apps/dashboard/config/initializers/rclone.rb
#2264 gave us a way to list remotes in an initializers. Let's go ahead and add it to the main repo so that sites with rclone installed and people how have rclone configurations will automatically have those added to their favorite path.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203395863573767) by [Unito](https://www.unito.io)
=> add rlcone initializer to auto populate rclone remotes

apps/dashboard/app/javascript/packs/batch_connect.js, apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml, apps/dashboard/test/system/batch_connect_test.rb
Fixes #2362 which ended up being a few bugs. I'll leave comments for rationale for changes in the files.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203338277276811) by [Unito](https://www.unito.io)
┆Link To Task: https://app.asana.com/0/1135148780858012/1203338277276811
=> Clamp bugfix

nginx_stage/lib/nginx_stage.rb, spec/e2e/nginx_stage_spec.rb
Fixes #1833 by rescuing when we cannot find a valid user for a given `pun_pid_path`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203451113806981) by [Unito](https://www.unito.io)
=> make nginx_clean safe to run against deleted users

apps/dashboard/app/apps/nav_config.rb, apps/dashboard/test/apps/nav_config_test.rb
Fix #1458 by renaming whitelist to allowlist in the NavConfig object.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203429604886100) by [Unito](https://www.unito.io)
=> navconfig to use allowlist to deprecate whitelist

apps/dashboard/app/views/widgets/_xdmod_widget_jobs.html.erb
Fixes #1956 by using the correct javascript Date API to get the numeric day of the month.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203451648779933) by [Unito](https://www.unito.io)
=> use correct Date api to get the day of the month

apps/dashboard/app/views/widgets/pinned_apps/_app.html.erb
The spinner should not appear for pinned apps that open in a new tab.
This fix will remove the `data-toggle` for apps that open in a new tab
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203457795213479) by [Unito](https://www.unito.io)
=> Fixed spinner for pinned apps opening in a new tab

apps/dashboard/test/apps/nav_config_test.rb
Our tests are currently pretty flaky. I believe it's because this test is modifying NavConfig but then never restoring it's defaults.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203460706615771) by [Unito](https://www.unito.io)
=> restore defaults when tearing down this test

apps/dashboard/app/models/permission.rb, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/fixtures/config/ondemand.d/string.yml
Allow for configurable facl domain because `osc.edu` is hard coded here.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203466062673806) by [Unito](https://www.unito.io)
=> allow for configurable facl domain

.github/workflows/tests.yml
tests are failing on #2400 because it can't find `rake`.  Not quite sure what's up but maybe it's the order of tests (unit tests install gems)? and having to force install rake?
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203473977852663) by [Unito](https://www.unito.io)
=> reorder tests to install gems first

apps/dashboard/app/apps/nav_bar.rb, apps/dashboard/app/apps/ood_app_group.rb, apps/dashboard/app/apps/ood_app_link.rb, apps/dashboard/app/controllers/batch_connect/session_contexts_controller.rb, apps/dashboard/app/controllers/batch_connect/sessions_controller.rb, apps/dashboard/app/controllers/concerns/batch_connect_concern.rb, apps/dashboard/app/models/user_configuration.rb, apps/dashboard/app/views/batch_connect/session_contexts/new.html.erb, apps/dashboard/app/views/batch_connect/sessions/index.html.erb, apps/dashboard/app/views/batch_connect/shared/_app_list.html.erb, apps/dashboard/app/views/batch_connect/shared/_app_menu.html.erb, apps/dashboard/config/locales/en.yml, apps/dashboard/test/apps/nav_bar_test.rb, apps/dashboard/test/apps/ood_app_link_test.rb, apps/dashboard/test/controllers/concerns/batch_connect_concern_test.rb, apps/dashboard/test/integration/sessions_test.rb, apps/dashboard/test/models/user_configuration_test.rb
Changes to generate the left hand side applications navigation in `Interactive Apps` and `Interactive Sessions` pages by discovering the `sys` applications that have been configured in a custom top level navigation.
As well, to add support for a custom configuration to define the navigation.
Fixes: #2326
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203412125609234) by [Unito](https://www.unito.io)
=> Added support for customizing left hand side applications menu

apps/dashboard/app/models/batch_connect/session.rb, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/fixtures/config/ondemand.d/booleans.yml
Fixes #722 by adding a configuration option to disable the default /bin/bash shell for batch connect apps.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203536562688943) by [Unito](https://www.unito.io)
=> add the ability to disable the shell for bc apps

apps/dashboard/app/javascript/packs/active_jobs.js
Fixes #1594 by correctly sort walltime column.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203524345535549) by [Unito](https://www.unito.io)
=> correctly sort walltime column

apps/dashboard/app/javascript/stylesheets/application.scss, apps/dashboard/app/javascript/stylesheets/files.scss, apps/dashboard/app/views/active_jobs/_extended_panel.html.erb, apps/dashboard/app/views/apps/_app.html.erb, apps/dashboard/app/views/files/_copy_move_popup.html.erb, apps/dashboard/app/views/files/_files_table.html.erb, apps/dashboard/app/views/files/index.html.erb, apps/dashboard/app/views/shared/_insufficient_quota_progress_bar.html.erb, apps/dashboard/app/views/support_ticket/email_service_template.html.erb, apps/dashboard/app/views/widgets/_xdmod_widget_job_efficiency.html.erb, apps/dashboard/app/views/widgets/_xdmod_widget_jobs.html.erb
Removed inline-styles from every file in the ondemand source code.
* Styles replaced with their bootstrap equivalent or near-equivalents. 
* Added some custom styles
* Added  a scss function to generate classes for width percents between 0 and 100 with format `w-${i}`.
Part of an effort to make ondemand compliant with [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203571489358983) by [Unito](https://www.unito.io)
=> Remove inline-styles

apps/dashboard/app/views/layouts/application.html.erb, apps/dashboard/app/views/layouts/nav/_custom_navigation.html.erb, apps/dashboard/app/views/layouts/nav/_group.html.erb, apps/dashboard/test/integration/custom_help_navigation_test.rb
Fixes to the custom help menu alignment.
Applied rubocop to the custom navigation tests
Fixes #2417
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203535177647161) by [Unito](https://www.unito.io)
=> Fixed custom help menu alignment

ood-portal-generator/spec/fixtures/ood-portal.conf.all, ood-portal-generator/spec/fixtures/ood-portal.conf.default, ood-portal-generator/spec/fixtures/ood-portal.conf.dex, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-full, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-ldap, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-proxy, ood-portal-generator/spec/fixtures/ood-portal.conf.maint_with_ips, ood-portal-generator/spec/fixtures/ood-portal.conf.oidc, ood-portal-generator/spec/fixtures/ood-portal.conf.oidc-ssl, ood-portal-generator/spec/fixtures/ood-portal.dex-full.proxy.conf, ood-portal-generator/spec/fixtures/sum.default, ood-portal-generator/templates/ood-portal.conf.erb
- While in maintenance mode, do not redirect request URIs which start with "/public/maintenance/"
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203563876451004) by [Unito](https://www.unito.io)
=> ood-portal-generator: Serve any /public/maintenance/ file in maint mode

apps/dashboard/app/controllers/files_controller.rb, apps/dashboard/app/controllers/transfers_controller.rb, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/config/initializers/rclone.rb, apps/dashboard/test/controllers/files_controller_test.rb, apps/dashboard/test/fixtures/config/ondemand.d/booleans.yml, apps/dashboard/test/rclone_helper.rb
I was looking to document this feature and found this config a little laking. So Let's change the name and check in the initializer if it's enabled.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203603412068026) by [Unito](https://www.unito.io)
=> rename remote files config to remote_files_enabled

apps/dashboard/config/initializers/upgrade_to_2.1.rb
Since https://github.com/OSC/ondemand/pull/1526 all the batch connect cache files have moved. So, when folks upgrade to 2.1, let's sync these old files so that they don't lose their cached choices.
This is just a quality of life thing for folks when they upgrade they'll keep all their cached choices from 2.0.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203596885828344) by [Unito](https://www.unito.io)
=> add initializer to sync cache files from 2.0 to 2.1

apps/dashboard/app/helpers/batch_connect/sessions_helper.rb, apps/dashboard/config/locales/en.yml, apps/dashboard/test/helpers/batch_connect/sessions_helper_test.rb, apps/dashboard/test/integration/sessions_controller_test.rb
We should be using `button` tags here to delete & cancel sessions for accessibility reasons (so they can cycle through `b` buttons).
So this changes those elements from an `a` (link) to a button.
This has the added benefit of fixing a bug.
Fixes #659 by using a button that will always use `post` method. The issue in #659 is a race condition where the user clicks the button before the javascript has been attached to the element that toggles between an HTTP GET and an HTTP POST. Buttons directly use POST so there's no way to get into that bad state.
Holding in draft for the moment as tooltips seems to be interfering with the initial state of these elements.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203651238710489) by …
=> use a button for deleting & canceling instead of link

apps/dashboard/app/helpers/application_helper.rb, apps/dashboard/app/models/user_configuration.rb, apps/dashboard/app/views/layouts/nav/_help_dropdown.html.erb, apps/dashboard/test/helpers/application_helper_test.rb
Changed how to configure profile links so that they are consistent with how the custom navigation configuration is done.
The new configuration will look like:
```yaml
profile_links:
- title: "Default"
profile: ""
icon_uri: fas://user
- title: "Team 1"
profile: "team1"
- title: "Team 2"
profile: "team2"
```
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203673422093106) by [Unito](https://www.unito.io)
=> Profile links configuration made consistent with custom navigation

apps/dashboard/app/apps/request_tracker_service.rb, apps/dashboard/app/helpers/support_ticket_helper.rb, apps/dashboard/app/mailers/support_ticket_mailer.rb, apps/dashboard/app/views/support_ticket/email/_email.text.erb, apps/dashboard/app/views/support_ticket/email/email_layout.text.erb, apps/dashboard/app/views/support_ticket/email_service_template.html.erb, apps/dashboard/app/views/support_ticket/rt/rt_ticket_content.text.erb, apps/dashboard/config/environments/development.rb, apps/dashboard/config/environments/test.rb, apps/dashboard/config/locales/en.yml, apps/dashboard/test/fixtures/config/views/support_ticket/email/email_template_override.text.erb, apps/dashboard/test/helpers/support_ticket_helper_test.rb, apps/dashboard/test/integration/request_tracker_integration_test.rb, apps/dashboard/test/integration/support_ticket_integration_test.rb, apps/dashboard/test/mailers/support_ticket_mailer_test.rb
While creating the documentation for the new support ticket feature, I found a couple of items to improve:
* Update Header text so that is ready to use without updates.
* Make default Header description empty and move the configuration to the `support_ticket` property.
* Add username to the email and RT ticket bodies.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203750309735033) by [Unito](https://www.unito.io)
=> Improvements to the configuration for the support ticket form

apps/dashboard/app/javascript/packs/batch_connect.js
`auto_accounts` is going to create big lists of duplicates.
I.e., `auto_accounts` are going to generate an account per cluster, like so:
```
pzs0714|ascend||ascend-default
pzs0714|owens||owens-default
pzs0714|pitzer||pitzer-default
```
Generating form options like so. Obviously there are 3 options for value `PZS0714`, so this PR accounts for those duplciate options.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203777315915537) by [Unito](https://www.unito.io)
=> allow for duplicate option values

apps/dashboard/config/initializers/rclone.rb
This should be `next`, not `break` in this closure. `break` in fact causes an error.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203775848711918) by [Unito](https://www.unito.io)
=> rclone initializer is broken

apps/dashboard/app/apps/nav_bar.rb
Fixing the restart server static link
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203838949039349) by [Unito](https://www.unito.io)
=> Fixed link for restart server on NavBar.STATIC_LINKS

apps/dashboard/app/helpers/application_helper.rb, apps/dashboard/app/models/user_configuration.rb, apps/dashboard/app/views/layouts/nav/_group.html.erb, apps/dashboard/app/views/layouts/nav/_group_items.html.erb, apps/dashboard/app/views/layouts/nav/_help_dropdown.html.erb, apps/dashboard/config/locales/en.yml, apps/dashboard/test/helpers/application_helper_test.rb, apps/dashboard/test/models/user_configuration_test.rb
Added a new profile property called `help_menu` to add links to the Help dropdown menu.
Link definitions are consistent with the new custom `navbar`, uses the same logic.
See discussion in issue: https://github.com/OSC/ondemand/issues/2472
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203837213308996) by [Unito](https://www.unito.io)
=> Added support to add links to the help menu dropdown

apps/dashboard/app/javascript/packs/batch_connect.js, apps/dashboard/app/lib/account_cache.rb, apps/dashboard/app/lib/smart_attributes.rb, apps/dashboard/app/lib/smart_attributes/attributes/auto_qos.rb, apps/dashboard/test/application_system_test_case.rb, apps/dashboard/test/system/batch_connect_test.rb
This adds the `auto_qos` options that are cluster and account aware.
Because of the complexity involved in duplicate qos options, batch_connet.js has to account for not only duplicate option values, but also logic that would hide that option based off of some other option's value.
In draft right now while I write some tests.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203840805461116) by [Unito](https://www.unito.io)
=> add auto_qos batch connect option.

apps/dashboard/app/lib/smart_attributes/attributes/auto_modules.rb, apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml, apps/dashboard/test/system/batch_connect_test.rb
This creates the `default` module version in the `auto_modules_` feature. Users will be able to disable the default version in the `attributes` section.
This also fixes a bug where the `module_name/version` needs to be passed to the server, not just `version` which is useless.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203859758667359) by [Unito](https://www.unito.io)
=> show the default module for auto_modules. and fix the form value.

apps/dashboard/app/javascript/packs/support_ticket.js
The spinner was not showing after the Rails upgrade.
Using a different mechanism to show the spinner
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203867114919981) by [Unito](https://www.unito.io)
=> Fixed support ticket spinner after Rails upgrade

apps/dashboard/app/helpers/recently_used_apps_helper.rb, apps/dashboard/test/helpers/recently_used_apps_helper_test.rb
Fixed `recently_used_apps` widget to filter out `BatchConnect` apps that are not valid.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203865288161734) by [Unito](https://www.unito.io)
=> Updated recently_used_apps widget to only select valid applications

apps/dashboard/app/helpers/application_helper.rb, apps/dashboard/app/helpers/batch_connect/sessions_helper.rb, apps/dashboard/app/javascript/packs/batch_connect_sessions.js, apps/dashboard/app/models/user_configuration.rb, apps/dashboard/app/views/batch_connect/sessions/index.html.erb, apps/dashboard/app/views/layouts/application.html.erb, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/config/locales/en.yml, apps/dashboard/test/fixtures/config/ondemand.d/booleans.yml, apps/dashboard/test/helpers/batch_connect/sessions_helper_test.rb, apps/dashboard/test/integration/sessions_controller_test.rb
Added session relaunch button to session panel.
This will start a new interactive session based on the user context data available in a previously completed session.
Added as a experimental feature behind a feature toggle: `relaunch_session_enabled`
Implements https://github.com/OSC/ondemand/issues/2522
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203866900601621) by [Unito](https://www.unito.io)
=> Added session relaunch feature

apps/dashboard/app/helpers/batch_connect/sessions_helper.rb, apps/dashboard/app/javascript/stylesheets/support_ticket.scss
Looks like the version of `noVNC` deployed with the Dashboard is `1.3.0`, the one the link was using is `1.1.0`, fixing.
https://github.com/OSC/ondemand/tree/master/apps/dashboard/public/noVNC-1.3.0
Fixing the spinner overlay not being on top of the relaunch session button tooltip.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203875324489408) by [Unito](https://www.unito.io)
=> Fixed noVNC url + Improved spinner CSS

apps/dashboard/app/lib/account_cache.rb
Without caching this function call, we're lighting up `scontrol` calling it a whopping 240 times.
With this cache it'll only call it `scontrol` for as many clusters as we have (in our case 3).
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203878498181959) by [Unito](https://www.unito.io)
=> better caching for scontrol

apps/dashboard/config/environments/development.rb, apps/dashboard/config/environments/production.rb
Apparently I never actually tested this in dev. It's trying to use `/var/www/ood/apps/sys/dashboard/tmp` as the file cache which isn't writable.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203871036905567) by [Unito](https://www.unito.io)
=> use memory store caches

apps/dashboard/Gemfile.lock, apps/myjobs/Gemfile.lock
Before (or while) we release 2.1, we should patch 2.0 for the apptainer bug that affects linux host adapters. Some folks may take their time in upgrading and without this patch the linux host adapter is basically useless.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203869088746924) by [Unito](https://www.unito.io)
=> upgrade ood_core for apptainer patch (for release 2.0)

packaging/rpm/ondemand.spec
This ensures that RC releases will require the correct gem RPM
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203886257516660) by [Unito](https://www.unito.io)
=> Ensure ondemand-gems name includes the release

apps/dashboard/config/environments/production.rb, apps/myjobs/config/environments/production.rb, nginx_stage/lib/nginx_stage.rb, ood-portal-generator/lib/ood_portal_generator/view.rb, ood-portal-generator/spec/fixtures/ood-portal.conf.all, ood-portal-generator/spec/fixtures/ood-portal.conf.dex, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-full, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-ldap, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-no-proxy, ood-portal-generator/spec/fixtures/ood-portal.conf.maint_with_ips, ood-portal-generator/spec/fixtures/ood-portal.conf.nomaint, ood-portal-generator/spec/fixtures/ood-portal.conf.oidc, ood-portal-generator/spec/fixtures/ood-portal.conf.oidc-ssl, ood-portal-generator/spec/fixtures/ood-portal.dex-full.proxy.conf, ood-portal-generator/spec/fixtures/output/auth.conf, ood-portal-generator/spec/fixtures/output/auth_deb.conf, ood-portal-generator/spec/ood_portal_generator_view_spec.rb, ood-portal-generator/templates/ood-portal.conf.erb
change OOD_PUN_RAILS_CONFIG_HOSTS to ALLOWED_HOSTS to fix #2552.
I could have just added a duplicate environment variable in `nginx_stage` but I figured it'd be easier to just manage/remember 1 thing instead of having to recall that there's a duplicate.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203940749335895) by [Unito](https://www.unito.io)
=> change OOD_PUN_RAILS_CONFIG_HOSTS to ALLOWED_HOSTS

apps/dashboard/app/apps/nav_bar.rb, apps/dashboard/app/apps/ood_app_group.rb, apps/dashboard/app/javascript/stylesheets/apps.scss, apps/dashboard/app/views/layouts/nav/_group.html.erb, apps/dashboard/test/apps/nav_bar_test.rb, apps/dashboard/test/integration/dashboard_controller_test.rb, apps/dashboard/test/models/ood_app_group_test.rb
1.- Fix for the sorting of subcategories when application links are configured.
eg:
```yaml
nav_bar:
- title: "My Apps"
apps: "sys/*"
```
This should create sorted subcategory groupings for all matched apps.
2.- Fix for the image width and height for the custom navigation menu image
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203960947382686) by [Unito](https://www.unito.io)
=> Fixed navbar links sorting for application links + images

apps/dashboard/app/apps/nav_bar.rb, apps/dashboard/app/models/batch_connect/app.rb, apps/dashboard/app/views/widgets/pinned_apps/_app_content.html.erb, apps/dashboard/test/apps/nav_bar_test.rb, apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_desktop/local/oakley.yml, apps/dashboard/test/fixtures/usr/shared/bc_with_subapps/local/owens.yml, apps/dashboard/test/integration/custom_help_navigation_test.rb, apps/dashboard/test/integration/custom_navigation_test.rb, apps/dashboard/test/models/batch_connect/app_test.rb
Renamed `icon_uri` yaml property to `icon` to make it consistent with app manifest.
Will update the documentation if this PR passes review and is merged.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203975466181385) by [Unito](https://www.unito.io)
=> Renamed icon_uri yaml property to icon

apps/dashboard/app/helpers/application_helper.rb, apps/dashboard/app/javascript/stylesheets/pinned_apps.scss, apps/dashboard/test/helpers/application_helper_test.rb
Added support to use images from` /public` location (eg: `/var/www/ood/public`).
- By default, `icon_tag` helper prefixes image URIs with the application path, `/pun/sys/dashboard`. This was not allowing to use image deployed in the public Apache folder.
- This helper is used for pinned apps images and navigation items.
```yaml
tile:
title: "RStudio 400"
icon_uri: "/public/images/rstudio_logo.png"
border_color: "blue "
sub_caption: |
Custom Text Line 1
Line 2
Line 3
```
Pinned apps fixes to the image width when the custom image is wider than the tile.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203971746162607) by [Unito](https://www.unito.io)
=> Added support for images from /public location

apps/dashboard/app/views/layouts/nav/_group_items.html.erb, apps/dashboard/app/views/layouts/nav/_link.html.erb
Currently it is not possible to create custom navigation links without having an icon. The code will default to having the `fas://cog` icon when no icon is defined or when null icon is set.
We have a requirement for IQSS to create top level links without having an icon.
Update: keep the default as `fas://cog` when no icon is defined, but allow admins to set an empty string to remove the icon from rendering:
```yaml
help_bar:
- title: "About"
url: "https://www.iq.harvard.edu/research-computing#AboutSidNG"
icon: ""
```
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203977669800188) by [Unito](https://www.unito.io)
=> Added support for empty icons for custom navigation items

apps/dashboard/config/environments/production.rb, mod_ood_proxy/lib/ood/nginx_stage.lua, nginx_stage/lib/nginx_stage.rb
allowed hosts still doesn't work.  This actually fixes #2566 and I confirmed in containers. Both with a prehook set and without one.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203960902381432) by [Unito](https://www.unito.io)
=> default to allow no hosts

apps/dashboard/app/models/user_configuration.rb, apps/dashboard/app/views/dashboard/index.html.erb, apps/dashboard/test/models/user_configuration_test.rb
For our IQSS dashboard, we want to configure the homepage to display only widgets without showing the welcome message. Currently, there is no way of removing the welcome message without updating the `I18N` text. This solution is not profile friendly.
Added property to disable the welcome message
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203986030689007) by [Unito](https://www.unito.io)
=> Added configuration to disable the dashboard welcome message

apps/dashboard/app/views/layouts/application.html.erb
Fix #2588  and only use `tranfers_path` if its available.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203987184886869) by [Unito](https://www.unito.io)
=> only use tranfers_path if its available

apps/dashboard/package.json, apps/dashboard/yarn.lock
lock sweetalert2 to get rid of that to get rid of this advisory.
https://github.com/advisories/GHSA-457r-cqc8-9vj9
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203988854641796) by [Unito](https://www.unito.io)
=> lock sweetalert2

apps/dashboard/app/controllers/projects_controller.rb, apps/dashboard/app/controllers/scripts_controller.rb, apps/dashboard/app/models/project.rb, apps/dashboard/app/models/script.rb, apps/dashboard/app/views/projects/index.html.erb, apps/dashboard/app/views/projects/show.html.erb, apps/dashboard/test/integration/projects_controller_test.rb, apps/dashboard/test/models/projects_test.rb, apps/dashboard/test/system/jobs_app_test.rb
Fixes #2578 
This enhances projects to use numeric ids instead of directories for a variety of reasons. 
* Notably to decouple the URLs from the initial directory name (opening us up to allow for spaces). 
* What's more is it'll allow us to use directories _outside_ of the dataroot because the full path is in the lookup file (#2558 or #2301)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1204008884166928) by [Unito](https://www.unito.io)
=> projects to use numeric ids instead of directories

.github/workflows/changelog.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/tests.yml, .github/workflows/update.yml
update gh automation for deprecations. Fixes #2539. 
This updates basic actions from v2 to v3.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203996755347938) by [Unito](https://www.unito.io)
=> update gh automation for deprecations

apps/dashboard/app/lib/account_cache.rb, apps/dashboard/test/system/batch_connect_test.rb
optimize auto_accounts so it doesnt show duplicates.
Right now `auto_accounts` populates a huge list that requires `cluster` be set for dynamic hiding of the duplicates
Use this very simple form
```yaml
form:
- auto_accounts
```
and you'll see duplicates. One for each cluster.
This optimizes that a bit and only shows 1 account only and adds the appropriate `data-option-for` directives to hide them when a given cluster is chosen.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203995919330176) by [Unito](https://www.unito.io)
=> optimize auto_accounts so it doesnt show duplicates

apps/dashboard/app/controllers/application_controller.rb, apps/dashboard/app/models/user_configuration.rb, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/config/configuration_singleton_test.rb, apps/dashboard/test/integration/announcement_views_test.rb, apps/dashboard/test/models/user_configuration_test.rb
Moved `announcement_path` to UserConfiguration to allow for profile based configuration.
This will allow to have different announcements per profile.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1204033258533071) by [Unito](https://www.unito.io)
=> Migrated announcements_path property to UserConfiguration object

apps/dashboard/app/views/widgets/_sessions.html.erb, apps/dashboard/config/locales/en.yml, apps/dashboard/test/integration/active_sessions_widget_test.rb
We had an internal review of the active sessions widget and think that it is a better behaviour to not display it when there are no active sessions.
This will make the widget consistent with the pinned apps widget that is not rendered when there are no pinned apps configured.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204041285740648) by [Unito](https://www.unito.io)
=> Updated sessions widget to not render if there are no active sessions

apps/dashboard/app/javascript/packs/application.js, apps/dashboard/app/javascript/packs/config.js, apps/dashboard/app/views/layouts/application.html.erb, apps/dashboard/app/views/layouts/editor.html.erb, apps/dashboard/app/views/layouts/nav/_styles.html.erb
The only reason we worked on #1863 was due to inline `style-src` being restricted as a part of our content security policy.
As we've went through this exercise we've learned that we can use `content_security_policy` within partials.  As we've found #2615 there seems to be a timing issue involved in adding the style through javascript.
Well, this PR is to simply add the `<style>` partial back in and simply add a nonce to it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1204070234836611) by [Unito](https://www.unito.io)
=> use inline style with a nonce

apps/dashboard/app/views/apps/_app.html.erb, apps/dashboard/app/views/files/_breadcrumb.html.erb, apps/dashboard/app/views/files/_files_table.html.erb, apps/dashboard/app/views/layouts/nav/_featured_apps.html.erb, apps/dashboard/app/views/layouts/nav/_group_items.html.erb, apps/dashboard/app/views/products/show.html.erb, apps/dashboard/app/views/widgets/pinned_apps/_app_content.html.erb
Remove inline styles and use classes instead.  One file was in dos format, so it was converted to unix format.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204081829407007) by [Unito](https://www.unito.io)
=> remove inline styles

apps/dashboard/app/controllers/files_controller.rb
Remove this include to safely download large directories.  This include is not working well for writing large zips.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204102282887894) by [Unito](https://www.unito.io)
=> rm this include to safely dl large directories

apps/dashboard/app/apps/request_tracker_client.rb, apps/dashboard/app/apps/request_tracker_service.rb, apps/dashboard/app/apps/support_ticket_email_service.rb, apps/dashboard/app/apps/support_ticket_rt_service.rb, apps/dashboard/app/controllers/support_ticket_controller.rb, apps/dashboard/app/helpers/batch_connect/sessions_helper.rb, apps/dashboard/app/helpers/support_ticket_helper.rb, apps/dashboard/app/mailers/support_ticket_mailer.rb, apps/dashboard/app/models/concerns/support_ticket_validator.rb, apps/dashboard/app/models/support_ticket.rb, apps/dashboard/app/models/user_configuration.rb, apps/dashboard/app/views/layouts/nav/_help_dropdown.html.erb, apps/dashboard/app/views/support_ticket/email_service_template.html.erb, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/apps/request_tracker_client_test.rb, apps/dashboard/test/apps/request_tracker_service_test.rb, apps/dashboard/test/apps/support_ticket_email_service_test.rb, apps/dashboard/test/apps/support_ticket_rt_service_test.rb, apps/dashboard/test/config/configuration_singleton_test.rb, apps/dashboard/test/controllers/support_ticket_controller_test.rb, apps/dashboard/test/helpers/support_ticket_helper_test.rb, apps/dashboard/test/integration/request_tracker_integration_test.rb, apps/dashboard/test/integration/support_ticket_integration_test.rb, apps/dashboard/test/mailers/support_ticket_mailer_test.rb, apps/dashboard/test/models/support_ticket_test.rb, apps/dashboard/test/models/user_configuration_test.rb
Migrated `support_ticket` configuration from `ConfigurationSingleton` to `UserConfiguration` to add profile support.
We were doing an internal review and realized that different profiles might have different email or config settings for the support ticket configuration. Or one profile might want to disable the functionality.
The PR looks bigger than it is. It is just that the config was used in a lot of places.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204092217715450) by [Unito](https://www.unito.io)
=> Moved support_ticket configuration to UserConfiguration class

apps/dashboard/app/javascript/packs/files/file_ops.js
This primarily fixes #2629 by correctly show alerts for download links and working through that workflow. This also fixes #2630.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204107104013047) by [Unito](https://www.unito.io)
=> correctly show alerts for download links

apps/dashboard/app/models/posix_file.rb, apps/dashboard/app/models/remote_file.rb
Fixes #2624 by hiding non ascii filenames.
We may be able to show them at some point, but will never be able to edit, download or update them.  We cannot build routes with non utf-8 characters.  We _may_ be able to map them to say question marks instead, but if you it'd be nearly impossible to know which file to choose if they're all `????`. 
In any case, this'll work in the interem and I can create a follow up ticket for CRUDing them.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1204092595862193) by [Unito](https://www.unito.io)
=> filter files that have non utf-8 characters in their filenames

apps/dashboard/app/javascript/packs/batch_connect.js, apps/dashboard/test/system/batch_connect_test.rb
Fixes #2543 by disabling the option even if Safari is going to force us to show it.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1204122235609044) by [Unito](https://www.unito.io)
=> also disable when hidning for Safari

apps/dashboard/app/controllers/files_controller.rb, apps/dashboard/app/javascript/packs/files/data_table.js
Fix #2644 by never caching the files controllers' json response.
So the issue in #2644 is the json response is cached and we're navigating back to it. So the simple solution is to just never cache it at all.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204140193860403) by [Unito](https://www.unito.io)
=> fix #2644 by never caching the files controllers' json response

apps/dashboard/app/models/announcement.rb, apps/dashboard/test/models/announcements_test.rb
Fixes #2634 to catch a SyntaxError in an announcement.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204149453120476) by [Unito](https://www.unito.io)
=> rescue SyntaxErrors in announcements

packaging/deb/control
Add `file` to deb dependencies to fix #241 because we do indeed use this command here:
https://github.com/OSC/ondemand/blob/dda7c0dd579765c5f983874f6f139f083804f883/apps/dashboard/app/models/posix_file.rb#L162
rpm packages already correctly depend on this package.
https://github.com/OSC/ondemand/blob/dda7c0dd579765c5f983874f6f139f083804f883/packaging/rpm/ondemand.spec#L60
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204169923391279) by [Unito](https://www.unito.io)
=> add file to deb dependencies

apps/dashboard/app/controllers/scripts_controller.rb, apps/dashboard/app/helpers/scripts_helper.rb, apps/dashboard/app/models/script.rb, apps/dashboard/app/views/scripts/show.html.erb, apps/dashboard/config/routes.rb
Show smart attributes in a form and start a #submit API.
Fixes #2574 - so if you have edited a script like so:
```yaml
---
title: 'some title'
form:
- auto_accounts
```
The `#show` page will then render that form and submit it (although the #submit is currently just a TODO message)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1204155189343444) by [Unito](https://www.unito.io)
=> show smart attributes in a form and start a #submit API

apps/dashboard/config/initializers/session_store.rb
This PR fixes a bug with OOD running in a container with multiple users accessing the dashboard.
`Etc.getlogin` returns root in some cases, which causes the Rails session store (#2434) to attempt to use the same directory for all users, as seen below:
```
[ood@027a5853a2cc ~]$ ls -la /var/tmp/
total 20
drwxrwxrwt.  4 root root 4096 Mar 15 13:24 .
drwxr-xr-x. 20 root root 4096 Mar 15 13:24 ..
drwxr-xr-x.  3 root root 4096 Mar 15 13:24 ondemand-nginx
drwx------.  3 ood  ood  4096 Mar 15 13:24 root
```
When some user other than `ood` in this case tries to access the dashboard, they get an error due to not being able to create a directory under `/var/tmp/root/`.
Minimal example of `Etc.getlogin` behaviour with rootless Podman:
```
[rkarlsso@blahake ~]$ podman run -ti ruby:latest /bin/bash …
```
=> Fix Rails session store using wrong username in some cases

nginx_stage/templates/pun.conf.erb
Fixes #2000. Confusingly, we have to set this option to true to disable the check.  I.e., enabling it disables the security check.
Looks like #2459 didn't actually resolve this issue because I still see the checks in the logs in 2.1.0.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204186168209349) by [Unito](https://www.unito.io)
=> actually disable security checks

.github/workflows/tests.yml
#2683 showed us that having version in the name of e2e tests may be a bit flaky when having to update the version.
Distributions on the other hand are likely to be more stable, so let's just key off of distributions.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204228624415238) by [Unito](https://www.unito.io)
=> only have distribution in e2e test names

apps/dashboard/app/models/files.rb
Fix #2626 in 2.0. Can't directly use the commit from #2626, so it's a new commit.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204217665658392) by [Unito](https://www.unito.io)
=> fix #2626 in 2.0

apps/dashboard/app/models/script.rb, apps/dashboard/app/views/projects/show.html.erb, apps/dashboard/test/system/jobs_app_test.rb
This starts work on #2653 by keeping a log file of all the jobs that a script has submitted.
It added a column to `projects#show` so there's a little updates to that page as well.
To test simply submit a job with a given script and see the job id listed in the new column.  Submitting another job updates the column so that the most recent job id is there.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1204276144165791) by [Unito](https://www.unito.io)
=> Initialize tracking jobs

apps/dashboard/app/javascript/packs/path_selector/data_table.js, apps/dashboard/app/views/batch_connect/session_contexts/_path_selector.html.erb
To test this.  It is best to use Code Server, but technically it will work with any form, i suppose.
Add the following to your App's form.
If you remove all of the "options", you will get the default of showing directories only.
```
working_dir:
widget: "path_selector"
label: "Working Directory"
help: "Select your project directory; defaults to $HOME"
options:
- files
- hidden
```
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204254857145488) by [Unito](https://www.unito.io)
=> Path selector form options

apps/dashboard/app/views/projects/_form.html.erb
Widen this column to take the entire space available.
Before:
After:
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1204292995937729) by [Unito](https://www.unito.io)
=> widen this column to take the entire space

apps/dashboard/app/views/widgets/pinned_apps/_app.html.erb
Removed `method=get` on pinned apps links that are not preset. This is to avoid Rails JS creating and submitting a form.
This will remove the browser message to re-submit the form when refreshing the page after selecting a pinned app.
Fixes #2705
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1204293578283656) by [Unito](https://www.unito.io)
=> Removed redundant method=get for pinned apps

apps/dashboard/app/javascript/packs/projects.js
Don't log error, instead defer and html update.
This is making tests a bit flaky, which test for console messages. So let's just catch it and defer the HTML update.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204309217669179) by [Unito](https://www.unito.io)
=> dont log error, instead defer and html update

apps/dashboard/app/javascript/packs/icon_picker.js, apps/dashboard/app/javascript/stylesheets/icon_picker.scss
Add the ability search icons in `projects#edit`
Now when you type in the input field it'll hide what isn't found. Then when you choose something, it'll show all the icons once again.
Here's an example of searching `arr` and you get all the arrow type icons.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204303342536010) by [Unito](https://www.unito.io)
=> add the ability search icons

apps/dashboard/app/controllers/projects_controller.rb, apps/dashboard/app/models/project.rb, apps/dashboard/app/views/projects/_form.html.erb, apps/dashboard/app/views/projects/index.html.erb, apps/dashboard/config/locales/en.yml, apps/dashboard/test/system/jobs_app_test.rb
This starts the work for project templates in #2720.It doesn't do anything now, it just lays the foundation for template support.There's an extra button on `projects#index` and if you choose to create a project from a template, you'll see an additional dropdown select for the template to create the project from. Only this select field is empty right now.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204311629738788) by [Unito](https://www.unito.io)
=> start support for project templates

apps/dashboard/app/controllers/concerns/batch_connect_concern.rb, apps/dashboard/test/controllers/concerns/batch_connect_concern_test.rb
Added code to remove duplicated applications from the `interactive apps` and `my interactive sessions ` left hand navigation.
Fixes #2728
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204343462275185) by [Unito](https://www.unito.io)
=> Removed duplicated applications from interactive apps menu

apps/dashboard/app/lib/account_cache.rb
This will catch errors bubbling up from `ood_core` like this one that can happen because of an `ood_core` bug.
https://github.com/OSC/ood_core/issues/806
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1204364892830709) by [Unito](https://www.unito.io)
=> catch errors from account queries

apps/dashboard/app/javascript/packs/config.js, apps/dashboard/app/javascript/packs/files/uppy_ops.js, apps/dashboard/app/views/layouts/application.html.erb, apps/dashboard/test/system/files_test.rb
Fixes #2764.
Adds possibility to add localization to Uppy through the locale files. Full list of possible options [here](https://github.com/transloadit/uppy/blob/96ae2bf04981f73b63ebc034156bcf418ded11a5/packages/@uppy/locales/src/en_US.js).
Example locale file:
```
en:
dashboard:
uppy:
strings:
exceedsSize: '%{file} exceeds...'
```
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1204432436718528) by [Unito](https://www.unito.io)
=> Add localization for Uppy

apps/dashboard/app/lib/smart_attributes/attribute.rb, apps/dashboard/app/lib/smart_attributes/attributes/auto_scripts.rb, apps/dashboard/app/models/script.rb, apps/dashboard/test/system/jobs_app_test.rb
There's some wonkiness in Script initialization. namely in adding require fields like cluster and auto_scripts. This updates all that to force cluster and auto_scripts to be a part of the script and serialize correctly. I've added Attribute#options_to_serialize to help with writing these objects out to yaml as it was filtering critical options and not writing them to yaml.
In draft while I work on updating tests as well.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204526234881462) by [Unito](https://www.unito.io)
=> work on script initialization and serialization.

apps/dashboard/app/controllers/scripts_controller.rb, apps/dashboard/app/lib/smart_attributes.rb, apps/dashboard/app/lib/smart_attributes/attributes/auto_batch_clusters.rb, apps/dashboard/app/models/script.rb, apps/dashboard/test/system/jobs_app_test.rb
This adds `auto_batch_clusters` to deal with the odd way we deal with clusters currently by creating them directly in the script model.
So instead of this logic being held in the script model itself, it's better to have a smart attribute that can handle this functionality and the script can just deal with it as a required field on initialization.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1204564742125102) by [Unito](https://www.unito.io)
=> add auto clusters

packaging/files/ondemand-nginx-tmpfiles
This is an attempt to bypass the /var/tmp cleanup timer that gets installed by default for systemd.
=> Add /var/tmp/ondemand-nginx to tmpfiles

ood-portal-generator/lib/ood_portal_generator/view.rb, ood-portal-generator/share/ood_portal_example.yml, ood-portal-generator/spec/ood_portal_generator_view_spec.rb
Cherry pick #2807
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1204592202958190) by [Unito](https://www.unito.io)
=> (release 3.0) Allow oidc_crypto_passphrase to be set for ood-portal-generator

nginx_stage/lib/nginx_stage/configuration.rb
We would like to use syslog for the nginx access and error logs, but we noticed that this is currently not possible as the paths are always expanded, for example `syslog:server=unix:/some/path` is expanded to `/root/syslog:server=unix:/some/path`, which is invalid. This PR excludes the [special cases](https://nginx.org/en/docs/ngx_core_module.html#error_log) `stderr`, `syslog:` and `memory:` from being expanded.
Note that syslog does not work completely due to issues with Passenger, but I'll be submitting a separate PR regarding that.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1204620175481781) by [Unito](https://www.unito.io)
=> Add possibility of using syslog for nginx logs

apps/dashboard/app/models/script.rb
Always sort batch clusters here to ensure tests run predictably in ruby 2.7.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204639594114648) by [Unito](https://www.unito.io)
=> sort batch clusters

apps/dashboard/app/models/script.rb
This was fixed in PR #2823 but the actual code that was effected wasn't. This just removes the workaround.
=> Remove Hard-coded Script Location

apps/dashboard/app/views/layouts/application.html.erb, apps/dashboard/app/views/layouts/nav/_develop_dropdown.html.erb, apps/dashboard/test/integration/custom_help_navigation_test.rb
Hides the custom help navigation menu based on the Configuration object
Fixes #2847
=> Hide develop custom menu template based on Configuration object

.github/workflows/tests.yml, Gemfile, Gemfile.lock, apps/dashboard/.yarnrc, apps/dashboard/Gemfile.lock, apps/myjobs/Gemfile.lock, apps/shell/.yarnrc, ood-portal-generator/Gemfile.lock, packaging/deb/control, packaging/deb/rules, packaging/rpm/ondemand.spec, spec/e2e/e2e_helper.rb
NodeJS update affects all OSes except EL7 and Amazon 2023
Ruby 3.1 update only affects EL8 and EL9
Fixes #2884
=> Update to NodeJS 18 and Ruby 3.1

ood-portal-generator/spec/fixtures/ood-portal.conf.all, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-full, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-ldap, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-no-proxy, ood-portal-generator/spec/fixtures/ood-portal.conf.oidc-ssl, ood-portal-generator/spec/fixtures/ood-portal.dex-full.proxy.conf, ood-portal-generator/templates/ood-portal.conf.erb
- Avoid double rewrites for http (non-https) rewrites, by setting the correct proxy_server value the first time.
=> ood-portal-generator: Use proxy_server in http rewrites

.github/workflows/lint.yml
Upgrade this action for GH deprecations.
Currently we're getting all of these warnings.
=> upgrade this action for GH deprecations

apps/dashboard/config/configuration_singleton.rb, apps/dashboard/config/routes.rb, apps/dashboard/test/fixtures/config/ondemand.d/booleans.yml, apps/dashboard/test/system/jobs_app_test.rb
Now that we have #2839 - we don't need this flag anymore.
=> rm unused config flag for new projects app

apps/dashboard/app/helpers/scripts_helper.rb, apps/dashboard/app/javascript/packs/script_edit.js, apps/dashboard/app/javascript/stylesheets/scripts.scss, apps/dashboard/app/views/scripts/editable_form_fields/_editable_select.html.erb
Add initial scaffolding for #2902 - disabling select options.
The `edit` ui looks like this now for editing select options. This PR does not include any functionality really. It let's you press the buttons as if you were adding or removing the options - but it doesn't actually save anything, it's just a starting point for later work.
=> add initial scaffolding for disabling select options

apps/dashboard/app/controllers/scripts_controller.rb, apps/dashboard/app/javascript/packs/script_edit.js, apps/dashboard/app/models/script.rb, apps/dashboard/app/views/scripts/editable_form_fields/_editable_select.html.erb
Following #2903 - when you click in the UI to add or remove an option from a select list, the system will start to populate an `input` field with the list of things you want to exclude. Since it's an `input` it'll directly send the exclude list with all the other parameters.
=> Send excludeable options

apps/dashboard/app/javascript/packs/files/globus.js, apps/dashboard/app/views/files/_globus.html.erb
Remove inline javascript related to globus configuration. The json data is now serialized and stored as a data attribute. Resolves OSC/ondemand#2890
=> Refactor globus inline js

apps/dashboard/Gemfile, apps/dashboard/Gemfile.lock, apps/dashboard/yarn.lock, apps/myjobs/Gemfile, apps/myjobs/Gemfile.lock, apps/shell/yarn.lock
#2923 is failing because we haven't updated mocha in quite some time. This is the result of executing `rake update` plus updating mocha directly in the dashboard's Gemfile.
=> rake update + upgrading mocha manually.

apps/dashboard/app/lib/smart_attributes/attribute_factory.rb, apps/dashboard/app/lib/smart_attributes/attributes/auto_modules.rb, apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml, apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/template/script.sh.erb, apps/dashboard/test/models/batch_connect/session_test.rb, apps/dashboard/test/system/batch_connect_test.rb
Backports #2938 to 3.0.
Add support for module names with hyphens in them. Now you can add a module like `auto_modules_netcdf-serial` and reference them through `context.auto_modules_netcdf_serial` with underscores.
=> add support for module names with hyphens in them (#2938)

apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/config/configuration_singleton_test.rb
Fixes #2894 by sorting ondemand.d files by name before loading them.
=> sort ondemand.d files by name before loading

apps/dashboard/test/apps/support_ticket_email_service_test.rb, apps/dashboard/test/controllers/support_ticket_controller_test.rb, apps/dashboard/test/system/batch_connect_test.rb, apps/dashboard/test/system/jobs_app_test.rb, apps/dashboard/test/test_helper.rb
fix mocha deprecation warnings. 
Here's an example of such a warning:
....................Mocha deprecation warning at /home/jeff/ondemand/src/apps/dashboard/app/controllers/support_ticket_controller.rb:34:in `create': Expectation defined at /home/jeff/ondemand/src/apps/dashboard/test/controllers/support_ticket_controller_test.rb:74:in `block in <class:SupportTicketControllerTest>' expected positional hash ({:flash => {:notice => "support ticket message"}}), but received keyword arguments (:flash => {:notice => "support ticket message"}). These will stop matching when strict keyword argument matching is enabled. See the documentation for Mocha::Configuration#strict_keyword_argument_matching=.
=> fix mocha deprecation warnings

Dockerfile, Dockerfile.dev
As of #2885, we should also upgrade related container image versions. Currently, image build will fail:
=> Container images upgrade to NodeJS 18 and Ruby 3.1

Dockerfile.dev
add `gcc` to dev container to build dependent gems in the dev dashboard.
=> add gcc to dev container

apps/dashboard/app/controllers/scripts_controller.rb, apps/dashboard/app/models/script.rb, apps/dashboard/app/views/projects/show.html.erb, apps/dashboard/config/locales/en.yml, apps/dashboard/test/system/jobs_app_test.rb
Added new controller and model functions to delete a script.
Moved the individual script outputs for a script into its own folder to facilitate deleting them.
This is a draft to get early feedback
=> Add delete script functionality for new job composer (#2820)

apps/dashboard/app/javascript/packs/path_selector/path_selector_data_table.js
Fixes #2673 by only reloading the file table when a directory is chosen. This has the added benefit of working for file selection.
=> only query the fs api if you navigate select a directory

apps/dashboard/config/configuration_singleton.rb, apps/dashboard/config/initializers/rclone.rb, apps/dashboard/lib/rclone_util.rb, apps/dashboard/test/fixtures/config/ondemand.d/booleans.yml, apps/dashboard/test/fixtures/config/rclone/rclone.conf, apps/dashboard/test/unit/rclone_util_test.rb
This PR adds a configuration option that can be enabled to add only valid and accessible Rclone remotes to favorite paths.
The remotes are validates by trying to list the directories in the remote in parallel with a timeout of 6s (this is mostly chosen due to strange Rclone timeout behaviour). The feature is disabled by default, enable by setting `OOD_REMOTE_VALIDATION` to true. This might not be the best name for the configuration option, but was the shortest reasonable name I could think of (maybe `OOD_RCLONE_REMOTE_VALIDATION` would be better?).
=> Validate Rclone remotes in initializer

apps/dashboard/app/lib/smart_attributes/attributes/auto_scripts.rb
When there are no scripts: `AUTO_SCRIPT_EXTENSIONS = ['sh', 'csh', 'bash', 'slurm', 'sbatch', 'qsub']` in the project directory, adding a script into a project fails as the options array is empty.
Fix to avoid these errors.
=> Added check to avoid errors when empty options array

apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/config/configuration_singleton_test.rb
Backports #2944
Sort ondemand.d files by name before loading them. This guarantees the order of these files so that sites can order them appropriately.
=> backport sort ondemand.d files by name before loading (#2944)

apps/dashboard/app/models/script.rb, apps/dashboard/test/models/script_test.rb, apps/dashboard/test/system/jobs_app_test.rb
PR with a proposal to change the script storage from id based script files into an id based directory.
The resulting directory structure is as follows:
```
projects/
├─ 1/
│  ├─ .ondemand/
│  │  ├─ scripts/
│  │  │  ├─ 1/
│  │  │  │  ├─ form.yml
│  │  │  │  ├─ cache.json
│  │  │  │  ├─ job_history.log
```
=> Updated script storage for new job composer

apps/dashboard/app/controllers/projects_controller.rb, apps/dashboard/app/models/project.rb, apps/dashboard/app/views/projects/_form.html.erb, apps/dashboard/config/locales/en.yml, apps/dashboard/test/models/projects_test.rb, apps/dashboard/test/system/jobs_app_test.rb
Fixes: #2558 
DRAFT PR => still needs work, but the structure is there.
Implementation to allow overriding the project path when creating a project.
As the `directory` field is a `attr_reader`, I have disable updating the value on edit.
The implementation uses the `path_selector` widget.
=> Added implementation for overriding project location path

apps/dashboard/app/models/project.rb, apps/dashboard/app/models/script.rb, apps/dashboard/app/views/projects/index.html.erb, apps/dashboard/app/views/projects/show.html.erb, apps/dashboard/test/system/jobs_app_test.rb
Fixes #2991 
Updated project and script model to use random alphanumeric strings as ids
Had to add `created_at` field to the script model to order the scripts as they are created.
=> Updated project and script model to use random alphanumeric ids

apps/dashboard/app/models/batch_connect/app.rb, apps/dashboard/test/fixtures/apps/bc_with_subapps/form.yml, apps/dashboard/test/fixtures/apps/bc_with_subapps/local/oakley.yml, apps/dashboard/test/fixtures/apps/bc_with_subapps/local/owens.yml, apps/dashboard/test/fixtures/apps/bc_with_subapps/manifest.yml, apps/dashboard/test/models/batch_connect/app_test.rb
Adding support to override category, subcategory, and metadata in the subapps yml configuration.
Fixes: #3005
=> Added support to override category, subcategory, and metadata in subapps

.github/workflows/tests.yml
With #3003 failing for unknown reasons - let's add test.log to the artifact(s) we upload.
=> also upload logs when system tests fail

apps/dashboard/app/controllers/projects_controller.rb, apps/dashboard/app/models/project.rb, apps/dashboard/app/views/projects/_form.html.erb, apps/dashboard/app/views/projects/edit.html.erb, apps/dashboard/app/views/projects/index.html.erb, apps/dashboard/app/views/projects/new.html.erb, apps/dashboard/config/locales/en.yml, apps/dashboard/test/models/projects_test.rb, apps/dashboard/test/system/jobs_app_test.rb
Fixes https://github.com/OSC/ondemand/issues/2976
Updated project validation now that project directory can be configured by the user.
Draft PR to showcase approach for new project validation using create and update flows
=> Updated new job composer project validation - Single Project Model

apps/dashboard/app/views/layouts/_config.html.erb, apps/dashboard/app/views/layouts/application.html.erb, apps/dashboard/app/views/layouts/editor.html.erb
This is a simple refactor that does a couple things:
* changes the config tag from `meta` to `div` because, well it isn't really meta.
* puts all this configuration into a partial because, as you can see, the `editor`'s layout is already out of sync.
=> change config to a div and put it in a partial

apps/dashboard/app/controllers/projects_controller.rb, apps/dashboard/app/models/project.rb, apps/dashboard/test/models/projects_test.rb
Fixes: #2954 
First implementation to sync the files from a template into a new project.
All files from the template will be copied in this implementation.
It is based on the batch connect session stage method.
Regarding the template interface, I have removed the link to add a project from a template and always added the templates if any available. Let me know if I should revert this part.
=> Added template files sync when creating a project from a template

apps/dashboard/app/javascript/packs/path_selector/path_selector.js, apps/dashboard/app/javascript/packs/path_selector/path_selector_data_table.js, apps/dashboard/app/views/batch_connect/session_contexts/_path_selector.html.erb, apps/dashboard/test/system/batch_connect_test.rb
Looks like the initial directory was hard coded to the user's home. This addition allows users to set the `directory`.
To enable a different initial directory just add the `directory` attribute like so:
```yaml
form:
- path
attributes:
path:
widget: 'path_selector'
directory: /some/other/directory
```
=> path_selector to support initial directory w/ tests

apps/dashboard/app/models/hpc_module.rb, apps/dashboard/test/application_system_test_case.rb, apps/dashboard/test/models/hpc_module_test.rb, apps/dashboard/test/system/batch_connect_test.rb
auto_modules needs to filter hidden modules so they don't show up in the UI.
=> backport Filter hidden modules (#2997) to 3.0.

apps/dashboard/app/helpers/scripts_helper.rb, apps/dashboard/app/javascript/packs/script_edit.js
Fixes #3017, #3050 
Fixes to change the dropdown selected item when it is removed using the remove button.
As well, added an alert when removing the last item in a dropdown to stop users removing all dropdown items.
There is as well a fix the the code to initialize the disabled items. 
And added autocomplete=off to form items to fix the Firefox issue for selected dropdown items
=> Edit script javascript fixes for selected dropdown items

apps/dashboard/app/models/active_jobs/jobstatusdata.rb
from discourse - https://discourse.openondemand.org/t/ood-3-0-1-and-undetermined-info-when-looking-at-cluster-job-info/2897/5
It appears end time can be `NONE` as well as `N/A` so let's account for that.
This will now show blank end time and start times which I'm actually OK with (previous behavior wouldn't show them at all if they were `N/A`)
=> account for NONE time value

apps/dashboard/config/initializers/upgrade_to_3.0.rb
I don't know for a fact that this is causing #3028 but such an expensive glob against an NFS storage can't be good.
=> short circuit this glob if youve already upgraded

apps/dashboard/app/javascript/packs/batch_connect.js, apps/dashboard/app/javascript/packs/config.js, apps/dashboard/app/views/batch_connect/session_contexts/_form.html.erb, apps/dashboard/app/views/layouts/_config.html.erb, apps/dashboard/test/system/batch_connect_test.rb
Fixes #2950 so that the javascript file (with path_selector and other updates) will get loaded all the time. Only when `bc_dynamic_js` is enabled (the config now exposed through javascript) will the javascript file create event handlers for the same.
=> expose bc_dynamic_js to javascript so we can always load these files

apps/dashboard/app/javascript/stylesheets/projects.scss, apps/dashboard/app/javascript/stylesheets/scripts.scss
Fixes #3016 by thicken border on hover instead of resizing.
=> thicken border on hover instead of resizing

apps/dashboard/app/models/posix_file.rb, apps/dashboard/test/models/files_test.rb, apps/dashboard/test/system/files_test.rb
add stronger validations on symlinks. This breaks a little compatibility where we used to show invalid symlinks in views, notably broken symlinks (symlinks to files that no longer exist).
=> add stronger validations on symlinks

packaging/deb/rules, packaging/rpm/ondemand.spec, spec/e2e/00_package_spec.rb
rm recursive permissions on project manager because after setting the directory to 750 in puppet - the manifest.yml file is still 700 - which is unreadable by us.
=> rm recursive permissions on project manager

apps/dashboard/app/javascript/packs/path_selector/path_selector.js, apps/dashboard/app/javascript/packs/path_selector/path_selector_data_table.js, apps/dashboard/app/views/batch_connect/session_contexts/_path_selector.html.erb, apps/dashboard/test/system/batch_connect_test.rb
This updates the path selector to actually use configurations to hide hidden things and files.
Here's an example configuration with defaults.
```yaml
---
cluster:
- owens
form:
- path
attributes:
path:
widget: 'path_selector'
show_hidden: false
show_files: true
```
=> Path selector config hide

apps/dashboard/app/javascript/stylesheets/apps.scss
Currently some of the FontAwesome icons flow over the fixed width that is set for the icons. Visible in the screenshot here:
This PR sets the proper width for FA icons, while keeping the size the same:
This happens since [FA sets the width](https://github.com/FortAwesome/Font-Awesome/blob/afecf2af5d897b763e5e8e28d46aad2f710ccad6/css/fontawesome.css#L62) of `.fa-fw` to `1.25em`. I added `margin-right` to non-FA icons to align app names properly, although another option would be to set width (and height) to `1.25em` for those, but that would affect the size or aspect ratio of them.
=> Fix FontAwesome icon width in navbar app icons

apps/dashboard/app/controllers/scripts_controller.rb, apps/dashboard/app/helpers/batch_connect/session_contexts_helper.rb, apps/dashboard/app/helpers/scripts_helper.rb, apps/dashboard/app/javascript/packs/script_edit.js, apps/dashboard/app/models/script.rb, apps/dashboard/app/views/batch_connect/session_contexts/_fixed.html.erb, apps/dashboard/app/views/scripts/editable_form_fields/_edit_fixed_field.html.erb, apps/dashboard/app/views/scripts/editable_form_fields/_editable_number.html.erb, apps/dashboard/app/views/scripts/editable_form_fields/_editable_select.html.erb, apps/dashboard/app/views/scripts/editable_form_fields/_generic.html.erb, apps/dashboard/app/views/scripts/show.html.erb, apps/dashboard/config/locales/en.yml, apps/dashboard/test/models/script_test.rb, apps/dashboard/test/system/jobs_app_test.rb
Fixes #2948
Prototype to implement fixes values within new Job Composer scripts.
I am not sure about the UI as the combination of the dropdown + Add/Remove actions + Set as static are all linked.
I am not sure either of using the SmartAttributes `fixed` property to implement this feature, but seems like the right approach.
This PR shows what I had to do to make it work with SmartAttributes and the `fixed` property, but it is more a hack than a PR.
@johrstrom what is your idea for the UI?
And for the backend? Should the fixed property be use for this feature?
=> Functional prototype for static values in Scripts

apps/shell/yarn.lock
The CI is very flaky right now trying to setup the shell application. Just running `bin/setup` updates yarn.lock to this status.  That is how I've arrived at this diff - by simply installing.
=> attempt to fix CI

apps/dashboard/app/apps/favorite_path.rb, apps/dashboard/app/apps/ood_app.rb, apps/dashboard/app/views/files/_favorites.html.erb
This PR adds cloud icons for favorite paths for remote storages both in the navbar and in the file browser.
The navbar items are currently somewhat ugly due to the spacing, but that is fixed in my other open PR (#3075).
=> Add cloud icons for remote favorite paths

packaging/rpm/ondemand.spec
disregard brp-python-bytecompile errors so el7 can continue to build.
=> disregard brp-python-bytecompile errors

apps/dashboard/app/models/batch_connect/session.rb, apps/dashboard/test/models/batch_connect/session_test.rb
Stop serializing the connection view, and instead read it from the app directly.
=> Stop serializing the connection view.

apps/dashboard/app/controllers/files_controller.rb, apps/dashboard/config/initializers/validate_send_files.rb
Override sendfile to use Rails to read & send the file instead of Nginx.
=> override sendfile

apps/dashboard/app/helpers/scripts_helper.rb, apps/dashboard/app/javascript/packs/script_edit.js, apps/dashboard/app/views/scripts/editable_form_fields/_edit_field_buttons.html.erb
Fixes to the edit script javascript functionality:
- Fixed error when adding a new field after removing all fields in the form.
- Disabled `Add new option` button while there is one in progress.
- Disabled `Add new option` button if no more fields to add.
- Fixed form submission when all form fields are deleted.
=> Fixes to edit script javascript

apps/dashboard/app/helpers/scripts_helper.rb, apps/dashboard/test/helpers/scripts_helper_test.rb
Removing the "Remove" button from the `auto_batch_clusters` field in the edit script page
=> Disabled deleting auto_batch_clusters from edit script forms

apps/dashboard/app/models/posix_transfer.rb, apps/dashboard/app/models/transfer.rb, apps/dashboard/test/system/files_test.rb
Work on #2668 to refactor the removal of files to use ruby APIs instead of issuing the `rm` command.
=> Refactor transfer rm

apps/dashboard/Gemfile.lock, apps/myjobs/Gemfile.lock
3.0.2 has this bug with regards to Markdown Message of the Days. I tracked it down to the `Loofah` library which didn't even have `html4_fragment` until a few months ago.
https://discourse.openondemand.org/t/motd-error-after-update-to-3-0-2/3002
=> upgrade loofah to use html4_fragment

apps/dashboard/app/models/allowlist_policy.rb
Since #3057 and a few others, we're checking the allowlist all the time now. So, let's start caching the results so that we don't have to make the same operation all the time.
=> cache allowlist permitted?

apps/shell/app.js
"fixes #2269"
Fixes shell timeout issue by adding heartbeat function as described here https://discourse.openondemand.org/t/novnc-and-shell-session-timeout-after-1-minute/1622/6
Fix verified by other users in issue
=> Fixed shell app timing out after ~50 secs

apps/dashboard/app/assets/stylesheets/common.scss
Fixes issue https://github.com/OSC/ondemand/issues/3136
Would there be anywhere `.clickable` is used where we WOULDN'T want it to indicate with an underline on hover? Also, do we want to bother with active/inactive colors as well?
=> Underline .clickable on hover

apps/dashboard/app/assets/stylesheets/common.scss, apps/dashboard/app/javascript/path_selector/path_selector_data_table.js, apps/dashboard/app/views/batch_connect/session_contexts/_path_selector.html.erb
Fixes #3061 
https://github.com/OSC/ondemand/assets/6969170/1198894e-fb8e-4705-a402-7a861dc148a0
=> Adds loading icon to path selector UI on table refresh

.github/workflows/tests.yml, apps/shell/package.json, apps/shell/yarn.lock
Update `node-pty` so that builds can continue. Right now there's an(other) issue with `node-gyp` in the packaging repository. So this update is to fix the transient dependency on `node-gyp` along with any other bugfixes this version may have.
=> Update node pty

apps/dashboard/app/javascript/path_selector/path_selector_data_table.js, apps/dashboard/app/views/batch_connect/session_contexts/_path_selector.html.erb, apps/dashboard/config/locales/en.yml
Fixes #3145 
https://github.com/OSC/ondemand/assets/6969170/ca912a37-4ec9-46f6-88c1-8479e95c31ac
=> 3145 path selector error handling

apps/dashboard/app/lib/smart_attributes/attributes/auto_modules.rb, apps/dashboard/test/lib/smart_attributes/auto_modules_test.rb
A bug from discourse - https://discourse.openondemand.org/t/auto-modules-module-name-label/3054 - where you're unable to correctly set the label on the `auto_modules` smart attribute.
To replicate you could:
* enable auto modules with the environment variable `OOD_MODULE_FILE_DIR`. 
* check production config for files - https://github.com/search?q=repo%3AOSC%2Fosc-ood-config%20OOD_MODULE_FILE_DIR&type=code  - or use/copy the test fixtures
* Use a simple form like this that attempts to set the label on `auto_modules_R`
```yaml
cluster:
- pitzer
- owens
form:
- auto_modules_R
attributes:
auto_modules_R:
label: "my cool R Version"
```
Or - since I provided  a test, you could checkout the current master version of the auto_modules file and run that test.
=> correctly set auto_modules' label

apps/shell/app.js
Fixes #3137  by stop using node-pty's deprecated APIs.  Note that there was never an 'error' or 'close' event as far as I could tell.
There was an 'exit' event, but we didn't listen for it. (maybe that called triggered `close`?)
https://github.com/microsoft/node-pty/blob/6a385f94c1c15bc9c7688eda4c3666f6fbceede6/typings/node-pty.d.ts#L65
=> stop using node-pty's deprecated APIs

apps/shell/yarn.lock
add dev dependencies back to yarn.lock because our automation to update dependencies is currently failing because what's locked is only production dependencies, not `devDependencies`. A mistake I seem to have introduced in #3079.
https://github.com/OSC/ondemand/actions/workflows/update.yml
=> add dev dependencies back to shell's yarn.lock

apps/dashboard/app/javascript/script_edit.js, apps/dashboard/app/views/scripts/edit.html.erb, apps/dashboard/app/views/scripts/editable_form_fields/_editable_select.html.erb, apps/dashboard/test/system/jobs_app_test.rb
Fixes #3097 
Improvements to the way select field options are managed when the fixed property is selected.
=> Improved form fixed field UI for new Job Composer scripts

apps/dashboard/app/views/projects/index.html.erb
Regardless of #3133  - we should add `preview` so folks know it's not stable.
=> add preview mode to heading

apps/dashboard/app/views/projects/show.html.erb, apps/dashboard/config/locales/en.yml
This adds a link to project directory in `projects#show` as seen below.
This whole page's view is subject to change, but we would need some sort of file management in this view - this is just the lowest hanging fruit.
=> add a link to project directory in projects#show

apps/dashboard/app/models/batch_connect/app.rb
This is a small patch on top of #3149 which osc-bot closed for whatever reason.
=> Lint fixup

apps/dashboard/app/views/projects/show.html.erb
Similar to #3172 this adds `preview` text to project#show as well.
=> add preview header to projects#show as well

apps/dashboard/app/helpers/batch_connect/session_contexts_helper.rb, apps/dashboard/app/javascript/path_selector/path_selector.js, apps/dashboard/app/javascript/path_selector/path_selector_data_table.js, apps/dashboard/app/views/batch_connect/session_contexts/_favorites.html.erb, apps/dashboard/app/views/batch_connect/session_contexts/_path_selector.html.erb
Fixes #3032 
https://github.com/OSC/ondemand/assets/6969170/c1308179-db81-4c05-bf62-7a6df885c10a
=> 3032 support favorites in path selector

apps/dashboard/app/javascript/dynamic_forms.js, apps/dashboard/test/system/batch_connect_test.rb
Fixes #2659 by adding the ability to add `data-hide-` directives to checkboxes.  Here's a simple form I've been using to demonstrate this. I'm going to keep this in draft while I write tests.
```yaml
cluster:
- pitzer
- owens
form:
- checkbox_test
- path
attributes:
path:
widget: path_selector
checkbox_test:
widget: check_box
html_options:
data:
hide-path-when-un-checked: true
```
=> add the ability for data-hide- directives on checkboxes

apps/dashboard/app/javascript/dynamic_forms.js, apps/dashboard/test/application_system_test_case.rb, apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml, apps/dashboard/test/models/batch_connect/session_test.rb, apps/dashboard/test/system/batch_connect_test.rb
Fixes #3182 so that `data-set-` directives on options can check and un-check checkboxes.
Here's a variation of the from I'd been using to test this. Selecting the different options from `option_selector` flips the checkbox from checked to un-checked and back and forth.
```yaml
cluster:
- pitzer
- owens
form:
- checkbox_test
- option_selector
attributes:
option_selector:
widget: select
options:
- [
'check', 'check',
data-set-checkbox-test: '1'
]
- [
'un-check', 'un-check',
data-set-checkbox-test: '0'
]
checkbox_test:
widget: check_box
```
=> support for dynamic checkboxes

apps/dashboard/app/javascript/files/data_table.js
Fixes #2818
https://github.com/OSC/ondemand/assets/6969170/1e407c7c-a281-4a21-870c-4c9d957927d8
I found an even listener on window that detects back/forward button presses. I read into the `Vary` header and could not understand how it would help solve this problem. From my understanding, the `reloadTable()` function changes the URL without a request, and so the back/forward buttons go back to/forward to URLs without any request changes. So a header change doesn't really effect whether or not `reloadTable()` is called.
Tested in Firefox, Chrome, and Safari.
=> Adds onpopstate listener to capture back/forward button changes

apps/dashboard/app/controllers/settings_controller.rb, apps/dashboard/test/integration/settings_controller_test.rb
Fixes to the SettingsController after the CurrentUser settings refactoring.
I didn't see this was needed when the refactoring was done. And the tests available were not sufficient to catch this.
I have fixed both.
=> Fixes to SettingsController after CurrentUser settings refactoring

apps/dashboard/app/models/batch_connect/session.rb
Batch connect apps to use safer rsync args. By safer I mean in https://discourse.openondemand.org/t/setup-ood-in-vm/3135/16 the user describes issues with using `-a` when copying to NFS storage devices that do not allow a “chgrp” command.
=> bc apps rsync with safer args

apps/dashboard/app/controllers/projects_controller.rb, apps/dashboard/app/models/script.rb, apps/dashboard/app/views/projects/show.html.erb, apps/dashboard/config/locales/en.yml, apps/dashboard/test/models/script_test.rb
Added clusters validation to `projects.show` page.
If there are no options defined for the` auto_batch_clusters` Smart Attribute, the system will show a flash message and disable all the script actions in the `projects.show` page.
Fixes #2690
=> Added cluster validation to projects.show page to disable script actions

apps/dashboard/test/config/configuration_singleton_test.rb
Every time we add a configuration - we need to update test fixture files.
My thinking is, if it works for any of them, it'll work for all of them, so let's just do that instead (5 being just a number really) so that we don't have to continually update these tests every time we add a new configuration item.
=> only test the first 5 so we dont have to update these all the time

apps/dashboard/app/helpers/batch_connect/sessions_helper.rb, apps/dashboard/app/models/batch_connect/app.rb, apps/dashboard/app/models/batch_connect/session.rb, apps/dashboard/test/integration/sessions_controller_test.rb
Adding the option to have a custom completed.{md, html}.erb to show up only when the job is completed (e.g. to show a download link with an output file from the job)
=> Adding custom completed.{md, html}.erb

apps/dashboard/app/models/user_configuration.rb, apps/dashboard/test/models/user_configuration_test.rb
While configuring the FASRC and Sid profiles for our IQSS OOD installation and after discussions with the IQSS team, we have a proposal to improve how the current profile is selected in OOD.
The new approach will only select a profile if there is a definition of it in the configuration and manually selected profiles will take precedence over automatically selected ones.
We think this new approach will improve the configuration and user experience of working with profiles.
The new logic is:
If `Configuration.host_based_profiles` is true, use current request host as the profile.
If there is a profile selected in the UserSettingStore and this profiles is defined, use it.
If there is a profile defined that matches the current request host, use it.
If there is a default profile configured and …
=> Profile automatic selection improvements

ood-portal-generator/spec/fixtures/ood-portal.conf.all, ood-portal-generator/templates/ood-portal.conf.erb
Added support to remove the automatic redirect to the servername/proxy_server domains without having to remove the `servername` property or disabling rewrites.
We would like to access the OnDemand instance through multiple domains, but want to keep the rewrite rules and the `servername` config in place and use `server_aliases` for the alternative domains.
I was thinking of adding a check based on server_aliases being empty, but then I realized that this change will affect existing configurations. That is why the new property `multiple_hosts` was added.
=> Added support for multiple domains for  Apache config in portal generator

apps/dashboard/app/javascript/dynamic_forms.js, apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml, apps/dashboard/test/system/batch_connect_test.rb
correctly handle options that start with numbers. This fixes the bug that was filed on discourse - https://discourse.openondemand.org/t/data-option-for-option-does-not-work/3139
=> correctly handle options that start with numbers

apps/dashboard/app/javascript/path_selector/path_selector_data_table.js
This fixes a bug where the last visited was a file and the javascript cannot handle this fact on initialization.
Steps to replicate:
* load a batch connect app with a path selector
* navigate to a file and select it as the path
* refresh the page
* attempt to select something else. you'll find that the initial directory cannot load.
This fixes that issue, albeit a little invasively. We have to change the cache value to an object so we can determine if it's a file in the initialUrl method.
=> path selector bugfix

apps/dashboard/app/controllers/projects_controller.rb, apps/dashboard/app/controllers/scripts_controller.rb, apps/dashboard/app/models/script.rb, apps/dashboard/config/locales/en.yml, apps/dashboard/test/models/script_test.rb
Creates a default executable script in the project's directory when a new Script is created.
As well, it adds a validation message when there are no executable scripts in the project.
Fixes #3255
=> Created default executable script on new Script and added validation

apps/dashboard/app/models/project.rb, apps/dashboard/test/models/projects_test.rb
Added id into manifest data serialization.
As id is not supported by the current `Manifest` implementation and it is likely that other project metadata items will need to be stored in the manifest, I have removed the dependency with the `Manifest` class and store the data directly in the `Project` class.
Fixes #3120
=> Updated projects to serliaze id into projects manifest

apps/dashboard/app/assets/stylesheets/data_tables.scss, apps/dashboard/app/views/batch_connect/session_contexts/_path_selector.html.erb, apps/dashboard/app/views/files/_files_table.html.erb, apps/dashboard/test/system/files_test.rb, apps/dashboard/test/system/remote_files_test.rb
change sorting css styles to be more accessible
This changes the sorting chevrons on the files app and path selector data tables to be more accessible. Specifically, so screen-readers don't read the sorting chevrons fixing #3153.
This does also change the visual style to have 1 chevron, and it's only applied to the column that's currently being used to sort the table.
Before:
After:
=> change sorting css styles to be more accessible

apps/dashboard/app/javascript/prefill_templates/prefill_submit.js, apps/dashboard/app/javascript/prefill_templates/prefill_templates.js, apps/dashboard/app/views/batch_connect/session_contexts/_form.html.erb, apps/dashboard/app/views/batch_connect/session_contexts/_prefill_templates.html.erb, apps/dashboard/config/locales/en.yml
Here are some small, mostly cosmetic changes to batch connect templates. I'll go through them all if they're not listed here:
The biggest change is to use `camel_case` for HTML ids. Others i'll describe inline.
=> small fixups for bc templates

.github/workflows/release.yml
This is work for #2538 because the version listed here uses that set output.
=> use updated rseng/zenodo-release

apps/dashboard/app/helpers/dashboard_helper.rb
While working on the navigation bar, I noticed this logo is throwing off the rest of the page by extending beyond the page.
You can even see this in production 3.0 right now: Notice how the image extends over the navigation bar.
=> logo fixup

apps/dashboard/app/models/project.rb, apps/dashboard/app/models/script.rb, apps/dashboard/test/fixtures/projects/chemistry-5533/.ondemand/manifest.yml, apps/dashboard/test/fixtures/projects/chemistry-5533/.ondemand/scripts/8woi7ghd/form.yml, apps/dashboard/test/fixtures/projects/chemistry-5533/.ondemand/scripts/gtqxzsek/form.yml, apps/dashboard/test/fixtures/projects/chemistry-5533/.ondemand/scripts/jxbrz2vm/form.yml, apps/dashboard/test/fixtures/projects/chemistry-5533/assignment_1.sh, apps/dashboard/test/fixtures/projects/chemistry-5533/assignment_2.sh, apps/dashboard/test/fixtures/projects/chemistry-5533/assignment_3.sh, apps/dashboard/test/fixtures/projects/chemistry-5533/input_data/assignment_1.inp, apps/dashboard/test/system/jobs_app_test.rb
Fixes #3177
Update scripts when copying from templates because things like `auto_scripts` need to be aware of the project directory (the newly created project, not the template's directory).
=> update scripts when copying from templates

apps/dashboard/app/views/batch_connect/session_contexts/_form.html.erb, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/config/locales/en.yml, apps/dashboard/test/system/batch_connect_test.rb
Fixes #3303 
This also changes the language (through internationalization) from `prefill templates` to `save(d) settings`. I think that just sounds better. `template` seems a bit esoteric to me, where `save` and `settings` seem to fit better - especially for new users.
=> add config for prefill templates

CHANGELOG.md, apps/dashboard/app/helpers/application_helper.rb, apps/dashboard/app/views/layouts/application.html.erb, apps/dashboard/app/views/layouts/nav/_all_apps.html.erb, apps/dashboard/app/views/layouts/nav/_develop_dropdown.html.erb, apps/dashboard/app/views/layouts/nav/_featured_apps.html.erb, apps/dashboard/app/views/layouts/nav/_group.html.erb, apps/dashboard/app/views/layouts/nav/_group_items.html.erb, apps/dashboard/app/views/layouts/nav/_help_dropdown.html.erb, apps/dashboard/app/views/layouts/nav/_link.html.erb, apps/dashboard/app/views/layouts/nav/_log_out.html.erb, apps/dashboard/app/views/layouts/nav/_logo.html.erb, apps/dashboard/app/views/layouts/nav/_sessions.html.erb, apps/dashboard/app/views/layouts/nav/_user.html.erb, apps/dashboard/test/html_helper.rb, apps/dashboard/test/integration/custom_help_navigation_test.rb, apps/dashboard/test/integration/custom_navigation_test.rb, apps/dashboard/test/integration/dashboard_controller_test.rb
This refactors the navigation bar to follow the `menubar` pattern.  I'll try to leave comments here and there for more description on the changes.
The example/documentation I'm following is here:
https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-navigation/
@abujeda can you please take a look at how this affects customizing the navigation bar? There could be some areas I missed and/or adversely affected.
=> refactor navbar to be menubar

apps/dashboard/app/models/concerns/user_setting_store.rb, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/config/initializers/upgrade_to_3.1.rb, apps/dashboard/test/integration/settings_controller_test.rb, apps/dashboard/test/models/concerns/user_setting_store_test.rb, apps/dashboard/test/models/user_configuration_test.rb, apps/dashboard/test/system/batch_connect_test.rb
mv the user settings file off the dataroot.
Fixes #3302 
@abujeda PTAL and see if this is going to be problematic for you. I don't know how to handle the case when folks have redefined the old config path/filename.
=> mv the user settings file off the dataroot

apps/dashboard/config/application.rb
In IQSS, we have 2 custom BatchConnect templates that require 2 ruby classes in an specific lib folder.
We are currently adding these 2 ruby files into the installed OnDemand lib folder: `/var/www/ood/apps/sys/dashboard/lib ` under the expected path:` /ood_core/batch_connect/templates/`
We would like support to load these classes from the external config root to keep all customizations and overrides together as well as not modify the dashboard file structure.
We might develop as well custom SmartAttributes and this will help to deploy them
=> Added external lib folder to autoload path

apps/dashboard/test/system/jobs_app_test.rb
this fixes a flaky test. The test is flaky because `Dir.glob` works differently on different systems & Ruby version.
So instead of globbing, we'll just call the script form by id.
=> stop globbing and just use the script id

apps/dashboard/app/javascript/script_show.js, apps/dashboard/app/lib/account_cache.rb, apps/dashboard/app/views/scripts/show.html.erb
enable dynamic forms in the scripts#show page. This is primarily when scripts add `queues`. This list of select options needs to be dynamic, so this adds the javascript to be dynamic as well as the relevant `data-option-for` directives.
=> enable dynamic forms in the scripts#show page

apps/dashboard/app/views/batch_connect/session_contexts/_prefill_templates.html.erb, apps/dashboard/config/locales/en.yml
add close buttons to this modal because there were none before.
This also changes `h5` tags to just divs for accessibility.
=> add close buttons to this modal

apps/dashboard/app/controllers/apps_controller.rb
The route 
> app GET  /apps/show/:name(/:type(/:owner))(.:format) apps#show {:type=>"sys"}
with a 'path' URL parameter causes an application error. 
```
#<NoMethodError: undefined method `uri' for #<AppsController:0x0000000001f5e0>
Did you mean?  URI>
...
```
Example using 'myjobs':
https://ondemand-test.osc.edu/pun/sys/dashboard/apps/show/myjobs 
redirects to
https://ondemand-test.osc.edu/pun/sys/myjobs without issues.
https://ondemand-test.osc.edu/pun/sys/dashboard/apps/show/myjobs?path=x
causes the above error.
I verified after the change dashboard/apps/show/myjobs?path=x redirects to /myjobs/x and displays the below instead of an error. 
> The page you were looking for doesn't exist.
> You may have mistyped the address or the page may have moved.
> 
> If you are the application owner …
=> Fix an error at /apps/show/:name?path=x

apps/dashboard/app/views/projects/show.json.jbuilder, apps/dashboard/test/models/projects_test.rb, apps/dashboard/test/system/jobs_app_test.rb
Some test improvements for the new project size feature
=> Improved testing for Project size feature

apps/dashboard/app/apps/nav_bar.rb, apps/dashboard/test/apps/nav_bar_test.rb
Adding sorting to the NavBar group selection subcategories.
fixes #3343
=> Fixes to the nav_bar group selection subcategory order

apps/dashboard/app/assets/stylesheets/pinned_apps.scss
PR #3075 affected the images for pinned apps, adding a right margin that was not needed in this context.
This is a fix to reset the right margin to 0.
=> Fixed app-icon margin for Pinned Apps after update in #3075 PR

apps/dashboard/app/models/project.rb, apps/dashboard/test/models/projects_test.rb
Fixes to` Project.initializer` and `Project.new_record?` to avoid loading an existing manifest when instantiating a new project with the same directory as another project.
Before `new_record?` was returning false if the user adds a directory override that points to an existing project.
I discover this issue when testing changes for #3107
=> Removed setting id in Project.initializer to fix project validation edge case

apps/dashboard/app/views/batch_connect/sessions/card/_host.html.erb
We're testing OOD 3.1 and I noticed the behaviour for host on app cards changed in #3211.
Upon closer inspection it turns out that if you have SSH to compute nodes disabled the users will see an internal server error on the My interactive sessions page while the job is starting (before `connection.yml` exists, so `session.connect` is not safe to call).
```
#<Errno::ENOENT: No such file or directory @ rb_sysopen - /users/robkarls/ondemand/data/sys/dashboard/batch_connect/dev/ood-base-jupyter/output/737014d2-07c4-47ac-b601-f157ba9bf322/connection.yml>
/var/www/ood/apps/sys/dashboard/app/models/batch_connect/session.rb:560:in `read'
/var/www/ood/apps/sys/dashboard/app/models/batch_connect/session.rb:560:in `read'
/var/www/ood/apps/sys/dashboard/app/models/batch_connect/session.rb:560:in …
```
=> Show app card host only for running sessions

ood-portal-generator/share/need_auth.html
Fixed a small spelling error in _need_auth.html_ when I was plugging around the code base for the `ood-portal-generator` utility. The spelling error is presented when you first deploy Open Ondemand, but have not yet configured an OpenIDC provider for Apache.
=> Fix spelling error in need_auth.html from ood-portal-generator 

apps/dashboard/esbuild.config.js
ensure build dir is clean when building assets. I found that this directory isn't always clean and it can leak stuff when you're building assets over and over again like we do in dev environments.
=> ensure build dir is clean when building assets

apps/dashboard/app/controllers/batch_connect/session_contexts_controller.rb, apps/dashboard/app/helpers/batch_connect/sessions_helper.rb, apps/dashboard/app/views/batch_connect/sessions/card/_card_header.html.erb, apps/dashboard/config/locales/en.yml
An idea for a new feature:
Add an edit button into the session card to pre-load the Interactive Apps form with the session launch parameters.
This might be useful if users need to adjust few parameters when launching a new session
=> Added edit session feature to load BatchConnect form with existing session parameters

apps/dashboard/app/helpers/batch_connect/session_contexts_helper.rb, apps/dashboard/app/views/batch_connect/session_contexts/_path_selector.html.erb, apps/dashboard/test/system/batch_connect_test.rb
Backport #3375 to 3.1 to allow the path_selector to redefine html options like label and help message.
=> backport #3375 to 3.1

apps/dashboard/app/views/batch_connect/sessions/card/_card_header.html.erb, apps/dashboard/test/integration/sessions_controller_test.rb
Small improvements => Removed edit session button from Session cards for preset applications.
The edit session button makes no sense for preset applications as the form will have no fields.
=> Removed edit session button in Session card for preset applications

apps/dashboard/app/views/batch_connect/sessions/index.html.erb, apps/dashboard/app/views/widgets/_sessions.html.erb, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/config/configuration_singleton_test.rb
Added POLL_DELAY environment variable to UserConfiguration class.
This change is backwards compatible with the environment variable.
Fixes #3413
=> Added POLL_DELAY environment variable to UserConfiguration class

apps/dashboard/app/models/batch_connect/session.rb, apps/dashboard/test/models/batch_connect/session_test.rb
We are using the `modified_at` session attribute in our Connection View session cards, and we'd like to roll the change up into the official distribution.
The `modified_at` value is used to construct a link to our Grafana resource utilization dashboard (see below).
I have prepared a corresponding change for the `ood-documentation` repo, but I thought I should see how this pull request goes before submitting a pull request there.
Here's the info.html.erb we are using with this change:
```
<%
grafana_url_prefix = 'YOUR-URL-PREFIX-HERE'
start_time = created_at.to_i * 1000
if cache_completed
end_time = modified_at.to_i * 1000
else
end_time = 'now'
end
%>
<a href="<%= grafana_url_prefix %>&from=<%= start_time %>&to=<%= end_time %>&var-jobid=<%= job_id %>&refresh=5m" target="_blank">View this …
```
=> Include completed_at in serialized batch connect card attributes

apps/dashboard/app/models/launcher.rb, apps/dashboard/app/views/layouts/projects.html.erb, apps/dashboard/app/views/projects/_launcher_details.html.erb, apps/dashboard/app/views/projects/show.html.erb, apps/dashboard/test/system/project_manager_test.rb
This starts to redesign the projects#show page. It's only additive right now so that tests can pass and I can get a feel for what it should look like. 
The basic idea is that instead of having the table for all the launchers, we'd have this list that can toggle them. In that view (which only has text right now) is where you'd not only RUD launchers but also interact with the jobs that the launchers have created.
This is work for ticket #3109.
=> start to redesign the projects#show page

apps/dashboard/Gemfile, apps/dashboard/Gemfile.lock, apps/dashboard/app/controllers/files_controller.rb
This works to re-enable ActionController::Live. It replaces zip_tricks which is now deprecated with zip_kit which is the replacement.
It also fixes the issue with streaming zip files so ActionController::Live can be used in the downloading of zip files.
=> re-enable ActionController::Live

apps/dashboard/test/system/batch_connect_test.rb
#3439 tried to fix #3438, but alas, these tests continue to fail randomly. So let's try 10 seconds and see if that's enough time for the system tests to actually present this modal.
=> try to fix flaky tests again

apps/dashboard/app/lib/smart_attributes/attributes/auto_accounts.rb, apps/dashboard/test/lib/smart_attributes/auto_accounts_test.rb
Fixes #3456, though this starts out with just a test case just to demonstrate that this bug exists.
=> fix bug for auto_accounts

apps/dashboard/app/javascript/dynamic_forms.js, apps/dashboard/test/system/batch_connect_widgets_test.rb
Fixes #3425 
With the following `form.yml`:
```
form:
- path
- hide_path
attributes:
path:
widget: 'path_selector'
hide_path:
widget: 'select'
options:
- ['show path', 'show path']
- ['hide path', 'hide path', data-hide-path: true]
```
https://github.com/OSC/ondemand/assets/6969170/d8354895-72c9-441f-8f9b-b99709c3b22a
=> Fixes pathfinger_select widget with data-hide option

apps/dashboard/app/assets/stylesheets/projects.scss, apps/dashboard/app/javascript/projects.js, apps/dashboard/app/models/launcher.rb, apps/dashboard/app/views/projects/_launcher_details.html.erb, apps/dashboard/app/views/projects/show.html.erb
This enhances the projects#show page to list out the active jobs so that the page now lists out all the jobs that are currently running from a given launcher.
=> enhance the projects#show page with list of active jobs

apps/dashboard/app/models/hpc_job.rb, apps/dashboard/app/models/launcher.rb, apps/dashboard/app/views/projects/_launcher_details.html.erb, apps/dashboard/test/system/project_manager_test.rb
Fixes #3474. I did try Rails caching for a minute - but I don't think we'd want it because we will need a way to find `all` jobs, which caches really don't accommodate for - they're more about immediate access to key value pairs rather than searching across all values.
So, this PR just serializes more information in the current job history log.
=> serialize more job info

apps/dashboard/app/views/active_jobs/_ganglia_graphs_table.html.erb, apps/dashboard/app/views/active_jobs/extended_data.json.jbuilder, apps/dashboard/app/views/batch_connect/sessions/connections/_native_vnc.html.erb
I was testing some things in the nightly version of OOD, and I noticed there was an internal server error after starting the VNC.
I assume Rails 7 no longer accepts the `.html.erb` ending on the partial paths since this used to work previously.
```
#<ActionView::MissingTemplate: Missing partial batch_connect/sessions/connections/_native_vnc_linux.html.erb with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :md, :markdown, :jbuilder]}.
Searched in:
* "/etc/ood/config/apps/dashboard/views"
* "/var/www/ood/apps/sys/dashboard/app/views"
* "/opt/ood/ondemand/root/usr/share/gems/3.1/ondemand/3.1.20240324-169099.23584b9.nightly/gems/ood_appkit-2.1.4/app/views"
Did you mean?  batch_connect/sessions/connections/native_vnc_linux …
```
=> Fix paths for some partials

apps/dashboard/app/javascript/files/clip_board.js
I noticed some errors using the file browser in one of our instances, when clicking the Copy/Move button. Turns out there was a small typo in the code.
This PR fixes the error.
=> Fix file browser error on copy/move

ood-portal-generator/lib/ood_portal_generator/dex.rb, ood-portal-generator/lib/ood_portal_generator/view.rb, ood-portal-generator/spec/fixtures/ood-portal.conf.dex, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-full, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-ldap, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-no-proxy, ood-portal-generator/spec/fixtures/ood-portal.conf.oidc, ood-portal-generator/spec/fixtures/ood-portal.conf.oidc-ssl, ood-portal-generator/spec/fixtures/ood-portal.dex-full.proxy.conf, ood-portal-generator/spec/ood_portal_generator_view_spec.rb, ood-portal-generator/templates/ood-portal.conf.erb
Use relative `OIDCRedirectURI` where applicable, i.e., when not using a proxy server.
This is for partial support for #3442 - at least the OIDC bit.
=> use relative OIDCRedirectURI where applicable

apps/dashboard/app/helpers/application_helper.rb, apps/dashboard/app/views/layouts/application.html.erb, apps/dashboard/test/helpers/application_helper_test.rb, apps/dashboard/test/integration/custom_css_js_files_test.rb, apps/dashboard/test/system/batch_connect_test.rb
Adds support for type metadata for custom JavaScript files.
This change is backwards compatible.
```yaml
custom_javascript_files:
- src: "/js/file.js"
type: "module"
- "/js/other_file.js"
```
Possible fix for #3487
=> Added module support for custom javascript files

apps/dashboard/app/apps/nav_config.rb, apps/dashboard/app/models/user_configuration.rb, apps/dashboard/test/integration/dashboard_controller_test.rb, apps/dashboard/test/models/user_configuration_test.rb
=> Removes NavConfig class & Replaces its use

ood-portal-generator/spec/fixtures/ood-portal.conf.all, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-full, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-ldap, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-no-proxy, ood-portal-generator/spec/fixtures/ood-portal.conf.oidc-ssl, ood-portal-generator/spec/fixtures/ood-portal.dex-full.proxy.conf, ood-portal-generator/templates/ood-portal.conf.erb
redirect to HTTP_HOST to support aliases. Tests will fail for a bit while I update the fixtures, but I want to get a spot check on it before I proceed.
This should fix #3442 - or at least I'm hoping to.
=> redirect to HTTP_HOST to support aliases

apps/dashboard/test/system/batch_connect_test.rb, apps/dashboard/test/system/files_test.rb
fix flaky file test by resetting the session
Fixes #3492
=> fix flaky file test by resetting the session

apps/dashboard/app/javascript/products_show.js
We've been seeing this warning is esbuild for some time, so let's fix this expression here just to get rid of the warning.
```
$ node esbuild.config.js
▲ [WARNING] Comparison using the "===" operator here is always false [equals-new-object]
app/javascript/products_show.js:22:43:
22 │   if(button === undefined || button.data() === {}) { return; }
╵                                            ~~~
Equality with a new object is always false in JavaScript because the equality operator tests
object identity. You need to write code to compare the contents of the object instead. For
example, use "Array.isArray(x) && x.length === 0" instead of "x === []" to test for an empty
array.
```
=> fix this expression

apps/dashboard/app/models/launcher.rb, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/system/project_manager_test.rb
Fixes #3099 by allowing centers to define launcher fields that should get created when you create a new launcher.
=> add the ability to define default launcher fields

packaging/deb/control, packaging/rpm/ondemand.spec
This may be good to pull into 3.1 backport
=> Update Passenger and NGINX dependencies

apps/dashboard/app/helpers/system_status_helper.rb, apps/dashboard/app/views/system_status/index.turbo_stream.erb
=> Systemstatus visual updates

apps/dashboard/config/configuration_singleton.rb, apps/dashboard/config/routes.rb, apps/systemstatus/manifest.yml, packaging/rpm/ondemand.spec
=> Add system status to navigation bar

apps/dashboard/app/javascript/batch_connect_sessions.js, apps/dashboard/app/javascript/turbo_shim.js, apps/dashboard/app/views/batch_connect/sessions/index.html.erb
This is a simple refactor of turbo_shim.js to promote reuse because basically every component is going to poll as well as replace.
=> simple refactor of turbo shim

apps/dashboard/app/views/batch_connect/shared/_saved_settings_menu.html.erb, apps/dashboard/app/views/files/_default_label_error_messages.html.erb, apps/dashboard/app/views/layouts/application.html.erb, apps/dashboard/app/views/layouts/editor.html.erb
fixes #3580 
Replaces all defined `data-target` attributes with `data-bs-target` as is used in Bootstrap 5.
=> Update data-target attributes to data-bs-target

apps/dashboard/app/views/apps/_app_group_rows.html.erb, apps/dashboard/app/views/files/_shell_dropdown.html.erb
`dropright`, used to indicate the direction of a dropdown, is now `dropend` in bootstrap 5.
=> Dropright is now dropend

apps/dashboard/app/assets/stylesheets/batch_connect/saved_settings.scss, apps/dashboard/app/helpers/batch_connect/settings_helper.rb, apps/dashboard/app/models/batch_connect/settings.rb, apps/dashboard/app/views/batch_connect/settings/_action_buttons.html.erb, apps/dashboard/app/views/batch_connect/settings/show.html.erb, apps/dashboard/app/views/widgets/_saved_settings.html.erb, apps/dashboard/config/locales/en.yml, apps/dashboard/test/fixtures/file_output/user_settings/saved_settings_widget.yml, apps/dashboard/test/fixtures/file_output/user_settings/settings_helper.yml, apps/dashboard/test/helpers/batch_connect/settings_helper_test.rb, apps/dashboard/test/integration/saved_settings_controller_test.rb, apps/dashboard/test/integration/saved_settings_widget_test.rb
Created a saved settings widget to display the saved settings in the homepage.
Sample configuration:
```yaml
dashboard_layout:
rows:
- columns:
- width: 12
widgets:
- "saved_settings"
- "pinned_apps"
```
=> Added saved settings widget

apps/dashboard/app/javascript/batch_connect_sessions.js, apps/dashboard/app/views/widgets/_sessions.html.erb
The Active Sessions widget is meant to display a subset of the current active interactive sessions.
After the introduction of the Turbo Stream, all the session cards (regardless of the status) are replaced when an update is fetch from the server. This is causing that the active sessions widget goes from showing the first 3 active sessions to display all.
The fix is simply to disable the updates.
Later on, we will implement a solution to refresh the session data in the widget.
=> Fixes to the active sessions widget after the introduction of the Turbo Stream libraries

apps/dashboard/app/javascript/products_show.js, apps/dashboard/app/views/batch_connect/session_contexts/_prefill_templates.html.erb, apps/dashboard/app/views/batch_connect/session_contexts/new.html.erb, apps/dashboard/app/views/files/_copy_move_popup.html.erb, apps/dashboard/app/views/files/_default_label_error_messages.html.erb, apps/dashboard/app/views/layouts/_browser_warning.html.erb, apps/dashboard/app/views/layouts/application.html.erb, apps/dashboard/app/views/layouts/editor.html.erb, apps/dashboard/app/views/shared/_path_selector_table.html.erb, apps/dashboard/test/system/project_manager_test.rb
fixes #3591 
Changed data-dismiss to data-bs-dismiss to restore functionality.
Changed close to btn-close and removed span elements with &times to update buttons appearances to Bootstrap 5. The alignment still doesn't look quite right though:
=> Fix flash button after upgrade to Bootstrap 5

apps/dashboard/app/helpers/system_status_helper.rb, apps/dashboard/app/views/system_status/index.turbo_stream.erb
fixes #3569 
Cluster information is currently only available on Slurm. To ensure that the system status page works on other clusters, the following message is displayed when cluster information is not available ([Scheduler] being the scheduler used by the cluster).
=> Degrade gracefully when scheduler is not Slurm

apps/dashboard/app/javascript/dynamic_forms.js, apps/dashboard/test/system/batch_connect_widgets_test.rb
Fixes #3327 
form.yml
```
form:
- node_type
- cores
attributes:
node_type:
widget: select
options:
- [ 'small',  'small',  data-label-cores: 'Number of Cores (1-4)'  ]
- [ 'medium', 'medium', data-label-cores: 'Number of Cores (1-8)'  ]
- [ 'large',  'large',  data-label-cores: 'Number of Cores (1-16)' ]
cores:
widget: "number_field"
required: true
value: 1
```
https://github.com/OSC/ondemand/assets/6969170/fd671ea8-fcff-45a3-92cc-dea3d305ac20
=> Adds dynamic labels to form with data-label-*

apps/dashboard/test/system/files_test.rb
Correctly reset Capybara before these tests so that this test about checking for console logs really only applies to the files app and not some other page where we logged something.
=> correctly reset Capybara before these tests

apps/dashboard/app/views/system_status/index.turbo_stream.erb
The upgrade to bootstrap 5 resulted in some minor changes to the way tables are styled, necessitating a change to the styling of the system status page.
=> Update system-status page for bootstrap 5

apps/dashboard/app/assets/stylesheets/batch_connect/saved_settings.scss
Removed the double border and added the border radius to the saved settings navigation menu.
I have fixed, as well, the borders for the saved settings widget.
Images attached below
=> Improvements to the saved settings menu after Bootstrap upgrade

apps/dashboard/app/assets/stylesheets/application.scss
The navbar logo image size and padding for the whole navbar seems odd.
These are CSS fixes to bring them back as they were before the Boostrap5 upgrade.
If the new look and feel is expected, please cancel this PR.
We can fix the logo and padding for our installation using the custom CSS feature.
Images attached below.
=> Navbar logo and padding fixes after Bootstrp5 upgrade

apps/myjobs/Gemfile
climate_control needs to be production gem to be correctly loaded into the myjobs app.
=> climate_control needs to be production gem

apps/dashboard/app/views/layouts/_config.html.erb
Updated `_config.html.erb` partial to make `system_status_path` optional.
When system-status app is not enabled or deployed, the dashboard application breaks as `system_status_path` is not defined.
=> Fixed _config partial when system-status app is not enabled

apps/dashboard/app/controllers/files_controller.rb
Fixes #3114 
Sets the 'Content-Length' response header so the browser knows the total size and estimated download time of files.
=> Set 'content-length' header when downloading files

apps/dashboard/app/models/posix_file.rb, apps/dashboard/app/models/remote_file.rb, apps/dashboard/app/views/files/_file_action_menu.html.erb, apps/dashboard/app/views/files/index.json.jbuilder, apps/dashboard/test/system/files_test.rb
Fixes #3029 by not showing download buttons for things that are not downloadable (i.e., files that are not readable or pipes).
In draft while I write a test case.
=> hide download buttons for certain files

apps/dashboard/app/controllers/batch_connect/session_contexts_controller.rb
Fixes #3162.
Note: I'm not sure what the argument *against* the comments specifying what URL would be used to access the methods is. It seems like it would make sense to keep them.
=> Add return type comments

apps/dashboard/app/apps/ood_files_app.rb, apps/dashboard/test/system/files_test.rb
=> Fix favorites to consult allowlist

apps/dashboard/app/controllers/projects_controller.rb
I saw that the GitHub actions tests are sometimes failing due to the `ProjectsController` test.
This seems to the related to the Ajax call to get the project size made by the page after the project has been deleted.
This seems to be a race condition in the test and directory cleanup.
This fix will return a JSON 404 when the project is not available avoiding the redirect and the error due to the missing JSON response for the index page.
=> Added 404 JSON reponse to projects.show method

apps/dashboard/app/models/batch_connect/session.rb
vim swp files can be unreadable to users, especially if editing when opened with vim -R as root. This causes the rsync to
fail and job submission to be blocked. Excluding .*.swp files fixes that issue.
=> exclude vim swp files from rsync

apps/dashboard/app/javascript/apps.js, apps/dashboard/app/javascript/config.js, apps/dashboard/app/models/user_configuration.rb, apps/dashboard/app/views/layouts/_config.html.erb, apps/dashboard/test/models/user_configuration_test.rb
Added configuration for the default number of items for the `Datable` object used in the apps index page table.
This config can be extended to configure more `Datatable` options.
Fixes #3637 
```yaml
apps_datatable:
page_length: 4
```
=> Added configurable default number of apps to show in the apps table

apps/dashboard/app/controllers/application_controller.rb, apps/dashboard/app/controllers/projects_controller.rb, apps/dashboard/app/controllers/settings_controller.rb, apps/dashboard/app/models/announcement.rb, apps/dashboard/app/views/layouts/_announcements.html.erb, apps/dashboard/app/views/layouts/application.html.erb, apps/dashboard/config/locales/en.yml, apps/dashboard/test/fixtures/config/announcements/announcement_id.yml, apps/dashboard/test/fixtures/config/announcements/announcement_md.md, apps/dashboard/test/fixtures/config/announcements/announcement_view.yml, apps/dashboard/test/fixtures/config/announcements/announcement_yml.yml, apps/dashboard/test/fixtures/file_output/user_settings/announcements.yml, apps/dashboard/test/integration/announcement_views_test.rb, apps/dashboard/test/integration/settings_controller_test.rb, apps/dashboard/test/models/announcement_test.rb
This is a prototype PR and will require more work to complete the implementation.
Adding dismissible and required features to announcements.
- **Dismissible Announcements:** Will add a button to the announcement. When executed, the system will store that the announcement was completed in the user settings.
- **Required Announcements:** The same as dismissible, but will block all request to the application and only display an empty homepage with all the announcements until all required announcements have been executed.
Possbile implementation for #3634
=> Added dismissible and required features to announcements

apps/dashboard/app/models/motd_formatter/base_formatter.rb, apps/dashboard/app/models/motd_formatter/markdown.rb, apps/dashboard/app/models/motd_formatter/markdown_erb.rb, apps/dashboard/test/fixtures/files/motd_md_erb_w_html, apps/dashboard/test/models/motd_formatter/motd_formatter_markdown_erb_test.rb
From discourse: https://discourse.openondemand.org/t/motd-markdown-erb-format-not-working-after-upgrade-to-3-1-7/3623
Turns out we need to sanitize the `markdown_erb` MOTD format too. So this provides a base class that other classes can inherit the `safe_content` functionality from.
=> markdown_erb needs to sanitize html too

apps/dashboard/app/javascript/dashboard.js, apps/dashboard/app/javascript/utils.js, apps/dashboard/app/views/dashboard/index.html.erb
Work on #3697 for the `dashboard.js` file.
This turns `dashboard.js` into a module and removes the dependency on jQuery.
=> turn dashboard.js into a module

apps/dashboard/app/controllers/projects_controller.rb, apps/dashboard/app/models/launcher.rb, apps/dashboard/app/models/project.rb
Fixes #3685 
Updates the job log whenever a job is queried from the adapter, and does not query when the job is logged as being completed.
=> PM job state management

apps/dashboard/app/assets/stylesheets/application.scss, apps/dashboard/app/javascript/application.js, apps/dashboard/esbuild.config.js, apps/dashboard/package.json, apps/dashboard/yarn.lock
Since we upgraded Uppy, we can start to specify the packages to depend on with a bit more granularity, so this fixes that.
Also we can remove `data-confirm-modal` as we stopped importing it (for build and accessibility reasons), so let's remove it from package.json too.
Lastly, I found that when build errors occur, the esbuild still exists 0, meaning that rails will continue with the build. This addition ensures that we exit 1 when errors occur so that rails can stop the build process.
=> fix some JS dependencies

apps/dashboard/app/javascript/xdmod.js, apps/dashboard/app/javascript/xdmod/jobs.js
render xdmod jobs in plain js for a few reasons.
This is work on #3697, though tangentially. Really I'd like to get rid of Handlebars as a dependency and the content security policy violation it has (compiling/evaluating javascript `'unsafe-eval'`).
=> render xdmod jobs in plain js

apps/dashboard/app/controllers/files_controller.rb
CodeQl is complaining about this line not escaping backslashes (though it's not supposed to? it's escaping `"`s.) 
Upon investigation, it turns out Rails formats this for us and has a whole class for ContentDispositon header.
https://github.com/rails/rails/blob/bfd3cfdbfc38b25e53e5fe85f1c77a61c9c600b7/actionpack/lib/action_controller/metal/live.rb#L357
So I figure, let's remove the `gsub` call and let Rails do it's thing.  I could be convinced to duplicate what Rails does just to be sure, but it seems extraneous.
=> just supply zipname and have rails format it

apps/dashboard/app/javascript/files/data_table.js, apps/dashboard/app/models/posix_file.rb, apps/dashboard/app/models/remote_file.rb
Convert data to human sizes on the client.
This is an optimiztation found in #3026. I found that rails takes some time to do this calculation, so we can push it to the client instead in an attempt to speed up the responses.
=> convert data to human sizes on the client

apps/myjobs/app/models/workflow.rb
While doing some other work with myjobs, I found that after our upgrade to Rails 7 you can't use `<<` against the errors object anymore. So this fixes that to use the `add` api.
=> fix adding to errors after rails upgrade

apps/dashboard/app/javascript/dynamic_forms.js
dynamic bc also respond to hide: false.
I tried recently to use `data-hide-something: false` and it didn't work which is a bit annoying. Leaving it undefined (i.e., not there at all) is the current workaround, but it seems like it should also respond to `false` if it can.
=> dynamic bc also respond to hide: false

ood-portal-generator/spec/fixtures/ood-portal.conf.dex, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-full, ood-portal-generator/spec/fixtures/ood-portal.conf.dex-ldap, ood-portal-generator/spec/fixtures/ood-portal.dex-full.proxy.conf, ood-portal-generator/templates/ood-portal.conf.erb
Fixes #3673 by accounting for `/dex` (`dex_uri`) when enabling maintenance mode.
=> account for /dex (dex_uri) when enabling maintenance mode

mod_ood_proxy/lib/ood/proxy.lua, mod_ood_proxy/lib/pun_proxy.lua
fixes #3728 with solution provided by httpd devs. This works in my httpd bug reproducer - https://github.com/johrstrom/httpd-bug-reproducer/ - so I thought I'd try it here in our CI too.
=> fixes #3728 with solution provided by httpd devs

apps/dashboard/app/controllers/files_controller.rb, apps/dashboard/app/javascript/files/file_ops.js, apps/dashboard/app/javascript/files/uppy_ops.js, apps/dashboard/app/models/remote_file.rb, apps/dashboard/app/models/remote_transfer.rb
Uploading large files to remote filesystems has had problems for a long time (#2250), so I spent some time trying to find a solution and this was the result. I attempted to find some alternative solutions as Jeff commented on that issue, but was not able to find any.
This PR fixes #2250 by making the actual upload from the Rails temporary file to the remote filesystem happen in an Active Job instead of during the 60 second period (Apache `ProxyTimeout`) before Apache will return an error to the browser.
I was able to reuse most of the existing code for file transfers. The back end for uploads now sends a JSON response with a transfer if one was created, i.e. a transfer from `/tmp/RackMultipart...` to `s3remote:/mybucket/myobject`. The front end then queries the status of that transfer.
=> Fix large remote file uploads

apps/dashboard/app/models/launcher.rb, apps/dashboard/app/views/launchers/show.html.erb
Fixes #3409 
This commit doesn't display the information in any alternative format and instead just hides this information.
=> Hide fixed attributes

lib/tasks/test.rb
Fixes #3071 by finding the appropriate version of chromedriver and downloading it without folks having to search the json endpoints and download manually.
=> find chrome version and automatically dl the right driver

apps/dashboard/app/javascript/projects.js, apps/dashboard/app/models/hpc_job.rb, apps/dashboard/app/views/projects/_job_details.turbo_stream.erb
small fixups for job details panel. 
* The panel now stays open if it's being updated (it currently closes if it's open then updated)
* removes native from the details panel
* Fixes time displays to be a nice human readable format.
=> small fixups for job details panel

.github/workflows/update.yml
This workflow is broken right now trying to update the ffi gem for some reason.
This updates the ruby version to 3 which is more inline with the ruby version on most systems. It also removes the specific version of bundler just because I don't think it needs to be set and the most recent version should work fine.
I should also note that I can't replicate the issue locally. And I'm guessing it's because of the bundler version is smart enough to lock ffi from ood_core.
=> update the update workflow

ood_auth_map/lib/ood_auth_map/helpers.rb
From discourse: 
https://discourse.openondemand.org/t/user-mapping-doesnt-work-for-ad-users-with-accounts-in-etc-passwd/3714/4
Looks like we have to account for more in this regex. Specifically `@`s and `.`s.
=> account for more than just \w for usernames

apps/dashboard/app/javascript/projects.js, apps/dashboard/app/models/project.rb, apps/dashboard/app/views/projects/_job_details.turbo_stream.erb, apps/dashboard/app/views/projects/_job_details_content.html.erb, apps/dashboard/app/views/projects/show.html.erb
This updates projects#show to have separate sections for active jobs and completed jobs.  Also, completed jobs will no longer query for updates after it's completed.
Fixes #3758
=> pm - completed and active jobs

apps/dashboard/app/controllers/launchers_controller.rb, apps/dashboard/app/lib/smart_attributes/attributes/auto_job_name.rb, apps/dashboard/test/system/project_manager_test.rb
Fixes #3749 by allowing fixed to be set. It also tweaks the actual job name to be a little more compliant with the other apps.
=> allow auto_job_name to be fixed

apps/dashboard/app/models/posix_file.rb, apps/dashboard/test/models/files_test.rb, apps/dashboard/test/system/files_test.rb
fix downloadable? to account for other file types to work on #3026.
=> fix downloadable? to account for other file types

apps/dashboard/app/models/batch_connect/app.rb, apps/dashboard/app/views/batch_connect/session_contexts/_form.html.erb, apps/dashboard/test/fixtures/apps/bc_with_subapps/form.yml, apps/dashboard/test/fixtures/apps/bc_with_subapps/local/owens.yml, apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml, apps/dashboard/test/integration/batch_connect_test.rb, apps/dashboard/test/models/batch_connect/app_test.rb
This PR fixes #3405 by implementing a `form_header` option for the form YMLs. The form header will be shown only in the interactive app forms, as seen in the example screenshots in #3405.
Example usage:
```
form_header: |
[Documentation](/link/to/documentation)
The shell / SSH session will stay open and any programs started there will stay running...
attributes:
...
form:
...
```
=> Add support for interactive app form descriptions

apps/dashboard/app/controllers/launchers_controller.rb, apps/dashboard/app/lib/smart_attributes/attributes/auto_cores.rb
Fixes #3756 
Adds `:auto_cores_fixed` (as well as min and max) to the launchers controller and initializes rather than redefines `opts` for the attribute.
=> allow auto_cores to be fixed

apps/dashboard/app/models/launcher.rb, apps/dashboard/test/models/launcher_test.rb, apps/dashboard/test/system/project_manager_test.rb
More launcher id checks to get a handle on the codeql alerts.
While this doesn't satisfy the codeql alerts - I'm happy with it after some time. CodeQl would have us sanitize a bad value. I don't think we want to sanitize a bad value, I think we just want to force a good value if the value given is incorrect.
So this sets `@id` once and only once and makes a last minute check in `save` to be sure it's still correct (there's a test case that sets the instance variable and still tries to save).
=> More launcher id checks

apps/dashboard/app/models/launcher.rb, apps/dashboard/app/models/project.rb, apps/dashboard/test/models/projects_test.rb
CodeQl doesn't account for Rails validations, but even so I thought I'd strengthen them a bit.  I also just noticed that `scripts_dir` doesn't need to create the directory when it's called.
=> Project validations

apps/dashboard/test/models/launcher_test.rb
fix this test after last 2 merges. Tests started to fail. Now when you save launchers and they fail, the launcher directory is never actually created.
=> fix this test after last 2 merges

nginx_stage/test/fixtures/restart_confirmation.html, nginx_stage/test/views/pun_config_view_test.rb
add test for restart_confirmation in nginx_stage.
=> add test for restart_confirmation

apps/dashboard/app/models/allowlist_policy.rb
Thanks to the benchmark setup provided by Jeff in #3026, we were able to spend some time attempting to optimize the file browser file listing.
These optimizations were low hanging fruit with a decent impact on the runtime. It now returns early if no allowlist is defined (always allowed), and child paths are now determined by using strings rather than `Pathname`.
With an allowlist (`/users:/scratch:/projappl`, listing files in `/tmp`), there was a 2x speedup (50k files, 5 runs, 100s => 50s). Without an allowlist, the speedup was >3x (50k files, 5 runs, 49s => 14s).
The speedup depends heavily on the situation though, and the listing is only a part of the problem, as seen in #3801.
When manually testing the performance in a browser, the response time listing a directory with 50k files with …
=> Optimize allowlist handling

apps/shell/app.js
More shell ping/pong work to close connections after after a certain amount of time.
This
* disables the shell ping/pong functionality be default, with a configuration option to enable it.
* adds a configuration to disconnect a websocket after so much time of inactivity.
* adds a configuration to disconnect a websocket after so much time.
=> more shell ping/pong work

apps/shell/app.js
Backport shell ping/pong work to 3.1.
=> 3.1 shell ping

apps/dashboard/app/models/allowlist_policy.rb
Backport Optimize allowlist handling (#3804) to 3.1.
=> Optimize allowlist handling (#3804)

lib/tasks/test.rb
add lang wrappers to shellcheck. #3818 reminded me that these aren't being checked.
=> add lang wrappers to shellcheck

apps/dashboard/app/controllers/batch_connect/session_contexts_controller.rb, apps/dashboard/test/system/batch_connect_test.rb
Fixes #3604 by casting to an openstruct before writing the file. This ensures that attributes like `filter` (an Enumerable API) get correctly serialized.
=> Enumerable safe cachefile serialization

.github/workflows/tests.yml, apps/dashboard/test/system/files_test.rb
fix test ci because apparently `libsqlite3-dev` isn't on these images anymore?
=> fix test ci

apps/dashboard/app/controllers/files_controller.rb
It seems that I managed to introduce a regression in #3739, which I had missed during testing, but we noticed when testing 3.1.8 in a system where setgid bits are used. Sorry about that.
Uploading files to directories with the setgid bit set causes the response to the browser to be an internal server error as `PosixFile.handle_upload` returns the number of files affected by the chown operation to set the setgid bit rather than a Transfer or nil as intended.
This PR fixes that by explicitly checking whether the return value is a Transfer or not.
=> Fix error on file upload to directories with setgid bit

mod_ood_proxy/lib/node_proxy.lua
Fix for interactive apps not working after Apache 2.4.62, specifically when arguments are passed with ? character
=> Update node_proxy.lua - Fix for interactive apps not working

apps/dashboard/app/models/posix_file.rb, apps/dashboard/config/locales/en.yml, apps/dashboard/test/models/files_test.rb
Fixes #3835 by simply allowing the download of an empty directory.
=> allow empty directories to be downloaded

mod_ood_proxy/lib/node_proxy.lua, spec/e2e/proxy_spec.rb, spec/fixtures/extras/simple_origin_server.py
Fixes #3824, but really I just want to be sure the tests fail. The tests added in this PR reproduce/test for #3825, though I don't have a fix for it (yet)
=> Add e2e proxy tests for query parameters.

.github/workflows/tests.yml, apps/dashboard/test/system/files_test.rb
Fix test ci by populating these test files so that the directory isn't empty. This backports #3832 to 3.1.
=> fix test ci for 3.1 (#3832)

apps/dashboard/app/models/posix_file.rb
Fix #3851 by rescing this chown operation in case it fails.
=> rescue chown in case it fails

apps/dashboard/app/models/posix_file.rb
Backport #3856 to release 3.1.
Rescue chown in case it fails so the upload completes as successful.
=> backport - rescue chown in case it fails (#3856)

apps/dashboard/app/assets/stylesheets/application.scss, apps/dashboard/app/assets/stylesheets/xdmod.scss, apps/dashboard/app/javascript/utils.js, apps/dashboard/app/javascript/xdmod.js, apps/dashboard/app/javascript/xdmod/jobs.js, apps/dashboard/app/views/widgets/_xdmod_widget_jobs.html.erb, apps/dashboard/test/models/projects_test.rb
Added analytics metrics from XDMoD to the jobs widget.
The analytics are added on demand, with an AJAX call to each job. This call is triggered when the user clicks on one of the jobs.
Fixes #998
=> Added XDMoD analytics metrics to jobs widget

apps/dashboard/app/javascript/launcher_edit.js
Work on #3743 
Updates the information of the fixed checkbox when the environment variable changes so that it remains possible to fix/unfix it.
=> PM - Update fixed checkbox when environment variable changes

apps/dashboard/app/lib/smart_attributes.rb, apps/dashboard/app/lib/smart_attributes/attribute_factory.rb, apps/dashboard/app/lib/smart_attributes/attributes/global_attribute.rb, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/system/batch_connect_widgets_test.rb
Fixes #1763 by defining batch connect attributes in an `ondemand.d` file that can be used in batch connect forms. Note that these global configurations need to have the `global_` prefix to their name.
=> Global form items

apps/dashboard/app/models/project.rb, apps/dashboard/test/models/projects_test.rb
- Excludes `cache.json` and `job_log.yml` from projects created from templates.
- Adds tests for these exclusions.
=> 3176 exclude cache and logs from new template based projects

apps/dashboard/app/javascript/launcher_edit.js, apps/dashboard/app/views/launchers/editable_form_fields/_editable_select.html.erb
Fixes #3050 
Disables the remove button for the last option.
Note that this does not actually fix the attribute, just removes the ability for the user to click the remove button on the last option.
If we want to fix the option, it might make sense to allow the user to unfix the attribute by adding an item another item instead of disabling all of them. Otherwise, if the the attribute was fixed when there is only one option left, the "Fixed" checkbox would need to be unchecked and some arbitrary second option would need to be enabled.
=> script#edit don't allow user to remove last option

apps/dashboard/app/lib/smart_attributes/attribute.rb, apps/dashboard/test/system/batch_connect_widgets_test.rb
Fixes #3381 by lowercasing ids so that they always work with dynamic directives.
=> Normalize bc keys

.github/workflows/tests.yml, apps/dashboard/app/javascript/dynamic_forms.js, apps/dashboard/test/system/batch_connect_widgets_test.rb
Fixes #3538
First, I want to see how this tests, because I'm not 100% sure on it. I think it works for most cases, but tests will tell the tale.
Looking through the `git blame` I can see that #2158 added a lot of complication to fix #1658, but looking at #1658 a second time, I wonder if that even matters.
The issue in #1658 complained about mapping `OSC_JUPYTER` to `o_s_c_j_u_p_y_t_e_r`. But the issue is that this mapping is done to normalize keys in the tables. I'm thinking now that that odd mapping doesn't really matter.  As long as it's consistent, what's it matter?
=> greatly simplify snakeCaseWords

apps/dashboard/app/models/motd_formatter/base_formatter.rb, apps/dashboard/app/models/motd_formatter/markdown.rb, apps/dashboard/app/models/motd_formatter/markdown_erb.rb, apps/dashboard/test/fixtures/files/motd_md_erb_w_html, apps/dashboard/test/models/motd_formatter/motd_formatter_markdown_erb_test.rb
markdown_erb needs to sanitize html too.
This backports #3675 to release 3.1.
=> markdown_erb needs to sanitize html too (backport #3675)

apps/dashboard/app/controllers/active_jobs_controller.rb, apps/dashboard/app/models/active_jobs/jobstatusdata.rb, apps/dashboard/app/views/active_jobs/_extended_panel.html.erb, apps/dashboard/app/views/active_jobs/extended_data.json.jbuilder
After the refactoring completed in https://github.com/OSC/ondemand/pull/3700, a dependency was added to the `ActiveJobsHelper` to render the `status_label` method. The dependent method is in `ApplicationHelper`
This is breaking the Active jobs > job details AJAX call.
This is a possible fix for the issue
=> Fixed ActiveJobsHelper dependency on ApplicationHelper

apps/dashboard/app/views/launchers/editable_form_fields/_editable_select.html.erb
Moved `add` & `remove` buttons below the `choice` label in launcher's `_editable_select` partial.
=> 3436 clean-up PM launcher editable_select interface

apps/dashboard/app/lib/smart_attributes/attributes/auto_modules.rb, apps/dashboard/test/system/batch_connect_widgets_test.rb
Continuing #3867 auto_modules also need to be downcased to work with dynamic batch connect directives.
=> downcase auto modules so they are dynamic as well

apps/dashboard/app/models/launcher.rb, apps/dashboard/test/system/project_manager_test.rb, apps/myjobs/app/models/resource_mgr_adapter.rb
Fixes #3800 
Specify `workdir` when submitting batch jobs because these could be issued on clusters that centers use `submit_host` for. When using a `submit_host` the CWD when sbatch (or similar) is issued is $HOME (because they just sshed). So the `chdir` we use sparingly, only works when commands are being issued locally.
So, just specify the `workdir` when the job is submitted.
=> specify workdir when submitting batch jobs

apps/dashboard/app/javascript/turbo_shim.js
Fixes #3605. Note that the polling would have already stopped if a failure had occurred, it's just now with this addition it accounts for 401 unauthorized and provides an alert div when a failure occurs.
=> create an alert div if pollAndReplace fails

apps/dashboard/app/javascript/files/data_table.js
Fixes #3785 
Applies search to select all so that only visible rows are selected.
=> Files app - apply search to select all

apps/dashboard/app/views/files/edit.html.erb
Fixes #3662 to have a slightly better file editor layout.
before:
after:
Note that before, if the filename is rather long, it can start to overflow into multiple lines which looks kinda funny. Putting it here where it has 100% of the screen space I think is better.
=> better file editor layout

apps/dashboard/app/javascript/utils.js
Fixes #3803 because the `event.target` was actually the `span` which does not have an `href`. So this checks for the closest anchor (`a`) that has the `event.target` as a child.
=> check for the closest anchor when trying to open a link

nginx_stage/lib/nginx_stage.rb
Work on #3879 though it doesn't fix it.
It does however fix the issue of weird behaviour and errors like `missing PID file: /var/run/ondemand-nginx/true/passenger.pid`. The `true` being mapped here must be the `log.error` return value. So just return `nil` and compact. Users can still find the error messages in the system log.
=> account for this error and return nil

apps/dashboard/app/models/batch_connect/app.rb
Fixes #3857 by using `hidden_field` instead of fixing it. This will allow forms to actually have the value (which can be used in concert with dynamic batch connect directives) and correctly respond to `preset?`.
=> clusters should be hidden, not fixed.

apps/dashboard/app/models/batch_connect/session.rb, apps/dashboard/app/views/batch_connect/sessions/card/_card_body.html.erb, apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_paraview/completed.html.erb, apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_paraview/info.html.erb, apps/dashboard/test/system/batch_connect_sessions_test.rb
Fixes #3937 and adds some tests to boot.
=> Fix bc cards

apps/dashboard/app/helpers/batch_connect/sessions_helper.rb
Fixes to the tooltips for the edit and relaunch buttons in the session card.
All the buttons on the session card were using the Bootstrap tooltip feature that stopped working when Turbo Streams was introduced to render the cards.
This fix is for the default browser tooltip to work with these buttons.
=> Fixed tooltip for edit and re-launch buttons in the session card

apps/dashboard/app/helpers/batch_connect/sessions_helper.rb
While testing locally using the OOD version from source code, I started getting an error in some session cards when using the relaunch button. The error was: `"The cluster was never set. Either set it in form.yml.erb with `cluster` or `form.cluster` or set `cluster` in submit.yml.erb."`
After investigating, this is due to the changes to the cluster SmartAttribute that is added automatically to the session context. cluster is now a `hidden` attribute instead of `fixed`.
The issue is that sessions created before this change, will not have a value for `cluster` in the `user_defined_context.json` file. When generating the relaunch form, it will try to add a value from the user context for cluster these sessions will not have one.
The fix is simply to remove all the fields that do not have a …
=> Fixed session card relaunch button

apps/dashboard/app/lib/account_cache.rb
refactor qos computations so that the return value is a unique list of qos names that have the appropriate data- attributes applied to them.
Fixes #3933.
=> refactor qos

apps/dashboard/app/views/layouts/files.html.erb
Fixes #3958 by importing `files/index.js` as a module to avoid minified collisions.
=> import files/index.js as a module to avoid minified collisions

apps/dashboard/config/configuration_singleton.rb
correct this env variable and the ondemand.d config key.
I just happened to notice this when working on something else. 
* Environment variables should have the OOD_ prefix like the others do
* this key should have _poll_ (i.e., `status_poll_delay`) in it to match the environment variable.
=> correct this env variable and the ondemand.d config key

CHANGELOG.md
update changleog for 3.1.7 and 3.1.9
=> update changleog for 3.1.7 and 3.1.9

apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/config/configuration_singleton_test.rb
change this key slightly and an env variable.
Writing the docs for this and I noticed that there is no environment variable for this (POLL_DELAY being deprecated now), so this adds one. It also updates the key slightly from `sessions_poll_delay` to `bc_sessions_poll_delay` to be a little bit more specific.
=> change this key slightly and an env variable

apps/dashboard/app/javascript/files/globus.js
The globus JS is failing after the `files.html.erb` layout was updated to load `files/index.js` as a module.
Loading as a module automatically actives strict mode making variable declaration compulsury.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#strict_mode_for_modules
This is a minor fix for the globus.js
=> Fixed globus javascript variable declaration

apps/projects/manifest.yml
change the PM's icon because the project manager uses `magic` and they appear right next to each other in the menu.
=> change the PM's icon

apps/dashboard/app/javascript/files/data_table.js, apps/dashboard/app/views/files/_files_table.html.erb, apps/dashboard/app/views/files/_spinner.html.erb, apps/dashboard/test/system/remote_files_test.rb
=> Files busy signal

apps/dashboard/app/controllers/files_controller.rb, apps/dashboard/app/models/remote_transfer.rb, apps/dashboard/test/system/remote_files_test.rb
=> 3994 - fixes remote files test

apps/dashboard/app/javascript/files/data_table.js, apps/dashboard/app/javascript/files/file_ops.js, apps/dashboard/test/system/files_test.rb
Fixes #3666 
https://github.com/user-attachments/assets/e54d8230-dd9f-405b-91cf-ca8115acb125
=> 3666 disable dl btn when non dlable is checked files

apps/dashboard/Gemfile.lock, apps/dashboard/app/javascript/path_selector/path_selector.js, apps/dashboard/app/javascript/path_selector/path_selector_data_table.js, apps/dashboard/app/views/batch_connect/session_contexts/_path_selector.html.erb, apps/dashboard/app/views/projects/_form.html.erb, apps/dashboard/app/views/shared/_path_selector_table.html.erb, apps/dashboard/test/system/batch_connect_widgets_test.rb
Fixes #3037 
The following form.yml will generate a Select Path modal that shows only directories and Ruby files.
```
form:
- path
attributes:
path:
widget: "path_selector"
show_hidden: false
file_pattern: \.rb$
```
=> 3037 path select filename filter

apps/dashboard/app/apps/dev_router.rb, apps/dashboard/app/apps/sys_router.rb, apps/dashboard/config/locales/en.yml
=> Add i18n configuration for system installed captions

nginx_stage/lib/nginx_stage.rb, nginx_stage/lib/nginx_stage/generators/nginx_clean_generator.rb, spec/e2e/nginx_stage_spec.rb
Fixes #3879 by generating a list of inactive/disabled users and cleans up their PUNs and PUN related config files as well.
=> determin inactive users and clean their PUNs too

apps/dashboard/config/application.rb, apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/config/configuration_singleton_test.rb
Experimental feature to add support for a folder based OOD extensions structure.
The idea being that administrators can deploy OOD extensions by copying a folder to the new plugins directory.
More infor about the idea in #3916
To test:
Create the plugins folder:` /var/www/ood/apps/plugins`
Download the attached zip file. It contains a folder with an OOD extension.
Add the folder, `session_metrics`, into the plugins directory.
```
/var/www/ood/apps/plugins
│── session_metrics
│    ├── initializers
│    ├── lib
│    └── views
```
The attached zip file is an OOD extension to add Job metrics to the session card.
It requires a Slurm job scheduler to work.
[session_metrics.zip](https://github.com/user-attachments/files/18025165/session_metrics.zip)
Fixes #3916
=> Added support for multiple directories to deploy OOD extensions/customizations

apps/dashboard/test/system/batch_connect_widgets_test.rb, apps/dashboard/test/system/remote_files_test.rb
Adds sleep to the *correct* place in the test
=> 3994 - Fixes test

apps/dashboard/config/application.rb
Instead of just verifiying that the plugin directory is root owned, this verifies that _all_ files in the folders are root owned.
=> strengthen checks on plugin directories.

apps/dashboard/app/javascript/dynamic_forms.js, apps/dashboard/test/system/batch_connect_widgets_test.rb
Fixes #4013 
```
form:
- cluster
- node_type
attributes:
cluster:
widget: "select"
options:
- owens
- pitzer
node_type:
widget: "select"
options:
- standard
- [ 'gpu', 'gpu', data-exclusive-option-for-cluster-owens: true]
```
https://github.com/user-attachments/assets/16a11299-6624-4675-b01b-28e9ffafc94c
=> 4013 data exclusive option for

apps/dashboard/app/javascript/path_selector/path_selector.js, apps/dashboard/app/views/projects/_form.html.erb, apps/dashboard/app/views/projects/new.html.erb
Fixes #4052
When minified, these files conflict with jQuery, so import them as a module. Secondly, make this object const to avoid assinments to undeclared objects.
=> fix some minified javascript errors

apps/dashboard/app/javascript/path_selector/path_selector_data_table.js, apps/dashboard/app/javascript/utils.js, apps/dashboard/app/views/shared/_path_selector_table.html.erb
hide & show this element by id, rather than attempting to find the closest '.loading-icon' element to more reliably hide this.
This also adds a hide & show APIs to the utils.js file. The comments explain the same, but basically jQuery's hide() and show() API don't work on elements that have Bootstrap display classes like d-flex.
Fixes #4048
=> hide & show this element by id

apps/dashboard/test/system/batch_connect_widgets_test.rb
sleep here to fix this flaky test. This test can fail as given here: https://github.com/OSC/ondemand/actions/runs/12693786065/job/35382153664 executing before the modal pops up.
=> sleep here to fix this flaky test

Dockerfile, Dockerfile.dev
The current `Dockerfile` doesn't build any more with 4.0.0 on my end. With these changes it works again.
=> Fix Dockerfile

apps/dashboard/app/views/batch_connect/sessions/card/_card_header.html.erb, apps/dashboard/test/system/batch_connect_sessions_test.rb
=> only show nodes if it's positive

apps/dashboard/test/system/project_manager_test.rb
I can't seem to replicate this test failure locally, so I'm going to bounce this a few times to see if the test ever fails.
This is the test in question I'm trying to fix. 
I hope there's some issue in clearing it in javascript so that clearing it with backspaces is more consistent.
=> use backspace here to possibly make this test consistent

apps/dashboard/app/controllers/application_controller.rb, apps/dashboard/app/models/announcements.rb, apps/dashboard/test/models/announcements_test.rb
memorize announcements and filter for existing files to reduce warnings about `Announcement file not found:` here: https://github.com/OSC/ondemand/blob/1a685ab85ba2b228dd91e4c703fa9abbeb43923a/apps/dashboard/app/models/announcement.rb#L92
=> memorize announcements and filter for existing files

packaging/deb/control, packaging/rpm/ondemand.spec
Backport #4089 to the 4.0 release.
=> Require latest ondemand-passenger and ondemand-nginx (#4089) - 4.0

apps/dashboard/app/helpers/batch_connect/session_contexts_helper.rb, apps/dashboard/app/lib/smart_attributes/attribute.rb, apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml, apps/dashboard/test/system/batch_connect_widgets_test.rb
Allows inserting arbitrary Markdown into the app forms through the form.yml files.
The largest use case for us, which I've also seen others request on Discourse (e.g. [here](https://discourse.openondemand.org/t/custom-elements-in-form/3437) and [here](https://discourse.openondemand.org/t/how-to-create-headings-in-ood-form-yml-erb/2912)), would be use this to create headings/sections in the app form.
For example, the following form YML:
```
attributes:
slurm_partition:
label: "Slurm Partition"
widget: select
options:
- interactive
cores:
label: "Memory (GB)"
widget: number_field
value: 2
header_resources:
widget: markdown
value: |
---
header_settings:
widget: markdown
value: |
---
form:
- slurm_partition
- header_resources
- cores
- memory
- header_settings
- bc_email_on_started
```
would …
=> Add markdown widget for interactive app forms

apps/dashboard/app/javascript/path_selector/path_selector_data_table.js, apps/dashboard/test/system/batch_connect_widgets_test.rb
Fixes #4082 by ensuring we URL decode anything that's being saved in the path selector. This also adds a test to confirm.
=> ensure filenames are not url encoded

apps/dashboard/app/helpers/batch_connect/sessions_helper.rb, apps/dashboard/app/views/batch_connect/settings/_action_buttons.html.erb, apps/dashboard/app/views/batch_connect/settings/show.html.erb
update from data-toggle to data-bs-toggle to correct a few toggle panels. Specifically the native VNC connection tab, but this also fixes a tooltip or two.
Fixes #4114
=> update from data-toggle to data-bs-toggle

ACCESSIBILITY.md, CONTRIBUTING.md, DEVELOPMENT.md, README.md, VERSIONING_POLICY.md
- Skimmed through .md files with `aspell --lang=en_US`
- Miscellaneous wording improvements
=> Various typo and language fixes

apps/dashboard/app/helpers/batch_connect/sessions_helper.rb, apps/dashboard/app/views/batch_connect/settings/_action_buttons.html.erb, apps/dashboard/app/views/batch_connect/settings/show.html.erb
update from data-toggle to data-bs-toggle to correct a few toggle panels. Specifically the native VNC connection tab, but this also fixes a tooltip or two.
=> update from data-toggle to data-bs-toggle (#4115)

apps/dashboard/app/models/project.rb
Related to Issue #4121 
By default directory permissions were **rwxr-xr-x**. 
This is updated to **rwxr-x---**, thus groups can also read and execute the files inside of the project directory (as before) while others will have no permissions to ensure safety.
Locally tested the changes with OOD master branch instance running on OOD.
=> Updated the project directory permission allowing group to read and execute files

apps/dashboard/Gemfile.lock, apps/myjobs/Gemfile.lock
Backport gem updates to 4.0. Note I've got this in draft for a minute to get ood_core ready as well.
=> update OOD gems in 4.0

apps/dashboard/config/routes.rb
Backports #4133 to 4.0.
Permissive constraints on owner segment for apps/show to allow for usernames with dots and so on.
=> Permissive constraints on owner segment for apps/show (#4133)

packaging/rpm/ondemand-selinux.te
On RHEL 9, some files in the home directory are labeled with user_home_t rather than user_home_dir_t https://danwalsh.livejournal.com/63586.html appears to suggest that this is expected behaviour
=> Add user_home_t to SELinux tunable

Dockerfile.dev, lib/tasks/rake_helper.rb
This dev container is currently failing to build (and launch the PUN) complaining that `sudo` needs a password. This resolves that issue and also forces layering for podman builds.
=> Fix dev container

packaging/rpm/ondemand-selinux.te
On RHEL 9, some files in the home directory are labeled with user_home_t rather than user_home_dir_t https://danwalsh.livejournal.com/63586.html appears to suggest that this is expected behaviour
=> Add user_home_t to SELinux tunable (#4142) (release 4.0 backport)

apps/dashboard/app/apps/ood_app.rb
If an app has an external URL, use that in the navigation items' href instead of `/pun/sys/dashboard/apps/show/<appname>` which results in an error trying to redirect to another host.
=> allow redirect to other host in apps#show (#4140)

apps/dashboard/config/application.rb
After installing OODv4.0.0 and configure the plugins directory, I was getting the following error:
```
App 240 output: Error: The application encountered the following error: undefined method `safe_load_path?' for class Dashboard::Application (NoMethodError)
App 240 output:     /opt/ood/ondemand/root/usr/share/gems/3.3/ondemand/4.0.0-1/gems/railties-7.0.8.5/lib/rails/railtie.rb:228:in `method_missing'
```
This PR fixes this issue.
It would be great to retrofit to OODv4.0.0 branch so that it goes into the next release.
=> Fixed safe_load_path? method definition to avoid runtime errors

apps/dashboard/config/application.rb
Sorry Jeff, I inserted a type by mistake when committing the previous fix. I think it relates to pressing `ctr+s`.
This is a minor typo fix.
I tried to add a test for this, but could not figure out how to do it.
=> Fixed application class type for exist? method

apps/dashboard/app/helpers/application_helper.rb, apps/dashboard/test/helpers/application_helper_test.rb, apps/myjobs/app/views/layouts/application.html.erb
fixes 2895
test help: I have a test for the code modification but the code requires the environment to be in production mode, and I am having trouble getting that working in the test.
=> Bug fix/favicon referrerpolicy 2895

apps/dashboard/app/views/layouts/nav/_styles.html.erb
CSS selector update for the background color of the active navigation item.
It works on my local machine, but someone needs to verify this is the expected behaviour.
Fixes: #4181 
Add a value to the `brand_link_active_bg_color` property in the configuration or to `OOD_BRAND_LINK_ACTIVE_BG_COLOR` environment variable:
```YAML
brand_link_active_bg_color: red
```
=> Fixed CSS selectors for active navigation link color

apps/dashboard/app/controllers/projects_controller.rb, apps/dashboard/app/views/projects/_form.html.erb, apps/dashboard/app/views/projects/import.html.erb, apps/dashboard/app/views/projects/index.html.erb, apps/dashboard/config/locales/en.yml, apps/dashboard/config/locales/ja_JP.yml, apps/dashboard/config/locales/zh-CN.yml, apps/dashboard/config/routes.rb
Related to Issue https://github.com/OSC/ondemand/issues/4120
This is the first PR, to add the blueprint of the form that will allow a user to fill in the shared project path.
This path will later be saved into the user's .lookup-file
=> Added a form to projects to import a shared-project using directory path

apps/dashboard/app/javascript/files/data_table.js, apps/dashboard/app/models/posix_file.rb, apps/dashboard/app/views/files/index.json.jbuilder, apps/dashboard/test/system/files_test.rb
Do not provide href links to files when download is disabled and remove the 'view' button when downloading is disabled.
Fixes #4159 by showing only text for files when download is disabled (i.e., a `span` tag not an `a` tag with an `href`) and not showing the `View` button when downloading is disabled.
=> Do not provide href links to files when download is disabled.

apps/dashboard/test/lib/smart_attributes/auto_log_location_test.rb
use asset_nil here for fix deprecation warnings.
Specifically, these warnings:
```
DEPRECATED: Use assert_nil if expecting nil from test/lib/smart_attributes/auto_log_location_test.rb:52. This will fail in Minitest 6.
DEPRECATED: Use assert_nil if expecting nil from test/lib/smart_attributes/auto_log_location_test.rb:40. This will fail in Minitest 6.
```
=> use asset_nil here for fix deprecation warnings

apps/dashboard/app/apps/request_tracker_service.rb, apps/dashboard/app/apps/support_ticket_email_service.rb, apps/dashboard/app/apps/support_ticket_rt_service.rb, apps/dashboard/app/apps/support_ticket_service_now_service.rb, apps/dashboard/app/controllers/active_jobs_controller.rb, apps/dashboard/app/controllers/support_ticket_controller.rb, apps/dashboard/app/javascript/active_jobs.js, apps/dashboard/app/javascript/config.js, apps/dashboard/app/models/active_jobs/jobs_json_request_handler.rb, apps/dashboard/app/models/concerns/support_ticket_service.rb, apps/dashboard/app/models/support_ticket.rb, apps/dashboard/app/views/layouts/_config.html.erb, apps/dashboard/app/views/support_ticket/email/_email.text.erb, apps/dashboard/app/views/support_ticket/rt/rt_ticket_content.text.erb, apps/dashboard/app/views/support_ticket/servicenow/servicenow_content.text.erb, apps/dashboard/config/locales/en.yml, apps/dashboard/test/apps/request_tracker_service_test.rb, apps/dashboard/test/apps/support_ticket_email_service_test.rb, apps/dashboard/test/apps/support_ticket_rt_service_test.rb, apps/dashboard/test/apps/support_ticket_service_now_service_test.rb, apps/dashboard/test/integration/support_ticket_integration_test.rb, apps/dashboard/test/models/concerns/support_ticket_service_test.rb, apps/dashboard/test/models/support_ticket_test.rb
While doing a review of the support ticket functionality, I realized that the active jobs page does not currently integrate with the support ticket functionality.
Active jobs shows more than the interactive sessions running in the cluster and it could be really helpful for the user and the operations team to get information about the specific job when submitting a ticket.
This PR adds the support to include job information as well as adding the icon in the actives jobs page.
PS: Sorry for another PR 🙏 , this one looks bigger than it is. I needed to make the changes to all backend implementations.
=> Added support ticket to active jobs page

apps/dashboard/app/helpers/system_status_helper.rb
cast to string for safety to fix #4195. This can error when the cluster.d file doesn't have `v2.metadata.title`, so casting to string here avoids that.
=> cast to string for safety

apps/dashboard/app/helpers/system_status_helper.rb
Backport #4196 to the 4.0 release.
=> cast to string for safety (#4196)

.github/workflows/tests.yml, Gemfile, Gemfile.lock, spec/e2e/e2e_helper.rb
Fixes #4186 by removing Ubuntu 20.04 from the test CI and also removing Ruby 2.7.
Don't know if the defaults are correct or not.
=> drop support for Ubuntu 20.04 and Ruby 2.7

apps/dashboard/app/controllers/projects_controller.rb, apps/dashboard/app/models/project.rb
Related to Issue https://github.com/OSC/ondemand/issues/4120
This is the second PR, to add the directory of shared project path into a user's own project lookup file.
First PR: https://github.com/OSC/ondemand/pull/4178
Later, we will show the list of shared projects in import form based upon user's group-id.
=> Saved imported directory into lookup_file for shared projects

lib/tasks/development.rb
This fixes #4078 by ensuring at least ~1000 UIDs/GIDs available for the dev container.
The dev container previously failed to start services correctly due to there not being enough UIDs and GIDs mapped for the system accounts in the container. This issue occured when the host UID or GID were < 1000.
Before:
```
"IDMappings": {
"UidMap": [
"0:1:90760",
"90760:0:1"
],
"GidMap": [
"0:1:101",
"101:0:1"
]
},
```
After:
```
"IDMappings": {
"UidMap": [
"0:1:90760",
"90760:0:1"
],
"GidMap": [
"0:1:101",
"101:0:1",
"102:102:1000"
]
},
```
=> Ensure minimum 1000 UIDs/GIDs are mapped for the dev container

apps/dashboard/app/views/layouts/_footer.html.erb
This would allow you to use a specific CSS selector to hide/manipulate the version string using CSS enabling you to hide it to end-users if desired.
=> Add an id tag to the version string.

apps/dashboard/test/system/batch_connect_test.rb, apps/dashboard/test/system/preset_apps_navbar_test.rb, apps/dashboard/test/system/preset_apps_pinned_test.rb, apps/dashboard/test/system/products_dev_test.rb, apps/dashboard/test/system/project_manager_test.rb, spec/e2e/proxy_spec.rb
Fix the CI by adding sleep calls all over the place. Not the best thing to do, but it is sort of the only thing I can do at this time to keep moving forward.
Note that all these sleeps are only needed for the github CI - running the CI locally 'just works'.
This is a backport to 4.0.
=> backport fix CI (#4225)

apps/dashboard/app/javascript/dynamic_forms.js
backport #4245 to release 4.x.
=> account for clusters with - or _ characters (#4245)

apps/dashboard/app/views/shared/_insufficient_balance.html.erb, apps/dashboard/app/views/shared/_insufficient_balance_resource.html.erb, apps/dashboard/app/views/shared/_insufficient_quota.html.erb, apps/dashboard/app/views/shared/_insufficient_quota_resource.html.erb
=> Replace headings with list items in balance warnings

apps/dashboard/app/views/shared/_insufficient_quota_progress_bar.html.erb
Resolves #4227
Sets the width to the smallest of percentage or 100.
#jam
=> Fix Quota bar display when over 100% usage

apps/dashboard/app/controllers/apps_controller.rb
Cache icons so they're not re-requesting all the time.
Fixes #4268
=> cache icons

apps/dashboard/app/javascript/alert.js, apps/dashboard/app/javascript/files/sweet_alert.js, apps/dashboard/app/javascript/path_selector/path_selector_data_table.js, apps/dashboard/app/javascript/turbo_shim.js
Rename this function so it doesn't collide with `window.alert` which it currently does.  `OODAlert` was the best name I could come up with. don't know if there's a `railsAlert` or similar, but didn't want to try it and potentially collide with _it_ now or in the future.
=> rename this function so it doesn't collide with window.alert

apps/dashboard/app/views/batch_connect/shared/_app_menu.html.erb, apps/dashboard/test/integration/batch_connect_test.rb, apps/dashboard/test/integration/sessions_controller_test.rb
Shared apps left hand menu is not rendered when a custom navigation is configured. This is a bug.
Added rendering of shared apps left hand menu in all cases.
Fixes https://github.com/OSC/ondemand/issues/4286
=> Fixed rendering shared apps left hand menu

apps/dashboard/app/controllers/projects_controller.rb, apps/dashboard/app/javascript/projects_import.js, apps/dashboard/app/views/projects/import.html.erb, apps/dashboard/config/locales/en.yml, apps/dashboard/config/locales/ja_JP.yml, apps/dashboard/config/locales/zh-CN.yml
Related to Issue https://github.com/OSC/ondemand/issues/4120
This is the fifth PR to create a separate page of shared projects identified via user's group-id
First PR: https://github.com/OSC/ondemand/pull/4178
Second PR: https://github.com/OSC/ondemand/pull/4189
Third PR: https://github.com/OSC/ondemand/pull/4208
Fouth PR: https://github.com/OSC/ondemand/pull/4258
Code is tested on local OOD instance.
This is the end for this issue-epic!
[TO KEEP TRACK] https://github.com/OSC/ondemand/pull/4269 This PR can show importable directories on separate page.
=> Added a drop down menu in import directory form

apps/dashboard/app/views/batch_connect/shared/_app_menu.html.erb, apps/dashboard/test/integration/batch_connect_test.rb, apps/dashboard/test/integration/sessions_controller_test.rb
Fixed rendering shared apps left hand menu when custom navigation is configured.
=> backport #4291 to 4.0

apps/dashboard/app/controllers/files_controller.rb, apps/dashboard/app/models/posix_file.rb, apps/dashboard/app/models/remote_file.rb, apps/dashboard/config/configuration_singleton.rb
Add file size limit for editing both remote and local files.
Fixes #4311.
=> backport Add file editor limit (#4256) to 4.0

apps/dashboard/app/views/files/_shell_dropdown.html.erb, apps/dashboard/app/views/products/_product.html.erb, apps/dashboard/app/views/products/index.html.erb, apps/dashboard/app/views/products/show.html.erb, apps/dashboard/app/views/shared/_shell_button.html.erb, apps/dashboard/config/configuration_singleton.rb
refactor shell buttons so they can be disabled. This is work for #2193, though it does not complete it. That ticket has 4 tasks, this solves 3. I've saving active jobs extended data view for another pull request.
=> refactor shell buttons so they can be disabled

apps/dashboard/app/lib/smart_attributes/attributes/bc_num_nodes.rb
Related to issue: https://github.com/OSC/ondemand/issues/4287
In the next PR, I will use this new Smart Attribute to replace `bc_num_slots` in Project Manager.
=> Added new SmartAttribute bc_num_nodes to replace bc_num_slots in PM

apps/dashboard/app/controllers/launchers_controller.rb, apps/dashboard/app/helpers/launchers_helper.rb, apps/dashboard/app/javascript/launcher_edit.js, apps/dashboard/app/lib/smart_attributes.rb, apps/dashboard/app/views/launchers/edit.html.erb, apps/dashboard/test/system/project_manager_test.rb
Related to issue: https://github.com/OSC/ondemand/issues/4287
Last added PR: https://github.com/OSC/ondemand/pull/4323
Current Issue:
`bc_num_slots` is used for cores on `pbspro` while nodes on other schedulers. 
`bc_num_nodes` is used for nodes on all the schedulers.
`auto_cores` is used for cored on all the schedulers.
Now we need to either 
1. Change `bc_num_slots` to specify cores in submit script for all the schedulers (which is not favored as it is a legacy code of OOD)
2. Not to use `bc_num_slots` in PM and instead keep `auto_cores` only to avoid confusion.
I am open for suggestions.
=> Use Smart Attribute bc_num_nodes in PM to specify number of nodes to run a job

apps/dashboard/app/controllers/launchers_controller.rb, apps/dashboard/app/helpers/launchers_helper.rb, apps/dashboard/app/javascript/launcher_edit.js, apps/dashboard/app/views/launchers/edit.html.erb, apps/dashboard/test/system/project_manager_test.rb
It is a follow-up task for PR: https://github.com/OSC/ondemand/pull/4327
Related to issue: https://github.com/OSC/ondemand/issues/4287
bc_num_slots had mixed behavior, where it acted as `nodes` for some scheduler and `cores` for `pbspro` scheduler
=> Removed support of bc_num_slots as auto_cores will take its place in PM

ood-portal-generator/lib/ood_portal_generator/dex.rb, ood-portal-generator/spec/application_spec.rb
raise an error when dex configurations are provided, but dex is not installed. This is to fail fast and alert the user of the state.
Fixes #1994
=> raise an error under certain conditions.

nginx_stage/lib/nginx_stage/configuration.rb, nginx_stage/lib/nginx_stage/views/pun_config_view.rb, nginx_stage/share/nginx_stage_example.yml, nginx_stage/templates/pun.conf.erb
As discussed in https://github.com/OSC/ondemand/issues/4347 this PR adds an option to the users PUN configuration to disable the telemetry of Passenger.
=> Add option to disable Passenger telemetry

nginx_stage/lib/nginx_stage/configuration.rb, nginx_stage/lib/nginx_stage/views/pun_config_view.rb, nginx_stage/share/nginx_stage_example.yml, nginx_stage/templates/pun.conf.erb
Add option to disable Passenger telemetry while also accounting for sites that have it already set in passenger_options.
=> backport - Add option to disable Passenger telemetry (#4355) - to 4.0

nginx_stage/lib/nginx_stage/configuration.rb, nginx_stage/lib/nginx_stage/views/pun_config_view.rb, nginx_stage/share/nginx_stage_example.yml, nginx_stage/templates/pun.conf.erb
Add option to disable Passenger telemetry while also accounting for sites that have it already set in passenger_options.
=> backport - Add option to disable Passenger telemetry (#4355) - to 3.1

apps/dashboard/app/controllers/batch_connect/session_contexts_controller.rb, apps/dashboard/app/models/batch_connect/app.rb, apps/dashboard/app/models/concerns/encrypted_cache.rb, apps/dashboard/app/models/concerns/user_setting_store.rb, apps/dashboard/test/system/batch_connect_test.rb, apps/dashboard/test/system/batch_connect_widgets_test.rb, apps/dashboard/test/test_helper.rb
Encrypt password fields when caching them while catching the error for backward compatibility.
This also replaces the integration test with a system test.
=> backport - encrypt password fields when caching them (#4326) - to 3.1

apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/config/configuration_singleton_test.rb
use warn instead of Rails.logger.error because this class boots up before Rails does, so Rails.logger isn't available yet.
=> use warn instead of Rails.logger.error

apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/config/configuration_singleton_test.rb
Use $stderr instead of Rails.logger.error because this class boots up before Rails does, so Rails.logger isn't available yet.
=> backport - use warn instead of Rails.logger.error (#4370) - to 4.0

apps/dashboard/config/configuration_singleton.rb, apps/dashboard/test/config/configuration_singleton_test.rb
Use $stderr instead of Rails.logger.error because this class boots up before Rails does, so Rails.logger isn't available yet.
=> backport - use warn instead of Rails.logger.error (#4370) - to 3.1

apps/dashboard/app/apps/app_recategorizer.rb, apps/dashboard/app/apps/dev_router.rb, apps/dashboard/app/apps/ood_app.rb, apps/dashboard/app/apps/sys_router.rb, apps/dashboard/app/apps/usr_router.rb, apps/dashboard/app/models/batch_connect/app.rb, apps/dashboard/app/models/product.rb
refactor OodApp and BatchConnect::App to simplify their relationship. Confusingly, these 2 objects referenced each other. An OodApp had a BatchConnect::App object and vice versa, making it very difficult to (a) reason about and (b) cache/serialize.
So this simplifies the relationship by simply having OodApp the parent class which BatchConnect::App inherets and can reference through super.
I'll comment through these changes on specific areas that I'm trying to fix.
=> refactor OodApp and BatchConnect::App

packaging/rpm/ondemand.spec
Hardcode to 9.5 version while 9.6 is being released downstream of RHEL
=> Hardcode selinux-policy dependency for RHEL9

packaging/rpm/ondemand.spec
Hardcode to 9.5 version while 9.6 is being released downstream of RHEL
=> Hardcode selinux-policy dependency for RHEL9 (release_3.1)

packaging/rpm/ondemand.spec
Hardcode to 9.5 version while 9.6 is being released downstream of RHEL
=> Hardcode selinux-policy dependency for RHEL9 (release_4.0)

apps/dashboard/app/controllers/module_browser_controller.rb, apps/dashboard/app/models/hpc_module.rb, apps/dashboard/app/views/module_browser/_module_list.html.erb, apps/dashboard/test/models/hpc_module_test.rb
Fixes #4350 and refactors mod browser components accordingly
=> Refactor HpcModule to return all modules across clusters

.github/workflows/lint.yml, .github/workflows/release.yml
update workflows to ruby 3.3 to fix the lint workflow that is currently broken. This also updates the release workflow that would have likely broken in 4.1.
=> update workflows to ruby 3.3

apps/dashboard/app/models/launcher.rb
Workflows Epic Link - https://github.com/OSC/ondemand/issues/4338
We can now add dependent job-id list to the submit() call of Launchers.
=> Launchers now support 'after', 'afterok' etc. job-id lists in submit()

apps/dashboard/test/system/saved_settings_test.rb
I just noticed this small thing in a test that shouldn't be there.
=> rm this puts statement in test

apps/dashboard/app/helpers/system_status_helper.rb
Our cluster title contains the acronym of our institute, and I assume there will be others
Before:
After:
=> Do not titleize the cluster title in the Cluster Status helper

apps/dashboard/app/views/batch_connect/shared/_breadcrumb.html.erb, apps/dashboard/app/views/files/_files_table.html.erb, apps/dashboard/app/views/files/index.html.erb, apps/dashboard/app/views/products/_breadcrumbs.html.erb, apps/dashboard/app/views/shared/_path_selector_table.html.erb
With this PR I am taking the liberty to propose some style changes by adding some bootstrap classes here and there. 
Before:
After:
Before:
After:
Summary:
- Rounded borders for breadcrumbs
- Consistent spacing in files
- Gap + flex wrapping button array files for mobile mode
- No double border at files
I am new to this project so please tell me if I should do things differently!
=> Some file manager style changes + rounded breadcrumbs

apps/dashboard/app/apps/ood_app.rb
Fixes #3263. Now failures in checks to setup-production file will be logged as "Per user setup failed: file 'bin/setup-production' was not found at runtime" (file did not exist) or "Per user setup failed: file 'bin/setup-production' is not executable. Ensure the user has access to this file" (file was not executable).
=> add descriptive messages to setup-production errors

.github/workflows/tests.yml
remove patch ruby versions and apply permissions.
I'm removing the patch ruby versions because we're having issues updating nokogiri with Ruby 3.1. It requires some patch to psych that Debian 12 actually has but ruby 3.1.2 from this action does not.
=> rm patch ruby versions and apply permissions

apps/dashboard/app/lib/smart_attributes/attribute.rb, apps/dashboard/app/models/batch_connect/session_context.rb, apps/dashboard/app/models/concerns/bool_reader.rb, apps/dashboard/app/models/configuration_property.rb, apps/dashboard/config/configuration_singleton.rb
Fixes #4521 by adding the BoolReader module and using this whenever we need to cast a user-supplied string (such as those in config files) into a boolean. Passes all tests
=> Fix false values 4521

apps/dashboard/app/views/batch_connect/sessions/connections/_novnc.html.erb
As was [figured out here](https://discourse.openondemand.org/t/novnc-error-incomplete-zlib-block-for-interactive-desktop-sessions/2895), any use of the clipboard generates the error message _incomplete zlib block_ when the compression level is 0.
I would guess it is a bug in the noVNC library whereby it is still trying to decompress something that isn't compressed. This avoids the issue from happening by making it not possible to specify a level of less than 1.
=> Disable compression level 0 as it breaks the clipboard

apps/dashboard/public/noVNC-1.3.0/app/ui.js
Do not sync back the clipboard text if it only differs in newline representation (nl vs. crnl).
Fixes: #3839
=> dashboard: noVNC: Handle newline representation mismatch

apps/dashboard/app/assets/stylesheets/_variables.scss, apps/dashboard/app/views/layouts/nav/_all_apps.html.erb, apps/dashboard/app/views/layouts/nav/_develop_dropdown.html.erb, apps/dashboard/app/views/layouts/nav/_help_dropdown.html.erb, apps/dashboard/app/views/layouts/nav/_log_out.html.erb, apps/dashboard/app/views/layouts/nav/_sessions.html.erb, apps/dashboard/app/views/layouts/nav/_user.html.erb
Fixes #3390 
Removes custom $grid-breakpoints definitions to allow them to use default values instead.
=> Remove custom $grid-breakpoints definitions

apps/dashboard/app/helpers/active_jobs_helper.rb, apps/dashboard/app/models/active_jobs/jobstatusdata.rb, apps/dashboard/app/views/active_jobs/_job_details_node_view.html.erb
Fixes #3622. Adds two new parameters to cluster's custom attribute, `gpu-util` and `gpu-memory`, and conditionally adds the grafana tiles for interactive jobs or jobs that require gpus. (Interactive jobs seem to have 0 gpus but grafana still records gpu stats). Because cluster configurations are difficult to access for testing, I used the following snippet in active_jobs_helper.rb to simulate supplied values (starting from committed changes)
```rb
if ['cpu','memory','gpu-util','gpu-memory'].include?(report_type)
gpuvals = {'gpu-util' => 16, 'gpu-memory' => 18}
url_base = 'd-solo'
query_params[:panelId] = server[:dashboard]['panels'].merge(gpuvals)[report_type]
else
url_base = 'd'
end
```
Interactive jobs are detected by title, which is not ideal and may not catch all of them. However the …
=> add gpu panel to job stats

apps/dashboard/app/javascript/editor.js, apps/dashboard/app/views/files/edit.html.erb, apps/dashboard/config/locales/en.yml
Do not use soft tabs (spaces) in the file editor. Instead use actual tabs (`\t` characters).
=> use real tabs in file editor
