OSC/ondemand

.gitlab-ci.yml

@MorganRodgers @ericfranz @johrstrom Hopefully this helps determine failures by not suppressing execution output.

Show verbose output from CI/CD jobs

---

ood-portal-generator/templates/ood-portal.conf.erb

This is just a simple PR to update this one misspelling that confused this user in this discourse topic.
https://discourse.osc.edu/t/ood-update-from-1-5-to-1-6-experience/425

ood_portal.yml mispelled

---

ood-portal-generator/sbin/update_ood_portal

Add --detailed-exitcodes flag to update_ood_portal

---

ood-portal-generator/sbin/update_ood_portal

#65 initialize ood-portal if it doesnt exist

---

nginx_stage/share/nginx_stage_example.yml

Fix minor typos in example blocks

fix syntax errors in nginx_stage_example.yml

---

ood-portal-generator/lib/ood_portal_generator/view.rb
ood-portal-generator/share/ood_portal_example.yml
ood-portal-generator/templates/ood-portal.conf.erb

I am no ruby expert but something like this should resolve https://github.com/OSC/ondemand/issues/73

allow a proxy_server

---

packaging/ondemand.spec

Support keeping env vars for OOD for sudo

---

apps/activejobs/app/assets/stylesheets/application.scss
apps/activejobs/app/views/layouts/application.html.erb
apps/activejobs/app/views/layouts/nav/_styles.html.erb
apps/activejobs/config/configuration_singleton.rb
apps/myjobs/app/assets/stylesheets/application.css.scss
apps/myjobs/app/views/layouts/application.html.erb
apps/myjobs/app/views/layouts/nav/_styles.html.erb
apps/myjobs/config/configuration_singleton.rb

This implements the same branding configuration as the Dashboard app
for a more consistent user experience.

[feat] Allow for branding (Active|My)Jobs

---

packaging/ondemand-selinux.te
packaging/ondemand.spec

Fixes #110
I will do separate pull request for #112 because that change is going to be very involved and probably rewrite of SELinux policies.

SELinux improvements to work with local home dirs

---

.travis.yml
Rakefile
apps/dashboard/test/models/app_router_test.rb
apps/file-editor/app/controllers/pages_controller.rb
apps/file-editor/test/test_helper.rb
apps/myjobs/test/controllers/workflows_controller_test.rb

Adds to the Rakefile unit tests for all our Ruby apps, and fixes whatever test cases didn't pass.

Add app tests

---

packaging/ondemand-selinux.te

This will fix currently broken RPM builds.

Fix selinux policy

---

Rakefile
apps/myjobs/Gemfile.lock

Include development and test gems in production

---

packaging/ondemand.spec

@ericfranz another fix for failed builds.

Fix for missing rundir

---

CHANGELOG.md
apps/dashboard/public/noVNC-1.0.0/app.v3.js
apps/dashboard/public/noVNC-1.0.0/vnc.html

The holidays are upon us, let's remove this bugged feature until we can be sure our attempts to fix it don't cause other problems.

Undo bugged copy-paste hack

---

.github/workflows/issue-lifecycle.yml

This GitHub Action will automatically assign an issue to the backlog if it is created without a milestone.
See example:

Add GitHub Action for Issue Lifecycle

---

apps/myjobs/app/assets/javascripts/joyride.js
apps/myjobs/app/views/workflows/index.html.erb

Fix JoyRide tool tip position.

---

.github/workflows/issue-lifecycle.yml

This PR updates the default milestone assigned to an issue to Needs Triaged.

Update default issue milestone to Needs Triaged

---

apps/dashboard/app/apps/favorite_path.rb
apps/dashboard/app/apps/ood_files_app.rb
apps/dashboard/app/views/layouts/nav/_group.html.erb
apps/dashboard/test/controllers/dashboard_controller_test.rb

minor improvements to testing and style

Favorite path feature refactor and minor improvement

---

CHANGELOG.md
apps/dashboard/app/views/layouts/_footer.html.erb
apps/myjobs/app/views/workflows/index.html.erb

Fix cosmetic defects

---

Dockerfile
Rakefile

This is a continuation on work from #86 but with Rake tasks. I've been using this approach to test both infrastructure and app changes.

Add ability to do development inside Docker

---

ood-portal-generator/Gemfile
ood-portal-generator/Gemfile.lock
ood-portal-generator/lib/ood_portal_generator.rb
ood-portal-generator/lib/ood_portal_generator/application.rb
ood-portal-generator/lib/ood_portal_generator/dex.rb
ood-portal-generator/lib/ood_portal_generator/view.rb
ood-portal-generator/spec/application_spec.rb
ood-portal-generator/spec/dex_spec.rb
ood-portal-generator/spec/fixtures/dex.yaml.default
ood-portal-generator/spec/fixtures/dex.yaml.full
ood-portal-generator/spec/fixtures/dex.yaml.ldap
ood-portal-generator/spec/fixtures/ood-portal.conf.default
ood-portal-generator/spec/fixtures/ood-portal.conf.dex
ood-portal-generator/spec/fixtures/ood-portal.conf.dex-full
ood-portal-generator/spec/fixtures/ood-portal.conf.dex-ldap
ood-portal-generator/spec/fixtures/ood-portal.conf.maint_with_ips
ood-portal-generator/spec/fixtures/sum.default
ood-portal-generator/spec/fixtures/sum.dex
ood-portal-generator/spec/update_ood_portal_spec.rb
ood-portal-generator/templates/ood-portal.conf.erb

Fixes #393
I still need to update example config files and other places that document options.
I also need to adjust how URLs are handled so that things like docker and vagrant still work without drastic changes.

Switch from default of BasicAuth to using Dex

---

apps/dashboard/public/noVNC-1.1.0/app/ui.js
apps/dashboard/public/noVNC-1.1.0/core/rfb.js
apps/dashboard/public/noVNC-1.1.0/legacy/app.js
apps/dashboard/public/noVNC-1.1.0/vnc.html

This fixes the chrome copy and paste issue for chrome.

Copy and Paste Fix for #455 (chrome)

---

.github/workflows/document-merge.yml

fix documente merge workflow to use " instead of '

---

apps/dashboard/Gemfile
apps/dashboard/Gemfile.lock
apps/dashboard/app/controllers/batch_connect/sessions_controller.rb
apps/dashboard/app/helpers/batch_connect/sessions_helper.rb
apps/dashboard/app/models/batch_connect/session.rb
apps/dashboard/app/views/batch_connect/sessions/_panel.html.erb
apps/dashboard/app/views/batch_connect/sessions/connections/_completed.html.erb
apps/dashboard/config/locales/en.yml
apps/dashboard/test/models/batch_connect/session_test.rb
apps/dashboard/test/test_helper.rb

Fixes https://github.com/OSC/ondemand/issues/232

Preserve Batch Connect panel after job completes

---

CHANGELOG.md

update changelog for 1.8.2

---

apps/dashboard/app/assets/javascripts/application.js
apps/dashboard/app/views/dashboard/_xdmod_widget_job_efficiency.html.erb
apps/dashboard/app/views/dashboard/_xdmod_widget_jobs.html.erb
apps/dashboard/config/configuration_singleton.rb

- Job Efficiency Widget to display "No data available" if request is successful but there is no data available
- Make auto-login timeout configurable for IDPs that are slow

XDMoD widget edge cases

---

ood-portal-generator/lib/ood_portal_generator.rb
ood-portal-generator/lib/ood_portal_generator/application.rb
ood-portal-generator/lib/ood_portal_generator/dex.rb
ood-portal-generator/share/ood_portal_example.yml
ood-portal-generator/spec/application_spec.rb
ood-portal-generator/spec/fixtures/dex.yaml.default
ood-portal-generator/spec/fixtures/dex.yaml.full
ood-portal-generator/spec/fixtures/dex.yaml.full-redirect-uris
ood-portal-generator/spec/fixtures/dex.yaml.ldap
ood-portal-generator/spec/fixtures/dex.yaml.secret
ood-portal-generator/spec/fixtures/ood-portal.conf.dex
ood-portal-generator/spec/fixtures/ood-portal.conf.dex-full
ood-portal-generator/spec/fixtures/ood-portal.conf.dex-ldap
ood-portal-generator/spec/fixtures/sum.dex
ood-portal-generator/spec/ood_portal_generator_spec.rb
ood-portal-generator/spec/update_ood_portal_spec.rb

Allow Dex secret to be a file, more restrictive permissions on ood-portal.conf

---

apps/activejobs/app/models/jobs_json_request_handler.rb
apps/activejobs/app/models/jobstatusdata.rb

An issue should be opened on ood_core for native attributes for SGE

Added extended view ability to SGE

---

apps/dashboard/app/helpers/batch_connect/sessions_helper.rb

- Change starting => primary
- Change queued => info
- Leave completed => default

diff colors f queued & completed app sessions

---

apps/activejobs/app/assets/javascripts/application.js

* Improve HTML render functions by using JavaScript template literals.
* Set Active Jobs rows tabindex to 0
Improved all functions that concatenated strings like this:
```js
return "<div>" +
"<a class='btn btn-danger btn-xs action-btn' data-method='delete'" +
" data-confirm='Are you sure you want to delete " + data.jobname  + " - " + data.pbsid + "'" +
" href='" + data.delete_path + "'" +
" aria-labeledby='title' data-toggle='tooltip' title='Delete Job' >" + 
"<i class='glyphicon glyphicon-trash' aria-hidden='true'></i>" +  
"</a>" +
"</div>";
}
```
To use template literals:
```js
return `
<div>
<a
class="btn btn-danger btn-xs action-btn"
data-method="delete"
data-confirm="Are you sure you want to delete ${data.jobname} - ${data.pbsid}"
href="${data.delete_path}"
aria-labeled-by"title" …
```

 Improve Active Jobs JavaScript

---

apps/dashboard/app/views/dashboard/_xdmod_widget_job_efficiency.html.erb
apps/dashboard/app/views/dashboard/_xdmod_widget_jobs.html.erb
apps/myjobs/config/locales/en.yml

fixes #685 by changing the places XDMoD is shown to the user to Open XDMoD

change XDMoD to Open XDMoD where User Viewable

---

apps/dashboard/app/assets/javascripts/application.js
apps/dashboard/app/views/dashboard/_xdmod_widget_job_efficiency.html.erb
apps/dashboard/app/views/dashboard/_xdmod_widget_jobs.html.erb

use xdmod current user data for person_id in fetch

---

CHANGELOG.md

update changelog for v1.14.8

---

apps/activejobs/app/views/layouts/application.html.erb
apps/dashboard/app/views/batch_connect/session_contexts/new.html.erb
apps/dashboard/app/views/batch_connect/sessions/index.html.erb
apps/dashboard/app/views/layouts/application.html.erb
apps/file-editor/app/views/layouts/application.html.erb
apps/myjobs/app/views/layouts/application.html.erb
apps/shell/app.js
apps/shell/views/index.hbs

update html titles of apps to be a little more specific to reduce ambiguity

---

ood-portal-generator/lib/ood_portal_generator/view.rb
ood-portal-generator/share/ood_portal_example.yml
ood-portal-generator/spec/fixtures/ood-portal.conf.default
ood-portal-generator/spec/fixtures/ood-portal.conf.dex
ood-portal-generator/spec/fixtures/ood-portal.conf.dex-full
ood-portal-generator/spec/fixtures/ood-portal.conf.dex-ldap
ood-portal-generator/spec/fixtures/ood-portal.conf.maint_with_ips
ood-portal-generator/spec/fixtures/ood-portal.conf.nomaint
ood-portal-generator/spec/fixtures/ood-portal.conf.oidc
ood-portal-generator/spec/fixtures/ood-portal.conf.oidc-ssl
ood-portal-generator/spec/fixtures/sum.default
ood-portal-generator/spec/update_ood_portal_spec.rb
ood-portal-generator/templates/ood-portal.conf.erb

Replace security_disable_frames with security_csp_frame_ancestors

---

apps/activejobs/app/assets/javascripts/application.js

This PR adds a function for escaping HTML output: `escapeHtml(string: string)`

Add sanitize HTML function and sanitize on DataTable render

---

.github/workflows/tests.yml

Add names to CI GitHub Actions and add job step names.
|Old|New|
|-|-|
|unit-tests|Unit tests|
|e2e-tests|End-to-end tests|

Add name to GH actions

---

CHANGELOG.md

update changelog for v1.8.19

---

.github/workflows/document-merge.yml

only create doc tickets when the 'needs doc' label exists on a PR

---

.github/workflows/tests.yml

Improvements to CI pipeline:
- Unit and E2E tests now run parallel
- Add commit SHA to step name
- Add Ruby and Bundler version to step name
- Explicitly define PATCH (semver) in version number
- Switch to `ruby/setup-ruby@v1`

Improvements to CI pipeline

---

.github/workflows/tests.yml
Dockerfile
Gemfile.lock
apps/activejobs/Gemfile.lock
apps/dashboard/Gemfile.lock
apps/file-editor/Gemfile.lock
apps/myjobs/Gemfile.lock
nginx_stage/nginx_stage.gemspec
ood-portal-generator/Gemfile.lock
ood_auth_map/ood_auth_map.gemspec

These are versions OnDemand 2.0 will be using.

Test against newer Ruby and Bundler

---

apps/dashboard/Gemfile.lock
apps/dashboard/app/apps/ood_app.rb
apps/dashboard/app/controllers/apps_controller.rb
apps/dashboard/app/helpers/application_helper.rb
apps/dashboard/app/models/batch_connect/app.rb
apps/dashboard/app/views/products/_form_icon.html.erb
apps/dashboard/test/models/ood_app_test.rb

The image is breaking for SVG for some reason, as seen below.
Not sure why this is happening... I'm currently working on figuring this out and figured maybe you have any input or advice.

Add Support for SVG icons 

---

README.md

just one quick update to the readme for all this joss stuff before I forget.

add joss badge to the readme

---

nginx_stage/lib/nginx_stage.rb

Might be worth back porting into 1.8.

Ensure LOGNAME is set to PUN user

---

.github/workflows/udpate.yml
.github/workflows/update.yml

add a weekly GH action to update our dependencies and create a PR if any of them in fact update.
This is just get a head of some of the dependabot updates.

add a weekly GH action to update our dependencies

---

nginx_stage/lib/nginx_stage.rb

(1.8 release) Ensure LOGNAME is set to PUN user

---

README.md

Fixed the link to the discourse icon.

Fixed Discourse Icon

---

apps/shell/package.json

Changed version of node-notifier to be at least 8.0.1.

Changed to version of node-notifier to be atleast 8.0.1

---

apps/dashboard/app/apps/ood_app_group.rb
apps/dashboard/app/controllers/application_controller.rb
apps/dashboard/app/views/layouts/application.html.erb
apps/dashboard/app/views/layouts/nav/_featured_apps.erb
apps/dashboard/config/configuration_singleton.rb
apps/dashboard/test/controllers/dashboard_controller_test.rb

Rebased https://github.com/OSC/ondemand/pull/889

Update pinned apps menu rebased

---

apps/dashboard/app/views/layouts/nav/_featured_apps.erb

remove unnessecary hidden classes from all apps link

---

apps/dashboard/app/apps/token_matcher.rb
apps/dashboard/app/controllers/apps_controller.rb
apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/manifest.yml
apps/dashboard/test/fixtures/sys_with_gateway_apps/pseudofun/manifest.yml
apps/dashboard/test/integration/apps_test.rb
apps/dashboard/test/models/router_test.rb

fix #937 .  I wonder if we should also add `File::FNM_CASEFOLD` to be case insensitive.

Glob metadata

---

apps/dashboard/app/assets/stylesheets/_custom.scss.erb
apps/dashboard/app/assets/stylesheets/_variables.scss.erb
apps/dashboard/app/assets/stylesheets/application.scss
apps/dashboard/app/helpers/batch_connect/session_contexts_helper.rb
apps/dashboard/app/helpers/batch_connect/sessions_helper.rb
apps/dashboard/app/views/batch_connect/sessions/connections/_novnc.html.erb
apps/dashboard/app/views/shared/_insufficient_quota_progress_bar.html.erb

Bootstrap 4 – My Interactive Sessions (Running) panel

---

apps/dashboard/test/controllers/dashboard_controller_test.rb
apps/dashboard/test/html_helper.rb

This should fix the tests for bootstrap.

fix tests for bootstrap upgrade

---

apps/dashboard/app/assets/stylesheets/application.scss
apps/dashboard/app/views/layouts/application.html.erb

This adds logo configuration back in.

add configurable logo back into the navbar

---

apps/dashboard/app/views/apps/featured.html.erb

this will show shared apps in the featured dashboard.

reset featured.html.erb back to master version

---

apps/dashboard/app/helpers/batch_connect/sessions_helper.rb

My Interactive Sessions panel color based on job state:
**Running**
**Queued**
**Completed and Default**
**Held and Suspended**

Fix session panel colors

---

apps/dashboard/app/assets/stylesheets/_custom.scss.erb
apps/dashboard/app/views/products/_new_choose_method.html.erb
apps/dashboard/app/views/products/edit.html.erb
apps/dashboard/app/views/products/index.html.erb
apps/dashboard/app/views/products/new.html.erb
apps/dashboard/app/views/products/new_from_git_remote.html.erb
apps/dashboard/app/views/products/show.html.erb

- Add CSS shim for btn-default (https://github.com/OSC/ondemand/pull/973/commits/15739a8ca9ab0ec65d3a014d55e3a7cfb0fe311b)
- Breadcrumbs (https://github.com/OSC/ondemand/commit/4cf4cb7e8897241bbdcb5784f0d385ef2ebf0cd1)
- Button positioning (https://github.com/OSC/ondemand/pull/973/commits/3c4fab1053c5a784d64de7896077ab043a568306)
Closes #964
Closes #965
Closes #966
Overview
App Details
Edit App

Bootstrap 4 – Develop view

---

apps/dashboard/app/assets/stylesheets/_variables.scss.erb

Revert Bootstrap 4 font size to 16px

---

apps/dashboard/app/assets/javascripts/products.coffee
apps/dashboard/app/views/products/_form_git.html.erb

SSH key not found
SSH keydetected

Bootstrap 4 - Dev panel buttons pull-right to float-right 

---

apps/dashboard/app/views/layouts/nav/_featured_apps.html.erb

fix apps dropdown menu that is missing bootstrap 4 classes

---

apps/dashboard/app/assets/stylesheets/_variables.scss.erb
apps/dashboard/app/assets/stylesheets/apps.scss
apps/dashboard/app/views/layouts/nav/_link.html.erb
apps/dashboard/app/views/layouts/nav/_styles.html.erb

**Config used in demo:**
```env
OOD_BRAND_BG_COLOR='#0000ff'
OOD_BRAND_LINK_ACTIVE_BG_COLOR='#ff0000'
```
With branding environment set:
<video src="https://user-images.githubusercontent.com/6081892/111368465-4eb4e500-866c-11eb-99e2-f64d85ee6e1f.mov">
**Default:**

Dynamic branding colors (_styles.html.erb)

---

apps/dashboard/app/apps/featured_app.rb
apps/dashboard/app/apps/ood_app_group.rb
apps/dashboard/app/controllers/application_controller.rb
apps/dashboard/app/views/dashboard/_pinned_apps.html.erb
apps/dashboard/app/views/layouts/nav/_featured_apps.html.erb
apps/dashboard/config/locales/en.yml
apps/dashboard/test/integration/pinned_apps_test.rb
apps/dashboard/test/models/ood_app_group_test.rb

Replaces https://github.com/OSC/ondemand/pull/955

Internationalize "Pinned Apps" after refactor (no merge conflict)

---

ood-portal-generator/spec/fixtures/ood-portal.conf.all
ood-portal-generator/spec/fixtures/ood-portal.conf.default
ood-portal-generator/spec/fixtures/ood-portal.conf.dex
ood-portal-generator/spec/fixtures/ood-portal.conf.dex-full
ood-portal-generator/spec/fixtures/ood-portal.conf.dex-ldap
ood-portal-generator/spec/fixtures/ood-portal.conf.maint_with_ips
ood-portal-generator/spec/fixtures/ood-portal.conf.nomaint
ood-portal-generator/spec/fixtures/ood-portal.conf.oidc
ood-portal-generator/spec/fixtures/ood-portal.conf.oidc-ssl

update ood portal tests after #1010 changed the doc link

---

apps/dashboard/app/assets/stylesheets/files.scss
apps/dashboard/app/javascript/packs/files.js
apps/dashboard/app/views/files/index.html.erb
apps/dashboard/app/views/layouts/application.html.erb
apps/dashboard/package.json
apps/dashboard/yarn.lock

This PR creates an application pack for the Files app.
**Todo:**

Files application Webpacker pack

---

CHANGELOG.md

update changelog to prepare for v1.8.20

update changelog to prepare for v1.8.20

---

Dockerfile
nginx_stage/templates/pun.conf.erb
spec/e2e/browser_spec.rb

Fixes #1035 by adding redirects for the files and file-editor apps.

add redirects in the PUN config for the files and file-editor apps

---

apps/dashboard/yarn.lock

update dashboard's node dependencies

update dashboard's node dependencies

---

CHANGELOG.md

v2.0.2 changelog

---

apps/dashboard/app/models/transfer.rb

this was accidentally not committed; could use tests (along with the others) but maybe a separate issue for that

enforce allowlist policy on transfers

---

apps/dashboard/app/views/active_jobs/_job_details_node_view.html.erb

add margin between node graphs in activejobs

---

.github/workflows/document-merge.yml

Fix #1036 and start creating document tickets that have much better titles.

use the title of the PR to create the document ticket

---

.github/workflows/document-merge.yml

Fix #1036 for real.  I went off the documentation instead of actually trying in my test action repos. This does in fact work now.

fix document merge GH action

---

lib/tasks/docker.rb
lib/tasks/packaging.rb
lib/tasks/test.rb
spec/e2e/browser_spec.rb
spec/e2e/e2e_helper.rb
spec/e2e/pun_pre_hook_spec.rb
spec/fixtures/config/ood_portal/portal_with_prehook.yml
spec/fixtures/hooks/bad_pre_hook
spec/fixtures/hooks/good_pre_hook

this adds some e2e tests for the pun pre hook feature, but also refactors some things slightly to accomidate that like making starting and stopping the test container a bit easier and allowing for different mount points.

add tests for pun pre hook

---

Dockerfile
Dockerfile.dev
mod_ood_proxy/lib/ood/nginx_stage.lua
nginx_stage/lib/nginx_stage/generators/pun_config_generator.rb
nginx_stage/spec/generators/pun_config_generator_spec.rb
packaging/ondemand.spec
spec/fixtures/hooks/good_pre_hook

Fixes #1078
Setting to draft because I'd like to get #1090 in first. 
I'd also like to get in some sort of failsafe in. Whatever we fork+exec should have some sort of guardrail in place so that after so much time if it hasn't executed, we force kill it. So clearly a test case to handle this would be good.

use lua-posix to fork and set the environment in the pun_pre_hook

---

apps/dashboard/app/controllers/files_controller.rb

apply a users umask to the uploaded file

---

apps/dashboard/app/controllers/files_controller.rb

this was accidentally removed in the previous commit for adding zip downloading

fix mimetype handling in files app

---

CHANGELOG.md

update changelog for v2.0.6

---

apps/dashboard/app/models/files.rb

Fixes https://github.com/OSC/ondemand/issues/1119

properly handle caching of usernames from uids

---

CHANGELOG.md

update changelog for v2.0.7

---

CHANGELOG.md

update changelog for v2.0.8

---

ood-portal-generator/lib/ood_portal_generator/dex.rb
ood-portal-generator/spec/fixtures/dex.custom.yaml
ood-portal-generator/spec/fixtures/ood_portal.dex.yaml

Support changing Dex storage

---

ood-portal-generator/lib/ood_portal_generator/dex.rb
ood-portal-generator/spec/fixtures/dex.custom.yaml
ood-portal-generator/spec/fixtures/ood_portal.dex.yaml

Fixes #1140
This is for 1.8 release so can maybe get to community faster

(Release 1.8) Support changing Dex storage

---

spec/e2e/proxy_spec.rb
spec/fixtures/extras/simple_origin_server.py

Went to fix #521 and found the tests work directly! In fact, I went to RStudio where this bug is, and saw that it was indeed fixed.
In any case, here are test cases for it.

add tests for relative redirects

---

.github/workflows/tests.yml
apps/dashboard/app/javascript/packs/application.js

Added system dashboard tests to github action

---

apps/dashboard/app/models/batch_connect/app.rb
apps/dashboard/app/models/batch_connect/session.rb
apps/dashboard/test/fixtures/sys_with_interactive_apps/bc_jupyter/submit.yml.erb
apps/dashboard/test/models/batch_connect/app_test.rb
apps/dashboard/test/models/batch_connect/session_test.rb

Yet another fix for #864 (others being #948 and #915). This fixes #864, but only that issue. It does not attempt to fix #605.

enable staged_root to be present in submit.yml.erb fixing #864

---

CHANGELOG.md

update changelog for v2.0.9

---

apps/dashboard/config/configuration_singleton.rb

Changing variable name for better readability for issue #1052

---

.github/workflows/document-merge.yml

Fixes #1149
We have a couple PRs that will need automation, so may as well create some tickets for them before we forget.

create automation tickets based on labels

---

apps/dashboard/app/views/layouts/nav/_develop_dropdown.html.erb
apps/dashboard/app/views/layouts/nav/_help_dropdown.html.erb

Adjusting Help and Developer menus to drop from right.

---

CHANGELOG.md

update changelog for v2.0.10

---

apps/dashboard/app/helpers/batch_connect/sessions_helper.rb
apps/dashboard/app/models/batch_connect/session.rb
apps/dashboard/test/models/batch_connect/session_test.rb

Allow cluster to override OOD_BC_SSH_TO_COMPUTE_NODE

---

CHANGELOG.md

update changelog for version 2.0.11

update changelog for version 2.0.11

---

packaging/ondemand.spec

Ensure /etc/ood/api is packaged with secure permissions

---

.github/workflows/document-merge.yml

Fixes #1266
Found how to do this here: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags

Also handle merges to feature branches for Github Action

---

apps/dashboard/app/models/files.rb

Fix files preview. Set charset=utf-8 in Content-Type header

---

CHANGELOG.md

update changelog for v2.0.12

---

CHANGELOG.md

update changelog for v2.0.13

---

CHANGELOG.md

fix 2.0.13's release date because it's wrong, by 100 years lol.

fix 2.0.13's release date

---

lib/tasks/packaging.rb

Adding descriptions for some package:* rake tasks.

---

apps/dashboard/app/apps/usr_router.rb

I stumbled upon this recently and thought it's time to remove these comments, whatever they may have been.

remove commented code in usr router

---

CHANGELOG.md
packaging/ondemand.spec

Built the RPMs locally on my laptop with this change and RPMs built successfully.

Fix RPM builds to work with top-level Gemfile changes

---

Rakefile

Update workflow is still broken because it has to unbundle too.

update has to unbundle too

---

apps/dashboard/app/views/files/index.html.erb

alternate PR to #1346 bugfix #1322

bugfix 1312

---

apps/dashboard/app/views/active_jobs/_ganglia_graphs_table.html.erb
apps/dashboard/app/views/active_jobs/_job_details_node_view.html.erb

alternate to #1345 bugfix for #1031

bugfix alternate branch

---

Rakefile
debian/rules
lib/tasks/build.rb
lib/tasks/build_utils.rb
lib/tasks/install.rb

This builds and installs the passenger.so and nginx, though it does not configure them.

Deb build deps

---

Dockerfile

add rsync to container

---

apps/dashboard/app/javascript/packs/batchConnect.js
apps/dashboard/app/views/batch_connect/session_contexts/_form.html.erb
apps/dashboard/config/configuration_singleton.rb
apps/dashboard/config/webpack/environment.js
apps/dashboard/test/application_system_test_case.rb
apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml
apps/dashboard/test/system/batch_connect_test.rb
apps/dashboard/test/test_helper.rb

First attempt at #851. Currently in draft because it's not very solid (some hard coded stuff), but I wanted to give folks a heads up.
Right now this only responds to options for cluster (that's the hard coded bit), but the idea is it could respond to anything.
This needs:

batch connect auto add change handlers

---

apps/dashboard/app/javascript/packs/batchConnect.js

clean up batchConnect.js a little to use `let` over `var`, 'use strict' and get rid of console logs (we should get better with the dev tools debugger and breakpoints instead of logging all over the place).

clean up batchConnect.js a little

---

apps/dashboard/app/javascript/packs/batchConnect.js

Fixes #1391. 
optimize the batch connect js a little so that we only apply a change handler once. Previosly we'd applied a change handler for every option meaning when a change happened, the handler was called many times.
I put a lot of work this morning into other optimization strategies like cacheing all the `.data()` attributes in a lookup table, but we still need to query for the element to `.hide()` or `.show()` it anyway, so caching these where a bit pointless and worse added a lot of complexity trying to map camelcase to snake case.

optimize the batch connect js a little

---

lib/tasks/build_utils.rb
lib/tasks/files/mime.types
lib/tasks/install.rb
lib/tasks/templates/locations.ini.erb

This adds a couple files to the `.deb` package. Though if the locations.ini is correct, I don't know, but this is at least the infrastructure to template and install it.

Debian files

---

apps/dashboard/app/models/allowlist_policy.rb
apps/dashboard/test/models/allowlist_policy_test.rb

Adding tests for AllowlistPolicy class.

---

apps/shell/README.md
apps/shell/public/javascripts/hterm_all_1.91.mod.js
apps/shell/views/index.hbs

fixes the problem described in #1369 (however, that issue is not due to the keyboard inputs; just the display output itself. The numerous keycode-issues are still present with no easy fix)
Both old patches re-applied. I can confirm that the fix for https://github.com/OSC/ood-shell/issues/64 is still needed.
I can't verify the necessity of the other keycode fix as I'm unable to reproduce the issue.
Tested on linux with Firefox, Chromium, and Google Chrome.
Taken from https://chromium.googlesource.com/apps/libapps/hterm.org/ (since the sources have been moved around a bit)

Update hterm to 1.91 (shells)

---

apps/dashboard/app/controllers/files_controller.rb

force SVGs to be downloaded

---

.gitlab-ci.yml
lib/tasks/build_utils.rb
lib/tasks/packaging.rb

Support tagged builds for deb packages
Fixes #1527

Add nightly Ubuntu 20.04 builds

---

DEVELOPMENT.md
lib/tasks/development.rb

Sadly, in my haste to pull in #1494  - I made the crucial mistake of deleting the current docs!

reset developer docs bc it got wiped

---

apps/dashboard/yarn.lock

fix yarn lock because I had to rebase in #1550 and must have messed up the lockfile.

fix yarn lock

---

apps/dashboard/app/assets/javascripts/apps.js.coffee
apps/dashboard/app/javascript/packs/apps.js
apps/dashboard/app/views/apps/index.html.erb

move apps.js to webpack. fixes #1517

move apps.js to webpack

---

ood-portal-generator/Gemfile
ood-portal-generator/Gemfile.lock
ood-portal-generator/RAILS-LICENSE
ood-portal-generator/lib/ood_portal_generator/dex.rb
ood-portal-generator/lib/ood_portal_generator/hash_extensions.rb

Remove active support dependency for ood-portal-generator

---

.github/workflows/changelog.yml
.github/workflows/update.yml

fixes #1575

---

lib/tasks/development.rb

Fixes #1463 by adding ability to mount infra apps in dev container

add ability to mount infra apps in dev container

---

.rubocop.yml
CONTRIBUTING.md
apps/dashboard/.eslintrc.yml

doc updates surrounding style guides, with some updates to style guides.
This adds and eslint which fixes <link needed> and updates our method limits.

doc updates surrounding styleguides, with some updates to styleguides

---

Dockerfile

update dockerfile with all the recent developments

update dockerfile with all the recent developments

---

apps/dashboard/app/helpers/batch_connect/session_contexts_helper.rb

1a1e7131a7b59c58f068130f970fdea3f30cc308 was accidentally commited directly to master. This resets that change.
Also - I believe I've _now_ set the right permissions so even admins can't push to master.

reset accidental commit to mainline

---

.github/workflows/tests.yml
spec/e2e/e2e_helper.rb

Use versioned build repo for E2E tests

---

mod_ood_proxy/lib/logger.lua

Fix mod_ood_proxy Lua errors with Lua 5.3

---

mod_ood_proxy/lib/logger.lua

Fix mod_ood_proxy Lua errors with Lua 5.3 (Release 2.0)

---

apps/dashboard/app/views/files/index.html.erb

Fixes #1378 for 2.0
This is a backport of #1600, so mainline already has this fix.

backport #1600 to 2.0

---

CHANGELOG.md

Release notes for release 2.0.20 are ready for review.

Updated Release Notes for Release 2.0.20 - 12/01/2021

---

CONTRIBUTING.md

add html styleguide

---

.github/workflows/update.yml

update dependencies workflow use the right commit message.

update deps use the right commit message

---

packaging/deb/control
spec/e2e/e2e_helper.rb

Depend on NodeJS 14 for deb packages

---

apps/dashboard/app/javascript/packs/batchConnect.js
apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml
apps/dashboard/test/system/batch_connect_test.rb

add the ability to hide multiple items on a change

---

apps/dashboard/app/views/active_jobs/_extended_panel.html.erb

activejobs to use the right icon api

---

apps/dashboard/app/models/batch_connect/app.rb
apps/dashboard/test/fixtures/sys_with_interactive_apps/bc_paraview/submit.yml.erb
apps/dashboard/test/models/batch_connect/app_test.rb

write the submit yml when there are yml errors

---

CHANGELOG.md
apps/dashboard/app/javascript/packs/batchConnect.js
apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml
apps/dashboard/test/system/batch_connect_test.rb

Backport #1676 to the 2.0 release

backport 1676 to 2.0 release

---

.gitlab-ci.yml

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201546099455280/1201609824584650) by [Unito](https://www.unito.io)

Fix nightly builds

---

apps/dashboard/app/javascript/packs/active_jobs.js
apps/dashboard/app/views/active_jobs/index.html.erb

Fixes #1747
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201546099455280/1201611984165289) by [Unito](https://www.unito.io)

migrate activejobs javascript to webpack

---

apps/dashboard/app/models/files.rb

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201625178070145/1201628271829112) by [Unito](https://www.unito.io)

Added functionality to view yaml files inline with browser

---

apps/dashboard/test/system/products_dev_test.rb
apps/dashboard/test/system/products_test.rb
apps/dashboard/test/system/products_usr_test.rb
apps/dashboard/test/test_helper.rb

Addresses #1580
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201625178070145/1201665025942201) by [Unito](https://www.unito.io)

Adding systems tests for products.

---

apps/dashboard/app/controllers/jobs/projects_controller.rb
apps/dashboard/app/models/jobs/project.rb
apps/dashboard/app/views/jobs/projects/_form.html.erb
apps/dashboard/app/views/jobs/projects/create.html.erb
apps/dashboard/app/views/jobs/projects/destroy.html.erb
apps/dashboard/app/views/jobs/projects/edit.html.erb
apps/dashboard/app/views/jobs/projects/index.html.erb
apps/dashboard/app/views/jobs/projects/new.html.erb
apps/dashboard/app/views/jobs/projects/show.html.erb
apps/dashboard/app/views/jobs/projects/submit.html.erb
apps/dashboard/app/views/jobs/projects/update.html.erb
apps/dashboard/config/configuration_singleton.rb
apps/dashboard/config/routes.rb
apps/dashboard/test/fixtures/config/ondemand.d/booleans.yml
apps/dashboard/test/integration/jobs_controller_test.rb

Initial scaffolding for new jobs app alpha.
Because #1771 is failing, instead of merging 2 squashes into mainline, let's just merge them in one at a time.
Whoever pulls this - be sure to just merge - don't also squash.

Initial scaffolding for new jobs app alpha. (#1615)

---

apps/shell/public/javascripts/ood_shell.2.js

Fixes #1448
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201625178070145/1201675721981132) by [Unito](https://www.unito.io)

correctly initialize the shell app with the right profile

---

mod_ood_proxy/lib/nginx.lua
spec/e2e/proxy_spec.rb

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201625178070145/1201732270486413) by [Unito](https://www.unito.io)

Redirect proxy tests

---

apps/dashboard/app/models/batch_connect/session.rb
apps/dashboard/config/configuration_singleton.rb
apps/dashboard/test/models/batch_connect/session_test.rb

* Fixes #1439
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201737260616579) by [Unito](https://www.unito.io)

Make the batch connect session delete duration configurable.

---

apps/dashboard/test/system/jobs_app_test.rb

Adding basic systems tests.

---

apps/dashboard/app/javascript/packs/files/datatable.js
apps/dashboard/app/javascript/packs/files/uppy.js
apps/dashboard/app/views/files/_inline_js.html.erb
apps/dashboard/app/views/files/index.html.erb

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201906068488436) by [Unito](https://www.unito.io)

Completed Upload Functionality

---

CITATION.cff
README.md

add a CITATION.cff for the citation links
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files
How to manage newer versions and/or authors? I guess some automation is required.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201917211142459) by [Unito](https://www.unito.io)

add a CITATION.cff for the citation links

---

apps/dashboard/app/javascript/packs/config.js

Fixes #1894 
Defaults were pulled from the previous files. I tested this with both light and dark variants.
https://github.com/OSC/ondemand/blob/ba896cfd3559b8380d0fa3ac2df6b6e36a7073a0/apps/dashboard/app/views/layouts/nav/_styles.html.erb
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1201931977514709) by [Unito](https://www.unito.io)

ensure navbar has default colors

---

ood-portal-generator/spec/fixtures/ood-portal.conf.all
ood-portal-generator/templates/ood-portal.conf.erb

Fixes #1931 to additionally check for relative urls.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202053498682560) by [Unito](https://www.unito.io)

very simple regex for rnode location edits

---

Gemfile.lock

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202046644501506) by [Unito](https://www.unito.io)

Bump ood_packaging gem version

---

apps/dashboard/app/controllers/projects_controller.rb
apps/dashboard/app/models/project.rb
apps/dashboard/app/views/projects/_form.html.erb
apps/dashboard/app/views/projects/index.html.erb
apps/dashboard/config/locales/en.yml
apps/dashboard/test/models/projects_test.rb

Fixes #1938
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202206249745420) by [Unito](https://www.unito.io)

Adding I18n translations and updating tests

---

lib/tasks/rake_helper.rb
ood-portal-generator/lib/ood_portal_generator.rb
ood-portal-generator/spec/application_spec.rb
ood-portal-generator/spec/update_ood_portal_spec.rb

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202238367235600) by [Unito](https://www.unito.io)

Issue#1990 Use Etc.getpwn.name instead of Etc.getlogin #1990

---

apps/dashboard/app/views/layouts/application.html.erb

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202239213072566) by [Unito](https://www.unito.io)

Issue#1902 added alt text to the navbar img tag

---

DEVELOPMENT.md

correct the location of this file and add a note about CONTAINER_RT.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202240288174073) by [Unito](https://www.unito.io)

correct the location of this file

---

.rubocop.yml
lib/tasks/lint.rb

Fixes #1642.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202234830993369) by [Unito](https://www.unito.io)

only apply Rspec lint when rspec has been loaded

---

apps/shell/app.js

Added try-catch around yaml.safeload() to release_2.0 branch. Closes #1950
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202233308118730) by [Unito](https://www.unito.io)

Shell: Backport try catch on yaml.safeload to release_2.0

---

apps/dashboard/app/apps/manifest.rb
apps/dashboard/test/models/manifest_test.rb

Fixes #1969
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202257179595965) by [Unito](https://www.unito.io)

Bug fix/sanitize manifest

---

README.md

add a simple demo to the readme

---

packaging/ondemand.spec

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202284779856964) by [Unito](https://www.unito.io)

Depend on Passenger 6.0.14

---

packaging/deb/control
packaging/rpm/ondemand.spec

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202285933000866) by [Unito](https://www.unito.io)

Depend on Passenger 6.0.14 and NGINX 1.20.2

---

apps/dashboard/app/views/batch_connect/sessions/connections/_novnc.html.erb

Fixes #2023 
Fix VNC apps by skipping the pipeline here.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202302959952913) by [Unito](https://www.unito.io)

fix VNC apps by skipping the pipeline here

---

.github/workflows/tests.yml
.gitlab-ci.yml
Gemfile
Gemfile.lock
nginx_stage/lib/nginx_stage/secret_key_base_file.rb
nginx_stage/lib/nginx_stage/views/pun_config_view.rb
packaging/deb/rules
spec/e2e/default_install_spec.rb
spec/e2e/e2e_helper.rb
spec/e2e/nodesets/ubuntu-22.04.yml
spec/spec_helper_e2e.rb

Fixes #2009
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202331532568639) by [Unito](https://www.unito.io)

Support Ubuntu 22.04

---

packaging/deb/postinst

Enable Apache proxy_wstunnel for deb packages

---

packaging/ondemand.spec

[release_2.0] Depend on more specific ondemand-passenger RPM

---

apps/dashboard/Gemfile.lock
apps/myjobs/Gemfile.lock

This backports the rack updates we just got.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202355894868212) by [Unito](https://www.unito.io)

Update rack for 2.0

---

nginx_stage/lib/nginx_stage/configuration.rb

This is causing me issues when I upgrade and I would appreciate if the fix could be backported and make it into the RPMs.

Backport #1793 passenger_options fix to 2.0

---

ood-portal-generator/lib/ood_portal_generator/dex.rb
ood-portal-generator/spec/fixtures/dex.custom.yaml
ood-portal-generator/spec/fixtures/ood_portal.dex.yaml

Ensure tls_cert and tls_key for Dex can be set

---

ood-portal-generator/lib/ood_portal_generator/dex.rb
ood-portal-generator/spec/fixtures/dex.custom.yaml
ood-portal-generator/spec/fixtures/ood_portal.dex.yaml

Fixes #2162 for 2.0 release
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202671445229919) by [Unito](https://www.unito.io)

Ensure tls_cert and tls_key for Dex can be set [release_2.0]

---

apps/dashboard/app/javascript/packs/files/file_ops.js
apps/dashboard/app/views/files/index.html.erb

Closes #283
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202477441275800) by [Unito](https://www.unito.io)

Added button to refresh files table

---

nginx_stage/lib/nginx_stage.rb

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202686494911654) by [Unito](https://www.unito.io)

Remove GEM_HOME from PUN to retain old behavior with app development

---

nginx_stage/lib/nginx_stage.rb
nginx_stage/lib/nginx_stage/generators/app_config_generator.rb
nginx_stage/lib/nginx_stage/generators/nginx_clean_generator.rb
nginx_stage/lib/nginx_stage/generators/nginx_process_generator.rb
nginx_stage/lib/nginx_stage/generators/pun_config_generator.rb
nginx_stage/lib/nginx_stage/views/pun_config_view.rb
nginx_stage/templates/pun.conf.erb
spec/e2e/e2e_helper.rb

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202671561521607) by [Unito](https://www.unito.io)

[release_2.0] Ensure minimal environment with nginx_stage

---

apps/dashboard/app/helpers/application_helper.rb
apps/dashboard/app/models/user_configuration.rb
apps/dashboard/app/views/layouts/application.html.erb
apps/dashboard/test/helpers/application_helper_test.rb
apps/dashboard/test/integration/custom_css_files_test.rb
apps/dashboard/test/models/user_configuration_test.rb

Draft PR to discuss implementation details for including custom CSS files into OnDemand.
Implements: #2150
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201735133575781/1202679356534194) by [Unito](https://www.unito.io)

Added support for custom CSS files

---

spec/e2e/00_package_spec.rb

Test ondemand-nginx package permissions during E2E tests

---

CONTRIBUTING.md

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202699232514765) by [Unito](https://www.unito.io)

First pass at adding ood coding standards.

---

ood-portal-generator/lib/ood_portal_generator/dex.rb
ood-portal-generator/lib/ood_portal_generator/view.rb
ood-portal-generator/share/ood_portal_example.yml
ood-portal-generator/spec/application_spec.rb
ood-portal-generator/spec/fixtures/dex.custom.yaml
ood-portal-generator/spec/fixtures/dex.full.proxy.yaml
ood-portal-generator/spec/fixtures/dex.yaml.default
ood-portal-generator/spec/fixtures/dex.yaml.full
ood-portal-generator/spec/fixtures/dex.yaml.full-redirect-uris
ood-portal-generator/spec/fixtures/dex.yaml.ldap
ood-portal-generator/spec/fixtures/dex.yaml.no-proxy
ood-portal-generator/spec/fixtures/dex.yaml.secret
ood-portal-generator/spec/fixtures/dex.yaml.static_passwords
ood-portal-generator/spec/fixtures/ood-portal.conf.dex
ood-portal-generator/spec/fixtures/ood-portal.conf.dex-full
ood-portal-generator/spec/fixtures/ood-portal.conf.dex-ldap
ood-portal-generator/spec/fixtures/ood-portal.conf.dex-no-proxy
ood-portal-generator/spec/fixtures/ood-portal.dex-full.proxy.conf
ood-portal-generator/spec/fixtures/output/dex/insecure_default_dex.yml
ood-portal-generator/templates/ood-portal.conf.erb
spec/e2e/browser_spec.rb
spec/e2e/dex_no_proxy_spec.rb
spec/fixtures/config/ood_portal/portal_dex_no_proxy.yml

Fixes #2185
Improve issuer logic, fixes #2190
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202702529964484) by [Unito](https://www.unito.io)

Put Dex behing Apache reverse proxy by default

---

ood-portal-generator/spec/fixtures/ood-portal.conf.all
ood-portal-generator/spec/fixtures/ood-portal.conf.dex
ood-portal-generator/spec/fixtures/ood-portal.conf.dex-full
ood-portal-generator/spec/fixtures/ood-portal.conf.dex-ldap
ood-portal-generator/spec/fixtures/ood-portal.conf.dex-no-proxy
ood-portal-generator/spec/fixtures/ood-portal.conf.maint_with_ips
ood-portal-generator/spec/fixtures/ood-portal.conf.nomaint
ood-portal-generator/spec/fixtures/ood-portal.conf.oidc
ood-portal-generator/spec/fixtures/ood-portal.conf.oidc-ssl
ood-portal-generator/spec/fixtures/ood-portal.dex-full.proxy.conf
ood-portal-generator/spec/fixtures/output/auth.conf
ood-portal-generator/spec/fixtures/output/auth_deb.conf
ood-portal-generator/templates/ood-portal.conf.erb

Fixes #2196
Will backport to 2.0 once this is merged.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202710899416129) by [Unito](https://www.unito.io)

Improved maintenance page handling of 503 errors

---

apps/dashboard/app/views/active_jobs/_extended_panel.html.erb

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202730669607191) by [Unito](https://www.unito.io)

Do not display Open In Terminal button if SSH to compute is turned off (2.1)

---

apps/dashboard/app/apps/ood_app_group.rb
apps/dashboard/test/models/ood_app_group_test.rb

Fixes: #2217
Possible solution for the memory leak and new tests to check for updates
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202731739707479) by [Unito](https://www.unito.io)

Fixed memory leak for NavConfig.category

---

apps/dashboard/config/environments/development.rb
apps/dashboard/config/environments/production.rb
apps/dashboard/config/environments/test.rb
apps/myjobs/config/environments/production.rb
apps/myjobs/config/environments/test.rb
mod_ood_proxy/lib/logger.lua
mod_ood_proxy/lib/ood/nginx_stage.lua
mod_ood_proxy/lib/pun_proxy.lua
nginx_stage/lib/nginx_stage.rb
ood-portal-generator/lib/ood_portal_generator/view.rb
ood-portal-generator/spec/fixtures/ood-portal.conf.all
ood-portal-generator/spec/fixtures/ood-portal.conf.dex
ood-portal-generator/spec/fixtures/ood-portal.conf.dex-full
ood-portal-generator/spec/fixtures/ood-portal.conf.dex-ldap
ood-portal-generator/spec/fixtures/ood-portal.conf.dex-no-proxy
ood-portal-generator/spec/fixtures/ood-portal.conf.maint_with_ips
ood-portal-generator/spec/fixtures/ood-portal.conf.nomaint
ood-portal-generator/spec/fixtures/ood-portal.conf.oidc
ood-portal-generator/spec/fixtures/ood-portal.conf.oidc-ssl
ood-portal-generator/spec/fixtures/ood-portal.dex-full.proxy.conf
ood-portal-generator/spec/fixtures/output/auth.conf
ood-portal-generator/spec/fixtures/output/auth_deb.conf
ood-portal-generator/spec/ood_portal_generator_view_spec.rb
ood-portal-generator/templates/ood-portal.conf.erb

Fixes #1530
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202730713283317) by [Unito](https://www.unito.io)

Set Rails config.hosts in dashboard and myjobs

---

apps/dashboard/app/models/active_jobs/jobstatusdata.rb
apps/dashboard/lib/smart_attributes/attributes/bc_num_slots.rb

Backport #2194 to 2.0.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202725199928844) by [Unito](https://www.unito.io)

Fix for Fujitsu TCS resource manager (#2194)

---

apps/dashboard/app/models/active_jobs/jobstatusdata.rb

fix misspelled Submission
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202793484854169) by [Unito](https://www.unito.io)

fix misspelled Submission

---

ood-portal-generator/spec/fixtures/ood-portal.conf.all
ood-portal-generator/spec/fixtures/ood-portal.conf.dex
ood-portal-generator/spec/fixtures/ood-portal.conf.dex-full
ood-portal-generator/spec/fixtures/ood-portal.conf.dex-ldap
ood-portal-generator/spec/fixtures/ood-portal.conf.dex-no-proxy
ood-portal-generator/spec/fixtures/ood-portal.conf.maint_with_ips
ood-portal-generator/spec/fixtures/ood-portal.conf.nomaint
ood-portal-generator/spec/fixtures/ood-portal.conf.oidc
ood-portal-generator/spec/fixtures/ood-portal.conf.oidc-ssl
ood-portal-generator/spec/fixtures/ood-portal.dex-full.proxy.conf
ood-portal-generator/spec/fixtures/output/auth.conf
ood-portal-generator/spec/fixtures/output/auth_deb.conf
ood-portal-generator/templates/ood-portal.conf.erb

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202803792380183) by [Unito](https://www.unito.io)

Ensure host name is getting passed to PUN proxy

---

packaging/deb/control
packaging/rpm/ondemand.spec
spec/e2e/e2e_helper.rb

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202803792211858) by [Unito](https://www.unito.io)

Add rclone dependency

---

Dockerfile.dev

Remove rclone install and bump ondemand up in sequence.

---

apps/dashboard/README.md

add .env.overload docs to the README
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202831109860324) by [Unito](https://www.unito.io)

add .env.overload docs to the README

---

apps/dashboard/app/apps/router.rb
apps/dashboard/app/apps/token_matcher.rb
apps/dashboard/test/apps/token_matcher_test.rb

Possible fix for #2235 + associated tests
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202822760516249) by [Unito](https://www.unito.io)

Fix token matcher logic for sub apps (#2235)

---

apps/dashboard/app/apps/nav_bar.rb
apps/dashboard/test/apps/nav_bar_test.rb
apps/dashboard/test/integration/custom_navigation_test.rb

johrstrom Improved test coverage for full navigation configuration
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202956027512173) by [Unito](https://www.unito.io)

Full navigation configuration - improved test coverage

---

SECURITY.md

Update our security policy with the new email distro and add some timings around all the bullet points.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202975454008043) by [Unito](https://www.unito.io)

update our security policy

---

apps/dashboard/app/apps/app_recategorizer.rb
apps/dashboard/app/apps/bundler_helper.rb
apps/dashboard/app/apps/dev_router.rb
apps/dashboard/app/apps/favorite_path.rb
apps/dashboard/app/apps/manifest.rb
apps/dashboard/app/apps/nav_config.rb
apps/dashboard/app/apps/ood_app.rb
apps/dashboard/app/apps/ood_app_group.rb
apps/dashboard/app/apps/ood_app_link.rb
apps/dashboard/app/apps/ood_files_app.rb
apps/dashboard/app/apps/path_router.rb
apps/dashboard/app/apps/router.rb
apps/dashboard/app/apps/sys_router.rb
apps/dashboard/app/apps/token_matcher.rb
apps/dashboard/app/apps/usr_router.rb

Add some class level comments to the files in `apps/`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202956058864971) by [Unito](https://www.unito.io)

add some class level comments to the files in apps/

---

CONTRIBUTING.md

Add a section for project conventions and add the one project convention that I can think of.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202872760770990) by [Unito](https://www.unito.io)

add project conventions

---

apps/dashboard/app/helpers/active_jobs_helper.rb
apps/dashboard/app/helpers/app_helper.rb
apps/dashboard/app/helpers/application_helper.rb
apps/dashboard/app/helpers/batch_connect/session_contexts_helper.rb
apps/dashboard/app/helpers/batch_connect/sessions_helper.rb
apps/dashboard/app/helpers/dashboard_helper.rb
apps/dashboard/app/helpers/errors_helper.rb
apps/dashboard/app/helpers/files_helper.rb
apps/dashboard/app/helpers/permissions_helper.rb
apps/dashboard/app/helpers/products_helper.rb

This adds some comments for all our helper modules.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202967204074061) by [Unito](https://www.unito.io)

add module comments for helpers

---

apps/dashboard/app/jobs/application_job.rb
apps/dashboard/app/jobs/transfer_local_job.rb

Add some class comments for all the classes in the dashboard's `jobs/` folder.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202967203828608) by [Unito](https://www.unito.io)

add class comments for jobs

---

apps/dashboard/app/views/layouts/nav/_link.html.erb

Fix to the link alignment in the new full navigation rendering.
Images attached of the before and after the fix.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1202980504405447) by [Unito](https://www.unito.io)

Custom navigation CSS fix for small screen

---

apps/dashboard/app/controllers/active_jobs_controller.rb
apps/dashboard/app/controllers/application_controller.rb
apps/dashboard/app/controllers/apps_controller.rb
apps/dashboard/app/controllers/batch_connect/session_contexts_controller.rb
apps/dashboard/app/controllers/batch_connect/sessions_controller.rb
apps/dashboard/app/controllers/concerns/batch_connect_concern.rb
apps/dashboard/app/controllers/dashboard_controller.rb
apps/dashboard/app/controllers/errors_controller.rb
apps/dashboard/app/controllers/files_controller.rb
apps/dashboard/app/controllers/permissions_controller.rb
apps/dashboard/app/controllers/products_controller.rb
apps/dashboard/app/controllers/projects_controller.rb
apps/dashboard/app/controllers/settings_controller.rb
apps/dashboard/app/controllers/transfers_controller.rb

add some class documentation for controllers
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202956026999733) by [Unito](https://www.unito.io)

add some class documentation for controllers

---

Dockerfile.dev

Fixes #2130
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1202823841545499) by [Unito](https://www.unito.io)

enable dev mode in dev container

---

apps/dashboard/app/models/batch_connect/session.rb
apps/dashboard/app/views/batch_connect/sessions/_panel.html.erb

This PR is to enable this PR from `ood_core`: https://github.com/OSC/ood_core/pull/774
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203135767739235) by [Unito](https://www.unito.io)

Add vnc_container option

---

apps/dashboard/app/models/batch_connect/session.rb
apps/dashboard/app/views/batch_connect/sessions/_panel.html.erb

`ood_core` with the `vnc_container` hasn't been released yet, but this is to get ahead of that functionality when it is released.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203152267545672) by [Unito](https://www.unito.io)

Add vnc_container option (#2323)

---

apps/myjobs/app/models/resource_mgr_adapter.rb
apps/myjobs/app/models/workflow.rb
apps/myjobs/app/views/workflows/_edit_form_job_attrs.html.erb
apps/myjobs/config/locales/en.yml

Backport #1847 to release 2.0.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203143722306966) by [Unito](https://www.unito.io)

allow for job composer to copy environment (#1847)

---

apps/dashboard/app/javascript/packs/batchConnect.js
apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml
apps/dashboard/test/system/batch_connect_test.rb

Backport the bugfix #2330 for 2.0
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203236092487662) by [Unito](https://www.unito.io)

backport Dynanic batch connect with slashes bugfix (#2330)

---

apps/myjobs/app/models/workflow.rb
apps/myjobs/config/configuration_singleton.rb

Backport #2327 to release 2.0.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203253720751620) by [Unito](https://www.unito.io)

Add ENV override for showing/hiding job arrays (#2327)

---

CHANGELOG.md

update changelog for 2.0.29
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203272833563531) by [Unito](https://www.unito.io)

update changelog for 2.0.29

---

apps/dashboard/Gemfile.lock
apps/myjobs/Gemfile.lock

bump ood_core to next release to pick up bugfixes and the `vnc_container`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203272319843100) by [Unito](https://www.unito.io)

bump ood_core to next release

---

apps/dashboard/app/helpers/batch_connect/sessions_helper.rb
apps/dashboard/app/models/batch_connect/session.rb
apps/dashboard/lib/smart_attributes/attribute.rb
apps/dashboard/test/models/batch_connect/session_test.rb

Implementation idea for: https://github.com/OSC/ondemand/issues/2342
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203353719324192) by [Unito](https://www.unito.io)

Added support to show form parameters in session card

---

apps/dashboard/app/apps/manifest.rb
apps/dashboard/app/apps/ood_app.rb
apps/dashboard/app/apps/ood_app_link.rb
apps/dashboard/app/javascript/stylesheets/pinned_apps.scss
apps/dashboard/app/models/batch_connect/app.rb
apps/dashboard/app/views/widgets/pinned_apps/_app.html.erb
apps/dashboard/test/apps/nav_bar_test.rb
apps/dashboard/test/apps/token_matcher_test.rb
apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_desktop/local/oakley.yml
apps/dashboard/test/fixtures/usr/shared/bc_with_subapps/form.yml
apps/dashboard/test/fixtures/usr/shared/bc_with_subapps/local/oakley.yml
apps/dashboard/test/fixtures/usr/shared/bc_with_subapps/local/owens.yml
apps/dashboard/test/integration/custom_navigation_test.rb
apps/dashboard/test/integration/pinned_apps_test.rb
apps/dashboard/test/models/batch_connect/app_test.rb

Minor improvements to the pinned apps UI:
* Added support for more content on the tiles
* Added support to customize the tile border color
* Added support to override the pinned app content
Fixes #2345 
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203273058320060) by [Unito](https://www.unito.io)

Pinned Apps UI improvements

---

apps/dashboard/app/controllers/batch_connect/sessions_controller.rb
apps/dashboard/app/views/widgets/_sessions.html.erb
apps/dashboard/config/locales/en.yml
apps/dashboard/test/integration/active_sessions_widget_test.rb

Prototype for the active sessions widget
It displays the 3 most recent active sessions.
Fixes #2376
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203427527766721) by [Unito](https://www.unito.io)

Added active sessions widget

---

.github/workflows/tests.yml
apps/dashboard/test/models/batch_connect/session_test.rb

Add the `zeitwerk:check` task to our CI as it would have picked up the issue identified in #2382.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203451171322590) by [Unito](https://www.unito.io)

add rake zeitwerk:check to our CI

---

apps/dashboard/app/apps/token_matcher.rb
apps/dashboard/test/apps/token_matcher_test.rb

Possible solution for #2395
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203459743664454) by [Unito](https://www.unito.io)

Fixed token matcher string matching for apps with the same prefix

---

apps/dashboard/app/javascript/packs/application.js
apps/dashboard/package.json
apps/dashboard/yarn.lock

Fixes #2423
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203536841814347) by [Unito](https://www.unito.io)

update popper to correct v1 version

---

apps/dashboard/app/models/permission.rb

Fixes #2399 by correctly catching the error and adding it to the `errors` object.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203502382561660) by [Unito](https://www.unito.io)

correctly catch facl errors

---

apps/dashboard/test/integration/sessions_test.rb

Fixes #2424
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203542220996444) by [Unito](https://www.unito.io)

Fixed list of sessions to avoid picking up created sessions by other tests

---

apps/dashboard/config/initializers/session_store.rb

Fixes #1226
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203557610512033) by [Unito](https://www.unito.io)

use cache store for sessions if you can

---

apps/dashboard/app/javascript/packs/batchConnect.js
apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml
apps/dashboard/test/system/batch_connect_test.rb

Fix clamping to and from 0 to behave correctly on the 2.0 release.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203510953924063) by [Unito](https://www.unito.io)

Clamp bugfix (2.0 backport)

---

nginx_stage/templates/pun.conf.erb

Some work toward #2002 and any security related tech debt we need to attend to in 2.1.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203651317577417) by [Unito](https://www.unito.io)

disable passengers update check bc they cant update anyhow

---

apps/dashboard/app/apps/nav_bar.rb
apps/dashboard/app/apps/ood_app_group.rb
apps/dashboard/app/helpers/application_helper.rb
apps/dashboard/app/views/layouts/application.html.erb
apps/dashboard/app/views/layouts/nav/_develop_dropdown.html.erb
apps/dashboard/app/views/layouts/nav/_featured_apps.html.erb
apps/dashboard/app/views/layouts/nav/_group.html.erb
apps/dashboard/app/views/layouts/nav/_help_dropdown.html.erb
apps/dashboard/test/apps/nav_bar_test.rb
apps/dashboard/test/integration/custom_navigation_test.rb
apps/dashboard/test/models/ood_app_group_test.rb

Improvements and bug fixes to the custom navigation logic and configuration.
Fixes https://github.com/OSC/ondemand/issues/2336
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203635213960705) by [Unito](https://www.unito.io)

Configuration improvements for custom navigation bar

---

apps/dashboard/app/views/layouts/editor.html.erb

Fixes #2135
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203602909599157) by [Unito](https://www.unito.io)

use an actual button for saving file editor

---

apps/dashboard/app/apps/nav_config.rb
apps/dashboard/app/models/user_configuration.rb
apps/dashboard/test/models/user_configuration_test.rb

Fixes #2254 so folks know this is being deprecated and removed in 3.0.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203643781957165) by [Unito](https://www.unito.io)

add deprecation warnings for NavConfig

---

apps/dashboard/app/javascript/packs/batch_connect.js
apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml
apps/dashboard/test/system/batch_connect_test.rb

Fixes #2410
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203504213771323) by [Unito](https://www.unito.io)

allow for 2 or more elements to set min/max on 1 element 

---

ood-portal-generator/spec/fixtures/ood-portal.conf.all
ood-portal-generator/spec/fixtures/ood-portal.conf.dex
ood-portal-generator/spec/fixtures/ood-portal.conf.dex-full
ood-portal-generator/spec/fixtures/ood-portal.conf.dex-ldap
ood-portal-generator/spec/fixtures/ood-portal.conf.dex-no-proxy
ood-portal-generator/spec/fixtures/ood-portal.conf.maint_with_ips
ood-portal-generator/spec/fixtures/ood-portal.conf.oidc
ood-portal-generator/spec/fixtures/ood-portal.conf.oidc-ssl
ood-portal-generator/spec/fixtures/ood-portal.dex-full.proxy.conf
ood-portal-generator/spec/fixtures/output/auth.conf
ood-portal-generator/spec/fixtures/output/auth_deb.conf
ood-portal-generator/templates/ood-portal.conf.erb

Forward port #2436 to 2.1
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203596989929992) by [Unito](https://www.unito.io)

Fwd port maint assets

---

apps/dashboard/app/javascript/packs/batch_connect.js

Fixes #2409 but in draft now because there's another PR that'll likely conflict anyhow.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203518894777039) by [Unito](https://www.unito.io)

hide things when initializing, but dont show them

---

apps/myjobs/bin/setup-production

Fixes #149
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203658072761861) by [Unito](https://www.unito.io)

recognize that the db file is zero and rectify

---

apps/dashboard/app/apps/nav_bar.rb
apps/dashboard/test/apps/nav_bar_test.rb

Added aliases to static links and templates
Fixes [2460](https://github.com/OSC/ondemand/issues/2460)
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203673227776906) by [Unito](https://www.unito.io)

Added aliases to custom navbar links and templates

---

apps/dashboard/app/controllers/batch_connect/session_contexts_controller.rb
apps/dashboard/app/helpers/recently_used_apps_helper.rb
apps/dashboard/app/javascript/packs/pinned_apps.js
apps/dashboard/app/javascript/stylesheets/pinned_apps.scss
apps/dashboard/app/models/batch_connect/app.rb
apps/dashboard/app/views/custom_pages/index.html.erb
apps/dashboard/app/views/dashboard/index.html.erb
apps/dashboard/app/views/widgets/_pinned_apps.html.erb
apps/dashboard/app/views/widgets/_recently_used_apps.html.erb
apps/dashboard/app/views/widgets/pinned_apps/_app.html.erb
apps/dashboard/app/views/widgets/pinned_apps/_app_content.html.erb
apps/dashboard/config/locales/en.yml
apps/dashboard/test/fixtures/widgets/recently_used_apps/sys/bc_desktop/form.yml
apps/dashboard/test/fixtures/widgets/recently_used_apps/sys/bc_desktop/manifest.yml
apps/dashboard/test/fixtures/widgets/recently_used_apps/sys_bc_desktop.json
apps/dashboard/test/helpers/recently_used_apps_helper_test.rb
apps/dashboard/test/integration/pinned_apps_test.rb
apps/dashboard/test/integration/recently_used_apps_widget_test.rb

Recently used applications widget based on the list of application data cache files
Fixes: https://github.com/OSC/ondemand/issues/2477
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203796685604202) by [Unito](https://www.unito.io)

Added recently used applications widget

---

apps/dashboard/app/javascript/packs/config.js

Fixes #2463.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203822374576177) by [Unito](https://www.unito.io)

Remove Jquery and use dataset for data

---

apps/dashboard/app/javascript/packs/config.js
apps/dashboard/app/javascript/packs/files/uppy_ops.js
apps/dashboard/app/views/files/_inline_js.html.erb
apps/dashboard/app/views/layouts/application.html.erb

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203862028527344) by [Unito](https://www.unito.io)

Move max file size from inline to setting in config.js

---

apps/dashboard/app/views/batch_connect/sessions/connections/_novnc.html.erb

While reviewing #2534 I noticed this button is a bit hard to see, so let's give it a border so it stands out a bit more.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203877590045926) by [Unito](https://www.unito.io)

give this button a border

---

packaging/rpm/ondemand.spec

This will ensure that multiple RPMs can still be installed at same time
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203886871180795) by [Unito](https://www.unito.io)

Need to ensure gem path is also using release

---

apps/dashboard/Gemfile.lock
apps/myjobs/Gemfile.lock

update ood_core for apptainer bugfix (again). I'm fairly sure that ood_core 0.23.2 actually fixes our apptainer issues.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203906105519454) by [Unito](https://www.unito.io)

update ood_core for apptainer bugfix

---

mod_ood_proxy/lib/logger.lua
mod_ood_proxy/lib/ood/nginx_stage.lua
mod_ood_proxy/lib/pun_proxy.lua

Fixes #2566 because I did not update `mod_ood_proxy`.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203959817553194) by [Unito](https://www.unito.io)

mod_ood_proxy needs to use OOD_ALLOWED_HOSTS

---

apps/dashboard/app/javascript/packs/config.js
apps/dashboard/app/javascript/packs/files/clip_board.js
apps/dashboard/app/javascript/packs/files/file_ops.js
apps/dashboard/app/javascript/packs/files/uppy_ops.js
apps/dashboard/app/views/files/_inline_js.html.erb
apps/dashboard/app/views/layouts/application.html.erb

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1203912856196303) by [Unito](https://www.unito.io)

Use config.js to handle js setup for configs and csrf_token

---

nginx_stage/lib/nginx_stage.rb

fix misspelling in this comment
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203986435857884) by [Unito](https://www.unito.io)

fix misspelling in this comment

---

apps/dashboard/app/controllers/projects_controller.rb
apps/dashboard/app/controllers/scripts_controller.rb
apps/dashboard/app/helpers/scripts_helper.rb
apps/dashboard/app/models/script.rb
apps/dashboard/app/views/projects/show.html.erb
apps/dashboard/app/views/scripts/new.html.erb
apps/dashboard/app/views/scripts/show.html.erb
apps/dashboard/config/routes.rb
apps/dashboard/test/integration/projects_controller_test.rb

Fixes #1861 by starting the script models. Also fixes #2555, although partially.  I'll update the epic ticket with more followups.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203971508198883) by [Unito](https://www.unito.io)

Scripts models

---

apps/dashboard/README.md

update docs for developing ood_core
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203987727255598) by [Unito](https://www.unito.io)

update docs for developing ood_core

---

apps/dashboard/app/models/project.rb
apps/dashboard/app/views/projects/index.html.erb

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1203996426159477) by [Unito](https://www.unito.io)

Job composer/project index display icon

---

apps/dashboard/app/views/layouts/application.html.erb
apps/dashboard/app/views/layouts/editor.html.erb

Fixes #2615 (hopefully) by preloading the stylesheets.  #2615  only happens occasionally, so this only may fix it given there's no way to replicate the issue.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1204069700821238) by [Unito](https://www.unito.io)

preload stylesheets

---

apps/dashboard/app/controllers/scripts_controller.rb
apps/dashboard/app/lib/smart_attributes/attribute.rb
apps/dashboard/app/models/script.rb
apps/dashboard/app/views/scripts/show.html.erb

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204051038297071) by [Unito](https://www.unito.io)

enable scripts

---

apps/dashboard/public/noVNC-1.3.0/app/ui.js
apps/dashboard/public/noVNC-1.3.0/core/rfb.js

forward port #537 to 2.1 to have native copy/paste support for chrome.
Taken directory from #537 so @samirmansour get's the co-author credit.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204198459632367) by [Unito](https://www.unito.io)

forward port #537 to 2.1 to have native copy/paste support for chrome.

---

.github/workflows/tests.yml
Gemfile
Gemfile.lock
packaging/deb/control
packaging/rpm/ondemand.spec
spec/e2e/e2e_helper.rb

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204226840016813) by [Unito](https://www.unito.io)

Change to building OnDemand 3.0 packages

---

apps/dashboard/app/lib/smart_attributes.rb
apps/dashboard/app/lib/smart_attributes/attributes/auto_scripts.rb
apps/dashboard/app/models/script.rb

Fixes #2575 and also adds cluster to the form for good measure.  In draft right now because I'll need to rebase once #2649 is merged (this depends on the things added in that pull request).
With a configuration like so.  You're directory will be different and you'll actually need to create a script in that directory.
```yaml
---
title: 'some title'
form:
- auto_accounts
- auto_scripts
attributes:
auto_scripts:
directory: '/users/PZS0714/johrstrom/ondemand/dev/dashboard/data/projects/2'
```
You get a form like this.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204187868905323) by [Unito](https://www.unito.io)

Auto scripts

---

apps/dashboard/app/models/script.rb
apps/dashboard/test/system/jobs_app_test.rb
apps/dashboard/test/test_helper.rb

Add some test cases for scripts and fix some bugs.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1204240623405514) by [Unito](https://www.unito.io)

add some test cases for scripts and fix some bugs

---

apps/dashboard/app/javascript/packs/batch_connect.js
apps/dashboard/test/fixtures/sys_with_gateway_apps/bc_jupyter/form.yml
apps/dashboard/test/models/batch_connect/session_test.rb
apps/dashboard/test/system/batch_connect_test.rb

Fix #1659 by checking for string values.
Also fixes #2686
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1204227301750360) by [Unito](https://www.unito.io)

fix #1659 by checking for string values

---

apps/dashboard/app/javascript/packs/active_jobs.js

Fixes #2702 though I have to file another ticket because there are no errors, but I don't think that the `processing` functionality is actually working.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204283510894781) by [Unito](https://www.unito.io)

fix console errors in activejobs

---

apps/dashboard/app/javascript/packs/active_jobs.js
apps/dashboard/app/javascript/packs/utils.js

I just added this utility function `cssBadgeForState` which was basically pulled from this implementation.
So while I it's fresh in my mind, let's use it in the active jobs javascript. This also adds a helper function for capitalizing the first letter of a string.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204309968610968) by [Unito](https://www.unito.io)

Activejobs refactor utils

---

packaging/rpm/ondemand.spec

Fixes #2737
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204354835505102) by [Unito](https://www.unito.io)

Only depend on the selinux-policy version, not full version including release

---

apps/dashboard/app/controllers/scripts_controller.rb
apps/dashboard/app/helpers/scripts_helper.rb
apps/dashboard/app/javascript/packs/script_edit.js
apps/dashboard/app/models/script.rb
apps/dashboard/app/views/projects/show.html.erb
apps/dashboard/app/views/scripts/_add_new_field.html.erb
apps/dashboard/app/views/scripts/edit.html.erb
apps/dashboard/config/locales/en.yml
apps/dashboard/config/routes.rb

This starts support for editing scripts. This is about as far as I'm going to go in this PR.
To test this
* create a script that shows up in projects#show
* press the edit button for that script
* now you'll see an `Add new option` button.
* Press that button and you'll get a new in progress field as shown below
* `Add` does nothing at the moment, while `Remove` works.
* Changing the field to choose changes the help text.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1135148780858012/1204383563053604) by [Unito](https://www.unito.io)

Start edit scripts

---

apps/dashboard/app/views/batch_connect/shared/_app_menu.html.erb

Always show dev apps in my interactive sessions. Fixes #2756.
@abujeda FYI.
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204402605830855) by [Unito](https://www.unito.io)

always show dev apps in my interactive sessions

---

apps/dashboard/app/apps/nav_bar.rb
apps/dashboard/test/apps/nav_bar_test.rb

Changes to support overriding the app title and icon when creating custom navigation links using apps.
This only applies when token matches a single application.
Partially implements issue: #2774 
Incidentally, this will change the behaviour of some configurations.
Now the following example, will render a top level link instead of a menu with one appliation.
```yaml
- title: 'Jupyter'
icon: "fa://star"
apps: 'sys/jupyter'
```
The following example renders a menu with a single link. The link will be driven from the jupyter app with the title and icon overridden.
```yaml
- title: 'Single App Menu'
icon: 'fa://star'
links:
- title: 'Jupyter'
icon: 'fas://star'
apps: 'sys/jupyter'
```
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204571570469625) by …

Added support to override title and icon on app navigation items

---

ood-portal-generator/lib/ood_portal_generator/view.rb
ood-portal-generator/share/ood_portal_example.yml
ood-portal-generator/spec/ood_portal_generator_view_spec.rb

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204589926966692) by [Unito](https://www.unito.io)

Allow oidc_crypto_passphrase to be set for ood-portal-generator

---

apps/dashboard/app/models/script.rb
apps/dashboard/app/views/projects/show.html.erb

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204623748450475) by [Unito](https://www.unito.io)

Add quick launch button and quick launch ability

---

packaging/rpm/ondemand-selinux.te

Fixes #2825
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204638917673672) by [Unito](https://www.unito.io)

Add SELinux boolean to allow PUN to send email via SMTP

---

packaging/rpm/ondemand-selinux.te

Fixes #2825
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202821104799596/1204639217135038) by [Unito](https://www.unito.io)

(release_3.0) Add SELinux boolean to allow PUN to send email via SMTP

---

apps/dashboard/app/controllers/scripts_controller.rb

Check Projects Exist Before script#new

---

apps/dashboard/app/models/announcement.rb
apps/dashboard/app/models/batch_connect/app.rb
apps/dashboard/app/models/batch_connect/session.rb
apps/dashboard/app/views/batch_connect/sessions/connections/_custom.html.erb
apps/dashboard/config/configuration_singleton.rb
lib/tasks/rake_helper.rb
nginx_stage/lib/nginx_stage/generator.rb
ood-portal-generator/lib/ood_portal_generator/view.rb

Avoid deprecation warnings with ERB.new and Ruby 3.2

---

apps/dashboard/app/controllers/scripts_controller.rb
apps/dashboard/app/models/script.rb

Check In Project Dataroot Before Creating Project Path

---

apps/dashboard/app/controllers/scripts_controller.rb
apps/dashboard/test/system/jobs_app_test.rb

With the updates/bug fixes in #2852 - I thought it may be a good time to clean this up a bit.

Refactor find project

---

.github/workflows/tests.yml
.gitlab-ci.yml
Gemfile
Gemfile.lock
lib/tasks/packaging.rb
packaging/deb/rules
packaging/rpm/ondemand.spec
spec/e2e/e2e_helper.rb
spec/e2e/nodesets/amzn2023-aarch64.yml
spec/e2e/nodesets/el7-aarch64.yml
spec/e2e/nodesets/el8-aarch64.yml
spec/e2e/nodesets/el8.yml
spec/e2e/nodesets/el9-aarch64.yml
spec/e2e/nodesets/ubuntu-20.04-aarch64.yml
spec/e2e/nodesets/ubuntu-22.04-aarch64.yml

Support aarch64 builds

---

apps/dashboard/app/views/files/_globus.html.erb

add a nonce to the inline globus script tag to comply with our CSP.

add a nonce to the inline globus script tag

---

apps/dashboard/config/configuration_singleton.rb
apps/job-composer/manifest.yml
apps/projects/manifest.yml
packaging/deb/rules
packaging/rpm/ondemand.spec

Add dropdown entry for new job composer

---

apps/dashboard/app/lib/smart_attributes/attributes/auto_batch_clusters.rb
apps/dashboard/app/lib/smart_attributes/attributes/auto_scripts.rb

Fixes #2824 .
I still need to write a couple tests this afternoon for this, but it works currently.

Add SmartAttribute defaults for `auto_scripts` and `auto_batch_clusters`

---

apps/dashboard/app/lib/smart_attributes/attribute.rb

I just wanted to lint this file specifically because I'm a little tired of seeing all the linting errors in it.

Lint attribute

---

apps/dashboard/app/views/batch_connect/sessions/connections/_novnc.html.erb

backport #2995 to release 3.0.

Fixed quality and compression variable names in _novnc.html.erb (#2995)

---

apps/dashboard/app/models/hpc_module.rb
apps/dashboard/test/application_system_test_case.rb
apps/dashboard/test/models/hpc_module_test.rb
apps/dashboard/test/system/batch_connect_test.rb

Filter hidden modules

---

apps/dashboard/app/views/layouts/editor.html.erb

support file editor syntax highlighting for fortran

support file editor syntax highlighting for fortran

---

apps/dashboard/app/controllers/support_ticket_controller.rb
apps/dashboard/app/models/user_configuration.rb
apps/dashboard/config/locales/en.yml
apps/dashboard/test/controllers/support_ticket_controller_test.rb

Fixes #2867 
Improvements to error handling for support ticket configuration in controller

Improvements to error handling for support ticket configuration

---

apps/dashboard/test/system/jobs_app_test.rb

some small tweaks in these test cases
* using ' for literal strings
* removing `%Q{}` to prefer plain ol' string interpolation.

some small tweaks in these test cases

---

apps/dashboard/app/javascript/packs/script_edit.js
apps/dashboard/test/system/jobs_app_test.rb

Work on #3017. I'll fix both bugs in 2 separate PRs - this one only fixes the first bug identified in the ticket.  I also want to see what's up with the tests as they should have been failing for some time...

scripts#edit bug fixes

---

README.md

add hpc toolset tutorial to README

add hpc toolset tutorial to README

---

apps/dashboard/app/models/batch_connect/session.rb

This is a simple bugfix so that batch connect app ERB files are rendered in-situ then written instead of copying all the files then rewriting them.

render files in situ instead of copy & rewrite

---

apps/dashboard/app/helpers/dashboard_helper.rb
apps/dashboard/app/models/motd_formatter/markdown.rb
apps/dashboard/app/views/dashboard/_motd_markdown.html.erb
apps/dashboard/app/views/dashboard/_motd_rss.html.erb
apps/dashboard/config/configuration_singleton.rb
apps/dashboard/test/fixtures/config/ondemand.d/booleans.yml
apps/dashboard/test/fixtures/files/motd_md_w_html
apps/dashboard/test/integration/motd_integration_test.rb

Fixes #2682. I tried to get tests for the same but it's tough given nokogiri wants to reformat the page when you use it.

allow html to be rendered completely in some MOTD formats

---

apps/dashboard/app/models/posix_file.rb
apps/dashboard/test/system/files_test.rb

refactor PosixFile to allow for more easily usable validations (which will be coming in other PRs).

refactor PosixFile to allow for validations

---

apps/dashboard/lib/current_user.rb

alias in self to correct usage. This is going to fix tests, not clear how/why it worked before, but OK.

alias in self to correct usage.

---

apps/dashboard/test/system/batch_connect_test.rb

ensure the table refreshes in this test case

---

apps/dashboard/app/controllers/files_controller.rb
apps/dashboard/app/models/posix_file.rb
apps/dashboard/test/application_system_test_case.rb
apps/dashboard/test/system/files_test.rb

download hidden paths fixing #3044

download hidden paths

---

apps/dashboard/app/models/posix_transfer.rb
apps/dashboard/app/models/transfer.rb

refactor mv commands to Ruby libraries to continue the work on #2668

refactor mv commands to Ruby libraries

---

apps/dashboard/app/lib/account_cache.rb

foolishly, while working on #3123 I made a commit to master and pushed it, which it accepted because we allowed admins to bypass protections.
This resolves that because I don't want to muck about with the settings more and allow force pushes.

didnt mean to commit this to master branch

---

README.md

add slack to README

---

apps/dashboard/app/models/allowlist_policy.rb

use the real path as the cache key.

use the real path as the cache key

---

apps/shell/app.js

This is just a small refactor of #3135 to clean it up a bit.

simple refactor of shell's ping/pong

---

DEVELOPMENT.md

fix mount point docs

---

apps/dashboard/config/locales/ja_JP.yml

Add a Japanese locale because I'm learning Japanese, so I'm trying to get more muscle memory around the characters.
These translations could be incorrect, I used google and guessed as to which translation was most appropriate.

add a japanese locale

---

Dockerfile.dev

add nc to development container so developers can do simple echo origin servers. (`nc -e /bin/cat -lk 1234`)

add nc to development container

---

apps/bc_desktop/template/desktops/gnome.sh
apps/bc_desktop/template/script.sh.erb

Fixes #2896 with the additional bonus of fixing gnome on el7 (doesn't work on OSC systems currently).

Fix gnome desktop

---

apps/dashboard/app/javascript/path_selector/path_selector_data_table.js
apps/dashboard/app/views/batch_connect/session_contexts/_favorites.html.erb
apps/dashboard/app/views/batch_connect/session_contexts/_path_selector.html.erb

some small fixups for path selector, I'll detail each one in this PR.

some small fixups for path selector

---

apps/dashboard/app/models/batch_connect/session.rb

ensure staged_root has is writable by the user fixing #2798

ensure staged_root has is writable by the user

---

apps/dashboard/app/javascript/files/data_table.js
apps/dashboard/app/views/files/_files_table.html.erb

Fixes https://github.com/OSC/ondemand/issues/1177
https://github.com/OSC/ondemand/assets/6969170/e86d9f3c-d569-4675-8335-10c8a325c156

Adds select all option to files table

---

apps/dashboard/test/system/batch_connect_sessions_test.rb
apps/dashboard/test/system/jobs_app_test.rb

This bootstraps some tests for features that the students are working on.

Add some tests

---

apps/dashboard/app/javascript/path_selector/path_selector_data_table.js
apps/dashboard/test/system/batch_connect_test.rb

This fixes #3246. Added the test case first just to demonstrate that the current code fails this test.

fix cache key for path selector

---

apps/dashboard/app/assets/stylesheets/projects.scss
apps/dashboard/app/javascript/projects.js

Updates to `projects.js` to render errors into projects show page when fetching job information
Fixes #2718

Display errors in projects show page when fetching job information

---

apps/dashboard/app/views/layouts/nav/_featured_apps.html.erb
apps/dashboard/test/html_helper.rb
apps/dashboard/test/integration/custom_help_navigation_test.rb
apps/dashboard/test/integration/custom_navigation_test.rb
apps/dashboard/test/integration/dashboard_controller_test.rb

@johrstrom fixes to the test + changes needed to the featured_apps template

Fixes to navigation tests after accessibility improvements

---

apps/dashboard/app/models/posix_file.rb
apps/dashboard/test/system/files_test.rb

Fixes #3295 with a test to boot.

Fix non utf8 file

---

apps/dashboard/app/models/allowlist_policy.rb
apps/dashboard/app/models/posix_transfer.rb
apps/dashboard/test/jobs/transfer_local_job_test.rb
apps/dashboard/test/models/allowlist_policy_test.rb
apps/dashboard/test/models/transfer_test.rb
apps/dashboard/test/system/files_test.rb

This corrects some behavior in transferring files.

Transfer fix

---

apps/dashboard/app/lib/smart_attributes/attributes/auto_scripts.rb
apps/dashboard/test/fixtures/attributes/auto_scripts/script1.sh
apps/dashboard/test/fixtures/attributes/auto_scripts/script2.bash
apps/dashboard/test/fixtures/attributes/auto_scripts/script3.csh
apps/dashboard/test/fixtures/attributes/auto_scripts/script4.slurm
apps/dashboard/test/fixtures/attributes/auto_scripts/script5.sbatch
apps/dashboard/test/fixtures/attributes/auto_scripts/script6.qsub
apps/dashboard/test/lib/smart_attributes/auto_batch_clusters_test.rb
apps/dashboard/test/lib/smart_attributes/auto_scripts_test.rb

Added unit tests for:
- auto_batch_clusters
- auto_scripts
Fixes #2904

Added unit tests for auto_batch_clusters and auto_scripts SmartAttributes

---

apps/dashboard/app/views/batch_connect/sessions/card/_host.html.erb

Backport #3363 to release 3.1.

Show app card host only for running sessions (#3363)

---

apps/dashboard/app/javascript/config.js
apps/dashboard/app/views/layouts/_config.html.erb

This is a small PR to expose some more things to javascript through this configuration library so that we can refactor other things (like the xdmod widgets) to not inline javascript.

expose xdmod and analytics through js config

---

apps/dashboard/app/helpers/batch_connect/sessions_helper.rb
apps/dashboard/app/views/batch_connect/sessions/_panel.html.erb
apps/dashboard/app/views/batch_connect/sessions/card/_card_body.html.erb
apps/dashboard/app/views/batch_connect/sessions/card/_card_header.html.erb
apps/dashboard/test/helpers/batch_connect/sessions_helper_test.rb
apps/dashboard/test/integration/active_sessions_widget_test.rb
apps/dashboard/test/system/batch_connect_sessions_test.rb

more batch connect card refactor work. This moves a lot of the batch connect card rendering to partials. there are still things being rendered programmatically, but this finishes a big chunk of moving from helper methods to partials.

more batch connect card refactor work

---

apps/dashboard/app/views/batch_connect/sessions/connections/_novnc.html.erb
apps/dashboard/config/configuration_singleton.rb

Fixes https://github.com/OSC/ondemand/issues/3218

Extracts novnc connection compression & quality into Configuration variables

---

apps/dashboard/app/views/projects/_form.html.erb
apps/dashboard/config/locales/en.yml

Added checkbox to toggle setting the project directory override
Fixes #3107

Added project directory behind a frontend toggle checkbox

---

CONTRIBUTING.md

Given the conversation yesterday, I've added some notes on release branches.

add some notes on release branches

---

apps/dashboard/app/helpers/batch_connect/session_contexts_helper.rb
apps/dashboard/app/views/batch_connect/session_contexts/_path_selector.html.erb
apps/dashboard/test/system/batch_connect_test.rb

This adds the ability to relabel the path_selector widget.

allow the path_selector to redefine the label

---

apps/dashboard/app/assets/stylesheets/pinned_apps.scss

backport #3357 to 3.1.

---

CONTRIBUTING.md

Add ToC to Dev Guide

---

.zenodo.json
CITATION.cff

Update our citation files for new team members.

update citation materials

---

apps/dashboard/test/system/batch_connect_test.rb

Fixes #3422 by adding tests for setting path_selector favorites.

add test for setting path_selector favorites

---

apps/dashboard/app/javascript/files/data_table.js

Adds 'searchable: false' to actions column in files app

---

apps/dashboard/app/models/posix_file.rb

updated an insecure regular expression

update regular expression

---

apps/dashboard/app/javascript/projects_new.js
apps/dashboard/app/views/batch_connect/session_contexts/_path_selector.html.erb
apps/dashboard/app/views/projects/_form.html.erb
apps/dashboard/app/views/shared/_path_selector_table.html.erb

Fixes #3108 by adding the path_selector to projects#new page to select the directory one wishes to create the project from.

refactor this partial to be shared with other components

---

apps/dashboard/test/system/batch_connect_test.rb

These tests are still flaky.  Still trying to fix #3438.
In draft just to see how the CI works.

try again to fix flaky tests

---

apps/dashboard/app/javascript/application.js
apps/dashboard/app/views/apps/_app_group_rows.html.erb
apps/dashboard/app/views/files/_shell_dropdown.html.erb

Updates Popperjs import & x- selector renaming

---

.github/workflows/tests.yml

manually create a token for this workflow
Fixes #3532

manually create a token for this workflow

---

.github/workflows/document-merge.yml

https://github.com/OSC/ondemand/security/advisories/GHSA-5q6q-9pp2-4jv8

security: ghsa-5q6q-9pp2-4jv8

---

apps/dashboard/app/helpers/dashboard_helper.rb

Removes class 'w-100' from Dashboard logo

---

apps/dashboard/app/helpers/active_jobs_helper.rb
apps/dashboard/app/javascript/utils.js
apps/dashboard/app/javascript/xdmod.js
apps/dashboard/app/views/batch_connect/sessions/card/_card_header.html.erb

Work on #3461 
Updates badge classes for bootstrap 5.

Update Bootstrap Badge Classes

---

apps/dashboard/app/javascript/system_status.js

Refractor systemstatus polling

---

apps/dashboard/app/assets/stylesheets/_variables.scss
apps/dashboard/app/helpers/products_helper.rb
apps/dashboard/app/views/batch_connect/session_contexts/_form.html.erb
apps/dashboard/app/views/launchers/edit.html.erb
apps/dashboard/app/views/launchers/show.html.erb
apps/dashboard/app/views/products/_product.html.erb
apps/dashboard/app/views/products/show.html.erb
apps/dashboard/app/views/support_ticket/email_service_template.html.erb

Fixes #3576 
Fixed the width and color of buttons.

Update Bootstrap 5 Buttons

---

apps/dashboard/app/javascript/config.js
apps/dashboard/app/javascript/system_status.js
apps/dashboard/app/views/layouts/_config.html.erb
apps/dashboard/config/configuration_singleton.rb

Systemstatus poll config

---

apps/dashboard/app/apps/ood_app.rb

Verify app is a ruby app before running setup-production script

---

apps/dashboard/app/lib/smart_attributes/attributes/auto_modules.rb
apps/dashboard/test/lib/smart_attributes/auto_modules_test.rb

Adds ability to filter modules w/ string or regex

---

apps/dashboard/app/views/active_jobs/index.html.erb
apps/dashboard/app/views/layouts/application.html.erb
apps/dashboard/app/views/layouts/nav/_develop_dropdown.html.erb
apps/dashboard/app/views/layouts/nav/_help_dropdown.html.erb
apps/dashboard/test/integration/custom_help_navigation_test.rb

Replaces dropdown-menu-right with dropdown-menu-end

---

apps/dashboard/app/assets/stylesheets/batch_connect/sessions.scss
apps/dashboard/app/views/batch_connect/sessions/card/_card_header.html.erb

Possible fixes for the session card header color issues after upgrading Bootstrap to version 5
Fixes #3597

Fixes to the session card header color after Bootstrap5 upgrade

---

apps/dashboard/Gemfile
apps/dashboard/app/models/batch_connect/session.rb
apps/dashboard/app/models/concerns/sanitized_env.rb
apps/myjobs/app/models/concerns/sanitized_env.rb
apps/myjobs/app/models/resource_mgr_adapter.rb

cleanup the environment before submitting jobs

cleanup the environment before submitting jobs

---

CHANGELOG.md

add 3.1.7 to changelog

---

apps/dashboard/app/views/dashboard/_motd_markdown.html.erb
apps/dashboard/app/views/dashboard/_motd_osc.html.erb
apps/dashboard/app/views/dashboard/_motd_plaintext.html.erb
apps/dashboard/app/views/dashboard/_motd_rss.html.erb
apps/dashboard/app/views/widgets/_pinned_apps.html.erb
apps/dashboard/app/views/widgets/pinned_apps/_group.html.erb
apps/dashboard/test/integration/dashboard_layout_test.rb
apps/dashboard/test/integration/pinned_apps_test.rb

Fix dashboard headings

---

apps/dashboard/app/helpers/application_helper.rb
apps/dashboard/app/views/active_jobs/_extended_panel.html.erb
apps/dashboard/app/views/products/_product.html.erb
apps/dashboard/app/views/products/index.html.erb
apps/dashboard/app/views/products/show.html.erb
apps/dashboard/config/configuration_singleton.rb

Disable file and shell buttons when apps are unavailable

---

CHANGELOG.md
apps/dashboard/app/javascript/files/uppy_ops.js
apps/dashboard/app/lib/smart_attributes/attributes/bc_queue.rb

trying to get a pull request with the correct commit history 
fixes an issue stopping dependabot from updating websockets

Ws packages upgrade

---

apps/dashboard/app/models/balance.rb
apps/dashboard/app/models/concerns/uri_reader.rb
apps/dashboard/app/models/quota.rb
apps/dashboard/test/models/balance_test.rb
apps/dashboard/test/models/quota_test.rb

use File.read here instead of open for Balance and Quota classes. This adds a shared module so that they can both have the same algorithm.

use File.read here instead of open

---

apps/dashboard/test/system/project_manager_test.rb

Fixes #3714. I'll be bouncing this PR a few times just to be sure it always succeeds.

attempt to fix flaky test

---

apps/myjobs/app/controllers/workflows_controller.rb

only permit certain fields in the workflows controller for the job composer.
In draft for now while I test it.

only permit certain fields

---

apps/dashboard/app/assets/stylesheets/application.scss
apps/dashboard/package.json
apps/dashboard/yarn.lock

Fixes #3716. Turns out I just needed to add the dashboard's stylesheets as well as uppy core's.

upgrade uppy to 4.0

---

apps/dashboard/config/application.rb

update to use rails 7 defaults

update to use rails 7 defaults

---

apps/myjobs/config/application.rb

update myjobs to use rails 7.0 defaults

update myjobs to use rails 7.0 defaults

---

apps/dashboard/app/models/launcher.rb
apps/dashboard/test/models/launcher_test.rb

ensure launcher id matches a regex

ensure launcher id matches a regex

---

mod_ood_proxy/lib/node_proxy.lua

completed the fix of the issue partially fixed in https://github.com/OSC/ondemand/pull/3730

Fix for apache 2.4.62 - Update node_proxy.lua

---

apps/shell/app.js

timeout connections after some configurable time.

timeout connections after some configurable time

---

apps/dashboard/test/integration/projects_controller_test.rb

stub sinfo here for test reliability - I believe this fixes #3808

stub sinfo here for test reliability

---

apps/dashboard/app/javascript/projects.js
apps/dashboard/app/views/projects/_job_details.html.erb
apps/dashboard/app/views/projects/_job_details_content.html.erb
apps/dashboard/app/views/projects/show.html.erb

This restructures the projects#show page a little to get a better/columnar layout.

restructure a little to get a better layout

---

apps/dashboard/app/lib/smart_attributes/attribute_factory.rb
apps/dashboard/test/system/batch_connect_test.rb

Account for empty datefield

---

apps/dashboard/app/javascript/turbo_shim.js
apps/dashboard/app/javascript/utils.js

evaluate script tags when replacing html to fix #3618.

evaluate script tags when replacing html

---

apps/shell/package.json
apps/shell/yarn.lock

update express to 4.20.0

---

mod_ood_proxy/lib/node_proxy.lua

Backport #3791 to release 3.1.

backport #3791 to release 3.1

---

apps/dashboard/app/controllers/files_controller.rb

backport #3838 to 3.1

---

.github/workflows/update.yml

update ci needs sqlite devel package too

update ci needs sqlite devel package too

---

lib/tasks/build.rb
packaging/deb/rules
packaging/rpm/ondemand.spec

Standardize which gems get installed during packaging

---

apps/dashboard/app/javascript/path_selector/path_selector_data_table.js
apps/dashboard/app/views/shared/_path_selector_table.html.erb

Fixes #3524 ?? - It fixes the bug where the loading icon, but I wasn't having any problems with loading speed in either modal before or after this fix. 
Bug:
https://github.com/user-attachments/assets/aea39729-f738-46d2-ab95-b6c7c81019dd
Fix:
https://github.com/user-attachments/assets/b2df33ae-4a37-4a2b-9dc3-eb0973e95b4e

Fixes bug where icon shows up on 2nd path_selector on page

---

nginx_stage/lib/nginx_stage/user.rb
nginx_stage/spec/generators/pun_config_generator_spec.rb
nginx_stage/test/test_helper.rb

rm unused group calculation from nginx_stage

---

apps/dashboard/app/javascript/application.js
apps/dashboard/app/views/batch_connect/shared/_app_list_item.html.erb
apps/dashboard/test/integration/batch_connect_test.rb
apps/dashboard/test/integration/sessions_controller_test.rb

fix popovers on this app list

---

apps/dashboard/app/views/batch_connect/sessions/card/_card_header.html.erb

Fixes #4056 
correctly display cores

correctly display cores

---

apps/dashboard/app/javascript/icon_picker.js
apps/dashboard/test/system/project_manager_test.rb

Fixes #4053
Accounts for a search case when there are no characters available to index, and implements some tests to ensure correct behavior.

fix icon picker

---

apps/projects/manifest.yml

change navbar title of Project Manager

---

apps/dashboard/app/javascript/files/file_ops.js

Fix modal bug when file transfer fails

---

packaging/deb/control
packaging/rpm/ondemand.spec

Require latest ondemand-passenger and ondemand-nginx

---

apps/dashboard/test/system/batch_connect_widgets_test.rb

Continuing work on #3767 this adds a test case to ensure that `sanitize` is invoked here.

add test to ensure sanitize() works here

---

apps/dashboard/app/javascript/path_selector/path_selector_data_table.js
apps/dashboard/test/system/batch_connect_widgets_test.rb

ensure filenames are not url encoded (#4107)

ensure filenames are not url encoded (#4107)

---

mod_ood_proxy/lib/ood/user_map.lua

Fixes #4104.
I've tested this a bit with this helper script on OSC systems and I believe it can correctly handle all 3 cases - alphanumeric usernames, numeric usernames and UIDs.
<details>
```lua
function actual_username(username)
local num = tonumber(username)
if num then
local pwd = require "posix.pwd"
local data = pwd.getpwnam(num)
-- it's a numeric username.
if data then
return data.pw_name
-- not a numeric username, so must be a UID.
else
data = pwd.getpwuid(num)
return data.pw_name
end
-- it's not numeric, so just return the string.
else
return username
end
end
print(actual_username('johrstrom'))
print(actual_username(30961))
print(actual_username('30961'))
local pwd = require "posix.pwd"
print(pwd.getpwnam(12314))
```
</details>

account for numeric usernames

---

mod_ood_proxy/lib/ood/user_map.lua

Backport #4128 to account for numeric usernames.

account for numeric usernames (#4128)

---

apps/dashboard/config/application.rb

Fixed safe_load_path? method definition to avoid runtime errors (#4157)

---

apps/dashboard/app/views/layouts/nav/_styles.html.erb

Backports #4183 to the 4.0 release.

Fixed CSS selectors for active navigation link color (#4183)

---

apps/dashboard/app/controllers/files_controller.rb

This PR fulfills the AC of issue #4190
Acceptance Criteria:
```
def my_action_params
params.permit(:id, :path, :etc)
end
```

Refactored Files controller to use strong parameters.

---

apps/dashboard/app/views/batch_connect/session_contexts/_path_selector.html.erb
apps/dashboard/app/views/projects/_form.html.erb
apps/dashboard/app/views/shared/_path_selector_table.html.erb
apps/dashboard/config/locales/en.yml
apps/dashboard/config/locales/ja_JP.yml
apps/dashboard/config/locales/zh-CN.yml

internationalize "Select Path"

---

apps/dashboard/app/views/batch_connect/session_contexts/_path_selector.html.erb
apps/dashboard/app/views/projects/_form.html.erb
apps/dashboard/app/views/shared/_path_selector_table.html.erb
apps/dashboard/config/locales/en.yml
apps/dashboard/config/locales/ja_JP.yml
apps/dashboard/config/locales/zh-CN.yml

Backport #4176  to the 4.0 release.
Internationalize "Select Path" and add this to other locales.

internationalize "Select Path" (#4176)

---

apps/dashboard/app/assets/stylesheets/application.scss
apps/dashboard/app/views/layouts/nav/_logo.html.erb

ensure titles dont overflow to fix #228

ensure titles dont overflow

---

apps/dashboard/app/helpers/dashboard_helper.rb
apps/dashboard/app/helpers/recently_used_apps_helper.rb
apps/dashboard/test/integration/dashboard_layout_test.rb

Add Recently Used Apps to the default dashboard layout to fix #2508.

Add Recently Used Apps to the default dashboard layout

---

apps/dashboard/app/views/shared/_variable_progress_bar.html.erb
apps/dashboard/app/views/widgets/_balances.html.erb
apps/dashboard/app/views/widgets/_file_quota.html.erb
apps/dashboard/app/views/widgets/_file_quotas.html.erb
apps/dashboard/config/locales/en.yml

Work for #1158 to provide a file quota widget. 
This looks like this, showing different colors for given thresholds (80% for danger and 50% for warning)

add a file quota widget

---

apps/myjobs/db/schema.rb

missed this update after upgrading to rail 7

missed this update after upgrading to rail 7

---

apps/dashboard/app/lib/smart_attributes/attribute_factory.rb
apps/dashboard/app/lib/smart_attributes/attributes/auto_modules.rb
apps/dashboard/test/fixtures/modules/ascend.json
apps/dashboard/test/system/batch_connect_widgets_test.rb
apps/dashboard/test/test_helper.rb

support nested modules to fix #3378. In draft while I write some tests.

support nested modules

---

apps/dashboard/app/views/layouts/nav/_dropdown_item.html.erb
apps/dashboard/app/views/layouts/nav/_featured_apps.html.erb
apps/dashboard/app/views/layouts/nav/_group_items.html.erb

Add margin after icon and abstract dropdown item into partial

---

apps/dashboard/app/views/batch_connect/sessions/index.html.erb

Add landmarks for menu and session cards

---

apps/dashboard/app/javascript/projects_import.js
apps/dashboard/app/views/projects/import.html.erb
apps/dashboard/config/locales/en.yml
apps/dashboard/config/locales/ja_JP.yml
apps/dashboard/config/locales/zh-CN.yml

Related to Issue https://github.com/OSC/ondemand/issues/4120
This is the fourth PR to create a form to import shared projects if the user has a directory path.
First PR: https://github.com/OSC/ondemand/pull/4178
Second PR: https://github.com/OSC/ondemand/pull/4189
Third PR: https://github.com/OSC/ondemand/pull/4208

Created form for importing shared project via directory

---

apps/dashboard/app/lib/smart_attributes/attribute_factory.rb
apps/dashboard/app/lib/smart_attributes/attributes/global_attribute.rb
apps/dashboard/test/system/batch_connect_widgets_test.rb

support setting bc_ attributes globally
Fixes #4132
I'll probably add a test or two as well.

support setting bc_ attributes globally

---

apps/dashboard/app/javascript/aria_live_notify.js
apps/dashboard/app/javascript/batch_connect_sessions.js

Following up on #4061 I just wanted to refactor this specific utility out so that we can use it in other places.

small refactor to reuse notifying this aria live region

---

.github/workflows/tests.yml
apps/myjobs/Gemfile
apps/myjobs/Gemfile.lock

upgrade job composer's nokogiri

upgrade job composer's nokogiri

---

apps/dashboard/app/javascript/files/clip_board.js
apps/dashboard/app/javascript/files/data_table.js
apps/dashboard/app/javascript/files/file_ops.js
apps/dashboard/package.json
apps/dashboard/test/system/files_test.rb
apps/dashboard/test/system/remote_files_test.rb
apps/dashboard/yarn.lock

Remove handlebars to fix #4058

Rm handlebars

---

.github/workflows/tests.yml
spec/e2e/browser_spec.rb

Fix the CI from halting while trying to build the packages.

backport CI bug fix (#4279)

---

apps/dashboard/app/controllers/apps_controller.rb

backport cache icons (#4277) to 4.0

backport cache icons (#4277) to 4.0

---

apps/dashboard/app/javascript/path_selector/path_selector_data_table.js

Fix path selector and broken tests.

backport fix path selector and broken tests (#4302) to 4.0

---

apps/dashboard/app/javascript/path_selector/path_selector_data_table.js

Fix path selector and broken tests.

backport fix path selector and broken tests (#4302) to 3.1

---

CHANGELOG.md

fix links in changelog

---

apps/dashboard/app/views/active_jobs/_extended_panel.html.erb

small refactor regarding these buttons
* should be `btn-outline-dark` not `btn-outline-black`
* remove the use of inline styles
* add parentheses for clarity.

small refactor regarding these buttons

---

apps/dashboard/app/javascript/files/sweet_alert.js
apps/dashboard/app/views/files/_input_modal.html.erb
apps/dashboard/app/views/files/index.html.erb
apps/dashboard/config/locales/en.yml
apps/dashboard/test/system/files_test.rb
apps/dashboard/test/system/remote_files_test.rb

start to remove sweetalert by replacing the input box for renaming, deleting, and creating new files.
Starts work on #2592.

start to remove sweetalert

---

apps/dashboard/app/javascript/module_browser.js
apps/dashboard/app/javascript/utils.js
apps/dashboard/app/views/module_browser/_module_list.html.erb
apps/dashboard/app/views/module_browser/_toolbar.html.erb
apps/dashboard/app/views/module_browser/index.html.erb

Second PR related to Issue #3402
Depends on PR #4319

Add search and filter by cluster to module browser

---

apps/myjobs/app/models/workflow.rb

add a check to ensure the source directory is not a parent of the destination directory to avoid recursion errors.
Fixes #3426.

add check before staging

---

apps/myjobs/app/models/workflow.rb

add a check to ensure the source directory is not a parent of the destination directory to avoid recursion errors.

backport - add check before staging (#4367) - to 3.1

---

apps/myjobs/app/models/workflow.rb

add a check to ensure the source directory is not a parent of the destination directory to avoid recursion errors.

backport - add check before staging (#4367) - to 4.0

---

apps/dashboard/app/apps/dev_router.rb
apps/dashboard/app/apps/sys_router.rb
apps/dashboard/app/apps/usr_router.rb
apps/dashboard/app/models/batch_connect/app.rb

cache apps so they only render once
Fixes #210

cache apps so they only render once

---

apps/dashboard/config/locales/en.yml

Update this message for clarity.
Fixes #1200.

update this message for clarity

---

apps/dashboard/app/lib/smart_attributes/attributes/auto_modules.rb

sort modules in auto_modules
Fixes #4400

sort modules in auto_modules

---

apps/dashboard/app/views/shared/_path_selector_table.html.erb

path_selector remove h5 tag

---

apps/dashboard/app/models/active_jobs/jobstatusdata.rb

Add Slurm ArrayJobId and ArrayTaskId to extended panel

---

packaging/deb/control

relax ondemand-nginx and ondemand-passenger dependencies for debian
Fixes #4428

relax ondemand-nginx and ondemand-passenger dependencies for debian

---

apps/shell/app.js

Buffer shell logging to reduce output.
Fixes #2928

Shell logging

---

apps/shell/app.js

* fix error logging while trying to send data
* Combine duplicate send error logs into single line
Produces logs in the following format:
Send error: WebSocket is not open: readyState 2 (CLOSING) Send error: WebSocket is not open: readyState 2 (CLOSING) (5x in 5000ms)
* Kill node-pty terminal if websocket is closed
Terminal onData events seem to be handled before the websocket close events (which attempts to end the terminal), causing excessive attempts to send data over the websocket that are guaranteed to fail due to a closed websocket.
---------

backport - Shell logging (#4461) to 4.0

---

apps/shell/app.js

* fix error logging while trying to send data
* Combine duplicate send error logs into single line
Produces logs in the following format:
Send error: WebSocket is not open: readyState 2 (CLOSING) Send error: WebSocket is not open: readyState 2 (CLOSING) (5x in 5000ms)
* Kill node-pty terminal if websocket is closed
Terminal onData events seem to be handled before the websocket close events (which attempts to end the terminal), causing excessive attempts to send data over the websocket that are guaranteed to fail due to a closed websocket.
---------

backport - Shell logging (#4461) - to 3.1

---

apps/dashboard/app/models/batch_connect/app.rb

Respect user-defined cluster attribute from form.yml

---

apps/dashboard/app/helpers/module_browser_helper.rb
apps/dashboard/app/views/module_browser/index.html.erb
apps/dashboard/config/locales/en.yml
apps/dashboard/config/locales/ja_JP.yml
apps/dashboard/config/locales/zh-CN.yml
apps/dashboard/config/routes.rb
apps/module-browser/manifest.yml

Addresses #3402 
- Creates manifest for module browser
- Adds localizations
- Minor stylistic changes

Integrate module browser

---

apps/dashboard/config/locales/en-CA.yml
apps/dashboard/config/locales/fr-CA.yml

Feel free to use these for Canadian support!
I added both English with Canadian Spellings, and French for French / Quebec Canadians. 
It was tested on our OOD cluster

Add files via uploadAdd Canadian English and French locale files (en-CA.yml, fr-CA.yml)
